'use client'

import { SiteHeader } from '@/components/site-header'
import { SiteFooter } from '@/components/site-footer'
import { useLang } from '@/lib/lang/context'

const PRIVACY_TEXT: Record<string, Record<string, string>> = {
  title: { en: "Privacy Policy", ur: "پرائیویسی پالیسی", es: "Política de Privacidad", fr: "Politique de Confidentialité", ar: "سياسة الخصوصية", hi: "गोपनीयता नीति", zh: "隐私政策", pt: "Política de Privacidade", ru: "Политика конфиденциальности", de: "Datenschutzerklärung", ja: "プライバシーポリシー", ko: "개인정보 처리방침", it: "Informativa sulla Privacy", tr: "Gizlilik Politikası", id: "Kebijakan Privasi", bn: "গোপনীয়তা নীতি", vi: "Chính sách bảo mật", sw: "Sera ya Faragha" },
  lastUpdated: { en: "Last updated: July 18, 2026", ur: "آخری تجدید: 18 جولائی 2026", es: "Última actualización: 18 de julio de 2026", fr: "Dernière mise à jour: 18 juillet 2026", ar: "آخر تحديث: 18 يوليو 2026", hi: "अंतिम अपडेट: 18 जुलाई 2026", zh: "最后更新于 2026年7月18日", pt: "Última atualização: 18 de julho de 2026", ru: "Последнее обновление: 18 июля 2026 г.", de: "Zuletzt aktualisiert: 18. Juli 2026", ja: "最終更新日：2026年7月18日", ko: "최종 수정일: 2026년 7월 18일", it: "Ultimo aggiornamento: 18 luglio 2026", tr: "Son güncelleme: 18 Temmuz 2026", id: "Terakhir diperbarui: 18 Juli 2026", bn: "সর্বশেষ সংস্করণ: ১৮ জুলাই, ২০২৬", vi: "Cập nhật lần cuối: Ngày 18 tháng 7 năm 2026", sw: "Imesasishwa mwisho: 18 Julai 2026" },
  s1Title: { en: "1. Introduction", ur: "1. تعارف", es: "1. Introducción", fr: "1. Introduction", ar: "1. مقدمة", hi: "1. परिचय", zh: "1. 导言", pt: "1. Introdução", ru: "1. Введение", de: "1. Einleitung", ja: "1. はじめに", ko: "1. 서론", it: "1. Introduzione", tr: "1. Giriş", id: "1. Pendahuluan", bn: "১. সূচনা", vi: "1. Giới thiệu", sw: "1. Utangulizi" },
  s1Content: { en: "Welcome to Cardzy (cardzy.online). We operate the digital wish card & event invitation platform. This Privacy Policy explains how we collect, use, and protect information when you use our Service.", ur: "کارڈزی (cardzy.online) میں خوش آمدید۔ یہ پرائیویسی پالیسی وضاحت کرتی ہے کہ ہم آپ کی معلومات کس طرح جمع، استعمال اور محفوظ کرتے ہیں۔", es: "Bienvenido a Cardzy (cardzy.online). Esta Política explica cómo recopilamos, usamos y protegemos su información al utilizar nuestro Servicio.", fr: "Bienvenue sur Cardzy (cardzy.online). Cette politique explique comment nous collectons, utilisons et protégeons vos données personnelles.", ar: "أهلاً بك في كاردزي (cardzy.online). تشرح هذه السياسة كيفية جمع معلوماتك واستخدامها وحمايتها عند استخدام خدماتنا.", hi: "Cardzy (cardzy.online) में आपका स्वागत है। यह गोपनीयता नीति बताती है कि हम आपकी जानकारी का संग्रह, उपयोग और सुरक्षा कैसे करते हैं।", zh: "欢迎使用 Cardzy (cardzy.online)。本隐私政策说明我们在您使用服务时如何收集、使用和保护您的个人信息。", pt: "Bem-vindo ao Cardzy (cardzy.online). Esta Política explica como coletamos, usamos e protegemos suas informações ao usar nosso Serviço.", ru: "Добро пожаловать в Cardzy (cardzy.online). Настоящая Политика объясняет, как мы собираем, используем и защищаем ваши данные.", de: "Willkommen bei Cardzy (cardzy.online). Diese Richtlinie erläutert die Erhebung, Nutzung und den Schutz Ihrer Daten.", ja: "Cardzy (cardzy.online)へようこそ。本プライバシーポリシーは、お客様の個人情報の取り扱いについて説明します。", ko: "Cardzy (cardzy.online)에 오신 것을 환영합니다. 본 방침은 귀하의 개인정보 수집, 이용 및 보호 방법을 설명합니다.", it: "Benvenuto su Cardzy (cardzy.online). Questa Informativa spiega come raccogliamo, utilizziamo e proteggiamo i tuoi dati.", tr: "Cardzy (cardzy.online)'ye hoş geldiniz. Bu Gizlilik Politikası, verilerinizi nasıl topladığımızı ve koruduğumuzu açıklar.", id: "Selamat datang di Cardzy (cardzy.online). Kebijakan ini menjelaskan cara kami mengumpulkan dan melindungi data Anda.", bn: "Cardzy (cardzy.online)-এ স্বাগতম। এই গোপনীয়তা নীতি ব্যাখ্যা করে আমরা কীভাবে আপনার তথ্য সংগ্রহ, ব্যবহার ও সুরক্ষা করি।", vi: "Chào mừng bạn đến với Cardzy (cardzy.online). Chính sách này giải thích cách chúng tôi thu thập và bảo vệ thông tin của bạn.", sw: "Karibu Cardzy (cardzy.online). Sera hii inaeleza jinsi tunavyokusanya, kutumia na kulinda taarifa zako." },
  s2Title: { en: "2. Information We Collect", ur: "2. ہم جو معلومات جمع کرتے ہیں", es: "2. Información que Recopilamos", fr: "2. Informations que nous collectons", ar: "2. المعلومات التي نجمعها", hi: "2. एकत्र की जाने वाली जानकारी", zh: "2. 我们收集的信息", pt: "2. Informações que Coletamos", ru: "2. Информация, которую мы собираем", de: "2. Erhobene Informationen", ja: "2. 収集する情報", ko: "2. 수집하는 정보", it: "2. Informazioni Raccolte", tr: "2. Topladığımız Bilgiler", id: "2. Informasi yang Kami Kumpulkan", bn: "২. সংগৃহীত তথ্যসমূহ", vi: "2. Thông tin chúng tôi thu thập", sw: "2. Taarifa Tunazokusanya" },
  s2AccInfo: { en: "Account information: Name, email address, and phone number provided upon registration.", ur: "اکاؤنٹ کی معلومات: رجسٹریشن پر فراہم کردہ نام، ای میل ایڈریس اور فون نمبر۔", es: "Información de cuenta: Nombre, correo electrónico y teléfono al registrarse.", fr: "Informations de compte : Nom, adresse e-mail et numéro de téléphone lors de l'inscription.", ar: "معلومات الحساب: الاسم والبريد الإلكتروني ورقم الهاتف عند التسجيل.", hi: "खाता जानकारी: पंजीकरण के समय दिया गया नाम, ईमेल और फोन नंबर।", zh: "账户信息：注册时提供的姓名、电子邮箱及电话号码。", pt: "Informações da conta: Nome, e-mail e telefone fornecidos no registro.", ru: "Данные аккаунта: Имя, email и номер телефона при регистрации.", de: "Konto-Informationen: Name, E-Mail-Adresse und Telefonnummer bei der Registrierung.", ja: "アカウント情報：登録時に提供されたお名前、メールアドレス、電話番号。", ko: "계정 정보: 가입 시 제공된 이름, 이메일 주소 및 전화번호.", it: "Informazioni sull'account: Nome, e-mail e numero di telefono al momento della registrazione.", tr: "Hesap bilgileri: Kayıt sırasında sağlanan ad, e-posta ve telefon numarası.", id: "Informasi akun: Nama, email, dan nomor telepon saat mendaftar.", bn: "অ্যাকাউন্ট তথ্য: নিবন্ধনের সময় সরবরাহকৃত নাম, ইমেল ঠিকানা ও ফোন নম্বর।", vi: "Thông tin tài khoản: Tên, email và số điện thoại khi đăng ký.", sw: "Taarifa za akaunti: Jina, barua pepe na nambari ya simu wakati wa usajili." },
  s2CardContent: { en: "Card content: Personalized messages, titles, host names, and event details created on Cardzy.", ur: "کارڈ کا مواد: کارڈزی پر بنائے گئے ذاتی پیغامات، عنوانات، میزبانوں کے نام اور ایونٹ کی تفصیلات۔", es: "Contenido de tarjetas: Mensajes personalizados, títulos, nombres de anfitriones y detalles del evento.", fr: "Contenu des cartes : Messages personnalisés, titres, noms des hôtes et détails de l'événement.", ar: "محتوى البطاقات: الرسائل المخصصة والعناوين وأسماء المضيفين وتفاصيل الفعالية.", hi: "कार्ड सामग्री: कार्डजी पर बनाए गए व्यक्तिगत संदेश, शीर्षक, मेजबान का नाम और कार्यक्रम का विवरण।", zh: "贺卡内容：在 Cardzy 上创建的个性化祝词、标题、主办人姓名及活动详情。", pt: "Conteúdo dos cartões: Mensagens personalizadas, títulos, nomes de anfitriões e detalhes do evento.", ru: "Содержимое открыток: Персональные сообщения, заголовки, имена организаторов и детали мероприятий.", de: "Karteninhalte: Personalisierte Nachrichten, Titel, Namen der Gastgeber und Event-Details.", ja: "カードコンテンツ：Cardzyで作成されたメッセージ、タイトル、主催者名、イベント詳細。", ko: "카드 콘텐츠: Cardzy에서 작성된 개인 메시지, 제목, 주최자 이름 및 행사 상세 정보.", it: "Contenuto dei biglietti: Messaggi personalizzati, titoli, nomi degli ospiti e dettagli dell'evento.", tr: "Kart içeriği: Cardzy üzerinde oluşturulan kişisel mesajlar, başlıklar ve etkinlik detayları.", id: "Konten kartu: Pesan personal, judul, nama tuan rumah, dan detail acara.", bn: "কার্ড সামগ্রী: Cardzy-তে তৈরি করা ব্যক্তিগত বার্তা, শিরোনাম, আয়োজকদের নাম এবং ইভেন্টের বিবরণ।", vi: "Nội dung thiệp: Lời chúc, tiêu đề, tên gia chủ và thông tin sự kiện.", sw: "Maudhui ya kadi: Ujumbe wa kibinafsi, majina ya waandaaji na maelezo ya hafla." },
  s2UsageData: { en: "Usage & Analytics: Page views, card view counters, RSVP responses, and performance metrics.", ur: "استعمال اور اینالیٹکس: پیج ویوز، کارڈ ویو کاؤنٹر، آر ایس وی پی جوابات اور کارکردگی کے ڈیٹا۔", es: "Uso y analítica: Visitas a la página, contadores de tarjetas, respuestas RSVP y métricas de rendimiento.", fr: "Utilisation et statistiques : Vues de pages, compteurs de cartes, réponses RSVP et métriques.", ar: "بيانات الاستخدام والتحليلات: مشاهدات الصفحات وعنصر عداد البطاقات وإجابات التأكيد.", hi: "उपयोग और एनालिटिक्स: पेज व्यू, कार्ड व्यू काउंटर, RSVP उत्तर और प्रदर्शन आंकड़े।", zh: "使用与统计数据：页面浏览量、贺卡查看计数器、RSVP 回复及性能指标。", pt: "Uso e métricas: Visualizações de páginas, contadores de cartões, respostas RSVP e desempenho.", ru: "Статистика использования: Просмотры страниц, счетчики открыток, ответы RSVP и аналитика.", de: "Nutzung & Analysen: Seitenaufrufe, Zählerstände, RSVP-Antworten und Leistungsdaten.", ja: "利用状況とアナリティクス：ページビュー数、カード閲覧数、RSVP返信数。", ko: "이용 및 분석: 페이지 뷰, 카드 조회수, RSVP 응답 및 성과 지표.", it: "Uso e analisi: Visualizzazioni di pagina, contatori di biglietti, risposte RSVP e metriche.", tr: "Kullanım ve Analitik: Sayfa görüntülemeleri, kart sayaçları, RSVP yanıtları ve metrikler.", id: "Penggunaan & Analitik: Tampilan halaman, penghitung kartu, balasan RSVP, dan performa.", bn: "ব্যবহার ও বিশ্লেষণ: পৃষ্ঠা দেখা, کارڈ দেখার সংখ্যা, RSVP উত্তর এবং পারফরম্যান্স তথ্য।", vi: "Sử dụng & Phân tích: Lượt xem trang, lượt xem thiệp, phản hồi RSVP và hiệu suất.", sw: "Matumizi na Uchanganuzi: Idadi ya kutazama kurasa, kadi, majibu ya RSVP na viwango." },
  s3Title: { en: "3. How We Use Your Information", ur: "3. ہم آپ کی معلومات کا استعمال کیسے کرتے ہیں", es: "3. Cómo Usamos su Información", fr: "3. Utilisation de vos informations", ar: "3. كيف نستخدم معلوماتك", hi: "3. जानकारी का उपयोग", zh: "3. 信息的使用方式", pt: "3. Como Usamos suas Informações", ru: "3. Как мы используем вашу информацию", de: "3. Nutzung der Informationen", ja: "3. データの利用目的", ko: "3. 정보 이용 목적", it: "3. Uso delle Informazioni", tr: "3. Bilgilerin Kullanımı", id: "3. Penggunaan Informasi Anda", bn: "৩. তথ্যের ব্যবহার", vi: "3. Cách sử dụng thông tin", sw: "3. Matumizi ya Taarifa" },
  s3Content: { en: "We use collected information to provide, operate, and maintain the Cardzy platform; manage your account; authenticate secure access; process event invitations; and deliver relevant advertisements via Google AdSense without selling your data.", ur: "ہم جمع کی گئی معلومات کارڈزی پلیٹ فارم کی فراہمی، اکاؤنٹ کے انتظام، محفوظ رسائی اور گوگل ایڈسینس اشتہارات کے لیے استعمال کرتے ہیں۔", es: "Utilizamos la información recopilada para operar el servicio, administrar su cuenta, autenticar el acceso y mostrar anuncios a través de Google AdSense.", fr: "Nous utilisons vos données pour faire fonctionner le service, gérer votre compte, sécuriser les accès et afficher des annonces via Google AdSense.", ar: "نستخدم المعلومات المجمعة لتشغيل وإدارة المنصة، وإدارة حسابك، والمصادقة الآمنة، وعرض الإعلانات عبر جوجل أدسينس.", hi: "हम एकत्र की गई जानकारी का उपयोग सेवा प्रदान करने, आपके खाते का प्रबंधन करने, सुरक्षित पहुंच सत्यापित करने और गूगल ऐडसेंस विज्ञापन दिखाने के लिए करते हैं।", zh: "我们使用收集的信息来提供和运营 Cardzy 平台、管理您的账户、验证安全访问并展示 Google AdSense 广告。", pt: "Usamos as informações para operar a plataforma, gerenciar sua conta, autenticar acessos e exibir anúncios via Google AdSense.", ru: "Мы используем данные для предоставления услуг, управления аккаунтом, обеспечения безопасности и показа рекламы Google AdSense.", de: "Wir nutzen Ihre Daten zur Bereitstellung der Dienste, Nutzerverwaltung, Sicherheitsauthentifizierung und Anzeige von Google AdSense Anzeigen.", ja: "収集した情報は、サービスの提供、アカウント管理、セキュリティ認証、Google AdSense広告の表示に使用されます。", ko: "수집된 정보는 서비스 제공, 계정 관리, 안전한 인증 및 Google AdSense 광고 게재에 사용됩니다.", it: "Utilizziamo le informazioni per gestire il servizio, autenticare gli accessi e mostrare annunci tramite Google AdSense.", tr: "Toplanan bilgileri hizmet sağlamak, hesabınızı yönetmek, güvenli erişim doğrulamak ve Google AdSense reklamları sunmak için kullanırız.", id: "Kami menggunakan informasi untuk menyediakan layanan, mengelola akun, dan menampilkan iklan melalui Google AdSense.", bn: "আমরা সংগৃহীত তথ্য পরিষেবা পরিচালনা, অ্যাকাউন্ট ব্যবস্থাপনা, এর নিরাপত্তা বজায় এবং গুগল অ্যাডসেন্স বিজ্ঞাপন প্রদর্শনে ব্যবহার করি।", vi: "Chúng tôi sử dụng thông tin để vận hành dịch vụ, quản lý tài khoản, xác thực bảo mật và hiển thị quảng cáo Google AdSense.", sw: "Tunatumia taarifa kutoa huduma, kusimamia akaunti yako, na kuonyesha matangazo kupitia Google AdSense." },
  s4Title: { en: "4. Google AdSense & Cookies", ur: "4. گوگل ایڈسینس اور کوکیز", es: "4. Google AdSense y Cookies", fr: "4. Google AdSense et Cookies", ar: "4. جوجل أدسينس والملفات الكوكيز", hi: "4. गूगल ऐडसेंस और कुकीज़", zh: "4. Google AdSense 与 Cookie", pt: "4. Google AdSense e Cookies", ru: "4. Google AdSense и Файлы cookie", de: "4. Google AdSense & Cookies", ja: "4. Google AdSenseとCookie", ko: "4. Google AdSense 및 쿠키", it: "4. Google AdSense e Cookie", tr: "4. Google AdSense ve Çerezler", id: "4. Google AdSense & Cookie", bn: "৪. গুগল অ্যাডসেন্স ও কুকিজ", vi: "4. Google AdSense & Cookie", sw: "4. Google AdSense na Vidakuzi" },
  s4Content: { en: "We use Google AdSense to display advertisements. Google uses cookies to serve ads based on your prior visits to our website. You can opt out of personalized advertising by visiting Google Ads Settings. We also use essential cookies for user authentication and session management.", ur: "ہم اشتہارات دکھانے کے لیے گوگل ایڈسینس کا استعمال کرتے ہیں۔ گوگل آپ کے ویب سائٹ کے سابقہ دوروں کی بنیاد پر اشتہارات پیش کرنے کے لیے کوکیز کا استعمال کرتا ہے۔", es: "Utilizamos Google AdSense para mostrar anuncios. Google utiliza cookies para mostrar anuncios basados en sus visitas previas. Puede desactivar la publicidad personalizada en Configuración de anuncios de Google.", fr: "Nous utilisons Google AdSense pour diffuser des annonces. Google utilise des cookies pour diffuser des publicités basées sur vos visites antérieures.", ar: "نستخدم جوجل أدسينس لعرض الإعلانات. يستخدم جوجل ملفات الكوكيز لعرض الإعلانات بناءً على زياراتك السابقة لموقعنا.", hi: "हम विज्ञापन दिखाने के लिए गूगल ऐडसेंस का उपयोग करते हैं। गूगल आपकी पिछली यात्राओं के आधार पर विज्ञापन परोसने के लिए कुकीज़ का उपयोग करता है।", zh: "我们使用 Google AdSense 展示广告。Google 利用 Cookie 根据您之前访问本网站的情况向您投放广告。您可以随时在 Google 广告设置中选择退出个性化广告。", pt: "Utilizamos o Google AdSense para exibir anúncios. O Google usa cookies para veicular anúncios com base em suas visitas anteriores.", ru: "Мы используем Google AdSense для показа рекламы. Файлы cookie используются Google для подбора объявлений на основе ваших посещений.", de: "Wir verwenden Google AdSense zur Anzeige von Werbung. Google nutzt Cookies, um Anzeigen basierend auf Ihren vorherigen Besuchen zu schalten.", ja: "当サイトではGoogle AdSenseによる広告表示を行っています。Googleは過去の閲覧履歴に基づきCookieを使用して広告を配信します。", ko: "당사는 광고 게재를 위해 Google AdSense를 사용합니다. Google은 귀하의 이전 방문 기록을 바탕으로 쿠키를 활용해 맞춤형 광고를 제공합니다.", it: "Utilizziamo Google AdSense per mostrare annunci. Google utilizza i cookie per pubblicare annunci basati sulle tue visite precedenti.", tr: "Reklam göstermek için Google AdSense kullanıyoruz. Google, önceki ziyaretlerinize dayanarak reklam sunmak için çerezleri kullanır.", id: "Kami menggunakan Google AdSense untuk menampilkan iklan. Google menggunakan cookie untuk menyajikan iklan berdasarkan kunjungan Anda.", bn: "আমরা বিজ্ঞাপন প্রদর্শনের জন্য গুগল অ্যাডসেন্স ব্যবহার করি। গুগল পূর্ববর্তী পরিদর্শনের ভিত্তিতে বিজ্ঞাপন দেওয়ার জন্য কুকিজ ব্যবহার করে।", vi: "Chúng tôi sử dụng Google AdSense để hiển thị quảng cáo. Google sử dụng cookie để cung cấp quảng cáo dựa trên các lượt truy cập trước đó của bạn.", sw: "Tunatumia Google AdSense kuonyesha matangazo. Google inatumia vidakuzi kutoa matangazo kulingana na ziara zako za nyuma." },
  s5Title: { en: "5. Data Sharing & Third Parties", ur: "5. ڈیٹا کا اشتراک اور فریق ثالث", es: "5. Compartición de Datos y Terceros", fr: "5. Partage des Données", ar: "5. مشاركة البيانات والجهات الخارجية", hi: "5. डेटा साझाकरण", zh: "5. 数据共享与第三方", pt: "5. Compartilhamento de Dados", ru: "5. Передача данных третьим лицам", de: "5. Datenweitergabe an Dritte", ja: "5. データの第三者共有", ko: "5. 제3자 데이터 공유", it: "5. Condivisione dei Dati", tr: "5. Veri Paylaşımı", id: "5. Pembagian Data", bn: "৫. তথ্য আদান-প্রদান", vi: "5. Chia sẻ dữ liệu", sw: "5. Kushiriki Data" },
  s5Content: { en: "We do not sell your personal data. Data is strictly shared only with trusted infrastructure providers required to operate Cardzy, including Firebase/Google Cloud (for authentication and database storage), Vercel (for hosting and analytics), and Google AdSense (for ads).", ur: "ہم آپ کا ذاتی ڈیٹا فروخت نہیں کرتے۔ ڈیٹا صرف فائر بیس/گوگل کلاؤڈ، ورسل اور گوگل ایڈسینس کے ساتھ شیئر کیا جاتا ہے۔", es: "No vendemos sus datos personales. La información se comparte estrictamente con proveedores confiables como Firebase/Google Cloud, Vercel y Google AdSense.", fr: "Nous ne vendons pas vos données personnelles. Les données sont partagées uniquement avec Firebase/Google Cloud, Vercel et Google AdSense.", ar: "نحن لا نبيع بياناتك الشخصية. يتم مشاركة البيانات حصرياً مع مزودي الخدمة الموثوقين مثل فايبربيس، فيرسيل وجوجل أدسينس.", hi: "हम आपका व्यक्तिगत डेटा नहीं बेचते हैं। डेटा केवल विश्वसनीय प्रदाताओं जैसे फ़ायरबेस/गूगल क्लाउड, वर्सेल और गूगल ऐडसेंस के साथ साझा किया जाता है।", zh: "我们决不出售您的个人数据。数据仅在提供服务所必需的情况下与 Firebase/Google Cloud、Vercel 及 Google AdSense 严格共享。", pt: "Não vendemos seus dados pessoais. As informações são compartilhadas estritamente com provedores confiáveis como Firebase, Vercel e Google AdSense.", ru: "Мы не продаем ваши персональные данные. Передача осуществляется только надежным сервисам: Firebase/Google Cloud, Vercel и Google AdSense.", de: "Wir verkaufen Ihre persönlichen Daten nicht. Daten werden nur mit Firebase/Google Cloud, Vercel und Google AdSense geteilt.", ja: "お客様の個人情報を販売することはありません。データはFirebase/Google Cloud、Vercel、Google AdSenseとのみ厳重に共有されます。", ko: "당사는 개인정보를 판매하지 않습니다. 데이터는 서비스 운영에 필수적인 Firebase/Google Cloud, Vercel 및 Google AdSense와만 엄격히 공유됩니다.", it: "Non vendiamo i tuoi dati personali. I dati sono condivisi esclusivamente con fornitori affidabili come Firebase/Google Cloud, Vercel e Google AdSense.", tr: "Kişisel verilerinizi satmıyoruz. Veriler yalnızca Firebase/Google Cloud, Vercel ve Google AdSense gibi güvenilir sağlayıcılarla paylaşılır.", id: "Kami tidak menjual data pribadi Anda. Data hanya dibagikan kepada penyedia tepercaya seperti Firebase/Google Cloud, Vercel, dan Google AdSense.", bn: "আমরা আপনার ব্যক্তিগত তথ্য বিক্রি করি না। তথ্য শুধুমাত্র ফায়ারবেস/গুগল ক্লাউড, ভার্সেল এবং গুগল অ্যাডসেন্স এর সাথে শেয়ার করা হয়।", vi: "Chúng tôi không bán dữ liệu cá nhân của bạn. Dữ liệu chỉ được chia sẻ strictly với Firebase/Google Cloud, Vercel và Google AdSense.", sw: "Hatuuzi data yako ya kibinafsi. Taarifa inashirikiwa tu na watoa huduma wanaoaminika kama Firebase/Google Cloud, Vercel na Google AdSense." },
  s6Title: { en: "6. Data Retention", ur: "6. ڈیٹا کی نگہداشت", es: "6. Retención de Datos", fr: "6. Conservation des données", ar: "6. الاحتفاظ بالبيانات", hi: "6. डेटा प्रतिधारण", zh: "6. 数据保留", pt: "6. Retenção de Dados", ru: "6. Хранение данных", de: "6. Datenspeicherung", ja: "6. データの保持", ko: "6. 데이터 보관", it: "6. Conservazione dei Dati", tr: "6. Veri Saklama", id: "6. Retensi Data", bn: "৬. তথ্য সংরক্ষণ", vi: "6. Lưu trữ dữ liệu", sw: "6. Uhifadhi wa Data" },
  s6Content: { en: "We retain your account data and digital cards as long as your account is active. You can delete your wish cards or event invitations at any time directly from the host dashboard. To permanently request account deletion, contact us via email.", ur: "ہم آپ کے اکاؤنٹ کا ڈیٹا اور کارڈز اس وقت تک محفوظ رکھتے ہیں جب تک آپ کا اکاؤنٹ فعال رہتا ہے۔ آپ ڈیش بورڈ سے کسی بھی وقت کارڈ ڈیلیٹ کر سکتے ہیں۔", es: "Retenemos los datos de su cuenta mientras esté activa. Puede eliminar sus tarjetas o invitaciones en cualquier momento desde su panel de control.", fr: "Nous conservons vos données tant que votre compte est actif. Vous pouvez supprimer vos cartes à tout moment depuis votre tableau de bord.", ar: "نحتفظ ببيانات حسابك وبطاقاتك طالما أن حسابك نشط. يمكنك حذف بطاقاتك في أي وقت مباشرة من لوحة التحكم.", hi: "हम आपके खाते का डेटा तब तक बनाए रखते हैं जब तक आपका खाता सक्रिय रहता है। आप डैशबोर्ड से किसी भी समय अपने कार्ड मिटा सकते हैं।", zh: "只要您的账户处于活跃状态，我们就会保留您的账户数据和贺卡。您随时可以在控制台中直接删除已创建的贺卡和请柬。", pt: "Mantemos os dados da sua conta enquanto ela estiver ativa. Você pode excluir seus cartões a qualquer momento diretamente no painel.", ru: "Мы храним данные вашего аккаунта и открытки, пока аккаунт активен. Вы можете удалить открытки в любое время через панель управления.", de: "Wir speichern Ihre Daten, solange Ihr Konto aktiv ist. Sie können Ihre erstelleten Karten jederzeit über das Dashboard löschen.", ja: "アカウントが有効である限り、データおよび作成されたカードを保持します。カードはダッシュボードからいつでも削除可能です。", ko: "계정이 활성화되어 있는 동안 회원 데이터 및 카드가 보관됩니다. 호스트 대시보드에서 언제든지 카드를 삭제할 수 있습니다.", it: "Conserviamo i dati del tuo account finché l'account è attivo. Puoi eliminare i tuoi biglietti in qualsiasi momento dal dashboard.", tr: "Hesap verilerinizi hesabınız aktif olduğu sürece saklarız. Kartlarınızı dilediğiniz zaman panodan silebilirsiniz.", id: "Kami menyimpan data akun dan kartu Anda selama akun aktif. Anda dapat menghapus kartu kapan saja langsung dari dasbor.", bn: "আপনার অ্যাকাউন্ট সক্রিয় থাকা পর্যন্ত তথ্য ও کارڈ সংরক্ষিত থাকে। আপনি যেকোনো সময় ড্যাশবোর্ড থেকে کارڈ মুছে ফেলতে পারেন।", vi: "Chúng tôi lưu trữ dữ liệu tài khoản khi tài khoản còn hoạt động. Bạn có thể xóa thiệp bất kỳ lúc nào từ bảng điều khiển.", sw: "Tunahifadhi data ya akaunti yako na kadi maadam akaunti yako ipo hai. Unaweza kufuta kadi zako wakati wowote kutoka kwenye dashibodi." },
  s7Title: { en: "7. Children's Privacy", ur: "7. بچوں کی پرائیویسی", es: "7. Privacidad Infantil", fr: "7. Confidentialité des enfants", ar: "7. خصوصية الأطفال", hi: "7. बच्चों की गोपनीयता", zh: "7. 儿童隐私保护", pt: "7. Privacidade das Crianças", ru: "7. Конфиденциальность детей", de: "7. Schutz von Minderjährigen", ja: "7. お子様のプライバシー", ko: "7. 아동 개인정보 보호", it: "7. Privacy dei Minori", tr: "7. Çocukların Gizliliği", id: "7. Privasi Anak-anak", bn: "৭. শিশুদের গোপনীয়তা", vi: "7. Quyền riêng tư trẻ em", sw: "7. Faragha ya Watoto" },
  s7Content: { en: "Our Service is not directed to children under 13. We do not knowingly collect personal information from children under 13. If you believe we have inadvertently collected such information, please contact us immediately.", ur: "ہماری سروس 13 سال سے کم عمر بچوں کے لیے نہیں ہے۔ ہم جان بوجھ کر 13 سال سے کم عمر بچوں کی معلومات جمع نہیں کرتے۔", es: "Nuestro Servicio no está dirigido a niños menores de 13 años. No recopilamos a sabiendas información de niños menores de 13 años.", fr: "Notre service ne s'adresse pas aux enfants de moins de 13 ans. Nous ne collectons pas sciemment de données auprès d'enfants de moins de 13 ans.", ar: "خدمتنا ليست موجهة للأطفال دون سن 13 عاماً. نحن لا نجمع بشكل متعمد معلومات شخصية من الأطفال دون سن 13 عاماً.", hi: "हमारी सेवा 13 वर्ष से कम उम्र के बच्चों के लिए निर्देशित नहीं है। हम जानबूझकर 13 वर्ष से कम उम्र के बच्चों से जानकारी एकत्र नहीं करते हैं।", zh: "我们的服务不面向 13 岁以下的儿童。我们不会故意收集 13 岁以下儿童的个人信息。如发现有误收集，请立即联系我们。", pt: "Nosso Serviço não é direcionado a crianças menores de 13 anos. Não coletamos intencionalmente informações de crianças menores de 13 anos.", ru: "Наш сервис не предназначен для детей младше 13 лет. Мы намеренно не собираем персональные данные детей до 13 лет.", de: "Unser Dienst richtet sich nicht an Kinder unter 13 Jahren. Wir erheben nicht wissentlich personenbezogene Daten von Kindern unter 13 Jahren.", ja: "当サービスは13歳未満のお子様を対象としていません。13歳未満のお子様から個人情報を故意に収集することはありません。", ko: "본 서비스는 만 13세 미만 아동을 대상으로 하지 않습니다. 만 13세 미만 아동의 개인정보를 의도적으로 수집하지 않습니다.", it: "Il nostro Servizio non è rivolto a bambini di età inferiore a 13 anni. Non raccogliamo consapevolmente dati personali da minori di 13 anni.", tr: "Hizmetimiz 13 yaşın altındaki çocuklara yönelik değildir. 13 yaşın altındaki çocuklardan bilerek kişisel bilgi toplamıyoruz.", id: "Layanan kami tidak ditujukan untuk anak-anak di bawah 13 tahun. Kami tidak secara sengaja mengumpulkan data anak di bawah 13 tahun.", bn: "আমাদের পরিষেবা ১৩ বছরের কম বয়সী শিশুদের জন্য নির্দেশিত নয়। আমরা জেনে-বুঝে ১৩ বছরের কম বয়সী শিশুদের তথ্য সংগ্রহ করি না।", vi: "Dịch vụ của chúng tôi không hướng đến trẻ em dưới 13 tuổi. Chúng tôi không cố ý thu thập thông tin cá nhân của trẻ em dưới 13 tuổi.", sw: "Huduma wetu hauelekezwi kwa watoto walio chini ya miaka 13. Hatukusanyi kwa makusudi taarifa za watoto chini ya miaka 13." },
  s8Title: { en: "8. Your Rights & Data Choices", ur: "8. آپ کے حقوق اور اختیارات", es: "8. Sus Derechos y Opciones", fr: "8. Vos Droits", ar: "8. حقوقك وخياراتك", hi: "8. आपके अधिकार", zh: "8. 您的权利与数据选择", pt: "8. Seus Direitos", ru: "8. Ваши права", de: "8. Ihre Rechte", ja: "8. お客様の権利", ko: "8. 귀하의 권리", it: "8. I Tuoi Diritti", tr: "8. Haklarınız", id: "8. Hak-hak Anda", bn: "৮. আপনার অধিকারসমূহ", vi: "8. Quyền của bạn", sw: "8. Haki Zako" },
  s8Content: { en: "You have the right to access, update, or permanently request deletion of your personal account data. To exercise any of these rights, contact us at cardzyonline@gmail.com.", ur: "آپ کو اپنے ذاتی ڈیٹا تک رسائی، اسے اپ ڈیٹ کرنے یا ڈیلیٹ کرنے کا حق حاصل ہے۔ ان حقوق کا استعمال کرنے کے لیے cardzyonline@gmail.com پر رابطہ کریں۔", es: "Tiene derecho a acceder, actualizar o solicitar la eliminación de sus datos personales. Para ejercer estos derechos, contáctenos en cardzyonline@gmail.com.", fr: "Vous avez le droit d'accéder, de corriger ou de supprimer vos données personnelles. Pour exercer ces droits, contactez-nous à cardzyonline@gmail.com.", ar: "لديك الحق في الوصول إلى بياناتك الشخصية أو تحديثها أو طلب حذفها نهائياً. لممارسة هذه الحقوق، اتصل بنا على cardzyonline@gmail.com.", hi: "आपको अपने व्यक्तिगत डेटा को एक्सेस, अपडेट या हटाने का अनुरोध करने का अधिकार है। संपर्क करें: cardzyonline@gmail.com।", zh: "您有权访问、更新或要求永久删除您的个人账户数据。如需行使这些权利，请发送邮件至 cardzyonline@gmail.com 联系我们。", pt: "Você tem o direito de acessar, atualizar ou solicitar a exclusão de seus dados. Para exercer seus direitos, contate cardzyonline@gmail.com.", ru: "Вы имеете право просматривать, обновлять и удалять свои данные. По всем вопросам обращайтесь по адресу cardzyonline@gmail.com.", de: "Sie haben das Recht, Auskunft über Ihre Daten zu erhalten, diese zu korrigieren oder zu löschen. Kontakt: cardzyonline@gmail.com.", ja: "お客様にはご自身の個人情報へのアクセス、修正、削除を請求する権利があります。お問い合わせ：cardzyonline@gmail.com。", ko: "귀하는 개인정보에 대한 열람, 수정 및 삭제를 요청할 권리가 있습니다. 문의 사항은 cardzyonline@gmail.com으로 연락해 주세요.", it: "Hai il diritto di accedere, aggiornare o richiedere l'eliminazione dei tuoi dati personali. Scrivici a cardzyonline@gmail.com.", tr: "Kişisel verilerinize erişme, güncelleme veya silme hakkına sahipsiniz. İletişim için: cardzyonline@gmail.com.", id: "Anda berhak mengakses, memperbarui, atau menghapus data pribadi Anda. Hubungi kami di cardzyonline@gmail.com.", bn: "আপনার ব্যক্তিগত তথ্য অ্যাক্সেস, আপডেট বা মুছে ফেলার অনুরোধ করার অধিকার রয়েছে। যোগাযোগ করুন: cardzyonline@gmail.com।", vi: "Bạn có quyền truy cập, cập nhật hoặc yêu cầu xóa dữ liệu cá nhân. Liên hệ với chúng tôi tại cardzyonline@gmail.com.", sw: "Una haki ya kufikia, kusahihisha au kuomba kufutwa kwa data yako. Mawasiliano: cardzyonline@gmail.com." },
  s9Title: { en: "9. Security", ur: "9. سیکورٹی", es: "9. Seguridad", fr: "9. Sécurité", ar: "9. الأمان", hi: "9. सुरक्षा", zh: "9. 安全保障", pt: "9. Segurança", ru: "9. Безопасность", de: "9. Sicherheit", ja: "9. セキュリティ", ko: "9. 보안", it: "9. Sicurezza", tr: "9. Güvenlik", id: "9. Keamanan", bn: "৯. নিরাপত্তা", vi: "9. Bảo mật", sw: "9. Usalama" },
  s9Content: { en: "We implement industry-standard encryption and security protocols to safeguard your information. However, no method of transmission over the internet is 100% secure.", ur: "ہم آپ کی معلومات کی حفاظت کے لیے جدید ترین سیکورٹی اقدامات نافذ کرتے ہیں۔ تاہم، انٹرنیٹ پر کوئی بھی طریقہ 100٪ محفوظ نہیں ہے۔", es: "Implementamos medidas de seguridad estándar de la industria para proteger sus datos. Sin embargo, ningún método de transmisión en Internet es 100% seguro.", fr: "Nous mettons en œuvre des mesures de sécurité conformes aux normes pour protéger vos données. Cependant, aucune méthode n'est sécurisée à 100%.", ar: "نحن نطبق إجراءات أمنية مشددة وفقاً للمعايير الصناعية لحماية معلوماتك. ومع ذلك، لا توجد وسيلة نقل عبر الإنترنت آمنة بنسبة 100%.", hi: "हम आपकी जानकारी की सुरक्षा के लिए उद्योग-मानक सुरक्षा उपाय लागू करते हैं। हालांकि, इंटरनेट पर कोई भी संचरण 100% सुरक्षित नहीं है।", zh: "我们采取行业标准的加密与安全措施来保护您的数据。然而，任何互联网传输或电子存储方式都无法保证 100% 绝对安全。", pt: "Implementamos medidas de segurança padrão do setor para proteger seus dados. No entanto, nenhum método na internet é 100% seguro.", ru: "Мы применяем отраслевые стандарты безопасности для защиты ваших данных. Однако ни один метод передачи в сети не является на 100% безопасным.", de: "Wir setzen branchenübliche Sicherheitsmaßnahmen zum Schutz Ihrer Daten ein. Dennoch ist keine Übertragung im Internet zu 100% sicher.", ja: "お客様の情報を保護するために業界標準のセキュリティ対策を講じています。ただし、インターネット上の送信は100%の完全に安全を保証するものではありません。", ko: "당사는 귀하의 정보를 보호하기 위해 업계 표준 보안 조치를 시행하고 있습니다. 그러나 인터넷을 통한 데이터 전송이 100% 안전할 수는 없습니다.", it: "Adottiamo misure di sicurezza standard del settore per proteggere i tuoi dati. Tuttavia, nessun metodo su Internet è sicuro al 100%.", tr: "Bilgilerinizi korumak için endüstri standardı güvenlik önlemleri uyguluyoruz. Ancak internet üzerinden hiçbir yöntem %100 güvenli değildir.", id: "Kami menerapkan tindakan keamanan standar industri untuk melindungi data Anda. Namun, tidak ada metode di internet yang 100% aman.", bn: "আমরা আপনার তথ্য সুরক্ষিত রাখতে ইন্ডাস্ট্রি-স্ট্যান্ডার্ড সিকিউরিটি অনুসরণ করি। তবে ইন্টারনেটে কোনো প্রক্রিয়াই ১০০% নিশ্চিত নিরাপদ নয়।", vi: "Chúng tôi áp dụng các biện pháp bảo mật tiêu chuẩn ngành để bảo vệ thông tin. Tuy nhiên, không có phương thức truyền tải nào an toàn 100%.", sw: "Tunatumia viwango vya usalama vya tasnia kulinda taarifa zako. Hata hivyo, hakuna njia ya mtandao iliyo salama kwa 100%." },
  s10Title: { en: "10. Policy Updates", ur: "10. پالیسی میں تبدیلیاں", es: "10. Actualizaciones de la Política", fr: "10. Modifications de la Politique", ar: "10. تحديثات السياسة", hi: "10. नीति अपडेट", zh: "10. 隐私政策更新", pt: "10. Atualizaciones da Política", ru: "10. Обновления Политики", de: "10. Aktualisierungen dieser Richtlinie", ja: "10. 規約の更新", ko: "10. 방침의 변경", it: "10. Modifiche all'Informativa", tr: "10. Politika Güncellemeleri", id: "10. Pembaruan Kebijakan", bn: "১০. নীতি সংস্করণ", vi: "10. Cập nhật chính sách", sw: "10. Mabadiliko ya Sera" },
  s10Content: { en: "We may update this Privacy Policy periodically. We will notify users by updating the 'Last updated' date at the top of this page. Continued usage of Cardzy after changes constitutes acceptance.", ur: "ہم اس پرائیویسی پالیسی کو وقت کے ساتھ اپ ڈیٹ کر سکتے ہیں۔ تبدیلیوں کے بعد کارڈزی کا مسلسل استعمال اس کی قبولیت سمجھا جائے گا۔", es: "Podemos actualizar esta Política periódicamente. Notificaremos actualizando la fecha arriba. El uso continuado del servicio implica su aceptación.", fr: "Nous pouvons mettre à jour cette politique. Nous vous informerons en modifiant la date en haut de cette page.", ar: "قد نقوم بتحديث سياسة الخصوصية هذه من وقت لآخر. يعتبر استخدامك المستمر للموقع بعد التغييرات بمثابة موافقة عليها.", hi: "हम समय-समय पर इस गोपनीयता नीति को अपडेट कर सकते हैं। परिवर्तनों के बाद सेवा का निरंतर उपयोग स्वीकृति माना जाएगा।", zh: "我们可能会定期更新本隐私政策。政策更新后，本页面顶部的“最后更新”日期将同步修改。您继续使用 Cardzy 即视为接受更新后的政策。", pt: "Podemos atualizar esta Política periodicamente. O uso continuado do Cardzy após as alterações constitui sua aceitação.", ru: "Мы можем периодически обновлять Политику. Продолжение использования Cardzy после изменений означает ваше согласие с ними.", de: "Wir können diese Richtlinie gelegentlich aktualisieren. Die Fortsetzung der Nutzung nach Änderungen gilt als Zustimmung.", ja: "本ポリシーは定期的に更新される場合があります。変更後も当サービスを利用し続けることで、改定後の規約に同意したものとみなされます。", ko: "본 방침은 정기적으로 업데이트될 수 있습니다. 변경 후에도 Cardzy를 계속 이용하는 것은 개정된 방침에 동의하는 것으로 간주됩니다.", it: "Potremmo aggiornare questa Informativa periodicamente. L'uso continuato di Cardzy dopo le modifiche costituisce accettazione.", tr: "Bu Gizlilik Politikasını zaman zaman güncelleyebiliriz. Değişikliklerden sonra Cardzy'yi kullanmaya devam etmeniz kabul anlamına gelir.", id: "Kami dapat memperbarui Kebijakan ini secara berkala. Penggunaan berlanjut atas Cardzy setelah perubahan dianggap sebagai persetujuan.", bn: "ہم وقت کے ساتھ اس پالیسی کو اپ ڈیٹ کر سکتے ہیں۔ تبدیلیوں کے بعد خدمت کا تسلسل سے استعمال اس کی قبولیت مانا جائے گا۔", vi: "Chúng tôi có thể cập nhật chính sách này theo thời gian. Việc tiếp tục sử dụng dịch vụ sau khi thay đổi đồng nghĩa với việc chấp nhận.", sw: "Tunaweza kusahihisha Sera hii mara kwa mara. Kuendelea kutumia Cardzy baada ya mabadiliko kunamaanisha unakubali." },
  s11Title: { en: "11. Contact Us", ur: "11. رابطہ کریں", es: "11. Contáctenos", fr: "11. Contactez-nous", ar: "11. اتصل بنا", hi: "11. संपर्क करें", zh: "11. 联系我们", pt: "11. Fale Conosco", ru: "11. Связаться с нами", de: "11. Kontakt", ja: "11. お問い合わせ", ko: "11. 문의하기", it: "11. Contattaci", tr: "11. İletişim", id: "11. Hubungi Kami", bn: "১১. যোগাযোগ করুন", vi: "11. Liên hệ", sw: "11. Mawasiliano" },
  s11Content: { en: "If you have any questions, concerns, or requests regarding this Privacy Policy, please contact our support team at cardzyonline@gmail.com.", ur: "اگر آپ کے پاس اس پرائیویسی پالیسی سے متعلق کوئی سوالات ہیں تو ہم سے cardzyonline@gmail.com پر رابطہ کریں۔", es: "Si tiene alguna pregunta o solicitud sobre esta Política de Privacidad, contáctenos en cardzyonline@gmail.com.", fr: "Si vous avez des questions concernant cette politique de confidentialité, contactez-nous à cardzyonline@gmail.com.", ar: "إذا كان لديك أي أسئلة أو استفسارات بخصوص سياسة الخصوصية، يرجى التواصل معنا على cardzyonline@gmail.com.", hi: "यदि इस गोपनीयता नीति के संबंध में आपके कोई प्रश्न या अनुरोध हैं, तो हमसे cardzyonline@gmail.com पर संपर्क करें।", zh: "如果您对本隐私政策有任何疑问、建议或请求，请通过电子邮箱 cardzyonline@gmail.com 联系我们的支持团队。", pt: "Se você tiver dúvidas ou solicitações sobre esta Política de Privacidade, entre em contato em cardzyonline@gmail.com.", ru: "Если у вас есть вопросы по поводу настоящей Политики конфиденциальности, свяжитесь с нами по адресу cardzyonline@gmail.com.", de: "Wenn Sie Fragen oder Anliegen zu dieser Datenschutzerklärung haben, kontaktieren Sie uns unter cardzyonline@gmail.com.", ja: "本プライバシーポリシーに関するご質問やお問い合わせは、cardzyonline@gmail.com までご連絡ください。", ko: "본 개인정보 처리방침에 대해 궁금한 점이나 요청 사항이 있으시면 cardzyonline@gmail.com으로 문의해 주세요.", it: "Se hai domande o richieste riguardo a questa Informativa sulla Privacy, contattaci all'indirizzo cardzyonline@gmail.com.", tr: "Bu Gizlilik Politikası ile ilgili sorularınız veya talepleriniz için lütfen cardzyonline@gmail.com adresinden bizimle iletişime geçin.", id: "Jika Anda memiliki pertanyaan tentang Kebijakan Privasi ini, silakan hubungi tim kami di cardzyonline@gmail.com.", bn: "এই গোপনীয়তা নীতি সম্পর্কে আপনার কোনো প্রশ্ন থাকলে আমাদের সাথে cardzyonline@gmail.com ইমেলে যোগাযোগ করুন।", vi: "Nếu bạn có bất kỳ câu hỏi nào về Chính sách bảo mật này, vui lòng liên hệ với chúng tôi qua email cardzyonline@gmail.com.", sw: "Kama una maswali au maombi kuhusu Sera hii ya Faragha, tafadhali wasiliana nasi kupitia cardzyonline@gmail.com." },
}

export default function PrivacyPolicyPage() {
  const { lang } = useLang()

  const getText = (key: string) => {
    return PRIVACY_TEXT[key]?.[lang] || PRIVACY_TEXT[key]?.['en'] || ''
  }

  return (
    <div className="flex min-h-screen flex-col bg-background">
      <SiteHeader />
      <main className="flex-1 mx-auto max-w-3xl px-4 py-12 md:py-16 w-full">
        <h1 className="text-3xl font-extrabold text-primary mb-2">
          {getText('title')}
        </h1>
        <p className="text-sm text-muted-foreground mb-8">
          {getText('lastUpdated')}
        </p>

        <Section title={getText('s1Title')}>
          {getText('s1Content')}
        </Section>

        <Section title={getText('s2Title')}>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>{getText('s2AccInfo')}</li>
            <li>{getText('s2CardContent')}</li>
            <li>{getText('s2UsageData')}</li>
          </ul>
        </Section>

        <Section title={getText('s3Title')}>
          {getText('s3Content')}
        </Section>

        <Section title={getText('s4Title')}>
          {getText('s4Content')}
        </Section>

        <Section title={getText('s5Title')}>
          {getText('s5Content')}
        </Section>

        <Section title={getText('s6Title')}>
          {getText('s6Content')}
        </Section>

        <Section title={getText('s7Title')}>
          {getText('s7Content')}
        </Section>

        <Section title={getText('s8Title')}>
          {getText('s8Content')}
        </Section>

        <Section title={getText('s9Title')}>
          {getText('s9Content')}
        </Section>

        <Section title={getText('s10Title')}>
          {getText('s10Content')}
        </Section>

        <Section title={getText('s11Title')}>
          {getText('s11Content')}
        </Section>
      </main>
      <SiteFooter />
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-lg font-bold text-foreground mb-2">{title}</h2>
      <div className="text-sm text-muted-foreground leading-relaxed">{children}</div>
    </section>
  )
}
