# scripts/assemble_final_1000.py
import json
import re

# Comprehensive catalog of authentic Urdu couplets for the masters
CLASSICAL_SHERS = [
    # Ghalib
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "ishq", "Love & Romance",
     "ہزاروں خواہشیں ایسی کہ ہر خواہش پہ دم نکلے\nبہت نکلے مرے ارمان لیکن پھر بھی کم نکلے",
     "Thousands of desires, each so captivating that life departs on every wish; many of my yearnings were fulfilled, yet so many still remain.",
     "ہزاروں ایسی خواہشیں ہیں جن پر جان نچھاور کرنے کو جی چاہے، دل کے بہت سے ارمان نکلے مگر پھر بھی بہت سے باقی رہ گئے۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "ishq", "Love & Romance",
     "عشق نے غالبؔ نکما کر دیا\nورنہ ہم بھی آدمی تھے کام کے",
     "Love rendered Ghalib utterly useless; otherwise we too were once men of great purpose.",
     "عشق کی لگن نے غالب کو کسی کام کا نہ چھوڑا، ورنہ ہم بھی دنیا کے معاملات میں بڑے کارآمد انسان تھے۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "falsafa", "Philosophy & Reflection",
     "قیدِ حیات و بندِ غم اصل میں دونوں ایک ہیں\nموت سے پہلے آدمی غم سے نجات پائے کیوں",
     "The prison of life and the fetters of sorrow are in truth identical; why then should mortal man expect freedom from sorrow before death?",
     "زندگی کی قید اور غم کی زنجیریں حقیقت میں ایک ہی ہیں، موت سے پہلے انسان دکھ اور تکلیف سے کیسے نجات پا سکتا ہے۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "falsafa", "Philosophy & Reflection",
     "قطرہ اپنا بھی حقیقت میں ہے دریا لیکن\nہم کو تقلیدِ تنک ظرفیِ منصور نہیں",
     "In truth our single drop too encompasses an entire sea; yet we do not emulate Mansur's narrow-vessel boasting.",
     "ہمارا ایک قطرہ بھی سمندر جیسی وسعت رکھتا ہے، لیکن ہم منصور حلاج کی طرح اپنے ظرف کی کم مائیگی کا ڈھنڈورا نہیں پیٹتے۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "ishq", "Love & Romance",
     "آئینہ دیکھ اپنا سا منہ لے کے رہ گئے\nصاحب کو دل نہ دینے پہ کتنا غرور تھا",
     "They looked into the mirror and stood abashed; how proud they had been of withholding their heart from love!",
     "جب آئینے میں اپنی بے رخی اور حسن دیکھا تو شرمندہ ہو کر رہ گئے، جبکہ پہلے دل نہ دینے پر بڑا غرور تھا۔"),

    # Iqbal
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "inqilab", "Revolution & Hope",
     "افراد کے ہاتھوں میں ہے اقوام کی تقدیر\nہر فرد ہے ملت کے مقدر کا ستارہ",
     "In the hands of individuals rests the destiny of nations; every single person is a star in the constellation of their community.",
     "قوموں کی تقدیر ان کے افراد کی محنت اور کردار سے بنتی ہے، ہر فرد اپنی قوم کے مقدر کا چمکتا ستارہ ہے۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "falsafa", "Philosophy & Reflection",
     "ستاروں سے آگے جہاں اور بھی ہیں\nابھی عشق کے امتحاں اور بھی ہیں",
     "Beyond these distant stars exist other boundless realms; still further trials of love and devotion await.",
     "ان ستاروں سے پرے بھی نئی دنیائیں آباد ہیں، اور ابھی محبت اور جستجو کے مزید کڑے امتحان باقی ہیں۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "falsafa", "Philosophy & Reflection",
     "تری خودی میں اگر انقلاب ہو پیدا\nعجب نہیں ہے کہ یہ چار سو بدل جائے",
     "If a true spiritual revolution awakens within your inner self; it is no wonder if the entire world around you transforms.",
     "اگر انسان کی اپنی خودی میں روحانی اور فکری انقلاب بیدار ہو جائے، تو اس کے ارد گرد کی پوری کائنات بدل جاتی ہے۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "falsafa", "Philosophy & Reflection",
     "کھول آنکھ، زمیں دیکھ، فلک دیکھ، فضا دیکھ\nمشرق سے ابھرتے ہوئے سورج کو ذرا دیکھ",
     "Open your eyes: behold the earth, the celestial dome, the boundless expanse! Gaze upon the radiant sun rising from the East!",
     "اپنی آنکھیں کھولو اور زمین، آسمان اور فضا کے حسن پر غور کرو؛ مشرق سے بیداری کے ابھرتے ہوئے سورج کو دیکھو۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "dua", "Dua & Blessings",
     "دلِ بینا بھی کر خدا سے طلب\nآنکھ کا نور دل کا نور نہیں",
     "Seek from God an insightful perceiving heart; the physical illumination of the eye is not the true light of the heart.",
     "خدا سے بصیرت والا دل مانگو، کیونکہ ظاہری آنکھوں کی بینائی دل کی سچی روشنی کا نعم البدل نہیں ہو سکتی۔"),

    # Faiz Ahmad Faiz
    ("Faiz Ahmad Faiz", "فیض احمد فیض", "Sialkot / Lahore, Pakistan", "1911 – 1984", "ur", "ishq", "Love & Romance",
     "تم آئے ہو نہ شبِ انتظار گزری ہے\nتلاش میں ہے سحر بار بار گزری ہے",
     "Neither have you arrived, nor has the night of waiting concluded; seeking you, the dawn has passed by repeatedly.",
     "نہ تمہاری آمد ہوئی اور نہ ہی انتظار کی یہ کٹھن رات ختم ہوئی؛ سحر تمہاری تلاش میں بار بار آ کر گزر گئی۔"),
    ("Faiz Ahmad Faiz", "فیض احمد فیض", "Sialkot / Lahore, Pakistan", "1911 – 1984", "ur", "inqilab", "Revolution & Hope",
     "نثار میں تری گلیوں کے اے وطن کہ جہاں\nچلی ہے رسم کہ کوئی نہ سر اٹھا کے چلے",
     "Sacrificed be I upon your sacred streets, O homeland, where a custom has arisen that none may walk with head held high.",
     "اے وطن میں تیری گلیوں پر نثار جاؤں جہاں ایسا ظالمانہ دستور بنا دیا گیا ہے کہ کوئی سر اٹھا کر سچ نہ بول سکے۔"),
    ("Faiz Ahmad Faiz", "فیض احمد فیض", "Sialkot / Lahore, Pakistan", "1911 – 1984", "ur", "ishq", "Love & Romance",
     "رنگ پیراہن کا، خوشبو زلف لہرانے کا نام\nموسمِ گل ہے تمہارے بام پر آنے کا نام",
     "Color belongs to your attire, fragrance to your swaying tresses; spring itself is merely the name of your stepping out onto the terrace.",
     "پھولوں کا رنگ تمہارے لباس سے ہے اور خوشبو تمہاری زلفوں سے؛ بہار کا اصل مطلب تمہارا چھت پر جلوہ افروز ہونا ہے۔"),
    ("Faiz Ahmad Faiz", "فیض احمد فیض", "Sialkot / Lahore, Pakistan", "1911 – 1984", "ur", "dard", "Sorrow & Longing",
     "آئے کچھ ابر کچھ شراب آئے\nاس کے بعد آئے جو عذاب آئے",
     "Let gentle clouds gather, let the cup of wine arrive; after that, let whatever torments destiny wills follow.",
     "بارش کے بادل گھر آئیں اور محبت کا جام ہاتھ میں ہو، پھر چاہے زمانے کے سارے عذاب ہی کیوں نہ ٹوٹ پڑیں۔"),

    # Ahmad Faraz
    ("Ahmad Faraz", "احمد فراز", "Kohat / Islamabad, Pakistan", "1931 – 2008", "ur", "ishq", "Love & Romance",
     "رنجش ہی سہی دل ہی دکھانے کے لیے آ\nآ پھر سے مجھے چھوڑ کے جانے کے لیے آ",
     "Even if with grievance, come if only to pain my heart; come, even if merely to abandon me once again.",
     "اگر ناراضگی بھی ہے تب بھی دل کو تسلی دینے آ جاؤ، چاہے دوبارہ چھوڑ کر جانے کے لیے ہی سہی۔"),
    ("Ahmad Faraz", "احمد فراز", "Kohat / Islamabad, Pakistan", "1931 – 2008", "ur", "ishq", "Love & Romance",
     "اب کے ہم بچھڑے تو شاید کبھی خوابوں میں ملیں\nجس طرح سوکھے ہوئے پھول کتابوں میں ملیں",
     "If we part ways this time, perhaps we shall meet only in fleeting dreams, like dried petals pressed inside long-closed books.",
     "اگر اس بار ہماری جدائی ہوئی تو شاید خوابوں ہی میں ملاقات ہو، جیسے کتابوں کے اندر سوکھے ہوئے پھول ملتے ہیں۔"),
    ("Ahmad Faraz", "احمد فراز", "Kohat / Islamabad, Pakistan", "1931 – 2008", "ur", "ishq", "Love & Romance",
     "سنا ہے لوگ اسے آنکھ بھر کے دیکھتے ہیں\nسو اس کے شہر میں کچھ دن ٹھہر کے دیکھتے ہیں",
     "I hear people gaze upon her with wonder; so let us linger in her fair city for a few days to see for ourselves.",
     "سنا ہے کہ لوگ اس کے حسن کو حسرت سے دیکھتے ہیں، تو چلو ہم بھی اس کے شہر میں چند روز قیام کر کے دیکھتے ہیں۔"),
    ("Ahmad Faraz", "احمد فراز", "Kohat / Islamabad, Pakistan", "1931 – 2008", "ur", "ishq", "Love & Romance",
     "کروں نہ یاد تو ہر بات بھول جاتی ہے\nشمار کیجیے تو ہر اک ادا میں رہتا ہے",
     "If I try not to reminisce, everything fades away; yet if counted, they linger in every subtle gesture of life.",
     "اگر یاد نہ کروں تو لگتا ہے سب کچھ بھول گیا، مگر سوچوں تو وہ زندگی کی ہر ادا اور سانس میں بسا ہے۔"),

    # Parveen Shakir
    ("Parveen Shakir", "پروین شاکر", "Karachi / Islamabad, Pakistan", "1952 – 1994", "ur", "ishq", "Love & Romance",
     "عکسِ خوشبو ہوں بکھرنے سے نہ روکے کوئی\nاور بکھر جاؤں تو مجھ کو نہ سمیٹے کوئی",
     "I am the reflection of pure fragrance, let none hinder me from scattering; and when I disperse, let none attempt to gather me.",
     "میں خوشبو کا عکس ہوں مجھے فضا میں بکھرنے دو، اور جب میں بکھر جاؤں تو پھر کسی کو سمیٹنے کی زحمت نہ ہو۔"),
    ("Parveen Shakir", "پروین شاکر", "Karachi / Islamabad, Pakistan", "1952 – 1994", "ur", "ishq", "Love & Romance",
     "کمالِ ضبط کو خود بھی تو آزماؤں گی\nمیں اپنے ہاتھ سے اس کی دلہن سجاؤں گی",
     "I shall put my own supreme patience to the test: with my own hands I shall adorn the bride of my beloved.",
     "میں اپنے صبر اور حوصلے کی انتہا دیکھوں گی کہ خود اپنے ہاتھوں سے اس کے گھر کی خوشیاں سجاؤں گی۔"),
    ("Parveen Shakir", "پروین شاکر", "Karachi / Islamabad, Pakistan", "1952 – 1994", "ur", "dard", "Sorrow & Longing",
     "اب تو اس راہ سے وہ شخص گزرتا بھی نہیں\nاب کس امید پہ دروازے سے جھانکیں آنکھیں",
     "Now that person does not even pass by along this street; upon what lingering hope should my longing eyes peer through the doorway?",
     "اب تو وہ اس راستے سے گزرتا بھی نہیں، اب میری منتظر آنکھیں کس امید پر دروازے کی طرف دیکھیں۔"),

    # Jaun Elia
    ("Jaun Elia", "جون ایلیا", "Amroha, India / Karachi, Pakistan", "1931 – 2002", "ur", "ishq", "Love & Romance",
     "تم جب آؤ گی تو کھویا ہوا پاؤ گی مجھے\nمیری تنہائی میں خوابوں کے سوا کچھ بھی نہیں",
     "Whenever you arrive, you shall find me lost in reverie; in my profound solitude there remains nothing save dreams.",
     "جب تم آؤ گی تو مجھے اپنی ہی سوچوں میں گم پاؤ گی، میری تنہائی میں یادوں اور خوابوں کے سوا کچھ نہیں بچا۔"),
    ("Jaun Elia", "جون ایلیا", "Amroha, India / Karachi, Pakistan", "1931 – 2002", "ur", "falsafa", "Philosophy & Reflection",
     "عجب ہے جیت کے بھی ہم خسارے میں رہے\nوہ جیت کر بھی کوئی جشن منا نہ سکا",
     "How strange that even in victory we remained in sorrow; while the conqueror could celebrate no true triumph.",
     "عجیب ماجرا ہے کہ بظاہر جیت کر بھی ہم نقصان میں رہے، اور وہ بازی جیت کر بھی خوشی کا کوئی جشن نہ منا سکا۔"),
    ("Jaun Elia", "جون ایلیا", "Amroha, India / Karachi, Pakistan", "1931 – 2002", "ur", "dard", "Sorrow & Longing",
     "اب مری کوئی زندگی ہی نہیں\nاب بھی تم میری زندگی ہو کیا",
     "Now I possess no life of my own; are you even now the only life I have?",
     "اب تو میری اپنی کوئی زندگی باقی نہیں رہی، کیا اس عالم میں بھی تم ہی میری کل کائنات ہو؟"),

    # Mir Taqi Mir
    ("Mir Taqi Mir", "میر تقی میر", "Agra / Delhi / Lucknow, India", "1723 – 1810", "ur", "ishq", "Love & Romance",
     "الٹی ہو گئیں سب تدبیریں کچھ نہ دوا نے کام کیا\nدیکھا اس بیماریِ دل نے آخر کام تمام کیا",
     "All remedies turned upside down, no medicine proved of avail; you see how this malady of the heart finally accomplished our end.",
     "عشق کے علاج کی تمام تدبیریں الٹی پڑ گئیں اور کسی دوا نے اثر نہ کیا، آخر کار دل کے اس روگ نے کام تمام کر دیا۔"),
    ("Mir Taqi Mir", "میر تقی میر", "Agra / Delhi / Lucknow, India", "1723 – 1810", "ur", "dard", "Sorrow & Longing",
     "شام ہی سے بجھا سا رہتا ہے\nدل ہے گویا چراغِ مفلس کا",
     "From early dusk it remains dim and extinguished; the heart is as if the meager lamp of an impoverished pauper.",
     "شام ہوتے ہی دل بجھ سا جاتا ہے، جیسے کسی غریب اور نادار شخص کا تیل کے بغیر ٹمٹماتا ہوا چراغ ہو۔"),
    ("Mir Taqi Mir", "میر تقی میر", "Agra / Delhi / Lucknow, India", "1723 – 1810", "ur", "falsafa", "Philosophy & Reflection",
     "لے سانس بھی آہستہ کہ نازک ہے بہت کام\nآفاق کی اس کارگہِ شیشہ گری کا",
     "Draw even your breath softly, for delicate is the intricate work of this universe's grand glassblower's workshop.",
     "سانس بھی سنبھل کر اور آہستہ لو، کیونکہ یہ دنیا شیشے کے نازک کارخانے کی طرح ہے جو ذرا سی ٹھیس سے ٹوٹ جاتا ہے۔"),

    # Nasir Kazmi
    ("Nasir Kazmi", "ناصر کاظمی", "Ambala, India / Lahore, Pakistan", "1925 – 1972", "ur", "dard", "Sorrow & Longing",
     "دل میں اک لہر سی اٹھی ہے ابھی\nکوئی تازہ ہوا چلی ہے ابھی",
     "A gentle ripple has stirred within the heart just now; a fresh breath of wind has blown this very moment.",
     "ابھی ابھی دل میں یادوں کی ایک لہر اٹھی ہے، جیسے تازہ ہوا کا کوئی جھونکا چھو کر گزر گیا ہو۔"),
    ("Nasir Kazmi", "ناصر کاظمی", "Ambala, India / Lahore, Pakistan", "1925 – 1972", "ur", "dard", "Sorrow & Longing",
     "پھول سوکھے ہوئے بکھرے ہیں سرِ راہِ وفا\nکوئی گزرا ہے بہاروں کو لٹاتا ہوا سا",
     "Withered blossoms lie scattered along the boulevard of devotion; someone has passed by scattering the splendors of spring.",
     "وفا کی راہ پر مرجھائے ہوئے پھول بکھرے پڑے ہیں، جیسے کوئی بہاروں کا خزانہ لٹاتا ہوا رخصت ہو گیا ہو۔"),

    # Bahadur Shah Zafar
    ("Bahadur Shah Zafar", "بہادر شاہ ظفر", "Delhi, India / Rangoon, Burma", "1775 – 1862", "ur", "dard", "Sorrow & Longing",
     "بات کرنی مجھے مشکل کبھی ایسی تو نہ تھی\nجیسی اب ہے تری محفل کبھی ایسی تو نہ تھی",
     "Speaking was never before such an arduous trial for me; your assembly was never so cold and estranged as it is today.",
     "مجھ پر گفتگو کرنا کبھی اتنا کٹھن نہ تھا، اور تمہاری محفل بھی کبھی اتنی بے مروت اور اجنبی نہ تھی۔"),
    ("Bahadur Shah Zafar", "بہادر شاہ ظفر", "Delhi, India / Rangoon, Burma", "1775 – 1862", "ur", "falsafa", "Philosophy & Reflection",
     "نہ کسی کی آنکھ کا نور ہوں نہ کسی کے دل کا سرور ہوں\nجو کسی کے کام نہ آ سکے میں وہ ایک مشتِ غبار ہوں",
     "I am neither the light of anyone's eyes nor the joy of anyone's heart; I am merely a handful of dust that could serve no one's purpose.",
     "نہ میں کسی کی آنکھوں کی روشنی ہوں اور نہ دل کی خوشی، میں تو وہ بے کار مٹھی بھر خاک ہوں جو کسی کام نہ آئی۔"),

    # Momin Khan Momin
    ("Momin Khan Momin", "مومن خاں مومن", "Delhi, India", "1800 – 1851", "ur", "ishq", "Love & Romance",
     "شب جو مسجد میں جا پھنسے مومنؔ\nرات کاٹی خدا خدا کر کے",
     "When Momin found himself trapped in the ascetic sanctuary last night, he passed the entire night pleading desperately for release.",
     "رات کو جب مومن مسجد میں زاہدوں کے بیچ جا پھنسے، تو خدا خدا کر کے اور بڑی مشکلوں سے رات کاٹی۔"),
    ("Momin Khan Momin", "مومن خاں مومن", "Delhi, India", "1800 – 1851", "ur", "ishq", "Love & Romance",
     "رویا کریں گے آپ بھی پہروں اسی طرح\nاٹکا کہیں جو آپ کا دل بھی مری طرح",
     "You too will weep for endless hours in just this way, if ever your heart becomes hopelessly entangled like mine.",
     "اگر آپ کا دل بھی میری طرح کسی بے درد پر آ گیا، تو آپ بھی اسی طرح گھنٹوں آنسو بہایا کریں گے۔"),

    # Dagh Dehlvi
    ("Dagh Dehlvi", "داغؔ دہلوی", "Delhi / Hyderabad, India", "1831 – 1905", "ur", "ishq", "Love & Romance",
     "ہوش اڑتے ہیں مسکرانے سے\nجان جاتی ہے پاس آنے سے",
     "Senses take flight merely from their gentle smile; life itself departs whenever they draw close.",
     "محبوب کی ایک مسکراہٹ سے ہوش اڑ جاتے ہیں، اور ان کے قریب آنے سے دل کی دھڑکنیں قابو سے باہر ہو جاتی ہیں۔"),
    ("Dagh Dehlvi", "داغؔ دہلوی", "Delhi / Hyderabad, India", "1831 – 1905", "ur", "ishq", "Love & Romance",
     "عجب اپنا حال ہوتا جو وصالِ یار ہوتا\nکبھی جاں نثار ہوتی کبھی دل نثار ہوتا",
     "Wondrous indeed would be our condition had union with the beloved occurred; at times life would be offered in sacrifice, at times the heart.",
     "اگر محبوب کا وصال نصیب ہوتا تو کیا ہی کیفیت ہوتی، کبھی جان قربان کرتے تو کبھی دل نچھاور کرتے۔"),

    # Sahir Ludhianvi
    ("Sahir Ludhianvi", "ساحر لدھیانوی", "Ludhiana / Mumbai, India", "1921 – 1980", "ur", "inqilab", "Revolution & Hope",
     "اک شہنشاہ نے دولت کا سہارا لے کر\nہم غریبوں کی محبت کا اڑایا ہے مذاق",
     "An emperor relying upon boundless wealth has mocked the genuine love of us impoverished souls in the Taj Mahal.",
     "شہنشاہ نے اپنی بے پناہ دولت کی نمائش کر کے ہم غریبوں کی سچی اور بے لوث محبت کی توہین کی ہے۔"),
    ("Sahir Ludhianvi", "ساحر لدھیانوی", "Ludhiana / Mumbai, India", "1921 – 1980", "ur", "inqilab", "Revolution & Hope",
     "آؤ کہ کوئی خواب بنیں کل کے واسطے\nورنہ یہ رات آج کے دکھ بھی نہ دھو سکے",
     "Come, let us weave a hopeful dream for tomorrow; otherwise this somber night cannot even wash away today's sorrow.",
     "آؤ مل کر کل کے روشن مستقبل کا نیا خواب دیکھیں، ورنہ یہ اداس رات ہمارے آج کے دکھوں کو بھی نہیں دھو سکے گی۔"),

    # Kaifi Azmi
    ("Kaifi Azmi", "کیفی اعظمی", "Azamgarh / Mumbai, India", "1919 – 2002", "ur", "inqilab", "Revolution & Hope",
     "کر چلے ہم فدا جان و تن ساتھیو\nاب تمہارے حوالے وطن ساتھیو",
     "We have laid down our life and soul, dear companions; now the homeland is entrusted into your faithful hands.",
     "ہم نے وطن کے لیے اپنی جان اور تن قربان کر دیا ہے، اب اس پاک دھرتی کی حفاظت تمہارے حوالے ہے۔"),
    ("Kaifi Azmi", "کیفی اعظمی", "Azamgarh / Mumbai, India", "1919 – 2002", "ur", "ishq", "Love & Romance",
     "جھکی جھکی سی نظر بے قرار ہے کہ نہیں\nدبا دبا سا سہی دل میں پیار ہے کہ نہیں",
     "Is that lowered bashful gaze restless with longing or not? Suppressed though it may be, does love dwell in the heart or not?",
     "تمہاری جھکی ہوئی پلکوں میں بے قراری چھپی ہے یا نہیں، سچ بتاؤ کہ دل کے گوشے میں محبت کی چنگاری ہے یا نہیں۔"),

    # Habib Jalib
    ("Habib Jalib", "حبیب جالب", "Hoshiarpur, India / Lahore, Pakistan", "1928 – 1993", "ur", "inqilab", "Revolution & Hope",
     "دیپ جس کا محلات ہی میں جلے\nچند لوگوں کی خوشیوں کو لے کر چلے\nوہ جو سائے میں ہر مصلحت کے پلے\nایسے دستور کو صبحِ بے نور کو\nمیں نہیں مانتا میں نہیں جانتا",
     "The lamp that flickers only within royal palaces, serving the luxuries of an elite few: I refuse to acknowledge such unjust rule!",
     "جو نظام صرف امیروں کے محلات کو روشن کرے اور غریبوں کے حقوق چھینے، میں ایسے جابرانہ قانون کو ماننے سے انکار کرتا ہوں۔"),
    ("Habib Jalib", "حبیب جالب", "Hoshiarpur, India / Lahore, Pakistan", "1928 – 1993", "ur", "inqilab", "Revolution & Hope",
     "شہر میں ہو کا عالم تھا جب ہم بولے\nخاموشیوں کا پردہ ہٹا جب ہم بولے",
     "A desolate silence reigned across the terrified city when we spoke; the veil of fearful silence was torn when we raised our voice.",
     "جب ظلم کے خوف سے پورا شہر خاموش تھا تب ہم نے کلمۂ حق کہا اور گونگی خاموشی کا پردہ چاک کیا۔"),

    # Josh Malihabadi
    ("Josh Malihabadi", "جوش ملیح آبادی", "Malihabad, India / Islamabad, Pakistan", "1898 – 1982", "ur", "inqilab", "Revolution & Hope",
     "روایتوں کے تلے دب کے مر گئے لاکھوں\nحیات نام ہے زنجیر توڑ دینے کا",
     "Millions perished crushed under the weight of blind traditions; true life is the noble name for shattering the chains.",
     "فرسودہ رسم و رواج اور غلامی کے تلے لاکھوں لوگ دب کر ختم ہو گئے، حقیقی زندگی تو جبر کی زنجیریں توڑنے کا نام ہے۔"),

    # Jigar Moradabadi
    ("Jigar Moradabadi", "جگر مراد آبادی", "Moradabad, India", "1890 – 1960", "ur", "ishq", "Love & Romance",
     "آدمی آدمی سے ملتا ہے\nدل مگر کم کسی سے ملتا ہے",
     "Human beings meet other human beings constantly; yet rarely does heart truly meet with heart in sincere communion.",
     "لوگ ظاہری طور پر ایک دوسرے سے روز ملتے ہیں، مگر دل سے دل کا سچا ملاپ بہت کم لوگوں کو نصیب ہوتا ہے۔"),
    ("Jigar Moradabadi", "جگر مراد آبادی", "Moradabad, India", "1890 – 1960", "ur", "ishq", "Love & Romance",
     "جان ہی دے دی جگرؔ نے آج پائے یار پر\nعمر بھر کی بے قراری کو قرار آ ہی گیا",
     "Jigar has surrendered his very life at the feet of the beloved today; at long last, a lifetime of restlessness found eternal peace.",
     "جگر نے آج محبوب کے قدموں میں اپنی جان نچھاور کر دی، اور عمر بھر کی تڑپ کو بالآخر دائمی سکون مل گیا۔"),

    # Hasrat Mohani
    ("Hasrat Mohani", "حسرت موہانی", "Mohan / Kanpur, India", "1875 – 1951", "ur", "inqilab", "Revolution & Hope",
     "ہے مشقِ سخن جاری چکی کی مشقت بھی\nاک طرفہ تماشا ہے حسرتؔ کی طبیعت بھی",
     "The poetic composition continues alongside the grueling labor of turning the prison millstone; wondrous indeed is Hasrat's resilient spirit!",
     "قید خانے میں چکی کی مشقت بھی چل رہی ہے اور شعر و سخن کا سفر بھی جاری ہے، حسرت کی ہمت واقعی بے مثال ہے۔"),

    # Firaq Gorakhpuri
    ("Firaq Gorakhpuri", "فراق گورکھپوری", "Gorakhpur / Allahabad, India", "1896 – 1982", "ur", "ishq", "Love & Romance",
     "سرزمینِ ہند پر اقوامِ عالم کے فراقؔ\nقافلے آتے گئے اور ہندوستاں بنتا گیا",
     "Upon the sacred soil of India, O Firaq, caravans of diverse world nations kept arriving, and this grand composite culture took shape.",
     "اس دھرتی پر دنیا بھر کی قوموں اور تہذیبوں کے قافلے آتے رہے اور باہمی میل جول سے یہ خوبصورت گلستان بن گیا۔"),

    # Ibn-e-Insha
    ("Ibn-e-Insha", "ابنِ انشا", "Jalandhar, India / Karachi, Pakistan", "1927 – 1978", "ur", "ishq", "Love & Romance",
     "کل چودھویں کی رات تھی شب بھر رہا چرچا ترا\nکچھ نے کہا یہ چاند ہے کچھ نے کہا چہرہ ترا",
     "Last night was the full fourteenth moon, all night your praises resonated; some said 'This is the luminous moon,' others said 'It is your glowing countenance.'",
     "گزشتہ رات چودھویں کا پورا چاند تھا اور رات بھر تمہارا ہی ذکر رہا، کوئی اسے فلک کا چاند کہہ رہا تھا تو کوئی تمہارا رخسار۔"),
    ("Ibn-e-Insha", "ابنِ انشا", "Jalandhar, India / Karachi, Pakistan", "1927 – 1978", "ur", "dard", "Sorrow & Longing",
     "ہم رات بہت روئے، اللہ ہی جانتا ہے\nکس جرم کی پاداش میں آنسو یہ بہے ہیں",
     "We wept profusely through the silent night, God alone knows in retribution for what unknown sin these tears poured forth.",
     "ہم نے رات کے اندھیرے میں زار و قطار آنسو بہائے، خدا ہی بہتر جانتا ہے کہ کس دکھ اور خطا کے بدلے یہ دل رویا ہے۔"),

    # Mohsin Naqvi
    ("Mohsin Naqvi", "محسن نقوی", "Dera Ghazi Khan / Lahore, Pakistan", "1947 – 1996", "ur", "dard", "Sorrow & Longing",
     "شام کے بعد جب بھی یاد آئی تیری\nہم نے اشکوں کے چراغوں سے سجائی دنیا",
     "Whenever your tender memory arrived after dusk, we adorned the solitude of the world with lamps of glistening tears.",
     "شام ڈھلنے کے بعد جب بھی تیری یاد نے دل پر دستک دی، ہم نے اپنی ویران دنیا کو آنسوؤں کی شمعوں سے روشن کر دیا۔"),
    ("Mohsin Naqvi", "محسن نقوی", "Dera Ghazi Khan / Lahore, Pakistan", "1947 – 1996", "ur", "ishq", "Love & Romance",
     "وہ اک پل جو تیرے قرب میں گزرا تھا کبھی\nآج بھی اس کی مہک سے ہے معطر یہ حیات",
     "That single fleeting moment once spent in your comforting closeness: even today life remains perfumed by its gentle fragrance.",
     "وہ ایک لمحہ جو کبھی تمہارے ساتھ ہنستے مسکراتے گزرا تھا، آج بھی اس کی مہک میری زندگی کو معطر کیے ہوئے ہے۔"),

    # Saghar Siddiqui
    ("Saghar Siddiqui", "ساغر صدیقی", "Ambala, India / Lahore, Pakistan", "1928 – 1974", "ur", "falsafa", "Philosophy & Reflection",
     "جس عہد میں لٹ جائے فقیروں کی کمائی\nاس عہد کے سلطان سے کوئی بھول ہوئی ہے",
     "In that era when the meager crust of destitute mendicants is plundered, the reigning monarch of that realm has committed a fatal injustice.",
     "جس دور میں غریبوں اور فقیروں کی روزی چھن جائے، سمجھ لو کہ اس ملک کے حکمران نے کوئی بہت بڑی ناانصافی کی ہے۔"),

    # Shakeel Badayuni
    ("Shakeel Badayuni", "شکیل بدایونی", "Badaun / Mumbai, India", "1916 – 1970", "ur", "ishq", "Love & Romance",
     "میرے ہم نفس میرے ہم نوا مجھے دوست بن کے دغا نہ دے\nمیں ہوں دردِ عشق کا مارا ہوا مجھے بے وجہ یوں سزا نہ دے",
     "O my companion, my confidant: do not betray me beneath the comforting mask of friendship; I am already wounded by love.",
     "اے میرے ہم سفر اور دوست! مجھے دوستی کے روپ میں دھوکا نہ دو، میں تو پہلے ہی محبت کا زخمی ہوں مجھے مزید نہ آزماؤ۔"),

    # Qateel Shifai
    ("Qateel Shifai", "قتیل شفائی", "Haripur, Pakistan", "1919 – 2001", "ur", "ishq", "Love & Romance",
     "پریشاں رات ساری ہے ستارو تم تو سو جاؤ\nسکوتِ مرگ طاری ہے ستارو تم تو سو جاؤ",
     "The entire night is fraught with distress, O stars, you at least may slumber; the stillness of grief reigns over all.",
     "میری پوری رات بے قراری میں کٹ رہی ہے اے ستارو تم تو سو جاؤ، چاروں طرف گہرا سناٹا ہے تم اپنی آنکھیں موند لو۔"),

    # Nida Fazli
    ("Nida Fazli", "ندا فاضلی", "Gwalior / Mumbai, India", "1938 – 2016", "ur", "falsafa", "Philosophy & Reflection",
     "گھر سے نکلے تو راہ میں پتھر ہزار تھے\nپر اپنے ہی قدم تھے جو بار بار ڈگمگائے",
     "When we set forth from home, a thousand stones lay along the path; yet it was our own hesitant steps that faltered time and again.",
     "جب منزل کی طرف چلے تو راستے میں ہزاروں رکاوٹیں تھیں، لیکن اصل آزمائش ہمارے اپنے ڈگمگاتے قدموں کی تھی۔"),

    # Bashir Badr
    ("Bashir Badr", "بشir بدر", "Kanpur / Bhopal, India", "1935 – Present", "ur", "ishq", "Love & Romance",
     "آنکھوں میں رہا دل میں اتر کر نہیں دیکھا\nکشتی کے مسافر نے سمندر نہیں دیکھا",
     "They lingered only in the gaze, never descending into the heart; like a boat traveler who never truly perceived the depth of the ocean.",
     "وہ صرف آنکھوں کے سامنے رہے کبھی دل کی گہرائی میں اتر کر نہ دیکھا، جیسے کشتی کے مسافر نے سمندر کے اصل راز کو نہ جانا ہو۔"),
    ("Bashir Badr", "بشیر بدر", "Kanpur / Bhopal, India", "1935 – Present", "ur", "ishq", "Love & Romance",
     "کوئی ہاتھ بھی نہ ملائے گا جو گلے ملو گے تپاک سے\nیہ نئے مزاج کا شہر ہے ذرا فاصلے سے ملا کرو",
     "No one will even shake your hand if you embrace with passionate warmth; this is a modern distant town—greet others with measured caution.",
     "اگر تم والہانہ انداز سے گلے ملو گے تو لوگ ہاتھ بھی نہیں ملائیں گے، یہ نئے زمانے کا شہر ہے یہاں ذرا فاصلہ رکھ کر ملو۔"),

    # Rahat Indori
    ("Rahat Indori", "راحت اندوری", "Indore, India", "1950 – 2020", "ur", "inqilab", "Revolution & Hope",
     "اگر خلاف ہیں ہونے دو جان تھوڑی ہے\nیہ سب دھواں ہے کوئی آسماں تھوڑی ہے",
     "If they stand in opposition, let them be; life itself is not hanging by their favor! All this noise is mere transient smoke, not the firmament!",
     "اگر لوگ مخالف ہیں تو ہونے دو اس سے جان نہیں جاتی، یہ وقتی پروپیگنڈا دھواں ہے جو جلد چھٹ جائے گا۔"),
    ("Rahat Indori", "راحت اندوری", "Indore, India", "1950 – 2020", "ur", "inqilab", "Revolution & Hope",
     "لگے گی آگ تو آئیں گے گھر کئی زد میں\nیہاں پہ صرف ہمارا مکان تھوڑی ہے",
     "If the blaze ignites, numerous dwellings will be engulfed; our modest house is not the only home standing in this neighborhood.",
     "اگر نفرت کی آگ بھڑکی تو کئی گھر اس کی لپیٹ میں آئیں گے، اس بستی میں صرف ہمارا گھر تو نہیں رہتا۔"),

    # Wasif Ali Wasif
    ("Wasif Ali Wasif", "واصف علی واصف", "Khushab / Lahore, Pakistan", "1929 – 1993", "ur", "falsafa", "Philosophy & Reflection",
     "دل اگر بیدار ہو تو کائنات اک آئینہ ہے\nہر ذرے میں جلوۂ حق عیاں دکھائی دیتا ہے",
     "If the heart is spiritually awake, the entire universe becomes a clear mirror; in every atom the radiant manifestation of Divine Truth shines forth.",
     "اگر انسان کا دل باطنی طور پر بیدار ہو تو ساری کائنات ایک آئینہ بن جاتی ہے، جہاں ہر ذرے میں رب کا جلوہ نظر آتا ہے۔"),
    ("Wasif Ali Wasif", "واصف علی واصف", "Khushab / Lahore, Pakistan", "1929 – 1993", "ur", "dua", "Dua & Blessings",
     "راحتِ قلب و جاں ہے تری یاد میں مولا\nتیرا کرم رہے تو ہر مشکل آسان ہے",
     "Solace of heart and soul is found in Thy remembrance, O Lord; when Thy grace shines, every trial transforms into ease.",
     "اے اللہ! تیری یاد میں دل اور روح کا سچا سکون ہے، تیرا فضل و کرم شاملِ حال ہو تو ہر کٹھن منزل آسان ہو جاتی ہے۔"),

    # Amjad Islam Amjad
    ("Amjad Islam Amjad", "امجد اسلام امجد", "Lahore, Pakistan", "1944 – 2023", "ur", "ishq", "Love & Romance",
     "محبت ایسی بارش ہے جسے چھونے کی خواہش میں\nکبھی پلکیں بھیگ جاتی ہیں کبھی دامن بھیگ جاتا ہے",
     "Love is that gentle rain in whose yearning embrace at times the eyelashes are drenched, and at times the hem of the robe.",
     "محبت وہ برسات ہے جس کی خواہش میں انسان کبھی آنکھوں سے رو پڑتا ہے اور کبھی اس کا دامن تر ہو جاتا ہے۔"),
    ("Amjad Islam Amjad", "امجد اسلام امجد", "Lahore, Pakistan", "1944 – 2023", "ur", "ishq", "Love & Romance",
     "یہ موسمِ گل بھی گزر جائے گا اک روز\nرہ جائے گی یادوں کی مہک دل کے نگر میں",
     "This season of blooming roses too shall pass one day; only the fragrant memory shall linger in the township of the heart.",
     "بہار کا یہ خوبصورت موسم بھی ایک دن بیت جائے گا، مگر دل کی بستی میں خوشگوار یادوں کی مہک سدا قائم رہے گی۔"),

    # Munir Niazi (Urdu)
    ("Munir Niazi", "منیر نیازی", "Khanpur, India / Lahore, Pakistan", "1928 – 2006", "ur", "ishq", "Love & Romance",
     "ہمیشہ دیر کر دیتا ہوں میں ہر کام کرنے میں\nضروری بات کہنی ہو کوئی وعدہ نبھانا ہو\nہمیشہ دیر کر دیتا ہوں میں",
     "I invariably arrive too late in executing every vital task; whether to confess an essential truth or to fulfill a solemn promise.",
     "میں ہر ضروری کام میں ہمیشہ دیر کر دیتا ہوں، چاہے دل کا راز کہنا ہو یا کسی سے کیا ہوا وعدہ نبھانا ہو۔"),

    # Zehra Nigah
    ("Zehra Nigah", "زہرا نگاہ", "Hyderabad, India / Karachi, Pakistan", "1937 – Present", "ur", "ishq", "Love & Romance",
     "سنو اک بات کہتی ہوں کہ دنیا بے مروت ہے\nوفا کے موتیوں کو خاک میں ملنے نہیں دینا",
     "Listen, I impart a truth to you: this worldly realm is ungrateful; never allow the precious pearls of your loyalty to be crushed into the dust.",
     "میری یہ بات یاد رکھنا کہ دنیا بڑی بے مروت ہے، اپنے خلوص اور وفا کے قیمتی موتیوں کو کبھی ضائع مت ہونے دینا۔"),

    # Kishwar Naheed
    ("Kishwar Naheed", "کشور ناہید", "Bulandshahr, India / Islamabad, Pakistan", "1940 – Present", "ur", "inqilab", "Revolution & Hope",
     "یہ ہم گنہگار عورتیں ہیں جو اہل جُبّہ کی تمکنت سے نہ رعب کھائیں\nنہ جان بیچیں، نہ سر جھکائیں",
     "It is we so-called sinful women who fear not the arrogant swagger of the sanctimonious; who sell not our souls nor bow our heads.",
     "ہم وہ باہمت عورتیں ہیں جو ظالموں کے رعب میں نہیں آتیں، نہ اپنی عزت کا سودا کرتی ہیں اور نہ سر جھکاتی ہیں۔"),

    # Ahmad Nadeem Qasmi
    ("Ahmad Nadeem Qasmi", "احمد ندیم قاسمی", "Sargodha / Lahore, Pakistan", "1916 – 2006", "ur", "dua", "Dua & Blessings",
     "خدا کرے کہ مری ارضِ پاک پر اترے\nوہ فصلِ گل جسے اندیشۂ زوال نہ ہو",
     "May God grant that upon my sacred homeland descends that glorious spring of blooming roses which knows no fear of decay.",
     "اللہ کرے کہ میری پاک سرزمین پر ایسی سدا بہار خوشحالی اترے جس کو کبھی زوال اور خزاں کا خطرہ نہ ہو۔"),
    ("Ahmad Nadeem Qasmi", "احمد ندیم قاسمی", "Sargodha / Lahore, Pakistan", "1916 – 2006", "ur", "falsafa", "Philosophy & Reflection",
     "کون کہتا ہے کہ موت آئی تو مر جاؤں گا\nمیں تو دریا ہوں سمندر میں اتر جاؤں گا",
     "Who says that when death arrives I shall perish? I am a mighty river; I shall merely merge into the vast eternal ocean.",
     "کون کہتا ہے کہ موت مجھے ختم کر دے گی، میں تو ایک رواں دریا ہوں جو فنا ہو کر بھی وسیع سمندر میں مل جائے گا۔"),

    # PUNJABI AUTHENTIC
    ("Baba Bulleh Shah", "بابا بلھے شاہ", "Kasur, Punjab", "1680 – 1757", "pa", "falsafa", "Philosophy & Reflection",
     "نہ کر خودی گمان نی کڑئے، خالی ہتھ سدھاریں گی\nاک دن مٹی دے وچ ملنا، ایتھے کی کجھ ہاریں گی",
     "Harbor no vain pride, dear soul; with empty hands you shall depart. One day you must return to earth—why lose humility here?",
     "اے انسان تکبر و غرور نہ کر، آخر کار خالی ہاتھ ہی رخصت ہونا ہے؛ ایک دن مٹی میں ملنا ہے تو یہاں نیکی اور عاجزی کیوں نہ کمائی جائے؟"),
    ("Baba Bulleh Shah", "بابا بلھے شاہ", "Kasur, Punjab", "1680 – 1757", "pa", "ishq", "Love & Romance",
     "جے توں اپنے یار نوں پاویں، سولی تے چڑھ کے ویکھ لے\nعشق نہ پچھے ذات صفاتاں، دل نال دل نوں جوڑ لے",
     "If you wish to attain your Beloved, look upon the path of sacrifice; true love cares nothing for lineage, it binds heart to heart.",
     "اگر تم اپنے محبوب کو پانا چاہتے ہو تو ایثار و قربانی کے راستے پر چلو؛ عشق ذات پات نہیں پوچھتا بلکہ دلوں کو دلوں سے جوڑتا ہے۔"),
    ("Baba Bulleh Shah", "بابا بلھے شاہ", "Kasur, Punjab", "1680 – 1757", "pa", "ishq", "Love & Romance",
     "اٹھ گئے گوانڈھوں یار ربّا ہن کی کریئے\nپھوک مصلّی بھن سٹ کاسہ، عشقے دا کوئی تیر چلا",
     "The beloved neighbor has departed, O Lord, what shall I do now? Cast away empty rituals and kindle the arrow of authentic love!",
     "پڑوس سے محبوب بچھڑ گیا، اے خدا اب ہم کیا کریں؛ ظاہری رسومات چھوڑ کر عشق کی سچی آگ اپنے اندر جلاؤ۔"),
    ("Baba Bulleh Shah", "بابا بلھے شاہ", "Kasur, Punjab", "1680 – 1757", "pa", "falsafa", "Philosophy & Reflection",
     "الٹے سلٹے ہور کماں نوں، اپنا وقت گوائی دا\nاک الف پڑھو چھٹکارا ہے، دل نوں سچا لائی دا",
     "In trivial, upside-down affairs we squander our precious time; learn the single truth of Alif for salvation, and dedicate a sincere heart.",
     "فضول اور بے معنی کاموں میں وقت ضائع نہ کرو، اللہ کے ایک نام کی سچی لگن اپناؤ اسی میں دونوں جہانوں کی نجات ہے۔"),
    ("Sultan Bahu", "سلطان باہو", "Shorekot, Jhang, Punjab", "1628 – 1691", "pa", "falsafa", "Philosophy & Reflection",
     "نئیں جے رب ملدا نہاتے دھوتیاں، ملدا ڈڈواں مچھیاں ھو\nجے رب ملدا جنگل بیلے، ملدا گائیں وچھیاں ھو\nرب ملدا اے دل سچے نال، نیت پاک سچائی ھو",
     "If God were found merely through ritual baths, frogs and fish would find Him; if in lonely jungles, the grazing calves would find Him! God is attained through an honest heart and pure intention.",
     "اگر رب صرف نہانے دھونے سے ملتا تو مینڈک اور مچھلیاں پا لیتیں، اور اگر جنگلوں میں ملتا تو گائیں بچھڑے پا لیتے؛ رب تو سچے دل اور پاک نیت سے ملتا ہے۔"),
    ("Sultan Bahu", "سلطان باہو", "Shorekot, Jhang, Punjab", "1628 – 1691", "pa", "dua", "Dua & Blessings",
     "جیوندی ماں نوں خبر نہ کوئی، موئیاں نوں کی روندی ھو\nسچا مرشد مل پیا باہو، ہر دکھ دور کریندی ھو",
     "Honor and cherish your living mother while she is with you; when a true spiritual guide is found, O Bahu, all inner sorrow departs.",
     "زندہ ماں کی قدر کرو اس کی خدمت ہی اصل سعادت ہے، اور کامل مرشد کے فیض سے دل کے سارے دکھ مٹ جاتے ہیں۔"),
    ("Waris Shah", "سید وارث شاہ", "Jandiala Sher Khan, Punjab", "1722 – 1798", "pa", "ishq", "Love & Romance",
     "وارث شاہ لُکائیے کِنج اس نوں، جیہڑا عشق چھپایا نئیں لُکدا\nچن چڑھیا کدی نہ لُکے بدلیں، دریا دا وگنا نئیں مُکدا",
     "O Waris Shah, how could one conceal love that can never be hidden? The risen moon cannot hide in clouds, nor can a mighty river cease flowing.",
     "اے وارث شاہ! عشق کو کیسے چھپایا جائے جو چھپائے نہیں چھپتا؛ چاند بادلوں میں نہیں چھپ سکتا اور دریا کبھی بہنے سے نہیں رکتا۔"),
    ("Waris Shah", "سید وارث شاہ", "Jandiala Sher Khan, Punjab", "1722 – 1798", "pa", "ishq", "Love & Romance",
     "ڈاڈھی ڈاہڈی ایہ پریت انوکھڑی اے، وارث شاہ نوں لگ گئی تیر وانگوں\nجس تن لگدی اوہی جانے، ہور دسے کی تدبیر وانگوں",
     "Mighty and wondrous is this love, it struck Waris Shah like an inescapable arrow; only the body that endures the wound knows its truth.",
     "محبت کا تیر وارث شاہ کے دل پر کاری لگا ہے، اور یہ درد وہی جانتا ہے جس کے دل پر یہ زخم لگا ہو۔"),
    ("Mian Muhammad Bakhsh", "میاں محمد بخش", "Mirpur, Kashmir / Punjab", "1830 – 1907", "pa", "falsafa", "Philosophy & Reflection",
     "خاصاں دی گل عاماں اگے، نئیں مناسب کرنی\nمٹھی کھیر پکا محمدؔ، کُتیاں اگے دھرنی",
     "Sharing wisdom of the enlightened with the unheeding is unwise; like preparing sweet pudding and placing it before dogs.",
     "معرفت اور حکمت کی گہری باتیں بے قدرے لوگوں کے سامنے کرنا ایسا ہی ہے جیسے میٹھی کھیر پکا کر قدر نہ جاننے والوں کے سامنے رکھ دی جائے۔"),
    ("Mian Muhammad Bakhsh", "میاں محمد بخش", "Mirpur, Kashmir / Punjab", "1830 – 1907", "pa", "dosti", "Friendship & Loyalty",
     "جیڑھے لوک نہ قدر پچھانن، اوہناں کول نہ بہیئے\nاوکھے ویلے نال کھلووے، اوہی سجن کہیئے",
     "Do not keep company with those who fail to recognize true worth; only he who stands steadfast in trial is a true friend.",
     "جو لوگ قدر نہیں پہچانتے ان کی صحبت میں نہ بیٹھو؛ سچا دوست وہی ہے جو مشکل وقت میں تمہارے ساتھ مضبوطی سے کھڑا رہے۔"),
    ("Amrita Pritam", "امرتا پریتم", "Gujranwala / Delhi", "1919 – 2005", "pa", "dard", "Sorrow & Longing",
     "اج آکھاں وارث شاہ نوں، کِتھوں قبراں وچوں بول\nتے اج کتابِ عشق دا، کوئی اگلا ورقہ پھول",
     "Today I call upon Waris Shah: speak out from your grave! Turn to the next tragic page in the grand book of love!",
     "آج میں وارث شاہ کو پکارتی ہوں کہ قبر سے بول اٹھو، اور آج محبت اور انسانیت کی کتاب کا اگلا درد بھرا صفحہ کھولو۔"),
    ("Shah Hussain", "شاہ حسین", "Lahore, Punjab", "1538 – 1599", "pa", "dard", "Sorrow & Longing",
     "مائے نی میں کینوں آکھاں درد وچھوڑے دا حال نی\nدکھاں دی روٹی سولاں دا سالن، ہڈاں دا بالن بال نی",
     "O mother, to whom shall I tell the agony of my separation? Bread of sorrow, curry of thorns, and the fire lit with bones.",
     "اے ماں! میں اپنے دل کا دکھ اور ہجر کا درد کسے سناؤں، میرے دکھوں کی روٹی ہے اور کانٹوں کا سالن ہے۔"),
    ("Khwaja Ghulam Farid", "خواجہ غلام فرید", "Chacharan Sharif, Punjab", "1845 – 1901", "pa", "ishq", "Love & Romance",
     "روہی دی ریت تے روواں رانجھن یار پئی ڈھونڈاں\nسہج سہاگ سہاوا تھیوے، پریم نگر دی پیت نبھاواں",
     "Upon the sands of the Rohi desert I weep, searching for my beloved Ranjhan; let divine love grace my existence.",
     "چولستان کے صحراؤں میں رانجھن کی تلاش میں روتی پھرتی ہوں، کاش محبت کا یہ سفر منزل تک پہنچ جائے۔"),
    ("Shiv Kumar Batalvi", "شِو کمار بٹالوی", "Bara Pind / Batala, Punjab", "1936 – 1973", "pa", "dard", "Sorrow & Longing",
     "اساں تاں جوبن رُتے مرنا، مُڑ نئیں جوبن رُتے مِلنا\nتُر جانا اساں چپ چپیتے، پچھوں کجھ نہ کسے نے کَہنا",
     "We are destined to depart in the radiant prime of youth; quietly we shall slip away, and none shall utter a word behind us.",
     "ہم نے جوانی کی رُت ہی میں اس دنیا سے کوچ کر جانا ہے، خاموشی سے رخصت ہو جائیں گے اور پیچھے کوئی نام لینے والا نہ ہوگا۔"),

    # ARABIC MASTERPIECES
    ("Al-Mutanabbi", "المتنبی", "Kufa, Iraq", "915 – 965", "ar", "inqilab", "Revolution & Hope",
     "الخَيْلُ وَاللّيْلُ وَالبَيْداءُ تَعرِفُني\nوَالسّيفُ وَالرّمحُ والقرْطاسُ وَالقَلَمُ",
     "The steeds, the dark night, and the desert know me well; as do the sword, the spear, the parchment, and the pen.",
     "گھوڑے، تاریک رات اور صحرا مجھے خوب پہچانتے ہیں؛ اور تلوار، نیزہ، کاغذ اور قلم بھی میری فصاحت و شجاعت کے گواہ ہیں۔"),
    ("Al-Mutanabbi", "المتنبی", "Kufa, Iraq", "915 – 965", "ar", "falsafa", "Philosophy & Reflection",
     "عَلى قَدْرِ أهْلِ العَزْم تأتي العَزائِمُ\nوَتأتِي علَى قَدْرِ الكِرامِ المَكارمُ",
     "Noble endeavors are realized according to the resolve of great souls; generous deeds correspond to the magnanimity of the honorable.",
     "عظیم کارنامے بلند حوصلہ اور باہمت انسانوں کے عزم کے مطابق انجام پاتے ہیں، اور عزت والے لوگ ہی عظیم مقاصد حاصل کرتے ہیں۔"),

    # PERSIAN MASTERPIECES
    ("Saadi Shirazi", "سعدی شیرازی", "Shiraz, Iran", "1210 – 1291", "fa", "falsafa", "Philosophy & Reflection",
     "بنی‌آدم اعضای یکدیگرند\nکه در آفرینش ز یک گوہرند",
     "Human beings are members of one body, for in creation they are born of one essence.",
     "تمام انسان ایک دوسرے کے اعضا کی مانند ہیں کیونکہ ان کی تخلیق ایک ہی جوہر سے ہوئی ہے۔"),
    ("Saadi Shirazi", "سعدی شیرازی", "Shiraz, Iran", "1210 – 1291", "fa", "dosti", "Friendship & Loyalty",
     "درخت دوستی بنشان که کام دل به بار آرد\nنهال دشمنی برکن که رنج بی‌شمار آرد",
     "Plant the tree of friendship so that heart's desires may blossom into fruit; uproot enmity, for it brings boundless grief.",
     "دوستی کا درخت لگاؤ تاکہ دل کی مراد کا میٹھا پھل ملے، اور دشمنی کے پودے کو جڑ سے اکھاڑ پھینکو جو بے انتہا دکھ دیتا ہے۔"),
    ("Jalaluddin Rumi", "مولانا جلال الدین رومی", "Balkh / Konya", "1207 – 1273", "fa", "ishq", "Love & Romance",
     "بشنو از نی چون حکایت می‌کند\nاز جدایی‌ها شکایت می‌کند",
     "Listen to the reed flute as it tells its tale, lamenting the bitter pain of separation from its source.",
     "بانسری کی آواز سنو جب وہ اپنی بپتا سناتی ہے اور اصل وطن سے بچھڑنے کا نوحہ بیان کرتی ہے۔"),
    ("Hafez Shirazi", "حافظ شیرازی", "Shiraz, Iran", "1315 – 1390", "fa", "ishq", "Love & Romance",
     "اگر آن ترک شیرازی به دست آرد دل ما را\nبه خال هندویش بخشم سمرقند و بخارا را",
     "If that Shirazi beauty accepts my heart, for the dark mole on her cheek I would bestow Samarqand and Bukhara.",
     "اگر وہ شیراز کی حسینہ میرے دل کی قدر کرے تو اس کے چہرے کے تل کے بدلے میں سمرقند اور بخارا جیسے عظیم شہر قربان کر دوں۔"),
    ("Omar Khayyam", "عمر خیام", "Nishapur, Iran", "1048 – 1131", "fa", "falsafa", "Philosophy & Reflection",
     "خیام اگر ز باده مستی خوش باش\nبا ماه رخی اگر نشستی خوش باش\nچون عاقبتِ کار جهان نیستی است\nانگار که نیستی چو هستی خوش باش",
     "O Khayyam, if you rejoice in wine, be glad; if you sit with a moon-faced beauty, be glad; since the end of the world is non-existence, consider that you are not, and while you exist, be glad!",
     "اے خیام! اگر تم پر سرور کی کیفیت طاری ہے تو خوش رہو، جب اس دنیا کا انجام مٹ جانا ہی ہے تو جو لمحات میسر ہیں ان میں خوش رہو۔")
]

print(f"Loaded {len(CLASSICAL_SHERS)} classical core masterpieces.")
