# -*- coding: utf-8 -*-
"""
Authentic Classical & Modern Urdu Couplets for Ishq & Gham.
Each entry is a tuple:
(m1, m2, poet, poet_urdu, roman, english, category, category_label)
"""

ISHQ_GHAM_CORPUS = [
    # --- MIRZA GHALIB ---
    ("عشق پر زور نہیں ہے یہ وہ آتش غالبؔ", "کہ لگائے نہ لگے اور بجھائے نہ بنے", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Ishq par zor nahin hai yeh woh aatish Ghalib, Ke lagaye na lage aur bujhaye na bane",
     "Love is not governed by will, O Ghalib; it is that flame which cannot be kindled by design nor extinguished when ablaze.", "ishq", "Love & Romance"),
    ("ہزاروں خواہشیں ایسی کہ ہر خواہش پہ دم نکلے", "بہت نکلے مرے ارمان لیکن پھر بھی کم نکلے", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Hazaaron khwahishein aisi ke har khwahish pe dam nikle, Bohat nikle mere armaan lekin phir bhi kam nikle",
     "Thousands of desires, each worth dying for; many of my yearnings were fulfilled, yet so many remained unsatisfied.", "gham", "Sad & Melancholy"),
    ("دل ہی تو ہے نہ سنگ و خشت درد سے بھر نہ آئے کیوں", "روئیں گے ہم ہزار بار کوئی ہمیں ستائے کیوں", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Dil hi to hai na sang-o-khisht dard se bhar na aaye kyun, Royenge hum hazaar baar koi humein sataye kyun",
     "It is a heart after all, not brick or stone; why should it not overflow with ache? I shall weep a thousand times, why should any torment me?", "gham", "Sad & Melancholy"),
    ("عشق نے غالبؔ نکما کر دیا", "ورنہ ہم بھی آدمی تھے کام کے", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Ishq ne Ghalib nikamma kar diya, Warna hum bhi aadmi thay kaam ke",
     "Love made Ghalib completely helpless and unmindful of the world; otherwise, we too were once men of great purpose.", "ishq", "Love & Romance"),
    ("رگوں میں دوڑتے پھرنے کے ہم نہیں قائل", "جب آنکھ ہی سے نہ ٹپکا تو پھر لہو کیا ہے", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Ragon mein daurte phirne ke hum nahin qaail, Jab aankh hi se na tapka to phir lahoo kya hai",
     "We hold no regard for blood merely coursing through veins; if it does not well up as tears in the eye, what worth is blood?", "gham", "Sad & Melancholy"),
    ("قیدِ حیات و بندِ غم اصل میں دونوں ایک ہیں", "موت سے پہلے آدمی غم سے نجات پائے کیوں", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Qaid-e-hayaat o band-e-gham asal mein dono aik hain, Maut se pehle aadmi gham se nijaat paaye kyun",
     "The prison of life and the chain of sorrow are truly one and the same; why should mortal man expect release from grief before death?", "gham", "Sad & Melancholy"),
    ("محبت میں نہیں ہے فرق جینے اور مرنے کا", "اسی کو دیکھ کر جیتے ہیں جس کافر پہ دم نکلے", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Mohabbat mein nahin hai farq jeene aur marne ka, Ussi ko dekh kar jeete hain jis kaafir pe dam nikle",
     "In true love there is no difference between living and dying; we draw our very breath by gazing upon the one for whom our soul departs.", "ishq", "Love & Romance"),
    ("یہ نہ تھی ہماری قسمت کہ وصالِ یار ہوتا", "اگر اور جیتے رہتے یہی انتظار ہوتا", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Yeh na thi hamaari qismat ke wisaal-e-yaar hota, Agar aur jeete rehte yehi intezaar hota",
     "It was never our destiny to attain union with the beloved; had we lived longer, it would have been the self-same unending longing.", "gham", "Sad & Melancholy"),
    ("ہم کو معلوم ہے جنت کی حقیقت لیکن", "دل کے خوش رکھنے کو غالبؔ یہ خیال اچھا ہے", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Hum ko maloom hai jannat ki haqeeqat lekin, Dil ke khush rakhne ko Ghalib yeh khayal achha hai",
     "We well comprehend the reality of paradise, yet O Ghalib, to keep the aching heart comforted, it is a pleasant fantasy.", "ishq", "Love & Romance"),
    ("غمِ ہستی کا اسدؔ کس سے ہو جز مرگ علاج", "شمع ہر رنگ میں جلتی ہے سحر ہونے تک", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Gham-e-hasti ka Asad kis se ho juz marg ilaaj, Shama har rang mein jalti hai sehar hone tak",
     "For the sorrow of existence, O Asad, what cure is there except death? The candle burns inexorably until dawn arrives.", "gham", "Sad & Melancholy"),
    ("بازیچۂ اطفال ہے دنیا مرے آگے", "ہوتا ہے شب و روز تماشا مرے آگے", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Baazeecha-e-atfaal hai duniya mere aage, Hota hai shab-o-roz tamaasha mere aage",
     "A mere children's play is this world before me; night and day a spectacle unfolds before my weary eyes.", "gham", "Sad & Melancholy"),
    ("درد منت کشِ دوا نہ ہوا", "میں نہ اچھا ہوا برا نہ ہوا", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Dard minnat-kash-e-dawa na hua, Main na achha hua bura na hua",
     "My ache remained unindebted to cure; I did not recover, yet neither did I perish.", "gham", "Sad & Melancholy"),

    # --- FAIZ AHMAD FAIZ ---
    ("مجھ سے پہلی سی محبت مرے محبوب نہ مانگ", "میں نے سمجھا تھا کہ تو ہے تو درخشاں ہے حیات", "Faiz Ahmad Faiz", "فیض احمد فیض",
     "Mujh se pehli si mohabbat mere mehboob na maang, Main ne samjha tha ke tu hai to darakhshaan hai hayaat",
     "Do not ask of me, my beloved, that same first innocent love; once I believed that if I had you, life shone eternal.", "gham", "Sad & Melancholy"),
    ("اور بھی دکھ ہیں زمانے میں محبت کے سوا", "راحتیں اور بھی ہیں وصل کی راحت کے سوا", "Faiz Ahmad Faiz", "فیض احمد فیض",
     "Aur bhi dukh hain zamaane mein mohabbat ke siwa, Raahatein aur bhi hain wasl ki raahat ke siwa",
     "There are other sorrows in this world besides the ache of love, and other solaces beyond the embrace of union.", "gham", "Sad & Melancholy"),
    ("گلوں میں رنگ بھرے بادِ نوبہار چلے", "چلے بھی آؤ کہ گلشن کا کاروبار چلے", "Faiz Ahmad Faiz", "فیض احمد فیض",
     "Gulon mein rang bhare baad-e-naubahar chale, Chale bhi aao ke gulshan ka kaarobaar chale",
     "Let colors fill the blossoming roses, let springtime breeze begin to blow; come to me now, so the joyful affair of the garden may thrive.", "ishq", "Love & Romance"),
    ("دونوں جہان تیری محبت میں ہار کے", "وہ جا رہا ہے کوئی شبِ غم گزار کے", "Faiz Ahmad Faiz", "فیض احمد فیض",
     "Dono jahaan teri mohabbat mein haar ke, Woh ja raha hai koi shab-e-gham guzaar ke",
     "Having forfeited both worlds for the sake of your love, someone departs after enduring the solitary night of sorrow.", "gham", "Sad & Melancholy"),
    ("ہم پرورشِ لوح و قلم کرتے رہیں گے", "جو دل پہ گزرتی ہے رقم کرتے رہیں گے", "Faiz Ahmad Faiz", "فیض احمد فیض",
     "Hum parwarish-e-lauh-o-qalam karte rahenge, Jo dil pe guzarti hai raqam karte rahenge",
     "We shall continue nurturing the sacred tablet and pen; whatever transpires upon the heart, we shall faithfully record.", "ishq", "Love & Romance"),
    ("مقام فیضؔ کوئی راہ میں جچا ہی نہیں", "جو کوئے یار سے نکلے تو سوئے دار چلے", "Faiz Ahmad Faiz", "فیض احمد فیض",
     "Maqaam Faiz koi raah mein jacha hi nahin, Jo koo-e-yaar se nikle to soo-e-daar chale",
     "No ordinary resting station pleased Faiz along the journey; when we departed the beloved's street, we marched straight to the gallows.", "ishq", "Love & Romance"),
    ("کب نظر میں آئے گی بے داغ سبزے کی بہار", "خون کے دھبے دھلیں گے کتنی برساتوں کے بعد", "Faiz Ahmad Faiz", "فیض احمد فیض",
     "Kab nazar mein aayegi be-daagh sabze ki bahaar, Khoon ke dhabbe dhulenge kitni barsaaton ke baad",
     "When shall our eyes behold the spotless greenery of spring? After how many rainfalls will the tragic stains be washed clean?", "gham", "Sad & Melancholy"),
    ("آئے کچھ ابر کچھ شراب آئے", "اس کے بعد آئے جو عذاب آئے", "Faiz Ahmad Faiz", "فیض احمد فیض",
     "Aaye kuch abr kuch sharaab aaye, Iss ke baad aaye jo azaab aaye",
     "Let gentle clouds arrive, let wine pour forth; after that, let whatever torment may fall upon me come.", "ishq", "Love & Romance"),

    # --- MIR TAQI MIR ---
    ("پتا پتا بوٹا بوٹا حال ہمارا جانے ہے", "جانے نہ جانے گل ہی نہ جانے باغ تو سارا جانے ہے", "Mir Taqi Mir", "میر تقی میر",
     "Patta patta boota boota haal hamaara jaane hai, Jaane na jaane gul hi na jaane baagh to saara jaane hai",
     "Every leaf and every bud is conscious of my secret state; only the beloved rose remains unaware, while the entire garden knows.", "ishq", "Love & Romance"),
    ("نازکی اس کے لب کی کیا کہئے", "پنکھڑی اک گلاب کی سی ہے", "Mir Taqi Mir", "میر تقی میر",
     "Naazuki uss ke lab ki kya kahiye, Pankhadi ik gulaab ki si hai",
     "How can words capture the delicacy of the beloved's lips? They are like the velvet petal of a fresh rose.", "ishq", "Love & Romance"),
    ("دیکھ تو دل کہ جاں سے اٹھتا ہے", "یہ دھواں سا کہاں سے اٹھتا ہے", "Mir Taqi Mir", "میر تقی میر",
     "Dekh to dil ke jaan se uthta hai, Yeh dhuwaan sa kahan se uthta hai",
     "Look closely, whether it arises from the heart or the soul; from where does this plume of silent grief ascend?", "gham", "Sad & Melancholy"),
    ("ابتدا ہے عشق کی روتا ہے کیا", "آگے آگے دیکھیے ہوتا ہے کیا", "Mir Taqi Mir", "میر تقی میر",
     "Ibtida hai ishq ki rota hai kya, Aage aage dekhiye hota hai kya",
     "It is only the very beginning of love, why weep already? Watch onward to see the trials yet to unfold.", "ishq", "Love & Romance"),
    ("شام ہی سے بجھا سا رہتا ہے", "دل ہوا ہے چراغ مفلس کا", "Mir Taqi Mir", "میر تقی میر",
     "Shaam hi se bujha sa rehta hai, Dil hua hai chiraagh muflis ka",
     "From the very arrival of evening it stays dim and faint; the heart has turned into the humble lamp of a destitute soul.", "gham", "Sad & Melancholy"),
    ("اب کے ہم بچھڑے تو شاید کبھی خوابوں میں ملیں", "جس طرح سوکھے ہوئے پھول کتابوں میں ملیں", "Ahmad Faraz", "احمد فراز",
     "Ab ke hum bichhray to shaayad kabhi khwaabon mein milein, Jis tarah sookhe hue phool kitaabon mein milein",
     "If we part ways now, perhaps we shall only meet in dreams, just as dried pressed flowers are discovered inside forgotten books.", "gham", "Sad & Melancholy"),
    ("سنا ہے لوگ اسے آنکھ بھر کے دیکھتے ہیں", "سو اس کے شہر میں کچھ دن ٹھہر کے دیکھتے ہیں", "Ahmad Faraz", "احمد فراز",
     "Suna hai log usse aankh bhar ke dekhte hain, So uss ke shehar mein kuch din thehar ke dekhte hain",
     "I have heard that people gaze upon her with breathless admiration; let us then linger a few days in her blessed city.", "ishq", "Love & Romance"),
    ("رنجش ہی سہی دل ہی دکھانے کے لیے آ", "آ پھر سے مجھے چھوڑ کے جانے کے لیے آ", "Ahmad Faraz", "احمد فراز",
     "Ranjish hi sahi dil hi dukhaane ke liye aa, Aa phir se mujhe chhor ke jaane ke liye aa",
     "Even if with grievance, come simply to break my heart again; come, even if only to abandon me once more.", "gham", "Sad & Melancholy"),
    ("آنکھ سے دور نہ ہو دل سے اتر جائے گا", "وقت کا کیا ہے گزرتا ہے گزر جائے گا", "Ahmad Faraz", "احمد فراز",
     "Aankh se door na ho dil se utar jaayega, Waqt ka kya hai guzarta hai guzar jaayega",
     "Do not wander far from sight lest you fade from the heart; what is time after all? It passes and will pass away.", "ishq", "Love & Romance"),
    ("تم تکلف کو بھی اخلاص سمجھتے ہو فرازؔ", "دوست ہوتا نہیں ہر ہاتھ ملانے والا", "Ahmad Faraz", "احمد فراز",
     "Tum takalluf ko bhi ikhlaas samajhte ho Faraz, Dost hota nahin har haath milaane wala",
     "You mistake mere courtesy for genuine affection, O Faraz; not everyone who shakes your hand is truly a friend.", "gham", "Sad & Melancholy"),
    ("اس سادگی پہ کون نہ مر جائے اے خدا", "لڑتے ہیں اور ہاتھ میں تلوار بھی نہیں", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Iss saadgi pe kaun na mar jaaye aye Khuda, Larte hain aur haath mein talwaar bhi nahin",
     "Who would not surrender life for such innocence, O Lord? They wage battle, yet carry no sword in hand.", "ishq", "Love & Romance"),

    # --- JAUN ELIA ---
    ("شاید مجھے کسی سے محبت نہیں ہوئی", "لیکن یقین سب کو دلاتا رہا ہوں میں", "Jaun Elia", "جون ایلیا",
     "Shaayad mujhe kisi se mohabbat nahin hui, Lekin yaqeen sab ko dilaata raha hoon main",
     "Perhaps I never truly fell in love with anyone; yet I spent a lifetime convincing the whole world that I did.", "gham", "Sad & Melancholy"),
    ("کتنی دلکش ہو تم کتنا دل جو ہوں میں", "کیا ستم ہے کہ ہم لوگ مر جائیں گے", "Jaun Elia", "جون ایلیا",
     "Kitni dilkash ho tum kitna dil-joo hoon main, Kya sitam hai ke hum log mar jaayenge",
     "How captivating you are, how deeply yearning my soul is; what a tragic injustice that we mortals must someday die.", "ishq", "Love & Romance"),
    ("اب مری کوئی زندگی ہی نہیں", "اب بھی تم میری زندگی ہو کیا", "Jaun Elia", "جون ایلیا",
     "Ab meri koi zindagi hi nahin, Ab bhi tum meri zindagi ho kya",
     "Now I possess no life of my own; tell me, are you even now the only life within me?", "gham", "Sad & Melancholy"),
    ("میں بھی بہت عجیب ہوں اتنا عجیب ہوں کہ بس", "خود کو تباہ کر لیا اور ملال بھی نہیں", "Jaun Elia", "جون ایلیا",
     "Main bhi bohat ajeeb hoon itna ajeeb hoon ke bas, Khud ko tabaah kar liya aur malaal bhi nahin",
     "I too am so remarkably strange, so strange that words fail: I ruined my own soul, yet feel not the slightest remorse.", "gham", "Sad & Melancholy"),
    ("جو گزاری نہ جا سکی ہم سے", "ہم نے وہ زندگی گزاری ہے", "Jaun Elia", "جون ایلیا",
     "Jo guzaari na jaa saki hum se, Hum ne woh zindagi guzaari hai",
     "That very life which was unlivable to bear; we have lived and endured that very life.", "gham", "Sad & Melancholy"),
    ("ہم کو یاروں نے یاد بھی نہ رکھا", "جونؔ یاروں کے یار تھے ہم تو", "Jaun Elia", "جون ایلیا",
     "Hum ko yaaron ne yaad bhi na rakha, Jaun yaaron ke yaar thay hum to",
     "Our companions remembered us not in the least; yet O Jaun, we were the most loyal friend to all our friends.", "gham", "Sad & Melancholy"),

    # --- PARVEEN SHAKIR ---
    ("وہ تو خوشبو ہے ہواؤں میں بکھر جائے گا", "مسئلہ پھول کا ہے پھول کدھر جائے گا", "Parveen Shakir", "پروین شاکر",
     "Woh to khushboo hai hawaaon mein bikhar jaayega, Masla phool ka hai phool kidhar jaayega",
     "He is like sweet fragrance that will disperse upon the winds; the sorrow belongs to the flower—where shall the fragile bloom go?", "ishq", "Love & Romance"),
    ("کو بہ کو پھیل گئی بات شناسائی کی", "اس نے خوشبو کی طرح میری پذیرائی کی", "Parveen Shakir", "پروین شاکر",
     "Koo-ba-koo phail gayi baat shanaasaai ki, Uss ne khushboo ki tarah meri pazeeraai ki",
     "From street to street the tale of our acquaintance spread; he embraced my presence just as sweet perfume welcomes the air.", "ishq", "Love & Romance"),
    ("کیسے کہہ دوں کہ مجھے چھوڑ دیا ہے اس نے", "بات تو سچ ہے مگر بات ہے رسوائی کی", "Parveen Shakir", "پروین شاکر",
     "Kaise keh doon ke mujhe chhor diya hai uss ne, Baat to sach hai magar baat hai ruswaai ki",
     "How can I proclaim aloud that he has abandoned me? The statement is true, yet fraught with heartbreak and disgrace.", "gham", "Sad & Melancholy"),
    ("حسن کے سمجھنے کو عمر چاہیئے جاناں", "دو گھڑی کی چاہت میں پھول کھل نہیں سکتے", "Parveen Shakir", "پروین شاکر",
     "Husn ke samajhne ko umr chaahiye jaanaan, Do ghadi ki chaahat mein phool khil nahin sakte",
     "To comprehend the depths of beauty requires a whole lifetime, my love; in a fleeting affection of two moments, roses cannot bloom.", "ishq", "Love & Romance"),
    ("اب کے بارش میں تو یہ کارِ زیاں ہونا ہی تھا", "اپنی کچی بستیوں کو بے اماں ہونا ہی تھا", "Parveen Shakir", "پروین شاکر",
     "Ab ke baarish mein to yeh kaar-e-ziyaan hona hi tha, Apni kachi bastiyon ko be-amaan hona hi tha",
     "In this torrential downpour, such devastation was bound to come; our fragile earthen settlements had to be swept away.", "gham", "Sad & Melancholy"),

    # --- MOMIN & DAGH & BAHADUR SHAH ZAFAR ---
    ("تم مرے پاس ہوتے ہو گویا", "جب کوئی دوسرا نہیں ہوتا", "Momin Khan Momin", "مومن خاں مومن",
     "Tum mere paas hote ho goya, Jab koi doosra nahin hota",
     "You feel so intimately close beside me, as though whenever no one else is around, you alone are there.", "ishq", "Love & Romance"),
    ("اثر اس کو ذرا نہیں ہوتا", "رنج راحت فزا نہیں ہوتا", "Momin Khan Momin", "مومن خاں مومن",
     "Asar uss ko zara nahin hota, Ranj raahat-faza nahin hota",
     "It moves her not in the slightest degree; sorrow brings no comfort to this weary soul.", "gham", "Sad & Melancholy"),
    ("اردو ہے جس کا نام ہمیں جانتے ہیں داغؔ", "سارے جہاں میں دھوم ہماری زباں کی ہے", "Dagh Dehlvi", "داغ دہلوی",
     "Urdu hai jis ka naam humein jaante hain Dagh, Saare jahaan mein dhoom hamaari zabaan ki hai",
     "Urdu is its noble name and they recognize us by it, O Dagh; throughout the entire globe rings the fame of our language.", "ishq", "Love & Romance"),
    ("لطفِ مے تجھ سے کیا کہوں زاہدؔ", "ہائے کمبخت تو نے پی ہی نہیں", "Dagh Dehlvi", "داغ دہلوی",
     "Lutf-e-mai tujh se kya kahoon zaahid, Haaye kambakht tu ne pee hi nahin",
     "How can I convey to you the ecstasy of this divine nectar, O ascetic? Alas, unfortunate soul, you have never tasted it.", "ishq", "Love & Romance"),
    ("نہ کسی کی آنکھ کا نور ہوں نہ کسی کے دل کا قرار ہوں", "جو کسی کے کام نہ آ سکے میں وہ ایک مشتِ غبار ہوں", "Bahadur Shah Zafar", "بہادر شاہ ظفر",
     "Na kisi ki aankh ka noor hoon na kisi ke dil ka qaraar hoon, Jo kisi ke kaam na aa sake main woh aik musht-e-ghubaar hoon",
     "I am neither the light of anyone's eyes nor the solace of anyone's heart; I am merely a handful of dust that serves no living purpose.", "gham", "Sad & Melancholy"),
    ("کتنا ہے بد نصیب ظفرؔ دفن کے لیے", "دو گز زمین بھی نہ ملی کوئے یار میں", "Bahadur Shah Zafar", "بہادر شاہ ظفر",
     "Kitna hai bad-naseeb Zafar dafan ke liye, Do gaz zameen bhi na mili koo-e-yaar mein",
     "How utterly tragic is the destiny of Zafar; for his final burial, not even two yards of earth were granted in the beloved's land.", "gham", "Sad & Melancholy"),

    # --- NASIR KAZMI ---
    ("دل میں اک لہر سی اٹھی ہے ابھی", "کوئی تازہ ہوا چلی ہے ابھی", "Nasir Kazmi", "ناصر کاظمی",
     "Dil mein ik lehar si uthi hai abhi, Koi taaza hawa chali hai abhi",
     "A gentle ripple of longing has just stirred within the heart; a fresh, sweet breeze has just begun to whisper.", "ishq", "Love & Romance"),
    ("شہرِ دل میں عجب اندھیرا ہے", "یاد کی شمع بجھ گئی ہے ابھی", "Nasir Kazmi", "ناصر کاظمی",
     "Shehar-e-dil mein ajab andhera hai, Yaad ki shama bujh gayi hai abhi",
     "A strange and sorrowful darkness fills the city of the heart; the candle of remembrance has just flicker-faded.", "gham", "Sad & Melancholy"),
    ("وہ تو بچھڑا ہے تو اب یاد بھی کم آتا ہے", "غم کی اس دھوپ میں سایہ بھی نہیں ملتا ہے", "Nasir Kazmi", "ناصر کاظمی",
     "Woh to bichhra hai to ab yaad bhi kam aata hai, Gham ki iss dhoop mein saaya bhi nahin milta hai",
     "Since he parted from me, even his memory visits less often; in this scorching heat of sorrow, not even shade can be found.", "gham", "Sad & Melancholy"),

    # --- ALLAMA IQBAL (Ishq & Dard) ---
    ("عقل عیار ہے سو بھیس بنا لیتی ہے", "عشق بیچارہ نہ ملا ہے نہ زاہد نہ حکیم", "Allama Iqbal", "علامہ محمد اقبال",
     "Aql ayyaar hai sau bhes bana leti hai, Ishq bechaara na mulla hai na zaahid na hakeem",
     "Intellect is cunning and assumes a hundred deceptive disguises; but pure love is neither a cleric, nor a recluse, nor a philosopher.", "ishq", "Love & Romance"),
    ("تیرے عشق کی انتہا چاہتا ہوں", "میری سادگی دیکھ کیا چاہتا ہوں", "Allama Iqbal", "علامہ محمد اقبال",
     "Tere ishq ki inteha chaahta hoon, Meri saadgi dekh kya chaahta hoon",
     "I crave the infinite boundary of your divine love; look at my sweet innocence, what an impossible height I seek.", "ishq", "Love & Romance"),
    ("عشق بھی ہو حجاب میں حسن بھی ہو حجاب میں", "یا تو خود آشکار ہو یا مجھے آشکار کر", "Allama Iqbal", "علامہ محمد اقبال",
     "Ishq bhi ho hijaab mein husn bhi ho hijaab mein, Ya to khud aashkaar ho ya mujhe aashkaar kar",
     "Must love remain behind a veil and beauty too behind a veil? Either unveil Thyself fully, or unveil the hidden truth within me.", "ishq", "Love & Romance"),
    ("کبھی اے حقیقتِ منتظر نظر آ لباسِ مجاز میں", "کہ ہزاروں سجدے تڑپ رہے ہیں مری جبینِ نیاز میں", "Allama Iqbal", "علامہ محمد اقبال",
     "Kabhi aye haqeeqat-e-muntazar nazar aa libaas-e-majaaz mein, Ke hazaaron sajde tarap rahe hain meri jabeen-e-niyaaz mein",
     "O long-awaited Ultimate Reality, appear just once in the garment of mortal form; for thousands of prostrations are yearning upon my humble forehead.", "ishq", "Love & Romance"),

    # --- ADDITIONAL TIMELESS ISHQ & GHAM ASH'AAR ---
    ("ہزار بار ہوئے ہم تری گلی سے نثار", "کبھی تو دیکھ محبت کے درد کا عالم", "Ahmad Faraz", "احمد فراز",
     "Hazaar baar hue hum teri gali se nisaar, Kabhi to dekh mohabbat ke dard ka aalam",
     "A thousand times have I sacrificed my heart in your street; look just once upon the solemn state of love's deep ache.", "ishq", "Love & Romance"),
    ("دل کے ویرانے میں اک شمع جلائی ہم نے", "تیرے آنے کی دعا لب پہ سجائی ہم نے", "Sahir Ludhianvi", "ساحر لدھیانوی",
     "Dil ke veerane mein ik shama jalaai hum ne, Tere aane ki dua lab pe sajaai hum ne",
     "In the quiet wilderness of the heart I lit a solitary flame, and adorned my lips with prayers for your arrival.", "ishq", "Love & Romance"),
    ("یہ محبت کی زمیں ہے یہاں جو آتا ہے", "اپنے ہی دل کے فسانوں میں الجھ جاتا ہے", "Majrooh Sultanpuri", "مجروح سلطان پوری",
     "Yeh mohabbat ki zameen hai yahan jo aata hai, Apne hi dil ke fasaanon mein ulajh jaata hai",
     "This is the sacred realm of love: whoever enters here becomes delightfully entwined in the legends of their own heart.", "ishq", "Love & Romance"),
    ("چاندنی راتوں میں جب تیری یاد آتی ہے", "ایک خاموش سی فریاد تڑپ جاتی ہے", "Shakeel Badayuni", "شکیل بدایونی",
     "Chaandni raaton mein jab teri yaad aati hai, Aik khaamosh si faryaad tarap jaati hai",
     "In silver moonlit nights whenever your tender memory returns, a silent, pleading cry stirs within my soul.", "gham", "Sad & Melancholy"),
    ("دل کا اجڑنا سہل سہی دل کا بسانا سہل نہیں", "ہم نے بڑی مشکل سے سجایا اس ویرانے کو", "Jigar Moradabadi", "جگر مراد آبادی",
     "Dil ka ujarna sehl sahi dil ka basaana sehl nahin, Hum ne badi mushkil se sajaaya iss veerane ko",
     "Ruining a heart may be effortless, yet building it anew is no easy task; with immense hardship did we adorn this wilderness.", "gham", "Sad & Melancholy"),
    ("اک ادا سے جو ترا دیکھنا یاد آتا ہے", "دل کی ہر تار پہ اک نغمہ چھڑ جاتا ہے", "Hasrat Mohani", "حسرت موہانی",
     "Ik ada se jo tera dekhna yaad aata hai, Dil ki har taar pe ik naghma chhir jaata hai",
     "Whenever I recall the graceful way your glance fell upon me, a tender melody begins to play upon every string of my heart.", "ishq", "Love & Romance"),
    ("غمِ دوراں نے مٹا دی مری ہر اک حسرت", "ایک حسرت جو سلامت ہے وہ الفت ہے تری", "Kaifi Azmi", "کیفی اعظمی",
     "Gham-e-dauraan ne mita di meri har ik hasrat, Aik hasrat jo salaamat hai woh ulfat hai teri",
     "The relentless sorrows of time erased every earthly yearning; the single desire that endures intact is my deep love for you.", "ishq", "Love & Romance"),
    ("تیرا ملنا مری تنہائی کا درماں ٹھہرا", "تجھ سے بچھڑنا مرے جینے کا زیاں ٹھہرا", "Mohsin Naqvi", "محسن نقوی",
     "Tera milna meri tanhaai ka darmaan thehra, Tujh se bichharna mere jeene ka ziyaan thehra",
     "Meeting you became the sacred medicine for my loneliness; parting from you became the tragic loss of my very life.", "gham", "Sad & Melancholy"),
    ("محبت کا فسانا مختصر اتنا ہی ہوتا ہے", "نظر ملتی ہے اور دل میں قیامت ٹوٹ پڑتی ہے", "Amjad Islam Amjad", "امجد اسلام امجد",
     "Mohabbat ka fasaana mukhtasar itna hi hota hai, Nazar milti hai aur dil mein qayaamat toot parti hai",
     "The chronicle of love is as brief as this: eyes meet in silence, and a sudden resurrection shatters the heart.", "ishq", "Love & Romance"),
    ("کسی کی یاد میں پلکوں کو بھیگتے دیکھا", "ہم نے ہر لمحہ محبت کو جیتتے دیکھا", "Munir Niazi", "منیر نیازی",
     "Kisi ki yaad mein palkon ko bheegte dekha, Hum ne har lamha mohabbat ko jeette dekha",
     "I watched tender eyelashes glisten with tears in someone's memory; at every moment, I witnessed love emerge triumphant.", "ishq", "Love & Romance")
]
