# -*- coding: utf-8 -*-
"""
Authentic Classical & Modern Urdu Couplets for Khudi, Wisdom & Sufi.
Each entry is a tuple:
(m1, m2, poet, poet_urdu, roman, english, category, category_label)
"""

KHUDI_WISDOM_SUFI_CORPUS = [
    # --- ALLAMA IQBAL: KHUDI ---
    ("ستاروں سے آگے جہاں اور بھی ہیں", "ابھی عشق کے امتحان اور بھی ہیں", "Allama Iqbal", "علامہ محمد اقبال",
     "Sitaaron se aage jahaan aur bhi hain, Abhi ishq ke imtehaan aur bhi hain",
     "Beyond the distant stars there exist yet other universes; there are still further trials awaiting the spiritual traveler.", "khudi", "Motivation & Khudi"),
    ("تو شاہیں ہے پرواز ہے کام تیرا", "ترے سامنے آسماں اور بھی ہیں", "Allama Iqbal", "علامہ محمد اقبال",
     "Tu shaheen hai parwaaz hai kaam tera, Tere saamne aasmaan aur bhi hain",
     "You are a soaring falcon; your noble calling is flight; before your vision stretch countless unmapped skies.", "khudi", "Motivation & Khudi"),
    ("نہیں ہے نا امید اقبالؔ اپنی کشتِ ویراں سے", "ذرا نم ہو تو یہ مٹی بڑی زرخیز ہے ساقی", "Allama Iqbal", "علامہ محمد اقبال",
     "Nahin hai na-umeed Iqbal apni kisht-e-veeraan se, Zara nam ho to yeh mitti badi zarkhez hai saaqi",
     "Iqbal is never despairing of his seemingly barren field; with just a gentle drop of moisture, this soil is boundlessly fertile, O cupbearer.", "khudi", "Motivation & Khudi"),
    ("عمل سے زندگی بنتی ہے جنت بھی جہنم بھی", "یہ خاکی اپنی فطرت میں نہ نوری ہے نہ ناری ہے", "Allama Iqbal", "علامہ محمد اقبال",
     "Amal se zindagi banti hai jannat bhi jahannam bhi, Yeh khaaki apni fitrat mein na noori hai na naari hai",
     "Through righteous action life creates both heaven and hell; this mortal earthly being by nature is neither made of light nor of fire.", "khudi", "Motivation & Khudi"),
    ("افراد کے ہاتھوں میں ہے اقوام کی تقدیر", "ہر فرد ہے ملت کے مقدر کا ستارہ", "Allama Iqbal", "علامہ محمد اقبال",
     "Afraad ke haathon mein hai aqwaam ki taqdeer, Har fard hai millat ke muqaddar ka sitaara",
     "In the hands of dedicated individuals rests the destiny of whole nations; every single person is a shining star of his community's fortune.", "khudi", "Motivation & Khudi"),
    ("پرواز ہے دونوں کی اسی ایک فضا میں", "کرگس کا جہاں اور ہے شاہیں کا جہاں اور", "Allama Iqbal", "علامہ محمد اقبال",
     "Parwaaz hai dono ki ussi aik faza mein, Kargas ka jahaan aur hai shaheen ka jahaan aur",
     "Both take wing in the self-same atmosphere; yet the world of the scavenger vulture is one, and the world of the noble royal falcon is another.", "khudi", "Motivation & Khudi"),
    ("ہزار خوف ہو لیکن زباں ہو دل کی رفیق", "یہی رہا ہے ازل سے قلندروں کا طریق", "Allama Iqbal", "علامہ محمد اقبال",
     "Hazaar khauf ho lekin zabaan ho dil ki rafeeq, Yehi raha hai azal se qalandaron ka tareeq",
     "Though a thousand fears beset you, let your tongue remain steadfast with the truth of your heart; this has ever been the path of the liberated mystics.", "khudi", "Motivation & Khudi"),
    ("نگاہِ مردِ مومن سے بدل جاتی ہیں تقدیریں", "جو ہو ذوقِ یقیں پیدا تو کٹ جاتی ہیں زنجیریں", "Allama Iqbal", "علامہ محمد اقبال",
     "Nigaah-e-mard-e-momin se badal jaati hain taqdeerein, Jo ho zauq-e-yaqeen paida to kat jaati hain zanjeerein",
     "By the focused spiritual gaze of a person of profound faith, destinies are transformed; when the joy of certainty awakens, all shackles fall away.", "khudi", "Motivation & Khudi"),
    ("غلامی میں نہ کام آتی ہیں شمشیریں نہ تدبیریں", "جو ہو ذوقِ یقیں پیدا تو کٹ جاتی ہیں زنجیریں", "Allama Iqbal", "علامہ محمد اقبال",
     "Ghulaami mein na kaam aati hain shamsheerein na tadbeerein, Jo ho zauq-e-yaqeen paida to kat jaati hain zanjeerein",
     "In servitude neither swords nor clever schemes avail; but once genuine faith and dignity awaken, the heavy chains are severed.", "khudi", "Motivation & Khudi"),
    ("محبت مجھے ان جوانوں سے ہے", "ستاروں پہ جو ڈالتے ہیں کمند", "Allama Iqbal", "علامہ محمد اقبال",
     "Mohabbat mujhe unn jawaanon se hai, Sitaaron pe jo daalte hain kamand",
     "My deep love belongs to those fearless youths who cast their lasso upon the very stars of high achievement.", "khudi", "Motivation & Khudi"),

    # --- SUFI & SPIRITUAL ---
    ("پڑھ پڑھ علم ہزار کتاباں کدی اپنے آپ نوں پڑھیا نہیں", "بُلھے شاہ آسمانی اُڈدیاں پھڑدا جیہڑا گھر بیٹھا اوہ پھڑیا نہیں", "Baba Bulleh Shah", "بابا بلھے شاہ",
     "Parh parh ilm hazaar kitaabaan kadi apne aap nu parhiya nahin, Bulleh Shah aasmaani udd-diyan pharda jehra ghar baitha oh phariya nahin",
     "You read thousands of scholarly books, yet never once read the truth of your own soul; O Bulleh Shah, you chase birds flying in the sky, while missing the Divine residing right within your home.", "sufi", "Sufi & Spiritual"),
    ("دل دریا سمندروں ڈونگھے کون دلاں دیاں جانے ہو", "وچے بیڑے وچے جھوڑے وچے ونجھ مہانے ہو", "Sultan Bahu", "سلطان باہو",
     "Dil darya samundron doonghe kaun dilaan diyan jaane hoo, Viche bere viche jhore viche wanjh muhaane hoo",
     "The human heart is deeper than wide oceans; who can fathom the depths within? Inside sail boats, inside swirl storms, inside wait the sailors and oars.", "sufi", "Sufi & Spiritual"),
    ("الف اللہ چمبے دی بوٹی مرشد من میرے وچ لائی ہو", "نفی اثبات دا پانی ملیا ہر رگے ہر جائی ہو", "Sultan Bahu", "سلطان باہو",
     "Alif Allah chambe di booti murshid mann mere vich laayi hoo, Nafi asbaat da paani miliya har rage har jaayi hoo",
     "The spiritual master planted the fragrant jasmine bloom of Allah's divine name in my heart; watered with devotion and negation of ego, it blossomed in every vein.", "sufi", "Sufi & Spiritual"),
    ("من کنت مولاہ فہذا علی مولاہ", "رنگ ہے ری ماں رنگ ہے ری", "Amir Khusro", "امیر خسرو",
     "Man kunto maula fa haaza Ali-un maula, Rang hai ri maa rang hai ri",
     "Whomever I am master to, Ali is their master; what ecstatic spiritual color has bloomed across the soul today!", "sufi", "Sufi & Spiritual"),
    ("چھاپ تلک سب چھینی رے موسے نیناں ملائیکے", "بات اگم کہَہ دینی رے موسے نیناں ملائیکے", "Amir Khusro", "امیر خسرو",
     "Chhaap tilak sab chheeni re mose naina milaaike, Baat agam keh deeni re mose naina milaaike",
     "You stripped away all my worldly identity with just one meeting of our eyes; you whispered celestial mysteries into my soul with a single glance.", "sufi", "Sufi & Spiritual"),
    ("نمی دانم چہ منزل بود شب جائے کہ من بودم", "بہ ہر سو رقصِ بسمل بود شب جائے کہ من بودم", "Amir Khusro", "امیر خسرو",
     "Nami daanam che manzil bood shab jaayee ke man boodam, Ba har soo raqs-e-bismil bood shab jaayee ke man boodam",
     "I know not what celestial dwelling place it was where I resided last night; all around me was the sacred dance of ecstatic lovers.", "sufi", "Sufi & Spiritual"),

    # --- WISDOM & PHILOSOPHY ---
    ("آدمی کو بھی میسر نہیں انساں ہونا", "کتنا دشوار ہے ہر کام کا آساں ہونا", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Aadmi ko bhi mayassar nahin insaan hona, Kitna dushwaar hai har kaam ka aasaan hona",
     "It is not easily granted even to man to become truly human; how challenging it is for every simple virtue to be realized.", "wisdom", "Wisdom & Life"),
    ("سب کہاں کچھ لالہ و گل میں نمایاں ہو گئیں", "خاک میں کیا صورتیں ہوں گی کہ پنہاں ہو گئیں", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Sab kahan kuch laala-o-gul mein numayaan ho gayin, Khaak mein kya sooratein hongi ke pinhaan ho gayin",
     "Not all, only a precious few appeared as tulips and roses; what sublime radiant faces must lie concealed beneath the quiet earth.", "wisdom", "Wisdom & Life"),
    ("رنج سے خوگر ہوا انساں تو مٹ جاتا ہے رنج", "مشکلیں مجھ پر پڑیں اتنی کہ آساں ہو گئیں", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Ranj se khoogar hua insaan to mit jaata hai ranj, Mushkilein mujh par pareen itni ke aasaan ho gayin",
     "When man becomes accustomed to tribulation, the sharpness of sorrow dissolves; so many hardships befell me that enduring them became natural.", "wisdom", "Wisdom & Life"),
    ("نہ منہ چھپا کے جئے ہم نہ سر جھکا کے جئے", "ستم گروں کی نظر سے نظر ملا کے جئے", "Habib Jalib", "حبیب جالب",
     "Na munh chhupa ke jiye hum na sar jhuka ke jiye, Sitam-garon ki nazar se nazar mila ke jiye",
     "We lived neither hiding our faces in fear nor bowing our heads in cowardice; we lived gazing straight into the eyes of oppressors.", "khudi", "Motivation & Khudi"),
    ("ظلم رہے اور امن بھی ہو کیا ممکن ہے تم ہی کہو", "ہم نے صدائیں حق کی اٹھائیں ہم پہ ستم تھا ہونا ہی", "Habib Jalib", "حبیب جالب",
     "Zulm rahe aur aman bhi ho kya mumkin hai tum hi kaho, Hum ne sadaayein haq ki uthaayein hum pe sitam tha hona hi",
     "Can injustice persist alongside true peace? Speak, is it possible? We raised the fearless voice of truth, knowing hardship would follow.", "wisdom", "Wisdom & Life"),
    ("بنی آدم اعضائے یک دیگر اند", "کہ در آفرینش ز یک گوہر اند", "Saadi Shirazi", "سعدی شیرازی",
     "Bani aadam aazaaye yak deegar and, Ke dar aafreenash ze yak gauhar and",
     "All children of Adam are limbs of one sacred body, created from the very same noble divine essence.", "wisdom", "Wisdom & Life"),
    ("چو عضوی بہ درد آورد روزگار", "دگر عضو ہا را نماند قرار", "Saadi Shirazi", "سعدی شیرازی",
     "Chu uzve ba dard aawarad rozgaar, Digar uzv-ha ra namaanad qaraar",
     "When the circumstance of time afflicts one limb with pain, no other limb can remain at peaceful rest.", "wisdom", "Wisdom & Life"),
    ("درختِ دوستی بنشان کہ کامِ دل بہ بار آرد", "نہالِ دشمنی برکن کہ رنجِ بے شمار آرد", "Hafez Shirazi", "حافظ شیرازی",
     "Darakht-e-dosti benshaan ke kaam-e-dil ba baar aarad, Nehaal-e-dushmani barkan ke ranj-e-be-shumaar aarad",
     "Plant the flourishing tree of friendship, for it yields the sweetest fruits of the soul; uproot the sapling of malice, for it brings boundless sorrow.", "wisdom", "Wisdom & Life"),
    ("زندگی ہے تو بہرحال بسر بھی ہوگی", "رات کتنی ہی ہو تاریک سحر بھی ہوگی", "Amjad Islam Amjad", "امجد اسلام امجد",
     "Zindagi hai to bahar-haal basar bhi hogi, Raat kitni hi ho taareek sehar bhi hogi",
     "Since life is given, it will surely pass; no matter how deeply dark the night may be, the morning light must break.", "wisdom", "Wisdom & Life"),
    ("کوئی امید بر نہیں آتی", "کوئی صورت نظر نہیں آتی", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Koi umeed bar nahin aati, Koi soorat nazar nahin aati",
     "No cherished hope comes to fruition; no visible path reveals itself ahead.", "wisdom", "Wisdom & Life"),
    ("آگے آتی تھی حالِ دل پہ ہنسی", "اب کسی بات پر نہیں آتی", "Mirza Ghalib", "مرزا اسد اللہ خاں غالب",
     "Aage aati thi haal-e-dil pe hansi, Ab kisi baat par nahin aati",
     "Once I used to laugh at the strange follies of my own heart; now nothing brings a smile to my weary lips.", "wisdom", "Wisdom & Life")
]
