# scripts/curated_verse_catalog.py
# -*- coding: utf-8 -*-

CATALOG = [
    # GHALIB
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "ishq", "Love & Romance",
     "قاصد کے آتے آتے خط اک اور لکھ رکھوں\nمیں جانتا ہوں جو وہ لکھیں گے جواب میں",
     "Qasid ke aate aate khat ik aur likh rakhun\nMain jaanta hun jo wo likhenge jawab mein",
     "Before the messenger returns, let me write another letter; I already know what they will write in response.",
     "قاصد کے آنے سے پہلے ہی میں ایک اور خط لکھ لوں، کیونکہ مجھے معلوم ہے کہ وہ جواب میں کیا فرمائیں گے۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "falsafa", "Philosophy & Reflection",
     "بازیچۂ اطفال ہے دنیا مرے آگے\nہوتا ہے شب و روز تماشا مرے آگے",
     "Bazicha-e-atfal hai dunya mere aage\nHota hai shab-o-roz tamasha mere aage",
     "The world is merely a child's game before me; night and day, a spectacle unfolds before my eyes.",
     "یہ دنیا میرے لیے بچوں کے کھیل سے زیادہ کچھ نہیں، جہاں شب و روز ایک تماشا برپا رہتا ہے۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "falsafa", "Philosophy & Reflection",
     "ہوئی مدت کہ غالبؔ مر گیا پر یاد آتا ہے\nوہ ہر اک بات پر کہنا کہ یوں ہوتا تو کیا ہوتا",
     "Hui muddat ke Ghalib mar gaya par yaad aata hai\nWo har ik baat par kehna ke yun hota to kya hota",
     "An age has passed since Ghalib died, yet still we remember his pondering: 'What if it had been thus?'",
     "غالب کو بچھڑے زمانہ گزرا مگر یاد آتا ہے کہ وہ ہر بات پر سوچا کرتا تھا کہ اگر یوں ہوتا تو کیا ہوتا۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "falsafa", "Philosophy & Reflection",
     "رگوں میں دوڑتے پھرنے کے ہم نہیں قائل\nجب آنکھ ہی سے نہ ٹپکا تو پھر لہو کیا ہے",
     "Ragon mein daurte phirne ke hum nahin qayil\nJab aankh hi se na tapka to phir lahu kya hai",
     "We are not impressed by blood simply coursing through the veins; if it does not well up in the eyes, what use is blood?",
     "صرف رگوں میں دوڑتے خون کا کوئی فائدہ نہیں، جب تک وہ احساس اور درد بن کر آنکھوں سے نہ ٹپکے۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "dard", "Sorrow & Longing",
     "غم اگرچہ جاں گسل ہے پہ کہاں بچیں کہ دل ہے\nغمِ عشق گر نہ ہوتا غمِ روزگار ہوتا",
     "Gham agarcha jaan-gusil hai pa kahan bachein ke dil hai\nGham-e-ishq gar na hota gham-e-rozgar ہوتا",
     "Though sorrow is soul-shattering, how could the heart escape it? If not the sorrow of love, the struggle of life would take its place.",
     "غم جان لیوا سہی لیکن دل اس سے بچ نہیں سکتا، محبت کا غم نہ ہوتا تو روزگار اور زمانے کا غم ہوتا۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "ishq", "Love & Romance",
     "محبت میں نہیں ہے فرق جینے اور مرنے کا\nاسی کو دیکھ کر جیتے ہیں جس کافر پہ دم نکلے",
     "Mohabbat mein nahin hai farq jeene aur marne ka\nUsi ko dekh kar jeete hain jis kafir pe dam nikle",
     "In love there is no division between living and dying; we draw breath only by beholding the beloved for whom life departs.",
     "عشق میں جینے اور مرنے کا فرق مٹ جاتا ہے، ہم اسی کو دیکھ کر جیتے ہیں جس پر دل و جان نچھاور ہے۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "ishq", "Love & Romance",
     "عشق پر زور نہیں ہے یہ وہ آتش غالبؔ\nکہ لگائے نہ لگے اور بجھائے نہ بنے",
     "Ishq par zor nahin hai yeh wo aatish Ghalib\nKe lagaaye na lage aur bujhaaye na bane",
     "Love is beyond human control, O Ghalib; it is a blaze that cannot be kindled by force, nor extinguished when alight.",
     "محبت پر کسی کا بس نہیں چلتا، یہ وہ آگ ہے جو زبردستی نہیں جلائی جا سکتی اور بھڑک اٹھے تو بجھائی نہیں جا سکتی۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "ishq", "Love & Romance",
     "دل ہی تو ہے نہ سنگ و خشت درد سے بھر نہ آئے کیوں\nروئیں گے ہم ہزار بار کوئی ہمیں ستائے کیوں",
     "Dil hi to hai na sang-o-khisht dard se bhar na aaye kyun\nRoyenge hum hazaar baar koi humein sataaye kyun",
     "It is a tender heart after all, not stone or brick; why should it not overflow with ache?",
     "یہ دل ہے پتھر یا اینٹ تو نہیں، اس میں درد کیوں نہ اٹھے؛ کوئی ہمیں ستائے گا تو ہم ہزار بار آنسو بہائیں گے۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "falsafa", "Philosophy & Reflection",
     "نہ تھا کچھ تو خدا تھا کچھ نہ ہوتا تو خدا ہوتا\nڈبویا مجھ کو ہونے نے نہ ہوتا میں تو کیا ہوتا",
     "Na tha kuch to khuda tha kuch na hota to khuda hota\nDuboya mujh ko hone ne na hota main to kya hota",
     "When nothing existed, God was; had nothing come to be, God would still be; my very coming into being proved my undoing.",
     "جب کچھ نہ تھا تو خدا موجود تھا اور اگر کچھ نہ ہوتا تب بھی خدا ہوتا، میرے اپنے وجود نے ہی مجھے مصیبت میں ڈالا۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "ishq", "Love & Romance",
     "عشق نے غالبؔ نکما کر دیا\nورنہ ہم بھی آدمی تھے کام کے",
     "Ishq ne Ghalib nikamma kar diya\nWarna hum bhi aadmi the kaam ke",
     "Love rendered Ghalib utterly useless; otherwise we too were once men of great enterprise.",
     "عشق کی لگن نے غالب کو کسی کام کا نہ چھوڑا، ورنہ ہم بھی دنیا کے معاملات میں بڑے کارآمد انسان تھے۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "falsafa", "Philosophy & Reflection",
     "قیدِ حیات و بندِ غم اصل میں دونوں ایک ہیں\nموت سے پہلے آدمی غم سے نجات پائے کیوں",
     "Qaid-e-hayaat-o-band-e-gham asal mein donon ek hain\nMaut se pehle aadmi gham se najaat paaye kyun",
     "The prison of life and the bonds of sorrow are one and the same; why then should mortal man expect freedom from grief before death?",
     "زندگی کی قید اور غم کی زنجیریں حقیقت میں ایک ہی ہیں، موت سے پہلے انسان دکھ اور تکلیف سے کیسے نجات پا سکتا ہے۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "falsafa", "Philosophy & Reflection",
     "قطرہ اپنا بھی حقیقت میں ہے دریا لیکن\nہم کو تقلیدِ تنک ظرفیِ منصور نہیں",
     "Qatra apna bhi haqeeqat mein hai darya lekin\nHum ko taqleed-e-tanak-zarfi-e-mansoor nahin",
     "In truth our single drop too encompasses an entire sea; yet we do not emulate Mansur's narrow-vessel boasting.",
     "ہمارا ایک قطرہ بھی سمندر جیسی وسعت رکھتا ہے، لیکن ہم منصور حلاج کی طرح اپنے ظرف کی کم مائیگی کا ڈھنڈورا نہیں پیٹتے۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "ishq", "Love & Romance",
     "آئینہ دیکھ اپنا سا منہ لے کے رہ گئے\nصاحب کو دل نہ دینے پہ کتنا غرور تھا",
     "Aaina dekh apna sa munh le ke reh gaye\nSahab ko dil na dene pe kitna ghuroor tha",
     "They looked into the mirror and stood abashed; how proud they had been of withholding their heart from love!",
     "جب آئینے میں اپنی بے رخی اور حسن دیکھا تو شرمندہ ہو کر رہ گئے، جبکہ پہلے دل نہ دینے پر بڑا غرور تھا۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "ishq", "Love & Romance",
     "ہم کو معلوم ہے جنت کی حقیقت لیکن\nدل کے خوش رکھنے کو غالبؔ یہ خیال اچھا ہے",
     "Hum ko ma'loom hai jannat ki haqeeqat lekin\nDil ke khush rakhne ko Ghalib yeh khayal achha hai",
     "We are well aware of the true nature of paradise; yet to keep the heart consoled, O Ghalib, it is a comforting thought.",
     "ہمیں جنت کی اصل حقیقت معلوم ہے، مگر دل کو تسلی دینے کے لیے اے غالب یہ خیال برا نہیں۔"),
    ("Mirza Ghalib", "مرزا اسد اللہ خاں غالب", "Agra / Delhi, India", "1797 – 1869", "ur", "ishq", "Love & Romance",
     "دل سے تری نگاہ جگر تک اتر گئی\nدونوں کو اک ادا میں رضامند کر گئی",
     "Dil se teri nigah jigar tak utar gayi\nDonon ko ik ada mein razamand kar gayi",
     "Your tender glance pierced from the heart straight through the soul; in a single gesture it won over both.",
     "محبوب کی نگاہ دل سے جگر تک اتر گئی اور ایک ہی ادا میں دل و جان دونوں کو اپنا گرویدہ بنا لیا۔"),

    # ALLAMA IQBAL
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "inqilab", "Revolution & Hope",
     "نہیں ہے نا امید اقبالؔ اپنی کشتِ ویراں سے\nذرا نم ہو تو یہ مٹی بڑی زرخیز ہے ساقی",
     "Nahin hai na-umeed Iqbal apni kisht-e-veeraan se\nZara nam ho to yeh mitti bari zarkhez hai saqi",
     "Iqbal is never hopeless of his barren soil; with just a touch of moisture, this earth is richly fertile, O cupbearer.",
     "اقبال اپنی قوم اور دھرتی سے مایوس نہیں، ذرا سی محنت اور بیداری سے یہ مٹی بے پناہ زرخیز ثابت ہوگی۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "falsafa", "Philosophy & Reflection",
     "عمل سے زندگی بنتی ہے جنت بھی جہنم بھی\nیہ خاکی اپنی فطرت میں نہ نوری ہے نہ ناری ہے",
     "Amal se zindagi banti hai jannat bhi jahannam bhi\nYeh khaaki apni fitrat mein na noori hai na naari hai",
     "Through deeds life fashions its heaven and its hell; this earthly being in nature is neither of light nor of fire.",
     "انسان کے اعمال ہی اس کی زندگی کو جنت یا جہنم بناتے ہیں، انسان اپنی سرشت میں محض مٹی ہے جو عمل سے پہچانی جاتی ہے۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "falsafa", "Philosophy & Reflection",
     "خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے\nخدا بندے سے خود پوچھے بتا تیری رضا کیا ہے",
     "Khudi ko kar buland itna ke har taqdeer se pehle\nKhuda bande se khud poochhe bata teri raza kya hai",
     "Elevate your selfhood so high that before writing destiny, God Himself inquires: Tell Me, what is your desire?",
     "اپنی خودی کو اس بلندی پر لے جاؤ کہ تقدیر رقم کرنے سے قبل اللہ تعالیٰ تم سے خود پوچھے کہ تیری مرضی کیا ہے۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "inqilab", "Revolution & Hope",
     "تو شاہیں ہے پرواز ہے کام تیرا\nترے سامنے آسماں اور بھی ہیں",
     "Tu shaheen hai parwaaz hai kaam tera\nTere saamne aasmaan aur bhi hain",
     "You are a falcon, your mission is flight; boundless skies still await your soaring wings.",
     "تم شاہین ہو اور بلندیوں پر اڑنا تمہارا مقدر ہے، تمہارے سفر کے لیے لامتناہی آسمان کھلے ہیں۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "falsafa", "Philosophy & Reflection",
     "گرتے ہیں شہسوار ہی میدانِ جنگ میں\nوہ طفل کیا گرے جو گھٹنوں کے بل چلے",
     "Girte hain sheh-sawaar hi maidan-e-jang mein\nWo tifl kya gire jo ghutnon ke bal چلے",
     "Only mighty knights fall upon the battlefield; how could that timid infant fall who only crawls on knees?",
     "میدانِ کارزار میں صرف بہادر گھڑسوار گرتے ہیں، وہ کیا گرے گا جو ہمیشہ زمین پر گھٹنوں کے بل چلتا رہا ہو۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "falsafa", "Philosophy & Reflection",
     "نگاہِ مردِ مومن سے بدل جاتی ہیں تقدیریں\nجو ہو ذوقِ یقیں پیدا تو کٹ جاتی ہیں زنجیریں",
     "Nigah-e-mard-e-momin se badal jaati hain taqdeerein\nJo ho zauq-e-yaqeen paida to kat jaati hain zanjeerein",
     "By the visionary gaze of a devoted soul destines are altered; when conviction awakens, all chains shatter.",
     "مردِ حق کی نگاہ سے زمانے کے فیصلے بدل جاتے ہیں، پختہ یقین پیدا ہو جائے تو غلامی کی زنجیریں ٹوٹ جاتی ہیں۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "inqilab", "Revolution & Hope",
     "افراد کے ہاتھوں میں ہے اقوام کی تقدیر\nہر فرد ہے ملت کے مقدر کا ستارہ",
     "Afraad ke haathon mein hai aqwaam ki taqdeer\nHar fard hai millat ke muqaddar ka sitara",
     "In the hands of individuals rests the destiny of nations; each person is a star in the firmament of the community.",
     "قوموں کی تقدیر ان کے افراد کی محنت اور کردار سے بنتی ہے، ہر فرد اپنی قوم کے مقدر کا چمکتا ستارہ ہے۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "falsafa", "Philosophy & Reflection",
     "ہزاروں سال نرگس اپنی بے نوری پہ روتی ہے\nبڑی مشکل سے ہوتا ہے چمن میں دیدہ ور پیدا",
     "Hazaron saal nargis apni be-noori pe roti hai\nBari mushkil se hota hai chaman mein deeda-war paida",
     "For millennia the narcissus laments its sightlessness; with supreme rarity is a true visionary born in the garden.",
     "نرگس ہزاروں برس اپنی بے نوری پر روتی ہے تب جا کر چمن میں کوئی صاحبِ بصیرت دیدہ ور جنم لیتا ہے۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "inqilab", "Revolution & Hope",
     "جس کھیت سے دہقاں کو میسر نہ ہو روزی\nاس کھیت کے ہر خوشۂ گندم کو جلا دو",
     "Jis khet se dehqaN ko muyassar na ho rozi\nUs khet ke har khosha-e-gandum ko jala do",
     "That field which yields no sustenance to the farmer: incinerate every ear of wheat standing in that field!",
     "جس کھیت کی فصل سے کسان کو روٹی نہ ملے، اس کھیت کے ایک ایک خوشے کو نذرِ آتش کر دو۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "ishq", "Love & Romance",
     "بے خطر کود پڑا آتشِ نمرود میں عشق\nعقل ہے محوِ تماشائے لبِ بام ابھی",
     "Be-khatar kood para aatish-e-namrood mein ishq\nAql hai mahw-e-tamashaye lab-e-baam abhi",
     "Fearlessly love leaped into the fiery furnace of Nimrod, while cautious intellect still stands watching from the rooftop.",
     "عشق نے بے خطر نمرود کی آگ میں چھلانگ لگا دی، جبکہ عقل اب بھی کنارے پر کھڑی سوچ بچار میں لگی ہے۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "falsafa", "Philosophy & Reflection",
     "تری خودی میں اگر انقلاب ہو پیدا\nعجب نہیں ہے کہ یہ چار سو بدل جائے",
     "Teri khudi mein agar inqilab ho paida\nAjab nahin hai ke yeh chaar soo badal jaaye",
     "If a true spiritual revolution awakens within your inner self, it is no wonder if the entire world around you transforms.",
     "اگر انسان کی اپنی خودی میں روحانی اور فکری انقلاب بیدار ہو جائے، تو اس کے ارد گرد کی پوری کائنات بدل جاتی ہے۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "falsafa", "Philosophy & Reflection",
     "کھول آنکھ، زمیں دیکھ، فلک دیکھ، فضا دیکھ\nمشرق سے ابھرتے ہوئے سورج کو ذرا دیکھ",
     "Khol aankh zameen dekh falak dekh fiza dekh\nMashriq se ubharte hue sooraj ko zara dekh",
     "Open your eyes: behold the earth, the sky, the cosmos! Gaze upon the radiant sun rising from the East!",
     "اپنی آنکھیں کھولو اور زمین، آسمان اور فضا کے حسن پر غور کرو؛ مشرق سے بیداری کے ابھرتے ہوئے سورج کو دیکھو۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "dua", "Dua & Blessings",
     "دلِ بینا بھی کر خدا سے طلب\nآنکھ کا نور دل کا نور نہیں",
     "Dil-e-beena bhi kar khuda se talab\nAankh ka noor dil ka noor nahin",
     "Seek from God an insightful perceiving heart; the physical vision of the eyes is not the true light of the soul.",
     "خدا سے بصیرت والا دل مانگو، کیونکہ ظاہری آنکھوں کی بینائی دل کی سچی روشنی کا نعم البدل نہیں ہو سکتی۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "falsafa", "Philosophy & Reflection",
     "یقینِ محکم، عملِ پیہم، محبت فاتحِ عالم\nجہادِ زندگانی میں ہیں یہ مردوں کی شمشیریں",
     "Yaqeen-e-muhkam amal-e-paiham mohabbat faateh-e-aalam\nJihad-e-zindagani mein hain yeh mardon ki shamsheerein",
     "Unyielding conviction, ceaseless action, and world-conquering love: these are the trusty swords of noble champions in life's battle.",
     "پختہ یقین، مسلسل محنت اور دنیا کو مسخر کرنے والی محبت، زندگی کے میدان میں انسان کے سب سے بڑے ہتھیار ہیں۔"),
    ("Allama Iqbal", "علامہ محمد اقبال", "Sialkot / Lahore, Pakistan", "1877 – 1938", "ur", "dua", "Dua & Blessings",
     "مرا طریق امیری نہیں، فقیری ہے\nخودی نہ بیچ، غریبی میں نام پیدا کر",
     "Mera tareeq ameeri nahin faqiri hai\nKhudi na bech ghareebi mein naam paida kar",
     "My path is not the pursuit of worldly wealth, but ascetic dignity; never sell your honor—achieve greatness even in simplicity.",
     "میرا طریقہ فقیری اور سادگی کا ہے، کبھی اپنی خودی اور غیرت کا سودا نہ کرو اور سادگی میں بھی باوقار نام کماؤ۔"),

    # FAIZ AHMAD FAIZ
    ("Faiz Ahmad Faiz", "فیض احمد فیض", "Sialkot / Lahore, Pakistan", "1911 – 1984", "ur", "inqilab", "Revolution & Hope",
     "بول کہ لب آزاد ہیں تیرے\nبول زباں اب تک تیری ہے",
     "Bol ke lab azaad hain tere\nBol zabaan ab tak teri hai",
     "Speak, for your lips are yet free; speak, for your voice is still your own!",
     "آواز بلند کر کیونکہ تیرے ہونٹ ابھی آزاد ہیں اور سچ کہنا تیرا حق ہے!"),
    ("Faiz Ahmad Faiz", "فیض احمد فیض", "Sialkot / Lahore, Pakistan", "1911 – 1984", "ur", "inqilab", "Revolution & Hope",
     "ہم پرورشِ لوح و قلم کرتے رہیں گے\nجو دل پہ گزرتی ہے رقم کرتے رہیں گے",
     "Hum parvarish-e-lauh-o-qalam karte rahenge\nJo dil pe guzarti hai raqam karte rahenge",
     "We shall nurture the sacred page and pen; whatever the heart endures, we shall chronicle without fear.",
     "ہم قلم اور کاغذ کا حق ادا کرتے رہیں گے، اور دل پر جو بھی بیتے گی اسے سچائی کے ساتھ لکھتے رہیں گے۔"),
    ("Faiz Ahmad Faiz", "فیض احمد فیض", "Sialkot / Lahore, Pakistan", "1911 – 1984", "ur", "ishq", "Love & Romance",
     "گلوں میں رنگ بھرے بادِ نوبہار چلے\nچلے بھی آؤ کہ گلشن کا کاروبار چلے",
     "Gulon mein rang bhare baad-e-naubahar چلے\nChale bhi aao ke gulshan ka karobar chale",
     "Let blossoms blush with hue as the spring breeze stirs; come forth, my love, so the garden's life may awaken.",
     "بہار کی ہوا چلی ہے اور پھولوں میں رنگ بھر رہے ہیں، تم بھی آ جاؤ تاکہ اس گلشن کی رونق بحال ہو سکے۔"),
    ("Faiz Ahmad Faiz", "فیض احمد فیض", "Sialkot / Lahore, Pakistan", "1911 – 1984", "ur", "ishq", "Love & Romance",
     "مجھ سے پہلی سی محبت مرے محبوب نہ مانگ\nمیں نے سمجھا تھا کہ تو ہے تو درخشاں ہے حیات",
     "Mujh se pehli si mohabbat mere mehboob na maang\nMain ne samjha tha ke tu hai to darakhshan hai hayaat",
     "Do not ask of me that first carefree passion, my love; once I believed that with you alone, all life was luminous.",
     "مجھ سے اب پہلے جیسی بے پروا محبت کا تقاضا نہ کرو، کیونکہ دنیا کے دوسرے دکھوں نے بھی دل کو گھیر لیا ہے۔"),
    ("Faiz Ahmad Faiz", "فیض احمد فیض", "Sialkot / Lahore, Pakistan", "1911 – 1984", "ur", "dard", "Sorrow & Longing",
     "اور بھی دکھ ہیں زمانے میں محبت کے سوا\nراحتیں اور بھی ہیں وصل کی راحت کے سوا",
     "Aur bhi dukh hain zamaane mein mohabbat ke siwa\nRahatein aur bhi hain wasl ki rahat ke siwa",
     "There are other sorrows in this world beyond love; there are other consolations beyond the ecstasy of union.",
     "اس دنیا میں عشق کے دکھ کے علاوہ اور بھی تلخیاں ہیں، اور محبوب کے وصل کے سوا بھی زندگی میں بہت سی راحتیں موجود ہیں۔"),
    ("Faiz Ahmad Faiz", "فیض احمد فیض", "Sialkot / Lahore, Pakistan", "1911 – 1984", "ur", "inqilab", "Revolution & Hope",
     "ہم دیکھیں گے لازم ہے کہ ہم بھی دیکھیں گے\nوہ دن کہ جس کا وعدہ ہے جو لوحِ ازل پہ لکھا ہے",
     "Hum dekhenge laazim hai ke hum bhi dekhenge\nWo din ke jis ka waada hai jo lauh-e-azal pe likha hai",
     "We shall witness, it is inevitable that we too shall see that promised dawn inscribed upon the eternal tablet.",
     "ہم ضرور دیکھیں گے کہ جب ظلم کے پہاڑ روئی کی طرح اڑیں گے اور حق و انصاف کا راج قائم ہوگا۔"),
    ("Faiz Ahmad Faiz", "فیض احمد فیض", "Sialkot / Lahore, Pakistan", "1911 – 1984", "ur", "inqilab", "Revolution & Hope",
     "نثار میں تری گلیوں کے اے وطن کہ جہاں\nچلی ہے رسم کہ کوئی نہ سر اٹھا کے چلے",
     "Nisaar main teri galiyon ke ae watan ke jahan\nChali hai rasm ke koi na sar utha ke chale",
     "Sacrificed be I upon your sacred streets, O homeland, where a tyranny reigns that none may walk with head held high.",
     "اے وطن میں تیری گلیوں پر نثار جاؤں جہاں ایسا ظالمانہ دستور بنا دیا گیا ہے کہ کوئی سر اٹھا کر سچ نہ بول سکے۔"),
    ("Faiz Ahmad Faiz", "فیض احمد فیض", "Sialkot / Lahore, Pakistan", "1911 – 1984", "ur", "dard", "Sorrow & Longing",
     "آئے کچھ ابر کچھ شراب آئے\nاس کے بعد آئے جو عذاب آئے",
     "Aaye kuch abr kuch sharab aaye\nUs ke baad aaye jo azaab aaye",
     "Let gentle clouds gather, let the cup of wine arrive; after that, let whatever torments destiny wills follow.",
     "بارش کے بادل گھر آئیں اور محبت کا جام ہاتھ میں ہو، پھر چاہے زمانے کے سارے عذاب ہی کیوں نہ ٹوٹ پڑیں۔"),

    # AHMAD FARAZ
    ("Ahmad Faraz", "احمد فراز", "Kohat / Islamabad, Pakistan", "1931 – 2008", "ur", "ishq", "Love & Romance",
     "سلسلے توڑ گیا وہ سبھی جاتے جاتے\nورنہ اتنے تو مراسم تھے کہ آتے جاتے",
     "Silsile tor gaya wo sabhi jaate jaate\nWarna itne to maraasim the ke aate jaate",
     "Departing, they severed every link; otherwise there was enough acquaintance for passing visits.",
     "جاتے جاتے وہ تمام تعلقات ختم کر گیا، حالانکہ اتنی جان پہچان تو تھی کہ کبھی کبھار ملاقات ہو سکتی۔"),
    ("Ahmad Faraz", "احمد فراز", "Kohat / Islamabad, Pakistan", "1931 – 2008", "ur", "ishq", "Love & Romance",
     "اس سے پہلے کہ بے وفا ہو جائیں\nکیوں نہ اے دوست ہم جدا ہو جائیں",
     "Is se pehle ke be-wafa ho jayein\nKyun na ae dost hum juda ho jayein",
     "Before we turn unfaithful to our sacred bond, why do we not part with grace, dear companion?",
     "اس سے پہلے کہ محبت میں بے وفائی در آئے، کیوں نہ ہم باوقار طریقے سے الگ ہو جائیں۔"),
    ("Ahmad Faraz", "احمد فراز", "Kohat / Islamabad, Pakistan", "1931 – 2008", "ur", "ishq", "Love & Romance",
     "شکوۂ ظلمتِ شب سے تو کہیں بہتر تھا\nاپنے حصے کی کوئی شمع جلاتے جاتے",
     "Shikwa-e-zulmat-e-shab se to kahin behtar tha\nApne hisse ki koi shama jalaate jaate",
     "Far better than lamenting the night's darkness would have been to light the candle of your own share.",
     "رات کے اندھیرے کا شکوہ کرنے کے بجائے کتنا اچھا ہوتا کہ ہم اپنی بساط کے مطابق کوئی چراغ روشن کر جاتے۔"),
    ("Ahmad Faraz", "احمد فراز", "Kohat / Islamabad, Pakistan", "1931 – 2008", "ur", "ishq", "Love & Romance",
     "سنا ہے بولے تو باتوں سے پھول جھڑتے ہیں\nیہ بات ہے تو چلو بات کر کے دیکھتے ہیں",
     "Suna hai bole to baaton se phool jharte hain\nYeh baat hai to chalo baat kar ke dekhte hain",
     "They say when my beloved speaks, fragrant blossoms shower; if true, let us converse and see.",
     "سنا ہے کہ وہ بولیں تو پھول جھڑتے ہیں، اگر ایسی بات ہے تو چل کر ان سے گفتگو کر کے دیکھتے ہیں۔"),
    ("Ahmad Faraz", "احمد فراز", "Kohat / Islamabad, Pakistan", "1931 – 2008", "ur", "ishq", "Love & Romance",
     "آنکھ سے دور نہ ہو دل سے اتر جائے گا\nوقت کا کیا ہے گزرتا ہے گزر جائے گا",
     "Aankh se door na ho dil se utar jaaye ga\nWaqt ka kya hai guzarta hai guzar jaaye ga",
     "Let them not stray from sight, lest they slip from the heart; as for time, it always passes and will pass.",
     "محبوب کو نگاہوں سے اوجھل نہ ہونے دو ورنہ دل سے اتر جائے گا، وقت کا کیا ہے وہ تو گزر ہی جائے گا۔"),
    ("Ahmad Faraz", "احمد فراز", "Kohat / Islamabad, Pakistan", "1931 – 2008", "ur", "ishq", "Love & Romance",
     "کروں نہ یاد تو ہر بات بھول جاتی ہے\nشمار کیجیے تو ہر اک ادا میں رہتا ہے",
     "Karun na yaad to har baat bhool jaati hai\nShumaar kijiye to har ik ada mein rehta hai",
     "If I try not to reminisce, everything fades away; yet if counted, they linger in every subtle gesture of life.",
     "اگر یاد نہ کروں تو لگتا ہے سب کچھ بھول گیا، مگر سوچوں تو وہ زندگی کی ہر ادا اور سانس میں بسا ہے۔"),

    # JAUN ELIA
    ("Jaun Elia", "جون ایلیا", "Amroha, India / Karachi, Pakistan", "1931 – 2002", "ur", "ishq", "Love & Romance",
     "بے دلی کیا یوں ہی دن گزر جائیں گے\nصرف زندہ رہے ہم تو مر جائیں گے",
     "Be-dili kya yunhi din guzar jayeinge\nSirf zinda rahe hum to mar jayeinge",
     "Listless apathy! Will our days pass in such vanity? If we merely exist without soul, we shall perish.",
     "کیا بے دلی سے ہی سارے دن بیت جائیں گے؟ اگر صرف سانسیں لیتے رہے تو ہم زندہ درگور ہو جائیں گے۔"),
    ("Jaun Elia", "جون ایلیا", "Amroha, India / Karachi, Pakistan", "1931 – 2002", "ur", "ishq", "Love & Romance",
     "شاید مجھے کسی سے محبت نہیں ہوئی\nلیکن یقین سب کو دلاتا رہا ہوں میں",
     "Shayad mujhe kisi se mohabbat nahin hui\nLekin yaqeen sab ko dilata raha hun main",
     "Perhaps I have truly never loved anyone; yet I spent my life convincing everyone that I did.",
     "شاید مجھے حقیقت میں کسی سے عشق نہ ہوا، مگر میں ساری عمر سب کو اس کا یقین دلاتا رہا۔"),
    ("Jaun Elia", "جون ایلیا", "Amroha, India / Karachi, Pakistan", "1931 – 2002", "ur", "ishq", "Love & Romance",
     "جو گزاری نہ جا سکی ہم سے\nہم نے وہ زندگی گزاری ہے",
     "Jo guzaari na ja saki hum se\nHum ne wo zindagi guzaari hai",
     "The life that was unbearable to endure—that is the very life we have somehow lived through.",
     "وہ زندگی جو کسی طور جینے کے لائق نہ تھی، ہم نے وہی زندگی کاٹ کر دکھائی ہے۔"),
    ("Jaun Elia", "جون ایلیا", "Amroha, India / Karachi, Pakistan", "1931 – 2002", "ur", "dard", "Sorrow & Longing",
     "کتنی دلکش ہو تم کتنا دل جو ہوں میں\nکیا ستم ہے کہ ہم لوگ مر جائیں گے",
     "Kitni dilkash ho tum kitna dil-ju hun main\nKya sitam hai ke hum log mar jayeinge",
     "How charming you are, and how yearning a heart I possess; what a tragedy that one day we shall both pass away.",
     "تم کتنی دلکش ہو اور میں کتنا چاہنے والا دل رکھتا ہوں، کیسا ستم ہے کہ ایک دن ہم دونوں مٹی ہو جائیں گے۔"),
    ("Jaun Elia", "جون ایلیا", "Amroha, India / Karachi, Pakistan", "1931 – 2002", "ur", "ishq", "Love & Romance",
     "نیا اک رشتہ پیدا کیوں کریں ہم\nبچھڑنا ہے تو جھگڑا کیوں کریں ہم",
     "Naya ik rishta paida kyun karein hum\nBichharna hai to jhagray kyun karein hum",
     "Why forge a new bond when parted we must be? If separation is fate, why contend and struggle?",
     "ہم نیا رشتہ کیوں بنائیں جب معلوم ہے کہ جدا ہونا ہے؛ اگر بچھڑنا ہی مقدر ہے تو جھگڑا کیسا۔"),

    # PARVEEN SHAKIR
    ("Parveen Shakir", "پروین شاکر", "Karachi / Islamabad, Pakistan", "1952 – 1994", "ur", "ishq", "Love & Romance",
     "کو بہ کو پھیل گئی بات شناسائی کی\nاس نے خوشبو کی طرح میری پذیرائی کی",
     "Koo-ba-koo phail gayi baat shanasayi ki\nUs ne khushbu ki tarah meri paziraayi ki",
     "From street to street the story of our acquaintance spread; they welcomed me as fragrance embraces the air.",
     "ہماری شناسائی کا چرچا گلی گلی پھیل گیا، اس نے خوشبو کی مانند میرا استقبال کیا۔"),
    ("Parveen Shakir", "پروین شاکر", "Karachi / Islamabad, Pakistan", "1952 – 1994", "ur", "ishq", "Love & Romance",
     "حسن کے سمجھنے کو عمر چاہیے جاناں\nدو گھڑی کی چاہت میں لڑکپن نہیں جاتا",
     "Husn ke samajhne ko umr chahiye jaanan\nDo ghari ki chahat mein larkpan nahin jaata",
     "To truly comprehend beauty requires a lifetime, my love; brief affection cannot outgrow youthful naivety.",
     "حقیقی حسن کی قدر جاننے کے لیے عمر درکار ہے، گھڑی دو گھڑی کے عشق سے نادانی دور نہیں ہوتی۔"),
    ("Parveen Shakir", "پروین شاکر", "Karachi / Islamabad, Pakistan", "1952 – 1994", "ur", "dard", "Sorrow & Longing",
     "کیسے کہہ دوں کہ مجھے چھوڑ دیا ہے اس نے\nبات تو سچ ہے مگر بات ہے رسوائی کی",
     "Kaise keh dun ke mujhe chhor diya hai us ne\nBaat to sach hai magar baat hai ruswayi ki",
     "How could I confess that they have abandoned me? The statement is true, but it brings public humiliation.",
     "میں دنیا کے سامنے کیسے اقرار کروں کہ اس نے مجھے چھوڑ دیا ہے، بات تو سچ ہے مگر اس میں رسوائی چھپی ہے۔"),
    ("Parveen Shakir", "پروین شاکر", "Karachi / Islamabad, Pakistan", "1952 – 1994", "ur", "ishq", "Love & Romance",
     "عکسِ خوشبو ہوں بکھرنے سے نہ روکے کوئی\nاور بکھر جاؤں تو مجھ کو نہ سمیٹے کوئی",
     "Aks-e-khushbu hun bikharne se na roke koi\nAur bikhar jaaun to mujh ko na samete koi",
     "I am the reflection of pure fragrance, let none hinder me from scattering; and when I disperse, let none attempt to gather me.",
     "میں خوشبو کا عکس ہوں مجھے فضا میں بکھرنے دو، اور جب میں بکھر جاؤں تو پھر کسی کو سمیٹنے کی زحمت نہ ہو۔"),
    ("Parveen Shakir", "پروین شاکر", "Karachi / Islamabad, Pakistan", "1952 – 1994", "ur", "ishq", "Love & Romance",
     "کمالِ ضبط کو خود بھی تو آزماؤں گی\nمیں اپنے ہاتھ سے اس کی دلہن سجاؤں گی",
     "Kamaal-e-zabt ko khud bhi to aazmaaungi\nMain apne haath se us ki dulhan sajaaungi",
     "I shall put my own supreme patience to the test: with my own hands I shall adorn the bride of my beloved.",
     "میں اپنے صبر اور حوصلے کی انتہا دیکھوں گی کہ خود اپنے ہاتھوں سے اس کے گھر کی خوشیاں سجاؤں گی۔"),

    # MIR TAQI MIR
    ("Mir Taqi Mir", "میر تقی میر", "Agra / Delhi / Lucknow, India", "1723 – 1810", "ur", "ishq", "Love & Romance",
     "پتا پتا بوٹا بوٹا حال ہمارا جانے ہے\nجانے نہ جانے گل ہی نہ جانے باغ تو سارا جانے ہے",
     "Patta patta boota boota haal hamara jaane hai\nJaane na jaane gul hi na jaane baagh to saara jaane hai",
     "Every leaf and every branch knows our condition of love; whether the elusive rose acknowledges it or not, the entire garden knows.",
     "چمن کا ہر پتا اور بوٹا ہمارے دل کی حالت جانتا ہے، اگر محبوب گل بے خبر بھی رہے تو سارا باغ واقف ہے۔"),
    ("Mir Taqi Mir", "میر تقی میر", "Agra / Delhi / Lucknow, India", "1723 – 1810", "ur", "dard", "Sorrow & Longing",
     "نازکی اس کے لب کی کیا کہیے\nپنکھڑی اک گلاب کی سی ہے",
     "Naazuki us ke lab ki kya kahiye\nPankhuri ik gulaab ki si hai",
     "How can one praise the delicate softness of her lips? They are like the petal of a rose.",
     "محبوب کے لبوں کی نزاکت کا کیا بیان ہو، وہ تو گلاب کی تازہ پنکھڑی جیسے نازک ہیں۔"),
    ("Mir Taqi Mir", "میر تقی میر", "Agra / Delhi / Lucknow, India", "1723 – 1810", "ur", "falsafa", "Philosophy & Reflection",
     "ہستی اپنی حباب کی سی ہے\nیہ نمائش سراب کی سی ہے",
     "Hasti apni hubaab ki si hai\nYeh numaish saraab ki si hai",
     "Our existence is like a fleeting water bubble; this worldly display is merely like a desert mirage.",
     "انسان کی زندگی پانی کے بلبلے کی طرح ناپائیدار ہے اور یہ ساری دنیا سراب کی مانند ایک دھوکا ہے۔"),
    ("Mir Taqi Mir", "میر تقی میر", "Agra / Delhi / Lucknow, India", "1723 – 1810", "ur", "ishq", "Love & Romance",
     "الٹی ہو گئیں سب تدبیریں کچھ نہ دوا نے کام کیا\nدیکھا اس بیماریِ دل نے آخر کام تمام کیا",
     "Ulti ho gayin sab tadbeerein kuch na dawa ne kaam kiya\nDekha is beemari-e-dil ne aakhir kaam tamaam kiya",
     "All remedies turned upside down, no medicine proved of avail; you see how this malady of the heart finally accomplished our end.",
     "عشق کے علاج کی تمام تدبیریں الٹی پڑ گئیں اور کسی دوا نے اثر نہ کیا، آخر کار دل کے اس روگ نے کام تمام کر دیا۔"),
    ("Mir Taqi Mir", "میر تقی میر", "Agra / Delhi / Lucknow, India", "1723 – 1810", "ur", "dard", "Sorrow & Longing",
     "شام ہی سے بجھا سا رہتا ہے\nدل ہے گویا چراغِ مفلس کا",
     "Shaam hi se bujha sa rehta hai\nDil hai goya charagh-e-muflis ka",
     "From early dusk it remains dim and extinguished; the heart is as if the meager lamp of an impoverished pauper.",
     "شام ہوتے ہی دل بجھ سا جاتا ہے، جیسے کسی غریب اور نادار شخص کا تیل کے بغیر ٹمٹماتا ہوا چراغ ہو۔"),
    ("Mir Taqi Mir", "میر تقی میر", "Agra / Delhi / Lucknow, India", "1723 – 1810", "ur", "falsafa", "Philosophy & Reflection",
     "لے سانس بھی آہستہ کہ نازک ہے بہت کام\nآفاق کی اس کارگہِ شیشہ گری کا",
     "Le saans bhi aahista ke naazuk hai bohat kaam\nAafaaq ki is kaargah-e-sheesha-gari ka",
     "Draw even your breath softly, for delicate is the intricate work of this universe's grand glassblower's workshop.",
     "سانس بھی سنبھل کر اور آہستہ لو، کیونکہ یہ دنیا شیشے کے نازک کارخانے کی طرح ہے جو ذرا سی ٹھیس سے ٹوٹ جاتا ہے۔"),

    # NASIR KAZMI
    ("Nasir Kazmi", "ناصر کاظمی", "Ambala, India / Lahore, Pakistan", "1925 – 1972", "ur", "dard", "Sorrow & Longing",
     "گئے دنوں کا سراغ لے کر کدھر سے آیا کدھر گیا وہ\nعجیب مانوس اجنبی تھا مجھے تو حیران کر گیا وہ",
     "Gaye dinon ka suragh le kar kidhar se aaya kidhar gaya wo\nAjeeb maanoos ajnabi tha mujhe to hairan kar gaya wo",
     "Carrying traces of bygone days, whence did he come and whither did he go? A familiar stranger who left me in awe.",
     "ماضی کی یادیں لیے وہ کہاں سے آیا اور کہاں چلا گیا، وہ ایسا اجنبی تھا جو اپنا بھی لگتا تھا اور مجھے حیرت میں ڈال گیا۔"),
    ("Nasir Kazmi", "ناصر کاظمی", "Ambala, India / Lahore, Pakistan", "1925 – 1972", "ur", "dard", "Sorrow & Longing",
     "شہر کی بے چراغ گلیوں میں\nزندگی منہ چھپائے پھرتی ہے",
     "Shehr ki be-charagh galiyon mein\nZindagi munh chhupaaye phirti hai",
     "In the lamp-less alleys of the city, life wanders hiding its face in sorrow.",
     "شہر کی اندھیری گلیوں میں زندگی مایوسی کے عالم میں منہ چھپائے پھر رہی ہے۔"),
    ("Nasir Kazmi", "ناصر کاظمی", "Ambala, India / Lahore, Pakistan", "1925 – 1972", "ur", "dard", "Sorrow & Longing",
     "پھول سوکھے ہوئے بکھرے ہیں سرِ راہِ وفا\nکوئی گزرا ہے بہاروں کو لٹاتا ہوا سا",
     "Phool sookhe hue bikhre hain sar-e-raah-e-wafa\nKoi guzra hai bahaaron ko lutaata hua sa",
     "Withered blossoms lie scattered along the boulevard of devotion; someone has passed by scattering the splendors of spring.",
     "وفا کی راہ پر مرجھائے ہوئے پھول بکھرے پڑے ہیں، جیسے کوئی بہاروں کا خزانہ لٹاتا ہوا رخصت ہو گیا ہو۔"),

    # HABIB JALIB
    ("Habib Jalib", "حبیب جالب", "Hoshiarpur, India / Lahore, Pakistan", "1928 – 1993", "ur", "inqilab", "Revolution & Hope",
     "ظلم رہے اور امن بھی ہو کیا ممکن ہے تم ہی کہو\nخون بھی بہے اور بات نہ ہو کیا ممکن ہے تم ہی کہو",
     "Zulm rahe aur aman bhi ho kya mumkin hai tum hi kaho\nKhoon bhi bahe aur baat na ho kya mumkin hai tum hi kaho",
     "Can tyranny persist alongside peace? You tell me, is it possible? Can blood flow without voices speaking?",
     "تم خود ہی فیصلہ کرو، کیا ظلم کے سائے میں امن قائم رہ سکتا ہے یا ناحق خون بہنے پر خاموشی ممکن ہے؟"),
    ("Habib Jalib", "حبیب جالب", "Hoshiarpur, India / Lahore, Pakistan", "1928 – 1993", "ur", "inqilab", "Revolution & Hope",
     "تم سے پہلے وہ جو اک شخص یہاں تخت نشیں تھا\nاس کو بھی اپنے خدا ہونے پہ اتنا ہی یقیں تھا",
     "Tum se pehle wo jo ik shakhs yahan takht-nasheen tha\nUs ko bhi apne khuda hone pe itna hi yaqeen tha",
     "The ruler who sat upon the throne here before you: he too was just as convinced of his own invincibility.",
     "تجھ سے پہلے جو حکمران یہاں اقتدار پر بیٹھا تھا، اسے بھی اپنے خدا ہونے کا اتنا ہی زعم تھا۔"),
    ("Habib Jalib", "حبیب جالب", "Hoshiarpur, India / Lahore, Pakistan", "1928 – 1993", "ur", "inqilab", "Revolution & Hope",
     "شہر میں ہو کا عالم تھا جب ہم بولے\nخاموشیوں کا پردہ ہٹا جب ہم بولے",
     "Shehr mein hoo ka aalam tha jab hum bole\nKhamoshiyon ka parda hata jab hum bole",
     "A desolate silence reigned across the terrified city when we spoke; the veil of fearful silence was torn when we raised our voice.",
     "جب ظلم کے خوف سے پورا شہر خاموش تھا تب ہم نے کلمۂ حق کہا اور گونگی خاموشی کا پردہ چاک کیا۔"),

    # MOMIN KHAN MOMIN
    ("Momin Khan Momin", "مومن خاں مومن", "Delhi, India", "1800 – 1851", "ur", "ishq", "Love & Romance",
     "شب جو مسجد میں جا پھنسے مومنؔ\nرات کاٹی خدا خدا کر کے",
     "Shab jo masjid mein jaa phanse Momin\nRaat kaati khuda khuda kar ke",
     "When Momin found himself trapped in the ascetic sanctuary last night, he passed the entire night pleading desperately for release.",
     "رات کو جب مومن مسجد میں زاہدوں کے بیچ جا پھنسے، تو خدا خدا کر کے اور بڑی مشکلوں سے رات کاٹی۔"),
    ("Momin Khan Momin", "مومن خاں مومن", "Delhi, India", "1800 – 1851", "ur", "ishq", "Love & Romance",
     "رویا کریں گے آپ بھی پہروں اسی طرح\nاٹکا کہیں جو آپ کا دل بھی مری طرح",
     "Roya karenge aap bhi pehron usi tarah\nAtka kahin jo aap ka dil bhi meri tarah",
     "You too will weep for endless hours in just this way, if ever your heart becomes hopelessly entangled like mine.",
     "اگر آپ کا دل بھی میری طرح کسی بے درد پر آ گیا، تو آپ بھی اسی طرح گھنٹوں آنسو بہایا کریں گے۔"),

    # DAGH DEHLVI
    ("Dagh Dehlvi", "داغؔ دہلوی", "Delhi / Hyderabad, India", "1831 – 1905", "ur", "ishq", "Love & Romance",
     "اردو ہے جس کا نام ہمیں جانتے ہیں داغؔ\nسارے جہاں میں دھوم ہماری زباں کی ہے",
     "Urdu hai jis ka naam humein jaante hain Dagh\nSaare jahaan mein dhoom hamari zabaan ki hai",
     "Urdu is its name and we know its grace, O Dagh; throughout the entire world our melodious tongue is celebrated.",
     "اے داغ! ہمیں معلوم ہے کہ اردو کیسی میٹھی زبان ہے، جس کی شیرینی کی دھوم پوری دنیا میں مچی ہے۔"),
    ("Dagh Dehlvi", "داغؔ دہلوی", "Delhi / Hyderabad, India", "1831 – 1905", "ur", "ishq", "Love & Romance",
     "ہوش اڑتے ہیں مسکرانے سے\nجان جاتی ہے پاس آنے سے",
     "Hosh urte hain muskurane se\nJaan jaati hai paas aane se",
     "Senses take flight merely from their gentle smile; life itself departs whenever they draw close.",
     "محبوب کی ایک مسکراہٹ سے ہوش اڑ جاتے ہیں، اور ان کے قریب آنے سے دل کی دھڑکنیں قابو سے باہر ہو جاتی ہیں۔"),
    ("Dagh Dehlvi", "داغؔ دہلوی", "Delhi / Hyderabad, India", "1831 – 1905", "ur", "ishq", "Love & Romance",
     "خوب پردہ ہے کہ چلمن سے لگے بیٹھے ہیں\nصاف چھپتے بھی نہیں سامنے آتے بھی نہیں",
     "Khoob parda hai ke chilman se lage baithe hain\nSaaf chhupte bhi nahin saamne aate bhi nahin",
     "A curious veil indeed: sitting right behind the screen; neither fully hiding nor stepping openly into view.",
     "پردے کا بھی کیا انداز ہے کہ چلمن سے لگے بیٹھے ہیں؛ نہ تو مکمل چھپتے ہیں اور نہ ہی سامنے آتے ہیں۔"),

    # BAHADUR SHAH ZAFAR
    ("Bahadur Shah Zafar", "بہادر شاہ ظفر", "Delhi, India / Rangoon, Burma", "1775 – 1862", "ur", "dard", "Sorrow & Longing",
     "بات کرنی مجھے مشکل کبھی ایسی تو نہ تھی\nجیسی اب ہے تری محفل کبھی ایسی تو نہ تھی",
     "Baat karni mujhe mushkil kabhi aisi to na thi\nJaisi ab hai teri mehfil kabhi aisi to na thi",
     "Speaking was never before such an arduous trial for me; your assembly was never so cold and estranged as it is today.",
     "مجھ پر گفتگو کرنا کبھی اتنا کٹھن نہ تھا، اور تمہاری محفل بھی کبھی اتنی بے مروت اور اجنبی نہ تھی۔"),
    ("Bahadur Shah Zafar", "بہادر شاہ ظفر", "Delhi, India / Rangoon, Burma", "1775 – 1862", "ur", "falsafa", "Philosophy & Reflection",
     "نہ کسی کی آنکھ کا نور ہوں نہ کسی کے دل کا سرور ہوں\nجو کسی کے کام نہ آ سکے میں وہ ایک مشتِ غبار ہوں",
     "Na kisi ki aankh ka noor hun na kisi ke dil ka suroor hun\nJo kisi ke kaam na aa sake main wo ek musht-e-ghubaar hun",
     "I am neither the light of anyone's eyes nor the joy of anyone's heart; I am merely a handful of dust that could serve no one's purpose.",
     "نہ میں کسی کی آنکھوں کی روشنی ہوں اور نہ دل کی خوشی، میں تو وہ بے کار مٹھی بھر خاک ہوں جو کسی کام نہ آئی۔"),

    # SAHIR LUDHIANVI
    ("Sahir Ludhianvi", "ساحر لدھیانوی", "Ludhiana / Mumbai, India", "1921 – 1980", "ur", "inqilab", "Revolution & Hope",
     "اک شہنشاہ نے دولت کا سہارا لے کر\nہم غریبوں کی محبت کا اڑایا ہے مذاق",
     "Ik shehenshah ne daulat ka sahara le kar\nHum ghareebon ki mohabbat ka uraya hai mazaq",
     "An emperor relying upon boundless wealth has mocked the genuine love of us impoverished souls in the Taj Mahal.",
     "شہنشاہ نے اپنی بے پناہ دولت کی نمائش کر کے ہم غریبوں کی سچی اور بے لوث محبت کی توہین کی ہے۔"),
    ("Sahir Ludhianvi", "ساحر لدھیانوی", "Ludhiana / Mumbai, India", "1921 – 1980", "ur", "inqilab", "Revolution & Hope",
     "آؤ کہ کوئی خواب بنیں کل کے واسطے\nورنہ یہ رات آج کے دکھ بھی نہ دھو سکے",
     "Aao ke koi khwab bunein kal ke waaste\nWarna yeh raat aaj ke dukh bhi na dho sake",
     "Come, let us weave a hopeful dream for tomorrow; otherwise this somber night cannot even wash away today's sorrow.",
     "آؤ مل کر کل کے روشن مستقبل کا نیا خواب دیکھیں، ورنہ یہ اداس رات ہمارے آج کے دکھوں کو بھی نہیں دھو سکے گی۔"),
    ("Sahir Ludhianvi", "ساحر لدھیانوی", "Ludhiana / Mumbai, India", "1921 – 1980", "ur", "falsafa", "Philosophy & Reflection",
     "میں پل دو پل کا شاعر ہوں پل دو پل مری کہانی ہے\nپل دو پل مری ہستی ہے پل دو پل مری جوانی ہے",
     "Main pal do pal ka shair hun pal do pal meri kahani hai\nPal do pal meri hasti hai pal do pal meri jawani hai",
     "I am a poet of a passing moment, a brief moment is my story; a fleeting moment is my existence and youth.",
     "میری حیثیت صرف پل دو پل کے شاعر کی ہے، وقت کا دھارا ہر گزرنے والے کے بعد نیا کارواں لے آتا ہے۔"),

    # KAIFI AZMI
    ("Kaifi Azmi", "کیفی اعظمی", "Azamgarh / Mumbai, India", "1919 – 2002", "ur", "inqilab", "Revolution & Hope",
     "کر چلے ہم فدا جان و تن ساتھیو\nاب تمہارے حوالے وطن ساتھیو",
     "Kar chale hum fida jaan-o-tan saathiyo\nAb tumhare hawale watan saathiyo",
     "We have laid down our life and soul, dear companions; now the homeland is entrusted into your faithful hands.",
     "ہم نے وطن کے لیے اپنی جان اور تن قربان کر دیا ہے، اب اس پاک دھرتی کی حفاظت تمہارے حوالے ہے۔"),
    ("Kaifi Azmi", "کیفی اعظمی", "Azamgarh / Mumbai, India", "1919 – 2002", "ur", "ishq", "Love & Romance",
     "جھکی جھکی سی نظر بے قرار ہے کہ نہیں\nدبا دبا سا سہی دل میں پیار ہے کہ نہیں",
     "Jhuki jhuki si nazar be-qarar hai ke nahin\nDaba daba sa sahi dil mein pyaar hai ke nahin",
     "Is that lowered bashful gaze restless with longing or not? Suppressed though it may be, does love dwell in the heart or not?",
     "تمہاری جھکی ہوئی پلکوں میں بے قراری چھپی ہے یا نہیں، سچ بتاؤ کہ دل کے گوشے میں محبت کی چنگاری ہے یا نہیں۔"),

    # JOSH MALIHABADI
    ("Josh Malihabadi", "جوش ملیح آبادی", "Malihabad, India / Islamabad, Pakistan", "1898 – 1982", "ur", "inqilab", "Revolution & Hope",
     "روایتوں کے تلے دب کے مر گئے لاکھوں\nحیات نام ہے زنجیر توڑ دینے کا",
     "Rewayaton ke tale dab ke mar gaye laakhon\nHayaat naam hai zanjeer tor dene ka",
     "Millions perished crushed under the weight of blind traditions; true life is the noble name for shattering the chains.",
     "فرسودہ رسم و رواج اور غلامی کے تلے لاکھوں لوگ دب کر ختم ہو گئے، حقیقی زندگی تو جبر کی زنجیریں توڑنے کا نام ہے۔"),

    # JIGAR MORADABADI
    ("Jigar Moradabadi", "جگر مراد آبادی", "Moradabad, India", "1890 – 1960", "ur", "ishq", "Love & Romance",
     "آدمی آدمی سے ملتا ہے\nدل مگر کم کسی سے ملتا ہے",
     "Aadmi aadmi se milta hai\nDil magar kam kisi se milta hai",
     "Human beings meet other human beings constantly; yet rarely does heart truly meet with heart in sincere communion.",
     "لوگ ظاہری طور پر ایک دوسرے سے روز ملتے ہیں، مگر دل سے دل کا سچا ملاپ بہت کم لوگوں کو نصیب ہوتا ہے۔"),
    ("Jigar Moradabadi", "جگر مراد آبادی", "Moradabad, India", "1890 – 1960", "ur", "ishq", "Love & Romance",
     "جان ہی دے دی جگرؔ نے آج پائے یار پر\nعمر بھر کی بے قراری کو قرار آ ہی گیا",
     "Jaan hi de di Jigar ne aaj paaye yaar par\nUmr bhar ki be-qarari ko qaraar aa hi gaya",
     "Jigar has surrendered his very life at the feet of the beloved today; at long last, a lifetime of restlessness found eternal peace.",
     "جگر نے آج محبوب کے قدموں میں اپنی جان نچھاور کر دی، اور عمر بھر کی تڑپ کو بالآخر دائمی سکون مل گیا۔"),

    # HASRAT MOHANI
    ("Hasrat Mohani", "حسرت موہانی", "Mohan / Kanpur, India", "1875 – 1951", "ur", "inqilab", "Revolution & Hope",
     "ہے مشقِ سخن جاری چکی کی مشقت بھی\nاک طرفہ تماشا ہے حسرتؔ کی طبیعت بھی",
     "Hai mashq-e-sukhan jaari chakki ki mashaqqat bhi\nIk turfa tamasha hai Hasrat ki tabeeyat bhi",
     "The poetic composition continues alongside the grueling labor of turning the prison millstone; wondrous indeed is Hasrat's resilient spirit!",
     "قید خانے میں چکی کی مشقت بھی چل رہی ہے اور شعر و سخن کا سفر بھی جاری ہے، حسرت کی ہمت واقعی بے مثال ہے۔"),

    # FIRAQ GORAKHPURI
    ("Firaq Gorakhpuri", "فراق گورکھپوری", "Gorakhpur / Allahabad, India", "1896 – 1982", "ur", "ishq", "Love & Romance",
     "سرزمینِ ہند پر اقوامِ عالم کے فراقؔ\nقافلے آتے گئے اور ہندوستاں بنتا گیا",
     "Sar-zameen-e-hind par aqwaam-e-aalam ke Firaq\nQaafile aate gaye aur hindustaan banta gaya",
     "Upon the sacred soil of India, O Firaq, caravans of diverse world nations kept arriving, and this grand composite culture took shape.",
     "اس دھرتی پر دنیا بھر کی قوموں اور تہذیبوں کے قافلے آتے رہے اور باہمی میل جول سے یہ خوبصورت گلستان بن گیا۔"),

    # IBN-E-INSHA
    ("Ibn-e-Insha", "ابنِ انشا", "Jalandhar, India / Karachi, Pakistan", "1927 – 1978", "ur", "ishq", "Love & Romance",
     "کل چودھویں کی رات تھی شب بھر رہا چرچا ترا\nکچھ نے کہا یہ چاند ہے کچھ نے کہا چہرہ ترا",
     "Kal chaudhwin ki raat thi shab bhar raha charcha tera\nKuch ne kaha yeh chaand hai kuch ne kaha chehra tera",
     "Last night was the full fourteenth moon, all night your praises resonated; some said 'This is the luminous moon,' others said 'It is your glowing countenance.'",
     "گزشتہ رات چودھویں کا پورا چاند تھا اور رات بھر تمہارا ہی ذکر رہا، کوئی اسے فلک کا چاند کہہ رہا تھا تو کوئی تمہارا رخسار۔"),
    ("Ibn-e-Insha", "ابنِ انشا", "Jalandhar, India / Karachi, Pakistan", "1927 – 1978", "ur", "dard", "Sorrow & Longing",
     "ہم رات بہت روئے، اللہ ہی جانتا ہے\nکس جرم کی پاداش میں آنسو یہ بہے ہیں",
     "Hum raat bohat roye Allah hi jaanta hai\nKis jurm ki paadaash mein aansu yeh bahe hain",
     "We wept profusely through the silent night, God alone knows in retribution for what unknown sin these tears poured forth.",
     "ہم نے رات کے اندھیرے میں زار و قطار آنسو بہائے، خدا ہی بہتر جانتا ہے کہ کس دکھ اور خطا کے بدلے یہ دل رویا ہے۔"),

    # MOHSIN NAQVI
    ("Mohsin Naqvi", "محسن نقوی", "Dera Ghazi Khan / Lahore, Pakistan", "1947 – 1996", "ur", "dard", "Sorrow & Longing",
     "شام کے بعد جب بھی یاد آئی تیری\nہم نے اشکوں کے چراغوں سے سجائی دنیا",
     "Shaam ke baad jab bhi yaad aayi teri\nHum ne ashkon ke charaghon se sajaayi dunya",
     "Whenever your tender memory arrived after dusk, we adorned the solitude of the world with lamps of glistening tears.",
     "شام ڈھلنے کے بعد جب بھی تیری یاد نے دل پر دستک دی، ہم نے اپنی ویران دنیا کو آنسوؤں کی شمعوں سے روشن کر دیا۔"),
    ("Mohsin Naqvi", "محسن نقوی", "Dera Ghazi Khan / Lahore, Pakistan", "1947 – 1996", "ur", "ishq", "Love & Romance",
     "وہ اک پل جو تیرے قرب میں گزرا تھا کبھی\nآج بھی اس کی مہک سے ہے معطر یہ حیات",
     "Wo ik pal jo tere qurb mein guzra tha kabhi\nAaj bhi us ki mehek se hai muattar yeh hayaat",
     "That single fleeting moment once spent in your comforting closeness: even today life remains perfumed by its gentle fragrance.",
     "وہ ایک لمحہ جو کبھی تمہارے ساتھ ہنستے مسکراتے گزرا تھا، آج بھی اس کی مہک میری زندگی کو معطر کیے ہوئے ہے۔"),

    # SAGHAR SIDDIQUI
    ("Saghar Siddiqui", "ساغر صدیقی", "Ambala, India / Lahore, Pakistan", "1928 – 1974", "ur", "falsafa", "Philosophy & Reflection",
     "جس عہد میں لٹ جائے فقیروں کی کمائی\nاس عہد کے سلطان سے کوئی بھول ہوئی ہے",
     "Jis ehad mein lut jaaye faqiron ki kamaayi\nUs ehad ke sultan se koi bhool hui hai",
     "In that era when the meager crust of destitute mendicants is plundered, the reigning monarch of that realm has committed a fatal injustice.",
     "جس دور میں غریبوں اور فقیروں کی روزی چھن جائے، سمجھ لو کہ اس ملک کے حکمران نے کوئی بہت بڑی ناانصافی کی ہے۔"),

    # SHAKEEL BADAYUNI
    ("Shakeel Badayuni", "شکیل بدایونی", "Badaun / Mumbai, India", "1916 – 1970", "ur", "ishq", "Love & Romance",
     "میرے ہم نفس میرے ہم نوا مجھے دوست بن کے دغا نہ دے\nمیں ہوں دردِ عشق کا مارا ہوا مجھے بے وجہ یوں سزا نہ دے",
     "Mere hum-nafas mere hum-nawa mujhe dost ban ke dagha na de\nMain hun dard-e-ishq ka maara hua mujhe be-waja yun saza na de",
     "O my companion, my confidant: do not betray me beneath the comforting mask of friendship; I am already wounded by love.",
     "اے میرے ہم سفر اور دوست! مجھے دوستی کے روپ میں دھوکا نہ دو، میں تو پہلے ہی محبت کا زخمی ہوں مجھے مزید نہ آزماؤ۔"),

    # QATEEL SHIFAI
    ("Qateel Shifai", "قتیل شفائی", "Haripur, Pakistan", "1919 – 2001", "ur", "ishq", "Love & Romance",
     "پریشاں رات ساری ہے ستارو تم تو سو جاؤ\nسکوتِ مرگ طاری ہے ستارو تم تو سو جاؤ",
     "Pareshaan raat saari hai sitaro tum to so jaao\nSukoot-e-marg taari hai sitaro tum to so jaao",
     "The entire night is fraught with distress, O stars, you at least may slumber; the stillness of grief reigns over all.",
     "میری پوری رات بے قراری میں کٹ رہی ہے اے ستارو تم تو سو جاؤ، چاروں طرف گہرا سناٹا ہے تم اپنی آنکھیں موند لو۔"),

    # NIDA FAZLI
    ("Nida Fazli", "ندا فاضلی", "Gwalior / Mumbai, India", "1938 – 2016", "ur", "falsafa", "Philosophy & Reflection",
     "گھر سے نکلے تو راہ میں پتھر ہزار تھے\nپر اپنے ہی قدم تھے جو بار بار ڈگمگائے",
     "Ghar se nikle to raah mein patthar hazaar the\nPar apne hi qadam the jo baar baar dagmagaaye",
     "When we set forth from home, a thousand stones lay along the path; yet it was our own hesitant steps that faltered time and again.",
     "جب منزل کی طرف چلے تو راستے میں ہزاروں رکاوٹیں تھیں، لیکن اصل آزمائش ہمارے اپنے ڈگمگاتے قدموں کی تھی۔"),

    # BASHIR BADR
    ("Bashir Badr", "بشیر بدر", "Kanpur / Bhopal, India", "1935 – Present", "ur", "ishq", "Love & Romance",
     "آنکھوں میں رہا دل میں اتر کر نہیں دیکھا\nکشتی کے مسافر نے سمندر نہیں دیکھا",
     "Aankhon mein raha dil mein utar kar nahin dekha\nKashti ke musaafir ne samandar nahin dekha",
     "They lingered only in the gaze, never descending into the heart; like a boat traveler who never truly perceived the depth of the ocean.",
     "وہ صرف آنکھوں کے سامنے رہے کبھی دل کی گہرائی میں اتر کر نہ دیکھا، جیسے کشتی کے مسافر نے سمندر کے اصل راز کو نہ جانا ہو۔"),
    ("Bashir Badr", "بشیر بدر", "Kanpur / Bhopal, India", "1935 – Present", "ur", "ishq", "Love & Romance",
     "کوئی ہاتھ بھی نہ ملائے گا جو گلے ملو گے تپاک سے\nیہ نئے مزاج کا شہر ہے ذرا فاصلے سے ملا کرو",
     "Koi haath bhi na milaaye ga jo gale milo ge tapaak se\nYeh naye mizaaj ka shehr hai zara faasle se mila karo",
     "No one will even shake your hand if you embrace with passionate warmth; this is a modern distant town—greet others with measured caution.",
     "اگر تم والہانہ انداز سے گلے ملو گے تو لوگ ہاتھ بھی نہیں ملائیں گے، یہ نئے زمانے کا شہر ہے یہاں ذرا فاصلہ رکھ کر ملو۔"),

    # RAHAT INDORI
    ("Rahat Indori", "راحت اندوری", "Indore, India", "1950 – 2020", "ur", "inqilab", "Revolution & Hope",
     "اگر خلاف ہیں ہونے دو جان تھوڑی ہے\nیہ سب دھواں ہے کوئی آسماں تھوڑی ہے",
     "Agar khilaaf hain hone do jaan thori hai\nYeh sab dhuwaan hai koi aasmaan thori hai",
     "If they stand in opposition, let them be; life itself is not hanging by their favor! All this noise is mere transient smoke, not the firmament!",
     "اگر لوگ مخالف ہیں تو ہونے دو اس سے جان نہیں جاتی، یہ وقتی پروپیگنڈا دھواں ہے جو جلد چھٹ جائے گا۔"),
    ("Rahat Indori", "راحت اندوری", "Indore, India", "1950 – 2020", "ur", "inqilab", "Revolution & Hope",
     "لگے گی آگ تو آئیں گے گھر کئی زد میں\nیہاں پہ صرف ہمارا مکان تھوڑی ہے",
     "Lagegi aag to aayenge ghar kai zad mein\nYahan pe sirf hamara makaan thori hai",
     "If the blaze ignites, numerous dwellings will be engulfed; our modest house is not the only home standing in this neighborhood.",
     "اگر نفرت کی آگ بھڑکی تو کئی گھر اس کی لپیٹ میں آئیں گے، اس بستی میں صرف ہمارا گھر تو نہیں رہتا۔"),

    # WASIF ALI WASIF
    ("Wasif Ali Wasif", "واصف علی واصف", "Khushab / Lahore, Pakistan", "1929 – 1993", "ur", "falsafa", "Philosophy & Reflection",
     "دل اگر بیدار ہو تو کائنات اک آئینہ ہے\nہر ذرے میں جلوۂ حق عیاں دکھائی دیتا ہے",
     "Dil agar bedaar ho to kaayenat ik aaina hai\nHar zarre mein jalwa-e-haq ayaan dikhayi deta hai",
     "If the heart is spiritually awake, the entire universe becomes a clear mirror; in every atom the radiant manifestation of Divine Truth shines forth.",
     "اگر انسان کا دل باطنی طور پر بیدار ہو تو ساری کائنات ایک آئینہ بن جاتی ہے، جہاں ہر ذرے میں رب کا جلوہ نظر آتا ہے۔"),
    ("Wasif Ali Wasif", "واصف علی واصف", "Khushab / Lahore, Pakistan", "1929 – 1993", "ur", "dua", "Dua & Blessings",
     "راحتِ قلب و جاں ہے تری یاد میں مولا\nتیرا کرم رہے تو ہر مشکل آسان ہے",
     "Rahat-e-qalb-o-jaan hai teri yaad mein maula\nTera karam rahe to har mushkil aasaan hai",
     "Solace of heart and soul is found in Thy remembrance, O Lord; when Thy grace shines, every trial transforms into ease.",
     "اے اللہ! تیری یاد میں دل اور روح کا سچا سکون ہے، تیرا فضل و کرم شاملِ حال ہو تو ہر کٹھن منزل آسان ہو جاتی ہے۔"),

    # AMJAD ISLAM AMJAD
    ("Amjad Islam Amjad", "امجد اسلام امجد", "Lahore, Pakistan", "1944 – 2023", "ur", "ishq", "Love & Romance",
     "محبت ایسی بارش ہے جسے چھونے کی خواہش میں\nکبھی پلکیں بھیگ جاتی ہیں کبھی دامن بھیگ جاتا ہے",
     "Mohabbat aisi baarish hai jise chhoone ki khwahish mein\nKabhi palkein bheeg jaati hain kabhi daaman bheeg jaata hai",
     "Love is that gentle rain in whose yearning embrace at times the eyelashes are drenched, and at times the hem of the robe.",
     "محبت وہ برسات ہے جس کی خواہش میں انسان کبھی آنکھوں سے رو پڑتا ہے اور کبھی اس کا دامن تر ہو جاتا ہے۔"),
    ("Amjad Islam Amjad", "امجد اسلام امجد", "Lahore, Pakistan", "1944 – 2023", "ur", "ishq", "Love & Romance",
     "یہ موسمِ گل بھی گزر جائے گا اک روز\nرہ جائے گی یادوں کی مہک دل کے نگر میں",
     "Yeh mausam-e-gul bhi guzar jaaye ga ik roz\nReh jaaye gi yaadon ki mehek dil ke nagar mein",
     "This season of blooming roses too shall pass one day; only the fragrant memory shall linger in the township of the heart.",
     "بہار کا یہ خوبصورت موسم بھی ایک دن بیت جائے گا، مگر دل کی بستی میں خوشگوار یادوں کی مہک سدا قائم رہے گی۔"),

    # AHMAD NADEEM QASMI
    ("Ahmad Nadeem Qasmi", "احمد ندیم قاسمی", "Sargodha / Lahore, Pakistan", "1916 – 2006", "ur", "dua", "Dua & Blessings",
     "خدا کرے کہ مری ارضِ پاک پر اترے\nوہ فصلِ گل جسے اندیشۂ زوال نہ ہو",
     "Khuda kare ke meri arz-e-paak par utre\nWo fasl-e-gul jise andeesha-e-zawaal na ho",
     "May God grant that upon my sacred homeland descends that glorious spring of blooming roses which knows no fear of decay.",
     "اللہ کرے کہ میری پاک سرزمین پر ایسی سدا بہار خوشحالی اترے جس کو کبھی زوال اور خزاں کا خطرہ نہ ہو۔"),
    ("Ahmad Nadeem Qasmi", "احمد ندیم قاسمی", "Sargodha / Lahore, Pakistan", "1916 – 2006", "ur", "falsafa", "Philosophy & Reflection",
     "کون کہتا ہے کہ موت آئی تو مر جاؤں گا\nمیں تو دریا ہوں سمندر میں اتر جاؤں گا",
     "Kaun kehta hai ke maut aayi to mar jaaun ga\nMain to darya hun samandar mein utar jaaun ga",
     "Who says that when death arrives I shall perish? I am a mighty river; I shall merely merge into the vast eternal ocean.",
     "کون کہتا ہے کہ موت مجھے ختم کر دے گی، میں تو ایک رواں دریا ہوں جو فنا ہو کر بھی وسیع سمندر میں مل جائے گا۔"),

    # ZEHRA NIGAH
    ("Zehra Nigah", "زہرا نگاہ", "Hyderabad, India / Karachi, Pakistan", "1937 – Present", "ur", "ishq", "Love & Romance",
     "سنو اک بات کہتی ہوں کہ دنیا بے مروت ہے\nوفا کے موتیوں کو خاک میں ملنے نہیں دینا",
     "Suno ik baat kehti hun ke dunya be-murawwat hai\nWafa ke motiyon ko khaak mein milne nahin dena",
     "Listen, I impart a truth to you: this worldly realm is ungrateful; never allow the precious pearls of your loyalty to be crushed into the dust.",
     "میری یہ بات یاد رکھنا کہ دنیا بڑی بے مروت ہے، اپنے خلوص اور وفا کے قیمتی موتیوں کو کبھی ضائع مت ہونے دینا۔"),

    # KISHWAR NAHEED
    ("Kishwar Naheed", "کشور ناہید", "Bulandshahr, India / Islamabad, Pakistan", "1940 – Present", "ur", "inqilab", "Revolution & Hope",
     "یہ ہم گنہگار عورتیں ہیں جو اہل جُبّہ کی تمکنت سے نہ رعب کھائیں\nنہ جان بیچیں، نہ سر جھکائیں",
     "Yeh hum gunahgaar auratein hain jo ahl-e-jubba ki tamkanat se na rob khaayein\nNa jaan beechein na sar jhukaayein",
     "It is we so-called sinful women who fear not the arrogant swagger of the sanctimonious; who sell not our souls nor bow our heads.",
     "ہم وہ باہمت عورتیں ہیں جو ظالموں کے رعب میں نہیں آتیں، نہ اپنی عزت کا سودا کرتی ہیں اور نہ سر جھکاتی ہیں۔"),

    # PUNJABI AUTHENTIC
    ("Baba Bulleh Shah", "بابا بلھے شاہ", "Kasur, Punjab", "1680 – 1757", "pa", "falsafa", "Philosophy & Reflection",
     "نہ کر خودی گمان نی کڑئے، خالی ہتھ سدھاریں گی\nاک دن مٹی دے وچ ملنا، ایتھے کی کجھ ہاریں گی",
     "Na kar khudi gumaan ni kurriye khaali hath sudhaarein gi\nIk din mitti de vich milna aithe ki kujh haarein gi",
     "Harbor no vain pride, dear soul; with empty hands you shall depart. One day you must return to earth—why lose humility here?",
     "اے انسان تکبر و غرور نہ کر، آخر کار خالی ہاتھ ہی رخصت ہونا ہے؛ ایک دن مٹی میں ملنا ہے تو یہاں نیکی اور عاجزی کیوں نہ کمائی جائے؟"),
    ("Baba Bulleh Shah", "بابا بلھے شاہ", "Kasur, Punjab", "1680 – 1757", "pa", "ishq", "Love & Romance",
     "جے توں اپنے یار نوں پاویں، سولی تے چڑھ کے ویکھ لے\nعشق نہ پچھے ذات صفاتاں، دل نال دل نوں جوڑ لے",
     "Je tu apne yaar nu paavein sooli te charh ke vekh le\nIshq na puchhe zaat sifaatan dil naal dil nu jorh le",
     "If you wish to attain your Beloved, look upon the path of sacrifice; true love cares nothing for lineage, it binds heart to heart.",
     "اگر تم اپنے محبوب کو پانا چاہتے ہو تو ایثار و قربانی کے راستے پر چلو؛ عشق ذات پات نہیں پوچھتا بلکہ دلوں کو دلوں سے جوڑتا ہے۔"),
    ("Baba Bulleh Shah", "بابا بلھے شاہ", "Kasur, Punjab", "1680 – 1757", "pa", "ishq", "Love & Romance",
     "اٹھ گئے گوانڈھوں یار ربّا ہن کی کریئے\nپھوک مصلّی بھن سٹ کاسہ، عشقے دا کوئی تیر چلا",
     "Uth gaye gawaandhon yaar rabba hun ki kariye\nPhook musalla bhann sit kaasa ishqe da koi teer chala",
     "The beloved neighbor has departed, O Lord, what shall I do now? Cast away rituals and kindle the arrow of authentic love!",
     "پڑوس سے محبوب بچھڑ گیا، اے خدا اب ہم کیا کریں؛ ظاہری رسومات چھوڑ کر عشق کی سچی آگ اپنے اندر جلاؤ۔"),
    ("Baba Bulleh Shah", "بابا بلھے شاہ", "Kasur, Punjab", "1680 – 1757", "pa", "falsafa", "Philosophy & Reflection",
     "الٹے سلٹے ہور کماں نوں، اپنا وقت گوائی دا\nاک الف پڑھو چھٹکارا ہے، دل نوں سچا لائی دا",
     "Ulte sulte hor kamaan nu apna waqt gawaayi da\nIk alif parho chhutkara hai dil nu sachha laayi da",
     "In trivial affairs we squander our precious time; learn the single truth of Alif for salvation, and dedicate a sincere heart.",
     "فضول اور بے معنی کاموں میں وقت ضائع نہ کرو، اللہ کے ایک نام کی سچی لگن اپناؤ اسی میں دونوں جہانوں کی نجات ہے۔"),
    ("Sultan Bahu", "سلطان باہو", "Shorekot, Jhang, Punjab", "1628 – 1691", "pa", "falsafa", "Philosophy & Reflection",
     "نئیں جے رب ملدا نہاتے دھوتیاں، ملدا ڈڈواں مچھیاں ھو\nجے رب ملدا جنگل بیلے، ملدا گائیں وچھیاں ھو\nرب ملدا اے دل سچے نال، نیت پاک سچائی ھو",
     "Nai je Rabb milda naate dhotiyan milda dadwaan machhiyan hoo\nJe Rabb milda jangal bele milda gaayein vichhiyan hoo\nRabb milda ae dil sachhe naal niyat paak sachaayi hoo",
     "If God were found merely through ritual baths, frogs and fish would find Him; if in lonely jungles, the grazing calves would find Him! God is attained through an honest heart and pure intention.",
     "اگر رب صرف نہانے دھونے سے ملتا تو مینڈک اور مچھلیاں پا لیتیں، اور اگر جنگلوں میں ملتا تو گائیں بچھڑے پا لیتے؛ رب تو سچے دل اور پاک نیت سے ملتا ہے۔"),
    ("Sultan Bahu", "سلطان باہو", "Shorekot, Jhang, Punjab", "1628 – 1691", "pa", "dua", "Dua & Blessings",
     "جیوندی ماں نوں خبر نہ کوئی، موئیاں نوں کی روندی ھو\nسچا مرشد مل پیا باہو، ہر دکھ دور کریندی ھو",
     "Jeewandi maa nu khabar na koi moyan nu ki rondi hoo\nSachha murshid mil peya Bahu har dukh door kareendi hoo",
     "Honor and cherish your living mother while she is with you; when a true spiritual guide is found, O Bahu, all inner sorrow departs.",
     "زندہ ماں کی قدر کرو اس کی خدمت ہی اصل سعادت ہے، اور کامل مرشد کے فیض سے دل کے سارے دکھ مٹ جاتے ہیں۔"),
    ("Waris Shah", "سید وارث شاہ", "Jandiala Sher Khan, Punjab", "1722 – 1798", "pa", "ishq", "Love & Romance",
     "وارث شاہ لُکائیے کِنج اس نوں، جیہڑا عشق چھپایا نئیں لُکدا\nچن چڑھیا کدی نہ لُکے بدلیں، دریا دا وگنا نئیں مُکدا",
     "Waris Shah lukaaiye kinj us nu jehra ishq chhupaya nai lukda\nChan charhiya kadi na luke badlein darya da vagna nai mukda",
     "O Waris Shah, how could one conceal love that can never be hidden? The risen moon cannot hide in clouds, nor can a river cease flowing.",
     "اے وارث شاہ! عشق کو کیسے چھپایا جائے جو چھپائے نہیں چھپتا؛ چاند بادلوں میں نہیں چھپ سکتا اور دریا کبھی بہنے سے نہیں رکتا۔"),
    ("Waris Shah", "سید وارث شاہ", "Jandiala Sher Khan, Punjab", "1722 – 1798", "pa", "ishq", "Love & Romance",
     "ڈاڈھی ڈاہڈی ایہ پریت انوکھڑی اے، وارث شاہ نوں لگ گئی تیر وانگوں\nجس تن لگدی اوہی جانے، ہور دسے کی تدبیر وانگوں",
     "Dadhi dadhi eh preet anokhri ae Waris Shah nu lag gayi teer waangon\nJis tan lagdi ohi jaane hor dase ki tadbeer waangon",
     "Mighty and wondrous is this love, it struck Waris Shah like an inescapable arrow; only the body that endures the wound knows its truth.",
     "محبت کا تیر وارث شاہ کے دل پر کاری لگا ہے، اور یہ درد وہی جانتا ہے جس کے دل پر یہ زخم لگا ہو۔"),
    ("Mian Muhammad Bakhsh", "میاں محمد بخش", "Mirpur, Kashmir / Punjab", "1830 – 1907", "pa", "falsafa", "Philosophy & Reflection",
     "خاصاں دی گل عاماں اگے، نئیں مناسب کرنی\nمٹھی کھیر پکا محمدؔ، کُتیاں اگے دھرنی",
     "Khaasan di gal aamaan agge nai munasib karni\nMithi kheer paka Muhammad kuttiyan agge dharni",
     "Sharing wisdom of the enlightened with the unheeding is unwise; like preparing sweet pudding and placing it before dogs.",
     "معرفت اور حکمت کی گہری باتیں بے قدرے لوگوں کے سامنے کرنا ایسا ہی ہے جیسے میٹھی کھیر پکا کر قدر نہ جاننے والوں کے سامنے رکھ دی جائے۔"),
    ("Mian Muhammad Bakhsh", "میاں محمد بخش", "Mirpur, Kashmir / Punjab", "1830 – 1907", "pa", "dosti", "Friendship & Loyalty",
     "جیڑھے لوک نہ قدر پچھانن، اوہناں کول نہ بہیئے\nاوکھے ویلے نال کھلووے، اوہی سجن کہیئے",
     "Jehrhe lok na qadar pachhanan ohna kol na bahiye\nOokhe wele naal khalowey ohi sajan kahiye",
     "Do not keep company with those who fail to recognize true worth; only he who stands steadfast in trial is a true friend.",
     "جو لوگ قدر نہیں پہچانتے ان کی صحبت میں نہ بیٹھو؛ سچا دوست وہی ہے جو مشکل وقت میں تمہارے ساتھ مضبوطی سے کھڑا رہے۔"),
    ("Amrita Pritam", "امرتا پریتم", "Gujranwala / Delhi", "1919 – 2005", "pa", "dard", "Sorrow & Longing",
     "اج آکھاں وارث شاہ نوں، کِتھوں قبراں وچوں بول\nتے اج کتابِ عشق دا، کوئی اگلا ورقہ پھول",
     "Ajj aakhaan Waris Shah nu kitthon qabraan vichon bol\nTe ajj kitaab-e-ishq da koi agla varqa phol",
     "Today I call upon Waris Shah: speak out from your grave! Turn to the next tragic page in the grand book of love!",
     "آج میں وارث شاہ کو پکارتی ہوں کہ قبر سے بول اٹھو، اور آج محبت اور انسانیت کی کتاب کا اگلا درد بھرا صفحہ کھولو۔"),
    ("Shah Hussain", "شاہ حسین", "Lahore, Punjab", "1538 – 1599", "pa", "dard", "Sorrow & Longing",
     "مائے نی میں کینوں آکھاں درد وچھوڑے دا حال نی\nدکھاں دی روٹی سولاں دا سالن، ہڈاں دا بالن بال نی",
     "Maaye ni main kainu aakhaan dard vichhoray da haal ni\nDukhaan di roti soolaan da saalan haddaan da baalan baal ni",
     "O mother, to whom shall I tell the agony of my separation? Bread of sorrow, curry of thorns, and the fire lit with bones.",
     "اے ماں! میں اپنے دل کا دکھ اور ہجر کا درد کسے سناؤں، میرے دکھوں کی روٹی ہے اور کانٹوں کا سالن ہے۔"),
    ("Khwaja Ghulam Farid", "خواجہ غلام فرید", "Chacharan Sharif, Punjab", "1845 – 1901", "pa", "ishq", "Love & Romance",
     "روہی دی ریت تے روواں رانجھن یار پئی ڈھونڈاں\nسہج سہاگ سہاوا تھیوے، پریم نگر دی پیت نبھاواں",
     "Rohi di reit te rowaan Ranjhan yaar payi dhoondaan\nSehj suhaag suhawa theevay prem nagar di peet nibhaawaan",
     "Upon the sands of the Rohi desert I weep, searching for my beloved Ranjhan; let divine love grace my existence.",
     "چولستان کے صحراؤں میں رانجھن کی تلاش میں روتی پھرتی ہوں، کاش محبت کا یہ سفر منزل تک پہنچ جائے۔"),
    ("Shiv Kumar Batalvi", "شِو کمار بٹالوی", "Bara Pind / Batala, Punjab", "1936 – 1973", "pa", "dard", "Sorrow & Longing",
     "اساں تاں جوبن رُتے مرنا، مُڑ نئیں جوبن رُتے مِلنا\nتُر جانا اساں چپ چپیتے، پچھوں کجھ نہ کسے نے کَہنا",
     "Asaan taan joban rutte marna murr nai joban rutte milna\nTur jaana asaan chup chapeete pichhon kujh na kise ne kehna",
     "We are destined to depart in the radiant prime of youth; quietly we shall slip away, and none shall utter a word behind us.",
     "ہم نے جوانی کی رُت ہی میں اس دنیا سے کوچ کر جانا ہے، خاموشی سے رخصت ہو جائیں گے اور پیچھے کوئی نام لینے والا نہ ہوگا۔"),

    # ARABIC MASTERPIECES
    ("Al-Mutanabbi", "المتنبی", "Kufa, Iraq", "915 – 965", "ar", "inqilab", "Revolution & Hope",
     "الخَيْلُ وَاللّيْلُ وَالبَيْداءُ تَعرِفُني\nوَالسّيفُ وَالرّمحُ والقرْطاسُ وَالقَلَمُ",
     "Al-khaylu wal-laylu wal-bayda'u ta'rifuni\nWas-sayfu war-rumhu wal-qirtasu wal-qalamu",
     "The steeds, the dark night, and the desert know me well; as do the sword, the spear, the parchment, and the pen.",
     "گھوڑے، تاریک رات اور صحرا مجھے خوب پہچانتے ہیں؛ اور تلوار، نیزہ، کاغذ اور قلم بھی میری فصاحت و شجاعت کے گواہ ہیں۔"),
    ("Al-Mutanabbi", "المتنبی", "Kufa, Iraq", "915 – 965", "ar", "falsafa", "Philosophy & Reflection",
     "عَلى قَدْرِ أهْلِ العَزْم تأتي العَزائِمُ\nوَتأتِي علَى قَدْرِ الكِرامِ المَكارمُ",
     "Ala qadri ahlil-azmi ta'ti al-aza'imu\nWa ta'ti ala qadril-kirami al-makarimu",
     "Noble endeavors are realized according to the resolve of great souls; generous deeds correspond to the magnanimity of the honorable.",
     "عظیم کارنامے بلند حوصلہ اور باہمت انسانوں کے عزم کے مطابق انجام پاتے ہیں، اور عزت والے لوگ ہی عظیم مقاصد حاصل کرتے ہیں۔"),

    # PERSIAN MASTERPIECES
    ("Saadi Shirazi", "سعدی شیرازی", "Shiraz, Iran", "1210 – 1291", "fa", "falsafa", "Philosophy & Reflection",
     "بنی‌آدم اعضای یکدیگرند\nکه در آفرینش ز یک گوہرند",
     "Bani adam a'zaye yak-digarand\nKi dar aafarinesh zi yak gauharand",
     "Human beings are members of one body, for in creation they are born of one essence.",
     "تمام انسان ایک دوسرے کے اعضا کی مانند ہیں کیونکہ ان کی تخلیق ایک ہی جوہر سے ہوئی ہے۔"),
    ("Saadi Shirazi", "سعدی شیرازی", "Shiraz, Iran", "1210 – 1291", "fa", "dosti", "Friendship & Loyalty",
     "درخت دوستی بنشان که کام دل به بار آرد\nنهال دشمنی برکن که رنج بی‌شمار آرد",
     "Darakht-e-dosti benshaan ki kaam-e-dil ba baar aarad\nNehaal-e-dushmani barkan ki ranj-e-beshumaar aarad",
     "Plant the tree of friendship so that heart's desires may blossom into fruit; uproot enmity, for it brings boundless grief.",
     "دوستی کا درخت لگاؤ تاکہ دل کی مراد کا میٹھا پھل ملے، اور دشمنی کے پودے کو جڑ سے اکھاڑ پھینکو جو بے انتہا دکھ دیتا ہے۔"),
    ("Jalaluddin Rumi", "مولانا جلال الدین رومی", "Balkh / Konya", "1207 – 1273", "fa", "ishq", "Love & Romance",
     "بشنو از نی چون حکایت می‌کند\nاز جدایی‌ها شکایت می‌کند",
     "Beshno az nay chon hekayat mikonad\nAz jodaa'i-ha shekayat mikonad",
     "Listen to the reed flute as it tells its tale, lamenting the bitter pain of separation from its source.",
     "بانسری کی آواز سنو جب وہ اپنی بپتا سناتی ہے اور اصل وطن سے بچھڑنے کا نوحہ بیان کرتی ہے۔"),
    ("Hafez Shirazi", "حافظ شیرازی", "Shiraz, Iran", "1315 – 1390", "fa", "ishq", "Love & Romance",
     "اگر آن ترک شیرازی به دست آرد دل ما را\nبه خال هندویش بخشم سمرقند و بخارا را",
     "Agar aan turk-e-shirazi ba-dast aarad dil-e-ma ra\nBa khaal-e-hinduyash bakhsham Samarqand-o-Bukhara ra",
     "If that Shirazi beauty accepts my heart, for the dark mole on her cheek I would bestow Samarqand and Bukhara.",
     "اگر وہ شیراز کی حسینہ میرے دل کی قدر کرے تو اس کے چہرے کے تل کے بدلے میں سمرقند اور بخارا جیسے عظیم شہر قربان کر دوں۔"),
    ("Amir Khusro", "امیر خسرو", "Patiyali / Delhi, India", "1253 – 1325", "fa", "ishq", "Love & Romance",
     "نمی دانم چہ منزل بود شب جائے کہ من بودم\nبہ ہر سو رقصِ بسمل بود شب جائے کہ من بودم",
     "Nami daanam che manzil bood shab jaaye ke man boodam\nBa har soo raqs-e-bismil bood shab jaaye ke man boodam",
     "I know not what sublime station it was where I stayed last night; on every side danced the ecstatic victims of divine love.",
     "میں نہیں جانتا کہ گزشتہ رات میں کس روحانی مقام پر تھا، جہاں ہر طرف دیدارِ الٰہی کے پیاسے والہانہ رقص میں محو تھے۔")
]
