# scripts/generate_master_replacements.py
# Curated authentic unique poetry replacements for Urdu, Punjabi, Persian, and Arabic

REPLACEMENTS_DATA = [
    # --- MIRZA GHALIB ---
    {
        "poet": "Mirza Ghalib",
        "poetUrdu": "مرزا اسد اللہ خاں غالب",
        "poetOrigin": "Agra / Delhi, India",
        "poetEra": "1797 – 1869",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "قاصد کے آتے آتے خط اک اور لکھ رکھوں\nمیں جانتا ہوں جو وہ لکھیں گے جواب میں",
        "romanText": "Qasid ke aate aate khat ik aur likh rakhun\nMain jaanta hun jo wo likhenge jawab mein",
        "englishTranslation": "Before the courier even returns, let me write another letter; I already know what they will write in response.",
        "urduTranslation": "قاصد کے آنے سے پہلے ہی میں ایک اور خط لکھ لوں، کیونکہ مجھے معلوم ہے کہ وہ جواب میں کیا فرمائیں گے۔",
        "meaning": "A masterstroke of romantic wit and impatient anticipation by Mirza Ghalib."
    },
    {
        "poet": "Mirza Ghalib",
        "poetUrdu": "مرزا اسد اللہ خاں غالب",
        "poetOrigin": "Agra / Delhi, India",
        "poetEra": "1797 – 1869",
        "originalLanguage": "ur",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "بازیچۂ اطفال ہے دنیا مرے آگے\nہوتا ہے شب و روز تماشا مرے آگے",
        "romanText": "Bazicha-e-atfal hai dunya mere aage\nHota hai shab-o-roz tamasha mere aage",
        "englishTranslation": "The world is merely a child's plaything before my eyes; night and day, a fleeting spectacle unfolds before me.",
        "urduTranslation": "یہ دنیا میرے لیے بچوں کے کھیل سے زیادہ کچھ نہیں، جہاں شب و روز ایک تماشا برپا رہتا ہے۔",
        "meaning": "Ghalib's philosophical detachment from worldly illusions and vanity."
    },
    {
        "poet": "Mirza Ghalib",
        "poetUrdu": "مرزا اسد اللہ خاں غالب",
        "poetOrigin": "Agra / Delhi, India",
        "poetEra": "1797 – 1869",
        "originalLanguage": "ur",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "ہوئی مدت کہ غالبؔ مر گیا پر یاد آتا ہے\nوہ ہر اک بات پر کہنا کہ یوں ہوتا تو کیا ہوتا",
        "romanText": "Hui muddat ke Ghalib mar gaya par yaad aata hai\nWo har ik baat par kehna ke yun hota to kya hota",
        "englishTranslation": "It has been an age since Ghalib passed away, yet still remembered is his eternal wonder: 'What if it had been thus?'",
        "urduTranslation": "غالب کو بچھڑے اک زمانہ گزرا مگر یاد آتا ہے کہ وہ ہر بات پر سوچا کرتا تھا کہ اگر یوں ہوتا تو کیا ہوتا۔",
        "meaning": "One of the most famous introspective closing couplets in Urdu literature."
    },
    {
        "poet": "Mirza Ghalib",
        "poetUrdu": "مرزا اسد اللہ خاں غالب",
        "poetOrigin": "Agra / Delhi, India",
        "poetEra": "1797 – 1869",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "یہ نہ تھی ہماری قسمت کہ وصالِ یار ہوتا\nاگر اور جیتے رہتے یہی انتظار ہوتا",
        "romanText": "Yeh na thi hamari qismat ke wisal-e-yaar hota\nAgar aur jeete rehte yahi intezar hota",
        "englishTranslation": "It was not in our destiny that union with the beloved would be granted; had we lived on forever, this yearning alone would remain.",
        "urduTranslation": "ہماری قسمت میں محبوب کا وصال نہ تھا، اگر عمر دراز بھی ملتی تو بس یہی انتظار مقدر رہتا۔",
        "meaning": "Classic lamentation on unrequited longing and fate."
    },
    {
        "poet": "Mirza Ghalib",
        "poetUrdu": "مرزا اسد اللہ خاں غالب",
        "poetOrigin": "Agra / Delhi, India",
        "poetEra": "1797 – 1869",
        "originalLanguage": "ur",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "رگوں میں دوڑتے پھرنے کے ہم نہیں قائل\nجب آنکھ ہی سے نہ ٹپکا تو پھر لہو کیا ہے",
        "romanText": "Ragon mein daurte phirne ke hum nahin qayil\nJab aankh hi se na tapka to phir lahu kya hai",
        "englishTranslation": "We are not impressed by blood simply coursing through the veins; if it does not well up in the eyes as tears of passion, what use is blood?",
        "urduTranslation": "صرف رگوں میں دوڑتے خون کا کوئی فائدہ نہیں، جب تک وہ احساس اور درد بن کر آنکھوں سے نہ ٹپکے۔",
        "meaning": "True passion requires emotional manifestation through heartfelt expression."
    },
    {
        "poet": "Mirza Ghalib",
        "poetUrdu": "مرزا اسد اللہ خاں غالب",
        "poetOrigin": "Agra / Delhi, India",
        "poetEra": "1797 – 1869",
        "originalLanguage": "ur",
        "category": "dard",
        "categoryLabel": "Sorrow & Longing",
        "originalText": "غم اگرچہ جاں گسل ہے پہ کہاں بچیں کہ دل ہے\nغمِ عشق گر نہ ہوتا غمِ روزگار ہوتا",
        "romanText": "Gham agarcha jaan-gusil hai pa kahan bachein ke dil hai\nGham-e-ishq gar na hota gham-e-rozgar hota",
        "englishTranslation": "Though grief is soul-shattering, how could the heart escape it? If not the sorrow of love, the struggle for livelihood would take its place.",
        "urduTranslation": "غم جان لیوا سہی لیکن دل اس سے بچ نہیں سکتا، محبت کا غم نہ ہوتا تو روزگار اور زمانے کا غم ہوتا۔",
        "meaning": "The inevitability of existential pain in human existence."
    },
    {
        "poet": "Mirza Ghalib",
        "poetUrdu": "مرزا اسد اللہ خاں غالب",
        "poetOrigin": "Agra / Delhi, India",
        "poetEra": "1797 – 1869",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "محبت میں نہیں ہے فرق جینے اور مرنے کا\nاسی کو دیکھ کر جیتے ہیں جس کافر پہ دم نکلے",
        "romanText": "Mohabbat mein nahin hai farq jeene aur marne ka\nUsi ko dekh kar jeete hain jis kafir pe dam nikle",
        "englishTranslation": "In love there is no division between living and dying; we draw our breath only by gazing upon that beloved for whom our life departs.",
        "urduTranslation": "عشق میں جینے اور مرنے کا فرق مٹ جاتا ہے، ہم اسی کو دیکھ کر جیتے ہیں جس پر دل و جان نچھاور ہے۔",
        "meaning": "The transcendent paradox of spiritual and romantic devotion."
    },

    # --- ALLAMA IQBAL ---
    {
        "poet": "Allama Iqbal",
        "poetUrdu": "علامہ محمد اقبال",
        "poetOrigin": "Sialkot / Lahore, Pakistan",
        "poetEra": "1877 – 1938",
        "originalLanguage": "ur",
        "category": "inqilab",
        "categoryLabel": "Revolution & Hope",
        "originalText": "نہیں ہے نا امید اقبالؔ اپنی کشتِ ویراں سے\nذرا نم ہو تو یہ مٹی بڑی زرخیز ہے ساقی",
        "romanText": "Nahin hai na-umeed Iqbal apni kisht-e-veeraan se\nZara nam ho to yeh mitti bari zarkhez hai saqi",
        "englishTranslation": "Iqbal is never hopeless regarding his barren field; with just a touch of moisture, this fertile soil can bloom beyond measure.",
        "urduTranslation": "اقبال اپنی قوم اور دھرتی سے مایوس نہیں، ذرا سی محنت اور بیداری سے یہ مٹی بے پناہ زرخیز ثابت ہوگی۔",
        "meaning": "An immortal anthem of resilience, renewal, and unshakable hope."
    },
    {
        "poet": "Allama Iqbal",
        "poetUrdu": "علامہ محمد اقبال",
        "poetOrigin": "Sialkot / Lahore, Pakistan",
        "poetEra": "1877 – 1938",
        "originalLanguage": "ur",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "عمل سے زندگی بنتی ہے جنت بھی جہنم بھی\nیہ خاکی اپنی فطرت میں نہ نوری ہے نہ ناری ہے",
        "romanText": "Amal se zindagi banti hai jannat bhi jahannam bhi\nYeh khaaki apni fitrat mein na noori hai na naari hai",
        "englishTranslation": "Through righteous deeds life shapes its heaven and its hell; in essence, this earthly being is neither creature of light nor flame.",
        "urduTranslation": "انسان کے اعمال ہی اس کی زندگی کو جنت یا جہنم بناتے ہیں، انسان اپنی سرشت میں محض مٹی ہے جو عمل سے پہچانی جاتی ہے۔",
        "meaning": "The supremacy of personal responsibility and decisive action."
    },
    {
        "poet": "Allama Iqbal",
        "poetUrdu": "علامہ محمد اقبال",
        "poetOrigin": "Sialkot / Lahore, Pakistan",
        "poetEra": "1877 – 1938",
        "originalLanguage": "ur",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے\nخدا بندے سے خود پوچھے بتا تیری رضا کیا ہے",
        "romanText": "Khudi ko kar buland itna ke har taqdeer se pehle\nKhuda bande se khud poochhe bata teri raza kya hai",
        "englishTranslation": "Elevate your selfhood to such sublime heights that before decreeing your destiny, God Himself inquires: Tell Me, what is your desire?",
        "urduTranslation": "اپنی خودی کو اس بلندی پر لے جاؤ کہ تقدیر رقم کرنے سے قبل اللہ تعالیٰ تم سے خود پوچھے کہ تیری مرضی کیا ہے۔",
        "meaning": "The ultimate declaration of spiritual empowerment and self-realization."
    },
    {
        "poet": "Allama Iqbal",
        "poetUrdu": "علامہ محمد اقبال",
        "poetOrigin": "Sialkot / Lahore, Pakistan",
        "poetEra": "1877 – 1938",
        "originalLanguage": "ur",
        "category": "inqilab",
        "categoryLabel": "Revolution & Hope",
        "originalText": "تو شاہیں ہے پرواز ہے کام تیرا\nترے سامنے آسماں اور بھی ہیں",
        "romanText": "Tu shaheen hai parwaaz hai kaam tera\nTere saamne aasmaan aur bhi hain",
        "englishTranslation": "You are a royal falcon whose sacred mission is to soar; vast boundless heavens still await your flight.",
        "urduTranslation": "تم شاہین ہو اور بلندیوں پر اڑنا تمہارا مقدر ہے، تمہارے سفر کے لیے لامتناہی آسمان کھلے ہیں۔",
        "meaning": "Iqbal's signature metaphor challenging youth to strive beyond perceived limits."
    },
    {
        "poet": "Allama Iqbal",
        "poetUrdu": "علامہ محمد اقبال",
        "poetOrigin": "Sialkot / Lahore, Pakistan",
        "poetEra": "1877 – 1938",
        "originalLanguage": "ur",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "گرتے ہیں شہسوار ہی میدانِ جنگ میں\nوہ طفل کیا گرے جو گھٹنوں کے بل چلے",
        "romanText": "Girte hain sheh-sawaar hi maidan-e-jang mein\nWo tifl kya gire jo ghutnon ke bal chale",
        "englishTranslation": "Only mighty knights fall upon the field of valor; how could that timid infant fall who only crawls upon knees?",
        "urduTranslation": "میدانِ کارزار میں صرف بہادر گھڑسوار گرتے ہیں، وہ کیا گرے گا جو ہمیشہ زمین پر گھٹنوں کے بل چلتا رہا ہو۔",
        "meaning": "Failure is the noble privilege of those who daringly strive for greatness."
    },
    {
        "poet": "Allama Iqbal",
        "poetUrdu": "علامہ محمد اقبال",
        "poetOrigin": "Sialkot / Lahore, Pakistan",
        "poetEra": "1877 – 1938",
        "originalLanguage": "ur",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "نگاہِ مردِ مومن سے بدل جاتی ہیں تقدیریں\nجو ہو ذوقِ یقیں پیدا تو کٹ جاتی ہیں زنجیریں",
        "romanText": "Nigah-e-mard-e-momin se badal jaati hain taqdeerein\nJo ho zauq-e-yaqeen paida to kat jaati hain zanjeerein",
        "englishTranslation": "By the visionary gaze of a devoted soul destines are transformed; when unshakable conviction awakens, all chains shatter.",
        "urduTranslation": "مردِ حق کی نگاہ سے زمانے کے فیصلے بدل جاتے ہیں، پختہ یقین پیدا ہو جائے تو غلامی کی زنجیریں ٹوٹ جاتی ہیں۔",
        "meaning": "The power of spiritual vision and relentless faith."
    },

    # --- FAIZ AHMAD FAIZ ---
    {
        "poet": "Faiz Ahmad Faiz",
        "poetUrdu": "فیض احمد فیض",
        "poetOrigin": "Sialkot / Lahore, Pakistan",
        "poetEra": "1911 – 1984",
        "originalLanguage": "ur",
        "category": "inqilab",
        "categoryLabel": "Revolution & Hope",
        "originalText": "بول کہ لب آزاد ہیں تیرے\nبول زباں اب تک تیری ہے",
        "romanText": "Bol ke lab azaad hain tere\nBol zabaan ab tak teri hai",
        "englishTranslation": "Speak out, for your lips are yet free; speak out, for your tongue still belongs to you!",
        "urduTranslation": "آواز بلند کر کیونکہ تیرے ہونٹ ابھی آزاد ہیں اور سچ کہنا تیرا حق ہے!",
        "meaning": "Faiz's stirring anthem against oppression and censorship."
    },
    {
        "poet": "Faiz Ahmad Faiz",
        "poetUrdu": "فیض احمد فیض",
        "poetOrigin": "Sialkot / Lahore, Pakistan",
        "poetEra": "1911 – 1984",
        "originalLanguage": "ur",
        "category": "inqilab",
        "categoryLabel": "Revolution & Hope",
        "originalText": "ہم پرورشِ لوح و قلم کرتے رہیں گے\nجو دل پہ گزرتی ہے رقم کرتے رہیں گے",
        "romanText": "Hum parvarish-e-lauh-o-qalam karte rahenge\nJo dil pe guzarti hai raqam karte rahenge",
        "englishTranslation": "We shall nurture the sacred slate and quill; whatever the heart endures, we shall chronicle without fear.",
        "urduTranslation": "ہم قلم اور کاغذ کا حق ادا کرتے رہیں گے، اور دل پر جو بھی بیتے گی اسے سچائی کے ساتھ لکھتے رہیں گے۔",
        "meaning": "The writer's sacred commitment to truth and artistic integrity."
    },
    {
        "poet": "Faiz Ahmad Faiz",
        "poetUrdu": "فیض احمد فیض",
        "poetOrigin": "Sialkot / Lahore, Pakistan",
        "poetEra": "1911 – 1984",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "گلوں میں رنگ بھرے بادِ نوبہار چلے\nچلے بھی آؤ کہ گلشن کا کاروبار چلے",
        "romanText": "Gulon mein rang bhare baad-e-naubahar chale\nChale bhi aao ke gulshan ka karobar chale",
        "englishTranslation": "Let colors fill the blossoms as the spring breeze stirs; come forth, my love, so the garden may awaken to its splendor.",
        "urduTranslation": "بہار کی ہوا چلی ہے اور پھولوں میں رنگ بھر رہے ہیں، تم بھی آ جاؤ تاکہ اس گلشن کا رونق بھرا کاروبار شروع ہو سکے۔",
        "meaning": "Lyrical masterpiece blending personal affection with hopeful social renewal."
    },
    {
        "poet": "Faiz Ahmad Faiz",
        "poetUrdu": "فیض احمد فیض",
        "poetOrigin": "Sialkot / Lahore, Pakistan",
        "poetEra": "1911 – 1984",
        "originalLanguage": "ur",
        "category": "dard",
        "categoryLabel": "Sorrow & Longing",
        "originalText": "مقام فیضؔ کوئی راہ میں جچا ہی نہیں\nجو کوئے یار سے نکلے تو سوئے دار چلے",
        "romanText": "Maqam Faiz koi raah mein jacha hi nahin\nJo koo-e-yaar se nikle to soo-e-daar chale",
        "englishTranslation": "No resting place pleased Faiz along the journey; once we departed the beloved's street, we walked straight toward the gallows.",
        "urduTranslation": "ہمیں راستے میں کوئی منزل راس نہ آئی، محبوب کی گلی سے رخصت ہوئے تو سیدھے دار و رسن کی راہ لی۔",
        "meaning": "Uncompromising devotion to love and political truth."
    },

    # --- MIR TAQI MIR ---
    {
        "poet": "Mir Taqi Mir",
        "poetUrdu": "میر تقی میر",
        "poetOrigin": "Agra / Delhi / Lucknow, India",
        "poetEra": "1723 – 1810",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "پتا پتا بوٹا بوٹا حال ہمارا جانے ہے\nجانے نہ جانے گل ہی نہ جانے باغ تو سارا جانے ہے",
        "romanText": "Patta patta boota boota haal hamara jaane hai\nJaane na jaane gul hi na jaane baagh to saara jaane hai",
        "englishTranslation": "Every leaf and every twig knows our state of love; whether the elusive rose acknowledges it or not, the entire garden knows.",
        "urduTranslation": "چمن کا ہر پتا اور بوٹا ہمارے دل کی حالت جانتا ہے، اگر محبوب گل بے خبر بھی رہے تو سارا باغ واقف ہے۔",
        "meaning": "Classic expression of all-consuming love recognized by the entire world."
    },
    {
        "poet": "Mir Taqi Mir",
        "poetUrdu": "میر تقی میر",
        "poetOrigin": "Agra / Delhi / Lucknow, India",
        "poetEra": "1723 – 1810",
        "originalLanguage": "ur",
        "category": "dard",
        "categoryLabel": "Sorrow & Longing",
        "originalText": "نازکی اس کے لب کی کیا کہیے\nپنکھڑی اک گلاب کی سی ہے",
        "romanText": "Naazuki us ke lab ki kya kahiye\nPankhuri ik gulaab ki si hai",
        "englishTranslation": "How can one praise the delicate softness of her lips? They are like the velvet petal of a fragrant rose.",
        "urduTranslation": "محبوب کے لبوں کی نزاکت کا کیا بیان ہو، وہ تو گلاب کی تازہ پنکھڑی جیسے نازک ہیں۔",
        "meaning": "Mir's unmatched tenderness and exquisite imagery."
    },
    {
        "poet": "Mir Taqi Mir",
        "poetUrdu": "میر تقی میر",
        "poetOrigin": "Agra / Delhi / Lucknow, India",
        "poetEra": "1723 – 1810",
        "originalLanguage": "ur",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "ہستی اپنی حباب کی سی ہے\nیہ نمائش سراب کی سی ہے",
        "romanText": "Hasti apni hubaab ki si hai\nYeh numaish saraab ki si hai",
        "englishTranslation": "Our existence is fleeting like a fragile water bubble; this worldly display is merely like a desert mirage.",
        "urduTranslation": "انسان کی زندگی پانی کے بلبلے کی طرح ناپائیدار ہے اور یہ ساری دنیا سراب کی مانند ایک دھوکا ہے۔",
        "meaning": "Poignant contemplation on the ephemeral nature of life."
    },

    # --- AHMAD FARAZ ---
    {
        "poet": "Ahmad Faraz",
        "poetUrdu": "احمد فراز",
        "poetOrigin": "Kohat / Islamabad, Pakistan",
        "poetEra": "1931 – 2008",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "سلسلے توڑ گیا وہ سبھی جاتے جاتے\nورنہ اتنے تو مراسم تھے کہ آتے جاتے",
        "romanText": "Silsile tor gaya wo sabhi jaate jaate\nWarna itne to maraasim the ke aate jaate",
        "englishTranslation": "Departing, they severed every tender tie; otherwise, surely there remained enough closeness for passing visits.",
        "urduTranslation": "جاتے جاتے وہ تمام تعلقات ختم کر گیا، حالانکہ اتنی جان پہچان تو تھی کہ کبھی کبھار ملاقات ہو سکتی۔",
        "meaning": "The pain of abrupt detachment after profound intimacy."
    },
    {
        "poet": "Ahmad Faraz",
        "poetUrdu": "احمد فراز",
        "poetOrigin": "Kohat / Islamabad, Pakistan",
        "poetEra": "1931 – 2008",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "اس سے پہلے کہ بے وفا ہو جائیں\nکیوں نہ اے دوست ہم جدا ہو جائیں",
        "romanText": "Is se pehle ke be-wafa ho jayein\nKyun na ae dost hum juda ho jayein",
        "englishTranslation": "Before we turn unfaithful to our promises, why do we not, dear companion, part with grace?",
        "urduTranslation": "اس سے پہلے کہ محبت میں بے وفائی در آئے، کیوں نہ ہم باوقار طریقے سے الگ ہو جائیں۔",
        "meaning": "Preserving the sanctity of love before bitterness destroys it."
    },
    {
        "poet": "Ahmad Faraz",
        "poetUrdu": "احمد فراز",
        "poetOrigin": "Kohat / Islamabad, Pakistan",
        "poetEra": "1931 – 2008",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "شکوۂ ظلمتِ شب سے تو کہیں بہتر تھا\nاپنے حصے کی کوئی شمع جلاتے جاتے",
        "romanText": "Shikwa-e-zulmat-e-shab se to kahin behtar tha\nApne hisse ki koi shama jalaate jaate",
        "englishTranslation": "Far better than lamenting the darkness of the night would have been to light the candle of your own share.",
        "urduTranslation": "رات کے اندھیرے کا شکوہ کرنے کے بجائے کتنا اچھا ہوتا کہ ہم اپنی بساط کے مطابق کوئی چراغ روشن کر جاتے۔",
        "meaning": "A call for proactive goodness rather than passive complaint."
    },

    # --- JAUN ELIA ---
    {
        "poet": "Jaun Elia",
        "poetUrdu": "جون ایلیا",
        "poetOrigin": "Amroha, India / Karachi, Pakistan",
        "poetEra": "1931 – 2002",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "بے دلی کیا یوں ہی دن گزر جائیں گے\nصرف زندہ رہے ہم تو مر جائیں گے",
        "romanText": "Be-dili kya yunhi din guzar jayeinge\nSirf zinda rahe hum to mar jayeinge",
        "englishTranslation": "Heartless apathy! Will our days pass in such vanity? If we merely exist without soul, we shall surely perish.",
        "urduTranslation": "کیا بے دلی سے ہی سارے دن بیت جائیں گے؟ اگر صرف سانسیں لیتے رہے تو ہم زندہ درگور ہو جائیں گے۔",
        "meaning": "Jaun Elia's raw existential agony regarding empty living."
    },
    {
        "poet": "Jaun Elia",
        "poetUrdu": "جون ایلیا",
        "poetOrigin": "Amroha, India / Karachi, Pakistan",
        "poetEra": "1931 – 2002",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "شاید مجھے کسی سے محبت نہیں ہوئی\nلیکن یقین سب کو دلاتا رہا ہوں میں",
        "romanText": "Shayad mujhe kisi se mohabbat nahin hui\nLekin yaqeen sab ko dilata raha hun main",
        "englishTranslation": "Perhaps I have truly never loved anyone; yet I spent my life convincing the whole world that I did.",
        "urduTranslation": "شاید مجھے حقیقت میں کسی سے عشق نہ ہوا، مگر میں ساری عمر سب کو اس کا یقین دلاتا رہا۔",
        "meaning": "Candid confession of emotional detachment and performative affection."
    },
    {
        "poet": "Jaun Elia",
        "poetUrdu": "جون ایلیا",
        "poetOrigin": "Amroha, India / Karachi, Pakistan",
        "poetEra": "1931 – 2002",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "جو گزاری نہ جا سکی ہم سے\nہم نے وہ زندگی گزاری ہے",
        "romanText": "Jo guzaari na ja saki hum se\nHum ne wo zindagi guzaari hai",
        "englishTranslation": "The life that was unbearable to endure—that is the very life we have somehow lived through.",
        "urduTranslation": "وہ زندگی جو کسی طور جینے کے لائق نہ تھی، ہم نے وہی زندگی کاٹ کر دکھائی ہے۔",
        "meaning": "Uncompromising melancholy on the harsh burden of consciousness."
    },

    # --- PARVEEN SHAKIR ---
    {
        "poet": "Parveen Shakir",
        "poetUrdu": "پروین شاکر",
        "poetOrigin": "Karachi / Islamabad, Pakistan",
        "poetEra": "1952 – 1994",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "کو بہ کو پھیل گئی بات شناسائی کی\nاس نے خوشبو کی طرح میری پذیرائی کی",
        "romanText": "Koo-ba-koo phail gayi baat shanasayi ki\nUs ne khushbu ki tarah meri paziraayi ki",
        "englishTranslation": "From street to street the story of our acquaintance spread; they welcomed me as tenderly as gentle fragrance embraces the air.",
        "urduTranslation": "ہماری شناسائی کا چرچا گلی گلی پھیل گیا، اس نے خوشبو کی مانند میرا استقبال کیا۔",
        "meaning": "Parveen Shakir's signature fragrance metaphor for delicate romance."
    },
    {
        "poet": "Parveen Shakir",
        "poetUrdu": "پروین شاکر",
        "poetOrigin": "Karachi / Islamabad, Pakistan",
        "poetEra": "1952 – 1994",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "حسن کے سمجھنے کو عمر چاہیے جاناں\nدو گھڑی کی چاہت میں لڑکپن نہیں جاتا",
        "romanText": "Husn ke samajhne ko umr chahiye jaanan\nDo ghari ki chahat mein larkpan nahin jaata",
        "englishTranslation": "To truly comprehend beauty requires an entire lifetime, my love; a brief fleeting affection cannot outgrow youthful naivety.",
        "urduTranslation": "حقیقی حسن کی قدر جاننے کے لیے عمر درکار ہے، گھڑی دو گھڑی کے عشق سے نادانی دور نہیں ہوتی۔",
        "meaning": "Emotional maturity versus youthful impulse in love."
    },
    {
        "poet": "Parveen Shakir",
        "poetUrdu": "پروین شاکر",
        "poetOrigin": "Karachi / Islamabad, Pakistan",
        "poetEra": "1952 – 1994",
        "originalLanguage": "ur",
        "category": "dard",
        "categoryLabel": "Sorrow & Longing",
        "originalText": "کیسے کہہ دوں کہ مجھے چھوڑ دیا ہے اس نے\nبات تو سچ ہے مگر بات ہے رسوائی کی",
        "romanText": "Kaise keh dun ke mujhe chhor diya hai us ne\nBaat to sach hai magar baat hai ruswayi ki",
        "englishTranslation": "How could I confess to the world that they have abandoned me? The statement is true, but it brings only public humiliation.",
        "urduTranslation": "میں دنیا کے سامنے کیسے اقرار کروں کہ اس نے مجھے چھوڑ دیا ہے، بات تو سچ ہے مگر اس میں رسوائی چھپی ہے۔",
        "meaning": "The dignity and vulnerability of enduring abandonment in silence."
    },

    # --- NASIR KAZMI ---
    {
        "poet": "Nasir Kazmi",
        "poetUrdu": "ناصر کاظمی",
        "poetOrigin": "Ambala, India / Lahore, Pakistan",
        "poetEra": "1925 – 1972",
        "originalLanguage": "ur",
        "category": "dard",
        "categoryLabel": "Sorrow & Longing",
        "originalText": "گئے دنوں کا سراغ لے کر کدھر سے آیا کدھر گیا وہ\nعجیب مانوس اجنبی تھا مجھے تو حیران کر گیا وہ",
        "romanText": "Gaye dinon ka suragh le kar kidhar se aaya kidhar gaya wo\nAjeeb maanoos ajnabi tha mujhe to hairan kar gaya wo",
        "englishTranslation": "Carrying traces of bygone days, whence did he come and whither did he vanish? A strangely familiar stranger who left me in utter wonder.",
        "urduTranslation": "ماضی کی یادیں لیے وہ کہاں سے آیا اور کہاں چلا گیا، وہ ایسا اجنبی تھا جو اپنا بھی لگتا تھا اور مجھے حیرت میں ڈال گیا۔",
        "meaning": "The haunting nostalgia of lost eras and elusive encounters."
    },
    {
        "poet": "Nasir Kazmi",
        "poetUrdu": "ناصر کاظمی",
        "poetOrigin": "Ambala, India / Lahore, Pakistan",
        "poetEra": "1925 – 1972",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "دل میں اک لہر سی اٹھی ہے ابھی\nکوئی تازہ ہوا چلی ہے ابھی",
        "romanText": "Dil mein ik lehar si uthi hai abhi\nKoi taaza hawa chali hai abhi",
        "englishTranslation": "A tender ripple has just arisen in the heart; a gentle fresh breeze has stirred this very moment.",
        "urduTranslation": "ابھی ابھی دل میں یاد کی ایک خوشگوار لہر اٹھی ہے، جیسے تازہ ہوا کا جھونکا گزر گیا ہو۔",
        "meaning": "A sudden rush of tender reminiscence in the quiet of dusk."
    },

    # --- HABIB JALIB ---
    {
        "poet": "Habib Jalib",
        "poetUrdu": "حبیب جالب",
        "poetOrigin": "Hoshiarpur, India / Lahore, Pakistan",
        "poetEra": "1928 – 1993",
        "originalLanguage": "ur",
        "category": "inqilab",
        "categoryLabel": "Revolution & Hope",
        "originalText": "ایسے دستور کو صبحِ بے نور کو\nمیں نہیں مانتا میں نہیں جانتا",
        "romanText": "Aise dastoor ko subh-e-be-noor ko\nMain nahin maanta main nahin jaanta",
        "englishTranslation": "Such unjust law, such dark cheerless dawn: I do not accept it, I do not recognize it!",
        "urduTranslation": "ظلم کے ایسے ضابطے اور روشنی سے محروم صبح کو میں تسلیم کرنے سے انکار کرتا ہوں۔",
        "meaning": "Pakistan's most iconic anti-authoritarian revolutionary chant."
    },
    {
        "poet": "Habib Jalib",
        "poetUrdu": "حبیب جالب",
        "poetOrigin": "Hoshiarpur, India / Lahore, Pakistan",
        "poetEra": "1928 – 1993",
        "originalLanguage": "ur",
        "category": "inqilab",
        "categoryLabel": "Revolution & Hope",
        "originalText": "ظلم رہے اور امن بھی ہو کیا ممکن ہے تم ہی کہو\nخون بھی بہے اور بات نہ ہو کیا ممکن ہے تم ہی کہو",
        "romanText": "Zulm rahe aur aman bhi ho kya mumkin hai tum hi kaho\nKhoon bhi bahe aur baat na ho kya mumkin hai tum hi kaho",
        "englishTranslation": "Can tyranny persist alongside true peace? Tell me, is it possible? Can blood be shed without voices rising?",
        "urduTranslation": "تم خود ہی فیصلہ کرو، کیا ظلم کے سائے میں امن قائم رہ سکتا ہے یا ناحق خون بہنے پر خاموشی ممکن ہے؟",
        "meaning": "A fearless confrontation demanding justice and accountability."
    },

    # --- MOMIN KHAN MOMIN ---
    {
        "poet": "Momin Khan Momin",
        "poetUrdu": "مومن خاں مومن",
        "poetOrigin": "Delhi, India",
        "poetEra": "1800 – 1851",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "تم مرے پاس ہوتے ہو گویا\nجب کوئی دوسرا نہیں ہوتا",
        "romanText": "Tum mere paas hote ho goya\nJab koi doosra nahin hota",
        "englishTranslation": "You seem to be right beside me in solace whenever there is no one else around.",
        "urduTranslation": "جب محفل میں کوئی دوسرا موجود نہیں ہوتا، تو یوں لگتا ہے جیسے تم میرے بالکل قریب ہو۔",
        "meaning": "Ghalib famously offered his entire Diwan in exchange for this single couplet."
    },
    {
        "poet": "Momin Khan Momin",
        "poetUrdu": "مومن خاں مومن",
        "poetOrigin": "Delhi, India",
        "poetEra": "1800 – 1851",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "اثر اس کو ذرا نہیں ہوتا\nرنج راحت فزا نہیں ہوتا",
        "romanText": "Asar us ko zara nahin hota\nRanj rahat-faza nahin hota",
        "englishTranslation": "My pleas leave them completely unmoved; nor does my grief ever transform into comforting ease.",
        "urduTranslation": "میری آہوں اور التجاؤں کا اس پر کوئی اثر نہیں ہوتا، اور یہ دکھ کبھی راحت میں تبدیل نہیں ہوتا۔",
        "meaning": "Classic lamentation of enduring an indifferent lover."
    },

    # --- DAGH DEHLVI ---
    {
        "poet": "Dagh Dehlvi",
        "poetUrdu": "داغؔ دہلوی",
        "poetOrigin": "Delhi / Hyderabad, India",
        "poetEra": "1831 – 1905",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "اردو ہے جس کا نام ہمیں جانتے ہیں داغؔ\nسارے جہاں میں دھوم ہماری زباں کی ہے",
        "romanText": "Urdu hai jis ka naam humein jaante hain Dagh\nSaare jahaan mein dhoom hamari zabaan ki hai",
        "englishTranslation": "Urdu is its name, and we know its grace, O Dagh; throughout the entire world our melodious tongue is celebrated.",
        "urduTranslation": "اے داغ! ہمیں معلوم ہے کہ اردو کیسی میٹھی زبان ہے، جس کی شیرینی کی دھوم پوری دنیا میں مچی ہے۔",
        "meaning": "The ultimate tribute to the beauty and prestige of the Urdu language."
    },
    {
        "poet": "Dagh Dehlvi",
        "poetUrdu": "داغؔ دہلوی",
        "poetOrigin": "Delhi / Hyderabad, India",
        "poetEra": "1831 – 1905",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "لطفِ مے تجھ سے کیا کہوں زاہد\nہائے کمبخت تو نے پی ہی نہیں",
        "romanText": "Lutf-e-mai tujh se kya kahun zaahid\nHaaye kambakht tu ne pee hi nahin",
        "englishTranslation": "How could I describe the ecstatic delight of wine to you, pious ascetic? Alas, you unfortunate soul have never tasted it!",
        "urduTranslation": "اے پارسا! تجھے بادۂ عشق کی لذت کا کیا علم، افسوس کہ تو نے محبت کا یہ جام کبھی چکھا ہی نہیں۔",
        "meaning": "Witty poetic rebuttal to joyless dogmatism."
    },

    # --- BAHADUR SHAH ZAFAR ---
    {
        "poet": "Bahadur Shah Zafar",
        "poetUrdu": "بہادر شاہ ظفر",
        "poetOrigin": "Delhi, India / Rangoon, Burma",
        "poetEra": "1775 – 1862",
        "originalLanguage": "ur",
        "category": "dard",
        "categoryLabel": "Sorrow & Longing",
        "originalText": "کتنا ہے بد نصیب ظفرؔ دفن کے لیے\nدو گز زمین بھی نہ ملی کوئے یار میں",
        "romanText": "Kitna hai bad-naseeb Zafar dafn ke liye\nDo gaz zameen bhi na mili koo-e-yaar mein",
        "englishTranslation": "How unfortunate is Zafar, who for his eternal rest could not receive even two yards of earth in the homeland of his beloved.",
        "urduTranslation": "ظفر کیسی بدقسمتی ہے کہ آخری آرام گاہ کے لیے اپنے محبوب وطن میں دو گز زمین بھی نصیب نہ ہوئی۔",
        "meaning": "Heartbreaking elegy of the exiled Mughal emperor in Burma."
    },
    {
        "poet": "Bahadur Shah Zafar",
        "poetUrdu": "بہادر شاہ ظفر",
        "poetOrigin": "Delhi, India / Rangoon, Burma",
        "poetEra": "1775 – 1862",
        "originalLanguage": "ur",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "عمرِ دراز مانگ کے لائے تھے چار دن\nدو آرزو میں کٹ گئے دو انتظار میں",
        "romanText": "Umr-e-daraaz maang ke laaye the chaar din\nDo aarzoo mein kat gaye do intezaar mein",
        "englishTranslation": "We had asked for a long life, yet received merely four fleeting days: two spent in yearning, and two in weary waiting.",
        "urduTranslation": "ہم زندگی کی لمبی دعا مانگ کر لائے تھے لیکن وہ چار دن ثابت ہوئی؛ دو آرزوؤں میں بیت گئے اور دو انتظار میں۔",
        "meaning": "Timeless meditation on life's shortness and unfulfilled hopes."
    },

    # --- SAHIR LUDHIANVI ---
    {
        "poet": "Sahir Ludhianvi",
        "poetUrdu": "ساحر لدھیانوی",
        "poetOrigin": "Ludhiana / Mumbai, India",
        "poetEra": "1921 – 1980",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "تعارف روگ بن جائے تو اس کا بھولنا بہتر\nتعلق بوجھ بن جائے تو اس کا توڑنا اچھا",
        "romanText": "Ta'aruf rog ban jaaye to us ka bhoolna behtar\nTa'alluq bojh ban jaaye to us ka torna achha",
        "englishTranslation": "If an acquaintance becomes a painful sickness, it is better to forget it; if a relationship becomes an unbearable burden, it is best to sever it.",
        "urduTranslation": "اگر کوئی جان پہچان دل کا روگ بن جائے تو اسے بھلا دینا چاہیے، اور اگر رشتہ بوجھ بن جائے تو اسے عزت سے ختم کر دینا بہتر ہے۔",
        "meaning": "Emotional wisdom regarding the release of toxic attachments."
    },
    {
        "poet": "Sahir Ludhianvi",
        "poetUrdu": "ساحر لدھیانوی",
        "poetOrigin": "Ludhiana / Mumbai, India",
        "poetEra": "1921 – 1980",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "وہ افسانہ جسے انجام تک لانا نہ ہو ممکن\nاسے اک خوبصورت موڑ دے کر چھوڑنا اچھا",
        "romanText": "Wo afsana jise anjaam tak laana na ho mumkin\nUse ik khoobsurat mor de kar chhorna achha",
        "englishTranslation": "That love story which cannot be carried to fulfillment: far better to grant it a graceful parting turn and let it rest.",
        "urduTranslation": "جس کہانی کی تکمیل ممکن نہ ہو، اسے کسی خوبصورت موڑ پر باوقار طریقے سے الوداع کہہ دینا ہی دانشمندی ہے۔",
        "meaning": "Graceful acceptance of romantic closure."
    },

    # --- KAIFI AZMI ---
    {
        "poet": "Kaifi Azmi",
        "poetUrdu": "کیفی اعظمی",
        "poetOrigin": "Azamgarh / Mumbai, India",
        "poetEra": "1919 – 2002",
        "originalLanguage": "ur",
        "category": "inqilab",
        "categoryLabel": "Revolution & Hope",
        "originalText": "اٹھ مری جان مرے ساتھ ہی چلنا ہے تجھے\nقلبِ ماحول میں لرزہ سا فگن ہونا ہے",
        "romanText": "Uth meri jaan mere saath hi chalna hai tujhe\nQalb-e-maahaul mein larza sa figan hona hai",
        "englishTranslation": "Arise, my beloved, you must walk shoulder-to-shoulder with me; we must ignite a tremor across the heart of this unjust world.",
        "urduTranslation": "اے میری ہم سفر اٹھو اور میرے قدم سے قدم ملا کر چلو، ہمیں اس پرانے نظام کی بنیادوں کو بدلنا ہے۔",
        "meaning": "Pioneering progressive poem demanding gender equality in social struggle."
    },

    # --- JOSH MALIHABADI ---
    {
        "poet": "Josh Malihabadi",
        "poetUrdu": "جوش ملیح آبادی",
        "poetOrigin": "Malihabad, India / Islamabad, Pakistan",
        "poetEra": "1898 – 1982",
        "originalLanguage": "ur",
        "category": "inqilab",
        "categoryLabel": "Revolution & Hope",
        "originalText": "کام ہے میرا تغیر، نام ہے میرا شباب\nنعرۂ بے باک ہوں میں، شورشِ بیدار ہوں",
        "romanText": "Kaam hai mera taghayyur, naam hai mera shabab\nNaara-e-bebaak hun main, shorish-e-bedaar hun",
        "englishTranslation": "My mission is revolution, my identity is untamed youth; I am a fearless battle-cry, an awakening storm!",
        "urduTranslation": "تبدیلی لانا میرا مقصد ہے اور نوجوانی میرا نام؛ میں ظلم کے خلاف ایک بے خوف نعرہ اور بیداری کی للکار ہوں۔",
        "meaning": "Josh Malihabadi's fiery ode to revolutionary change."
    },

    # --- HASRAT MOHANI ---
    {
        "poet": "Hasrat Mohani",
        "poetUrdu": "حسرت موہانی",
        "poetOrigin": "Mohan / Kanpur, India",
        "poetEra": "1875 – 1951",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "چپکے چپکے رات دن آنسو بہانا یاد ہے\nہم کو اب تک عاشقی کا وہ زمانہ یاد ہے",
        "romanText": "Chupke chupke raat din aansu bahana yaad hai\nHum ko ab tak aashiqi ka wo zamana yaad hai",
        "englishTranslation": "Silently shedding tears night and day remains vivid in memory; I still remember that golden era of passionate love.",
        "urduTranslation": "محبت میں رات دن چپکے چپکے آنسو بہانا ہمیں خوب یاد ہے، اور اس عاشقی کا سارا زمانہ دل میں محفوظ ہے۔",
        "meaning": "One of the most cherished ghazals of tender romance in Urdu."
    },

    # --- JIGAR MORADABADI ---
    {
        "poet": "Jigar Moradabadi",
        "poetUrdu": "جگر مراد آبادی",
        "poetOrigin": "Moradabad, India",
        "poetEra": "1890 – 1960",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "یہ عشق نہیں آساں بس اتنا سمجھ لیجے\nاک آگ کا دریا ہے اور ڈوب کے جانا ہے",
        "romanText": "Yeh ishq nahin aasaan bas itna samajh lije\nIk aag ka darya hai aur doob ke jaana hai",
        "englishTranslation": "Love is no easy endeavor, understand just this much: it is an ocean of fire, and one must plunge through to cross.",
        "urduTranslation": "محبت کوئی آسان راستہ نہیں، یہ تو آگ کا سمندر ہے جس میں خود کو فنا کر کے ہی منزل ملتی ہے۔",
        "meaning": "Immortal definition of the trials and devotion of true love."
    },

    # --- FIRAQ GORAKHPURI ---
    {
        "poet": "Firaq Gorakhpuri",
        "poetUrdu": "فراق گورکھپوری",
        "poetOrigin": "Gorakhpur / Allahabad, India",
        "poetEra": "1896 – 1982",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "بہت پہلے سے ان قدموں کی آہٹ جان لیتے ہیں\nتجھے اے زندگی ہم دور سے پہچان لیتے ہیں",
        "romanText": "Bohat pehle se un qadmon ki aahat jaan lete hain\nTujhe ae zindagi hum door se pehchaan lete hain",
        "englishTranslation": "We detect the whisper of those approaching footsteps from afar; O life, we recognize you even from the distant horizon.",
        "urduTranslation": "ہم دور ہی سے محبوب کی چاپ پہچان لیتے ہیں، اے زندگی ہم تجھے فاصلوں سے بھی بخوبی جان جاتے ہیں۔",
        "meaning": "Sublime sensitivity to the subtle movements of life and passion."
    },

    # --- IBN-E-INSHA ---
    {
        "poet": "Ibn-e-Insha",
        "poetUrdu": "ابنِ انشا",
        "poetOrigin": "Jalandhar, India / Karachi, Pakistan",
        "poetEra": "1927 – 1978",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "انشاؔ جی اٹھو اب کوچ کرو اس شہر میں جی کو لگانا کیا\nدیوانے ہوئے سرگرداں ہوئے اب چین سے جا کر سو رہنا",
        "romanText": "Insha ji utho ab kooch karo is shehr mein jee ko lagana kya\nDeewane hue sargardaan hue ab chain se jaa kar so rehna",
        "englishTranslation": "Rise, Insha ji, and depart; why anchor your heart in this uncaring town? You have wandered madly; now go and rest peacefully.",
        "urduTranslation": "اے انشا اب یہاں سے رخصت ہو جاؤ، اس بستی میں دل لگانے کا کیا حاصل؛ اب جا کر سکون کی نیند سو جاؤ۔",
        "meaning": "Immortal melancholic ballad of wanderlust, loneliness, and departure."
    },

    # --- MOHSIN NAQVI ---
    {
        "poet": "Mohsin Naqvi",
        "poetUrdu": "محسن نقوی",
        "poetOrigin": "Dera Ghazi Khan / Lahore, Pakistan",
        "poetEra": "1947 – 1996",
        "originalLanguage": "ur",
        "category": "dard",
        "categoryLabel": "Sorrow & Longing",
        "originalText": "یہ دل جو تیرے نام سے دھڑکتا تھا کبھی\nاب اس میں تیرے سوا کوئی بھی نہیں رہتا",
        "romanText": "Yeh dil jo tere naam se dharakta tha kabhi\nAb is mein tere siwa koi bhi nahin rehta",
        "englishTranslation": "This heart that once beat only to the rhythm of your name: now no one dwells within it except your sacred memory.",
        "urduTranslation": "یہ دل جو کبھی تیرے نام سے دھڑکتا تھا، آج بھی اس ویرانے میں تیری یاد کے سوا کسی کا بسیرا نہیں۔",
        "meaning": "Sacred solitude and eternal dedication to the memory of love."
    },

    # --- SAGHAR SIDDIQUI ---
    {
        "poet": "Saghar Siddiqui",
        "poetUrdu": "ساغر صدیقی",
        "poetOrigin": "Ambala, India / Lahore, Pakistan",
        "poetEra": "1928 – 1974",
        "originalLanguage": "ur",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "زندگی جبرِ مسلسل کی طرح کاٹی ہے\nجانے کس جرم کی پائی ہے سزا یاد نہیں",
        "romanText": "Zindagi jabr-e-musalsal ki tarah kaati hai\nJaane kis jurm ki paayi hai saza yaad nahin",
        "englishTranslation": "I have spent life like an enduring sentence of ceaseless hardship; for what unknown transgression I was punished, I recall no more.",
        "urduTranslation": "ہم نے زندگی کو ایک مسلسل قید اور جبر کی طرح گزارا، یہ بھی یاد نہیں کہ کس خطا کی سزا بھگت رہے ہیں۔",
        "meaning": "Saghar Siddiqui's haunting testament of bohemian suffering and resilience."
    },

    # --- SHAKEEL BADAYUNI ---
    {
        "poet": "Shakeel Badayuni",
        "poetUrdu": "شکیل بدایونی",
        "poetOrigin": "Badaun / Mumbai, India",
        "poetEra": "1916 – 1970",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "غمِ عاشقی سے کہہ دو کہ رہے پرے پرے ہی\nکہ یہاں تو زندگی بھی بڑی بے نقاب سی ہے",
        "romanText": "Gham-e-aashiqi se keh do ke rahe pare pare hi\nKe yahan to zindagi bhi bari be-naqaab si hai",
        "englishTranslation": "Tell the sorrows of passion to keep their distance; for here life itself is already exposed and raw.",
        "urduTranslation": "عشق کے غم کو کہو کہ ذرا دور رہے، کیونکہ یہاں تو خود زندگی کی الجھنیں ہی بے پناہ ہیں۔",
        "meaning": "Poetic balance between life's harsh struggles and romantic tenderness."
    },

    # --- QATEEL SHIFAI ---
    {
        "poet": "Qateel Shifai",
        "poetUrdu": "قتیل شفائی",
        "poetOrigin": "Haripur, Pakistan",
        "poetEra": "1919 – 2001",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "گرمیِ حسرتِ ناکام سے جل جاتے ہیں\nہم چراغوں کی طرح شام سے جل جاتے ہیں",
        "romanText": "Garmi-e-hasrat-e-nakaam se jal jaate hain\nHum charaghon ki tarah shaam se jal jaate hain",
        "englishTranslation": "From the burning embers of unfulfilled longing we burn; like solitary lamps, we ignite as evening falls.",
        "urduTranslation": "ہم اپنی ادھوری آرزوؤں کی تپش سے جلتے ہیں، اور شام ہوتے ہی چراغ کی مانند سلگ اٹھتے ہیں۔",
        "meaning": "Lyrical beauty on evening loneliness and enduring devotion."
    },

    # --- NIDA FAZLI ---
    {
        "poet": "Nida Fazli",
        "poetUrdu": "ندا فاضلی",
        "poetOrigin": "Gwalior / Mumbai, India",
        "poetEra": "1938 – 2016",
        "originalLanguage": "ur",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "کبھی کسی کو مکمل جہاں نہیں ملتا\nکہیں زمیں تو کہیں آسماں نہیں ملتا",
        "romanText": "Kabhi kisi ko mukammal jahaan nahin milta\nKahin zameen to kahin aasmaan nahin milta",
        "englishTranslation": "No soul ever receives a flawless complete universe; somewhere the earth is lacking, and somewhere the sky.",
        "urduTranslation": "اس دنیا میں کسی کو بھی سب کچھ مکمل نہیں ملتا، کسی کو زمین کم پڑتی ہے تو کسی کو آسمان نصیب نہیں ہوتا۔",
        "meaning": "Universal philosophy of contentment amid life's inevitable imperfections."
    },

    # --- BASHIR BADR ---
    {
        "poet": "Bashir Badr",
        "poetUrdu": "بشیر بدر",
        "poetOrigin": "Kanpur / Bhopal, India",
        "poetEra": "1935 – Present",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "اجالے اپنی یادوں کے ہمارے ساتھ رہنے دو\nنہ جانے کس گلی میں زندگی کی شام ہو جائے",
        "romanText": "Ujaale apni yaadon ke hamare saath rehne do\nNa jaane kis gali mein zindagi ki shaam ho jaaye",
        "englishTranslation": "Leave the soft illuminations of your memories beside me; who knows in which quiet street the dusk of life may arrive?",
        "urduTranslation": "اپنی یادوں کی روشنی میرے ساتھ رہنے دو، معلوم نہیں زندگی کی شام کس گلی میں ہو جائے۔",
        "meaning": "Cherishing memories as life's guiding lantern."
    },

    # --- RAHAT INDORI ---
    {
        "poet": "Rahat Indori",
        "poetUrdu": "راحت اندوری",
        "poetOrigin": "Indore, India",
        "poetEra": "1950 – 2020",
        "originalLanguage": "ur",
        "category": "inqilab",
        "categoryLabel": "Revolution & Hope",
        "originalText": "سبھی کا خون ہے شامل یہاں کی مٹی میں\nکسی کے باپ کا ہندوستاں تھوڑی ہے",
        "romanText": "Sabhi ka khoon hai shaamil yahan ki mitti mein\nKisi ke baap ka hindustaan thori hai",
        "englishTranslation": "The blood of every citizen is mingled in this sacred soil; this motherland belongs exclusively to no single power!",
        "urduTranslation": "اس دھرتی کی مٹی میں ہر فرد کا لہو شامل ہے، یہ وطن سب کا مشترکہ گھر ہے۔",
        "meaning": "Iconic progressive verse celebrating equality and civic fraternity."
    },

    # --- WASIF ALI WASIF ---
    {
        "poet": "Wasif Ali Wasif",
        "poetUrdu": "واصف علی واصف",
        "poetOrigin": "Khushab / Lahore, Pakistan",
        "poetEra": "1929 – 1993",
        "originalLanguage": "ur",
        "category": "dua",
        "categoryLabel": "Dua & Blessings",
        "originalText": "کرم کی اک نظر مولا ہمارے حال پر کر دے\nدلِ بے تاب کو اپنے کرم سے پر سکوں کر دے",
        "romanText": "Karam ki ik nazar maula hamare haal par kar de\nDil-e-betaab ko apne karam se pur-sukoon kar de",
        "englishTranslation": "Cast a single glance of grace, O Master, upon our fragile state; grant profound peace to this restless heart through Thy mercy.",
        "urduTranslation": "اے پروردگار! اپنے لطف و کرم کی ایک نگاہ فرما اور ہمارے بے چین دل کو سکون اور اطمینان عطا کر۔",
        "meaning": "A sublime spiritual prayer for inner tranquillity and divine grace."
    },

    # --- AMJAD ISLAM AMJAD ---
    {
        "poet": "Amjad Islam Amjad",
        "poetUrdu": "امجد اسلام امجد",
        "poetOrigin": "Lahore, Pakistan",
        "poetEra": "1944 – 2023",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "اگر کبھی میری یاد آئے تو چاند راتوں کی نرم چاندنی میں\nدبے قدم تم چلے ہی آنا، کہ منتظر ہے نگاہ میری",
        "romanText": "Agar kabhi meri yaad aaye to chaand raaton ki narm chaandni mein\nDabe qadam tum chale hi aana, ke muntazir hai nigaah meri",
        "englishTranslation": "If ever you recall my memory, come softly amidst the gentle glow of moonlit nights; my gaze forever waits for you.",
        "urduTranslation": "اگر کبھی میری یاد آئے تو چاندنی راتوں میں خاموشی سے چلے آنا، کہ میری نگاہیں تمہارے انتظار میں لگی ہیں۔",
        "meaning": "Lyrical nazm celebrating eternal devotion."
    },

    # --- PUNJABI MASTERPIECES ---
    {
        "poet": "Baba Bulleh Shah",
        "poetUrdu": "بابا بلھے شاہ",
        "poetOrigin": "Kasur, Punjab",
        "poetEra": "1680 – 1757",
        "originalLanguage": "pa",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "نہ کر خودی گمان نی کڑئے، خالی ہتھ سدھاریں گی\nاک دن مٹی دے وچ ملنا، ایتھے کی کجھ ہاریں گی",
        "romanText": "Na kar khudi gumaan ni kurriye, khaali hath sudhaarein gi\nIk din mitti de vich milna, aithe ki kujh haarein gi",
        "englishTranslation": "Harbor no vain pride, dear soul; with empty hands you shall depart. One day you must return to earth—why lose your humility here?",
        "urduTranslation": "اے انسان تکبر و غرور نہ کر، آخر کار خالی ہاتھ ہی رخصت ہونا ہے؛ ایک دن مٹی میں ملنا ہے تو یہاں نیکی اور عاجزی کیوں نہ کمائی جائے؟",
        "meaning": "Bulleh Shah's timeless call against worldly vanity and pride."
    },
    {
        "poet": "Baba Bulleh Shah",
        "poetUrdu": "بابا بلھے شاہ",
        "poetOrigin": "Kasur, Punjab",
        "poetEra": "1680 – 1757",
        "originalLanguage": "pa",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "جے توں اپنے یار نوں پاویں، سولی تے چڑھ کے ویکھ لے\nعشق نہ پچھے ذات صفاتاں، دل نال دل نوں جوڑ لے",
        "romanText": "Je tu apne yaar nu paavein, sooli te charh ke vekh le\nIshq na puchhe zaat sifaatan, dil naal dil nu jorh le",
        "englishTranslation": "If you wish to attain your Beloved, look upon the path of sacrifice; true love cares nothing for lineage or status, it binds heart to heart.",
        "urduTranslation": "اگر تم اپنے محبوب کو پانا چاہتے ہو تو ایثار و قربانی کے راستے پر چلو؛ عشق ذات پات نہیں پوچھتا بلکہ دلوں کو دلوں سے جوڑتا ہے۔",
        "meaning": "The ultimate transcendence of love beyond all worldly barriers."
    },
    {
        "poet": "Baba Bulleh Shah",
        "poetUrdu": "بابا بلھے شاہ",
        "poetOrigin": "Kasur, Punjab",
        "poetEra": "1680 – 1757",
        "originalLanguage": "pa",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "اٹھ گئے گوانڈھوں یار ربّا ہن کی کریئے\nپھوک مصلّی بھن سٹ کاسہ، عشقے دا کوئی تیر چلا",
        "romanText": "Uth gaye gawaandhon yaar rabba hun ki kariye\nPhook musalla bhann sit kaasa, ishqe da koi teer chala",
        "englishTranslation": "The beloved neighbor has moved away, O Lord, what shall I do now? Cast away empty rituals and kindle the arrow of authentic love!",
        "urduTranslation": "پڑوس سے محبوب بچھڑ گیا، اے خدا اب ہم کیا کریں؛ ظاہری رسومات چھوڑ کر عشق کی سچی آگ اپنے اندر جلاؤ۔",
        "meaning": "Sufi longing for the departed divine beloved."
    },
    {
        "poet": "Sultan Bahu",
        "poetUrdu": "سلطان باہو",
        "poetOrigin": "Shorekot, Jhang, Punjab",
        "poetEra": "1628 – 1691",
        "originalLanguage": "pa",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "نئیں جے رب ملدا نہاتے دھوتیاں، ملدا ڈڈواں مچھیاں ھو\nجے رب ملدا جنگل بیلے، ملدا گائیں وچھیاں ھو",
        "romanText": "Nai je Rabb milda naate dhotiyan, milda dadwaan machhiyan hoo\nJe Rabb milda jangal bele, milda gaayein vichhiyan hoo",
        "englishTranslation": "If God were found merely through ritual baths, frogs and fish would find Him; if He were found in lonely jungles, the grazing calves would find Him!",
        "urduTranslation": "اگر رب صرف ظاہری نہانے دھونے سے ملتا تو مینڈک اور مچھلیاں پا لیتیں، اور اگر جنگلوں میں ملتا تو گائیں بچھڑے پا لیتے؛ رب تو سچے دل میں ملتا ہے۔",
        "meaning": "Sultan Bahu exposing superficial religiosity in favor of pure spiritual love."
    },
    {
        "poet": "Waris Shah",
        "poetUrdu": "سید وارث شاہ",
        "poetOrigin": "Jandiala Sher Khan, Punjab",
        "poetEra": "1722 – 1798",
        "originalLanguage": "pa",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "وارث شاہ لُکائیے کِنج اس نوں، جیہڑا عشق چھپایا نئیں لُکدا\nچن چڑھیا کدی نہ لُکے بدلیں، دریا دا وگنا نئیں مُکدا",
        "romanText": "Waris Shah lukaaiye kinj us nu, jehra ishq chhupaya nai lukda\nChan charhiya kadi na luke badlein, darya da vagna nai mukda",
        "englishTranslation": "O Waris Shah, how could one conceal love that can never be hidden? The risen moon cannot hide behind clouds, nor can a mighty river cease flowing.",
        "urduTranslation": "اے وارث شاہ! عشق کو کیسے چھپایا جائے جو چھپائے نہیں چھپتا؛ چاند بادلوں میں نہیں چھپ سکتا اور دریا کبھی بہنے سے نہیں رکتا۔",
        "meaning": "The irrepressible, overwhelming power of genuine love."
    },
    {
        "poet": "Mian Muhammad Bakhsh",
        "poetUrdu": "میاں محمد بخش",
        "poetOrigin": "Mirpur, Kashmir / Punjab",
        "poetEra": "1830 – 1907",
        "originalLanguage": "pa",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "خاصاں دی گل عاماں اگے، نئیں مناسب کرنی\nمٹھی کھیر پکا محمدؔ، کُتیاں اگے دھرنی",
        "romanText": "Khaasan di gal aamaan agge, nai munasib karni\nMithi kheer paka Muhammad, kuttiyan agge dharni",
        "englishTranslation": "Sharing wisdom of the enlightened with the unheeding is unwise; like preparing sweet pudding and placing it before dogs who know no value.",
        "urduTranslation": "معرفت اور حکمت کی گہری باتیں بے قدرے لوگوں کے سامنے کرنا ایسا ہی ہے جیسے میٹھی کھیر پکا کر قدر نہ جاننے والوں کے سامنے رکھ دی جائے۔",
        "meaning": "Guarding sacred wisdom and discerning when to speak."
    },
    {
        "poet": "Mian Muhammad Bakhsh",
        "poetUrdu": "میاں محمد بخش",
        "poetOrigin": "Mirpur, Kashmir / Punjab",
        "poetEra": "1830 – 1907",
        "originalLanguage": "pa",
        "category": "dosti",
        "categoryLabel": "Friendship & Loyalty",
        "originalText": "جیڑھے لوک نہ قدر پچھانن، اوہناں کول نہ بہیئے\nاوکھے ویلے نال کھلووے، اوہی سجن کہیئے",
        "romanText": "Jehrhe lok na qadar pachhanan, ohna kol na bahiye\nOokhe wele naal khalowey, ohi sajan kahiye",
        "englishTranslation": "Do not keep company with those who fail to recognize true worth; only he who stands steadfast in times of trial deserves to be called a true friend.",
        "urduTranslation": "جو لوگ قدر نہیں پہچانتے ان کی صحبت میں نہ بیٹھو؛ سچا دوست وہی ہے جو مشکل وقت میں تمہارے ساتھ مضبوطی سے کھڑا رہے۔",
        "meaning": "True friendship is proven in times of adversity."
    },
    {
        "poet": "Amrita Pritam",
        "poetUrdu": "امرتا پریتم",
        "poetOrigin": "Gujranwala / Delhi",
        "poetEra": "1919 – 2005",
        "originalLanguage": "pa",
        "category": "dard",
        "categoryLabel": "Sorrow & Longing",
        "originalText": "اج آکھاں وارث شاہ نوں، کِتھوں قبراں وچوں بول\nتے اج کتابِ عشق دا، کوئی اگلا ورقہ پھول",
        "romanText": "Ajj aakhaan Waris Shah nu, kitthon qabraan vichon bol\nTe ajj kitaab-e-ishq da, koi agla varqa phol",
        "englishTranslation": "Today I call upon Waris Shah: speak out from your silent grave! Turn to the next tragic page in the grand book of love!",
        "urduTranslation": "آج میں وارث شاہ کو پکارتی ہوں کہ قبر سے بول اٹھو، اور آج محبت اور انسانیت کی کتاب کا اگلا درد بھرا صفحہ کھولو۔",
        "meaning": "Amrita Pritam's immortal elegy on the partition of Punjab."
    },
    {
        "poet": "Munir Niazi",
        "poetUrdu": "منیر نیازی",
        "poetOrigin": "Khanpur, India / Lahore, Pakistan",
        "poetEra": "1928 – 2006",
        "originalLanguage": "pa",
        "category": "dard",
        "categoryLabel": "Sorrow & Longing",
        "originalText": "کج شہر دے لوک وی ظالم سن، کج سانوں مرن دا شوق وی سی\nاک ہور دریا دا سامنا سی منیرؔ مینوں، اک پار کیتا تاں ویکھیا میں",
        "romanText": "Kujh shehr de lok vi zaalim san, kujh saanu maran da shauq vi si\nIk hor darya da saamna si Munir meinu, ik paar keeta taan vekheya main",
        "englishTranslation": "Partly the people of the city were cruel, and partly I too harbored a fatal desire; as soon as I crossed one surging river, O Munir, another river stood before me.",
        "urduTranslation": "کچھ تو شہر کے لوگ بے درد تھے اور کچھ ہمیں بھی وفا میں فنا ہونے کی چاہ تھی؛ اے منیر! ابھی ایک دریا پار کیا ہی تھا کہ آگے دوسرا دریا کھڑا ملا۔",
        "meaning": "Munir Niazi's iconic Punjabi couplet on life's relentless struggles."
    },

    # --- ARABIC MASTERPIECES ---
    {
        "poet": "Al-Mutanabbi",
        "poetUrdu": "المتنبی",
        "poetOrigin": "Kufa, Iraq",
        "poetEra": "915 – 965",
        "originalLanguage": "ar",
        "category": "inqilab",
        "categoryLabel": "Revolution & Hope",
        "originalText": "الخَيْلُ وَاللّيْلُ وَالبَيْداءُ تَعرِفُني\nوَالسّيفُ وَالرّمحُ والقرْطاسُ وَالقَلَمُ",
        "romanText": "Al-khaylu wal-laylu wal-bayda'u ta'rifuni\nWas-sayfu war-rumhu wal-qirtasu wal-qalamu",
        "englishTranslation": "The steeds, the dark night, and the vast desert know me well; as do the sword, the lance, the parchment, and the pen.",
        "urduTranslation": "گھوڑے، تاریک رات اور صحرا مجھے خوب پہچانتے ہیں؛ اور تلوار، نیزہ، کاغذ اور قلم بھی میری شجاعت اور فصاحت کے گواہ ہیں۔",
        "meaning": "The ultimate Arabic verse of poetic self-mastery, courage, and intellect."
    },
    {
        "poet": "Al-Mutanabbi",
        "poetUrdu": "المتنبی",
        "poetOrigin": "Kufa, Iraq",
        "poetEra": "915 – 965",
        "originalLanguage": "ar",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "عَلى قَدْرِ أهْلِ العَزْم تأتي العَزائِمُ\nوَتأتِي علَى قَدْرِ الكِرامِ المَكارمُ",
        "romanText": "Ala qadri ahlil-azmi ta'ti al-aza'imu\nWa ta'ti ala qadril-kirami al-makarimu",
        "englishTranslation": "Noble endeavors are realized in proportion to the resolve of great souls; and generous deeds correspond to the magnanimity of the honorable.",
        "urduTranslation": "عظیم کارنامے بلند حوصلہ اور باہمت انسانوں کے عزم کے مطابق انجام پاتے ہیں، اور عزت والے لوگ ہی عظیم مقاصد حاصل کرتے ہیں۔",
        "meaning": "Great achievements flow directly from unwavering will and honor."
    },

    # --- PERSIAN MASTERPIECES ---
    {
        "poet": "Saadi Shirazi",
        "poetUrdu": "سعدی شیرازی",
        "poetOrigin": "Shiraz, Iran",
        "poetEra": "1210 – 1291",
        "originalLanguage": "fa",
        "category": "falsafa",
        "categoryLabel": "Philosophy & Reflection",
        "originalText": "بنی‌آدم اعضای یکدیگرند\nکه در آفرینش ز یک گوہرند",
        "romanText": "Bani adam a'zaye yak-digarand\nKi dar aafarinesh zi yak gauharand",
        "englishTranslation": "Human beings are members of one body, for in creation they are born of one essence.",
        "urduTranslation": "تمام انسان ایک دوسرے کے اعضا کی مانند ہیں کیونکہ ان کی تخلیق ایک ہی جوہر سے ہوئی ہے۔ جب ایک کو دکھ پہنچتا ہے تو پورا جسم بے چین ہوتا ہے۔",
        "meaning": "Saadi's immortal humanist message inscribed at the United Nations entrance."
    },
    {
        "poet": "Saadi Shirazi",
        "poetUrdu": "سعدی شیرازی",
        "poetOrigin": "Shiraz, Iran",
        "poetEra": "1210 – 1291",
        "originalLanguage": "fa",
        "category": "dosti",
        "categoryLabel": "Friendship & Loyalty",
        "originalText": "درخت دوستی بنشان که کام دل به بار آرد\nنهال دشمنی برکن که رنج بی‌شمار آرد",
        "romanText": "Darakht-e-dosti benshaan ki kaam-e-dil ba baar aarad\nNehaal-e-dushmani barkan ki ranj-e-beshumaar aarad",
        "englishTranslation": "Plant the tree of friendship so that heart's desires may blossom into fruit; uproot the sapling of enmity, for it brings boundless grief.",
        "urduTranslation": "دوستی کا درخت لگاؤ تاکہ دل کی مراد کا میٹھا پھل ملے، اور دشمنی کے پودے کو جڑ سے اکھاڑ پھینکو جو بے انتہا دکھ دیتا ہے۔",
        "meaning": "Universal wisdom on cultivating brotherhood and eliminating bitterness."
    },
    {
        "poet": "Jalaluddin Rumi",
        "poetUrdu": "مولانا جلال الدین رومی",
        "poetOrigin": "Balkh / Konya",
        "poetEra": "1207 – 1273",
        "originalLanguage": "fa",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "بشنو از نی چون حکایت می‌کند\nاز جدایی‌ها شکایت می‌کند",
        "romanText": "Beshno az nay chon hekayat mikonad\nAz jodaa'i-ha shekayat mikonad",
        "englishTranslation": "Listen to the reed flute as it tells its tale, lamenting the bitter pain of separation from its source.",
        "urduTranslation": "بانسری کی آواز سنو جب وہ اپنی بپتا سناتی ہے اور اصل وطن سے بچھڑنے کا نوحہ بیان کرتی ہے۔",
        "meaning": "The opening couplet of the Masnavi, symbolizing the soul's divine homesickness."
    },
    {
        "poet": "Amir Khusro",
        "poetUrdu": "امیر خسرو",
        "poetOrigin": "Patiyali / Delhi, India",
        "poetEra": "1253 – 1325",
        "originalLanguage": "ur",
        "category": "ishq",
        "categoryLabel": "Love & Romance",
        "originalText": "چھاپ تلک سب چھینی رے موسے نیناں ملائی کے\nبات اگم کہہ دینی رے موسے نیناں ملائی کے",
        "romanText": "Chhaap tilak sab chheeni re mose naina milayi ke\nBaat agam keh deeni re mose naina milayi ke",
        "englishTranslation": "You took away all my pretense and ego with a single glance; you revealed the deepest mysteries of truth merely by meeting eyes.",
        "urduTranslation": "محبوب نے نظریں ملا کر میری ساری ظاہری شناخت مٹا دی، اور آنکھوں ہی آنکھوں میں معرفت کا گہرا راز سمجھا دیا۔",
        "meaning": "Amir Khusro's immortal Sufi classic dedicated to Hazrat Nizamuddin Auliya."
    }
]
