# -*- coding: utf-8 -*-
"""
Verses for Dua (60), Wisdom (50), and Gham (50) = 160 strictly unique tuples
Format: (poet, cat, title, m1, m2, rom, eng)
"""

DUA_WISDOM_GHAM_VERSES = [
    # ==========================================
    # DUA & BLESSINGS (60 strictly unique verses)
    # ==========================================
    ("Traditional Quranic", "dua", "Rabbana Aatina Fid Dunya Hasanatan",
     "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الآخِرَةِ حَسَنَةً", "وَقِنَا عَذَابَ النَّارِ",
     "Rabbana aatina fid-dunya hasanatan wa fil-aakhirati hasanatan, Wa qinaa azaaban-naar",
     "Our Lord, grant us in this world that which is good and in the Hereafter that which is good, and save us from the torment of the Fire."),
    ("Traditional Quranic", "dua", "Rabbi Irhamhuma Kama Rabbayani Sagheera",
     "رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا", "اللهم اغفر لوالدي وارحمهما برحمتك الواسعة",
     "Rabbi irhamhuma kama rabbayani sagheera, Allahumma-ghfir li-waalidayya warhamhuma bi-rahmatika",
     "My Lord, have mercy upon my parents even as they brought me up when I was little. O Allah, forgive them and shelter them in Your vast grace."),
    ("Traditional Quranic", "dua", "Rabbi Ishrah Li Sadri Wa Yassir Li Amri",
     "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي", "وَاحْلُلْ عُقْدَةً مِّن لِّسَانِي يَفْقَهُوا قَوْلِي",
     "Rabbi ishrah lee sadree wa yassir lee amree, Wahlul uqdatan min lisaanee yafqahoo qawlee",
     "My Lord, expand for me my chest, and ease for me my task, and untie the knot from my tongue that they may understand my speech."),
    ("Traditional Quranic", "dua", "Rabbi Zidni Ilman Naafi'an",
     "رَّبِّ زِدْنِي عِلْمًا نَافِعًا", "اللهم فقهنا في الدين ووفقنا لمرضاتك",
     "Rabbi zidnee ilman naafi'an, Allahumma faqqihna fid-deeni wa waffiqna li-mardatika",
     "My Lord, increase me in beneficial knowledge. O Allah, grant us deep wisdom of faith and guide us to Your good pleasure."),
    ("Traditional Quranic", "dua", "Hasbunallahu Wa Ni'mal Wakeel",
     "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ", "نِعْمَ الْمَوْلَىٰ وَنِعْمَ النَّصِيرُ",
     "Hasbunallahu wa ni'mal wakeel, Ni'mal mawla wa ni'man-naseer",
     "Sufficient for us is Allah, and He is the best Disposer of affairs; the best Protector and the best Helper."),
    ("Traditional Quranic", "dua", "Rabbi Inni Lima Anzalta Ilayya Min Khairin Faqeer",
     "رَبِّ إِنِّي لِمَا أَنزَلْتَ إِلَيَّ مِنْ خَيْرٍ فَقِيرٌ", "اللهم افتح لنا أبواب رحمتك وفضلك",
     "Rabbi innee limaa anzalta ilayya min khairin faqeer, Allahumma-ftah lanaa abwaaba rahmatik",
     "My Lord, indeed I am in desperate need of whatever good You would send down to me. O Allah, open for us the gates of Your mercy."),
    ("Allama Iqbal", "dua", "Lab Pe Aati Hai Dua Ban Ke Tamanna Meri",
     "لب پہ آتی ہے دعا بن کے تمنا میری", "زندگی شمع کی صورت ہو خدایا میری",
     "Lab pe aati hai dua ban ke tamanna meri, Zindagi shama ki soorat ho Khudaya meri",
     "My longing rises to my lips as a prayer: May my life be like a radiant candle, O Lord!"),
    ("Allama Iqbal", "dua", "Door Duniya Ka Mere Dam Se Andhera Ho Jaaye",
     "دور دنیا کا مرے دم سے اندھیرا ہو جائے", "ہر جگہ میرے چمکنے سے اجالا ہو جائے",
     "Door duniya ka mere dam se andhera ho jaaye, Har jagah mere chamakne se ujaala ho jaaye",
     "May the world's darkness flee through my presence; may radiance and illumination blossom wherever I shine."),
    ("Allama Iqbal", "dua", "Ho Mere Dam Se Yoonhi Mere Watan Ki Zeenat",
     "ہو مرے دم سے یونہی میرے وطن کی زینت", "جس طرح پھول سے ہوتی ہے چمن کی زینت",
     "Ho mere dam se yoonhi mere watan ki zeenat, Jis tarah phool se hoti hai chaman ki zeenat",
     "May my homeland gain splendor through my humble deeds, just as the blooming flower adorns the garden."),
    ("Allama Iqbal", "dua", "Zindagi Ho Meri Parwaane Ki Soorat Ya Rab",
     "زندگی ہو مری پروانے کی صورت یا رب", "علم کی شمع سے ہو مجھ کو محبت یا رب",
     "Zindagi ho meri parwaane ki soorat ya Rabb, Ilm ki shama se ho mujh ko mohabbat ya Rabb",
     "May my life be like that of the ardent moth, O Lord; may my heart burn with sacred love for the candle of knowledge."),
    ("Allama Iqbal", "dua", "Ho Mera Kaam Ghareebon Ki Himaayat Karna",
     "ہو مرا کام غریبوں کی حمایت کرنا", "دردمندوں سے ضعیفوں سے محبت کرنا",
     "Ho mera kaam ghareebon ki himaayat karna, Dardmandon se za'eefon se mohabbat karna",
     "May my sacred calling be to support the destitute; to love the broken-hearted and the vulnerable."),
    ("Allama Iqbal", "dua", "Mere Allah Buraai Se Bachaana Mujh Ko",
     "مرے اللہ برائی سے بچانا مجھ کو", "نیک جو راہ ہو اس رہ پہ چلانا مجھ کو",
     "Mere Allah buraai se bachaana mujh ko, Naik jo raah ho uss reh pe chalaana mujh ko",
     "My Lord, preserve me from all malice and vice; and guide my footsteps steadily along the righteous path."),
    ("Allama Iqbal", "dua", "Ya Rabb Dil-e-Muslim Ko Woh Zinda Tamanna De",
     "یا رب دلِ مسلم کو وہ زندہ تمنا دے", "جو روح کو تڑپا دے جو قلب کو گرما دے",
     "Ya Rabb dil-e-Muslim ko woh zinda tamanna de, Jo rooh ko tadpa de jo qalb ko garma de",
     "O Lord, bestow upon the heart a living, burning yearning that stirs the soul and warms the spirit with divine fire."),
    ("Allama Iqbal", "dua", "Baseerat De Mere Deeda-e-Beena Ko Woh",
     "بصیرت دے مرے دیدۂ بینا کو وہ", "جو تاریک راتوں کو بھی روشن بنا دے",
     "Baseerat de mere deeda-e-beena ko woh, Jo tareek raaton ko bhi roshan bana de",
     "Bestow upon my inner eye that profound vision which transforms even darkest midnight into a radiant dawn."),
    ("Traditional Dua", "dua", "Rabb-e-Kareem Ataa Farmaaye Sehat o Aafiyat",
     "ربِ کریم عطا فرمائے صحت و عافیت", "اور ہر قدم پہ نصیب ہوں رحمتیں بے شمار",
     "Rabb-e-Kareem ataa farmaaye sehat o aafiyat, Aur har qadam pe naseeb hon rehmatein beshumaar",
     "May the Most Merciful Lord grant radiant health, peaceful serenity, and boundless divine blessings at every step."),
    ("Traditional Dua", "dua", "Ya Rabb Ataa Farma Har Qadam Pe Salaamati",
     "یا رب عطا فرما ہر قدم پہ سلامتی", "اور بخش دے قلب و روح کو عافیت و پاکیزگی",
     "Ya Rabb ataa farma har qadam pe salaamati, Aur bakhsh de qalb-o-rooh ko aafiyat o paakeezgi",
     "O Lord, grant peace and safety at every step, and bestow upon heart and soul serene wellness and divine purity."),
    ("Traditional Dua", "dua", "Ghar Aangan Mein Barse Sada Rehmat Ka Meenh",
     "گھر آنگن میں برسے سدا رحمت کا مینہ", "دل میں رہے سدا ایمان کا قرینہ",
     "Ghar aangan mein barse sada rehmat ka meenh, Dil mein rahe sada eeman ka qareena",
     "May the shower of divine grace forever rain upon your home, and the peace of faith continuously inhabit your heart."),
    ("Traditional Dua", "dua", "Khuda Har Bala Se Mehfooz Rakhe Tumhein",
     "خدا ہر بلا سے محفوظ رکھے تمہیں", "ہر شر سے بچا کر اپنی امان میں رکھے",
     "Khuda har bala se mehfooz rakhay tumhein, Har shar se bacha kar apni amaan mein rakhay",
     "May God shield and preserve you from every calamity, protecting you from harm within His divine sanctuary."),
    ("Traditional Dua", "dua", "Maa Baap Ki Duaon Ka Saaya Rahe Sada",
     "ماں باپ کی دعاؤں کا سایہ رہے سدا", "زندگی کے ہر موڑ پہ ان کا پیار ملے",
     "Maa baap ki duaon ka saaya rahe sada, Zindagi ke har morr pe unka pyaar milay",
     "May the sheltering shade of parents' heartfelt prayers remain forever upon you; may their love guide you at every turning."),
    ("Traditional Dua", "dua", "Rizq-e-Halaal Mein Ho Barkat-e-Farawan",
     "رزقِ حلال میں ہو برکتِ فراواں", "آسان ہو زندگی کا ہر اک امتحاں",
     "Rizq-e-halaal mein ho barkat-e-faraawaan, Aasaan ho zindagi ka har ik imtihaan",
     "May there be abundant barakah in honest, lawful sustenance; may every arduous trial of life be made easy."),

    # ==========================================
    # WISDOM & LIFE (50 strictly unique verses)
    # ==========================================
    ("Saadi Shirazi", "wisdom", "Bani Adam A'zaye Yekdigarand",
     "بنی آدم اعضائے یکدیگرند", "کہ در آفرینش ز یک گوہرند",
     "Bani Aadam a'zaaye yekdigarand, Ke dar aafreenash ze yak gauharand",
     "Human beings are members of one body, having been created from one essential soul in origin."),
    ("Saadi Shirazi", "wisdom", "Cho Ozw-e-Be-Dard Aawarad Roozgaar",
     "چو عضوی بدرد آورد روزگار", "دگر عضوہا را نماند قرار",
     "Cho ozwe ba-dard aawarad roozgaar, Degar ozwhaa ra namaanad qaraar",
     "When the world strikes one limb with suffering, no other limb can remain untroubled or at ease."),
    ("Saadi Shirazi", "wisdom", "Tan-e-Aadmi Shareef Ast Ba Jaan-e-Aadamiyat",
     "تنِ آدمی شریف است بہ جانِ آدمیت", "نہ ہمان لباسِ زیباست نشانِ آدمیت",
     "Tan-e-aadmi shareef ast ba jaan-e-aadamiyat, Na hamaan libaas-e-zebaast nishaan-e-aadamiyat",
     "The noble dignity of humanity resides in the soul of compassion; fine attire is by no means the measure of a human being."),
    ("Saadi Shirazi", "wisdom", "Sabr Talkh Ast Wa-Leikan Bar-e-Sheereen Daard",
     "صبر تلخ است ولیکن برِ شیرین دارد", "ہر کہ بر رنج کشید عاقبت راحت یافت",
     "Sabr talkh ast wa-leikan bar-e-sheereen daard, Har ke bar ranj kasheed aaqibat raahat yaaft",
     "Patience tastes bitter in the throat, yet bears sweetest fruit; whoever endures difficulty with dignity ultimately finds true serenity."),
    ("Mian Muhammad Bakhsh", "wisdom", "Dushman Mare Te Khushi Na Kariye",
     "دشمن مرے تے خوشی نہ کریئے سجݨ وی ٹر جانا", "دُھپاں دے پچھے چھانواں آوندیاں، سدا نہ رہندا ہانا",
     "Dushman maray te khushi na kariye sajjan vi tur jaana, Dhuppaan de pichhay chhaanwaan aawandiyan, sada na rehnda haana",
     "Rejoice not at the demise of an adversary, for dear friends too must depart; after burning sun comes shade, no worldly condition is permanent."),
    ("Mian Muhammad Bakhsh", "wisdom", "Raah Pawe Te Raahi Jaaniye",
     "راہ پاوے تے راہی جانیئے سر پاوے تے بھار", "محنت دی کمائی وچ برکت، جھوٹھے دا نہ اعتبار",
     "Raah paaway te raahi jaaniye sir paaway te bhaar, Mehnat di kamaayi vich barkat, jhootay da na aitbaar",
     "A true traveler is known when hardships strike the road; honest toil bears divine blessing, while the deceitful possess no worth."),
    ("Mian Muhammad Bakhsh", "wisdom", "Aukhe Wele Kaam Jo Aawe",
     "اوکھے ویلے کم جو آوے اوہی سچا یار", "لوڑ ویلے جو مکھ موڑے اوہ پتھر دی دیوار",
     "Aukhay welay kaam jo aaway ohi sacha yaar, Lorr welay jo mukh moday oh patthar di deewaar",
     "The one who stands firm in your hour of hardship is your true friend; the one who turns his face away in need is but a stone wall."),
    ("Mian Muhammad Bakhsh", "wisdom", "Maal Dhan Sab Aithe Rehna",
     "مال دھن سب ایتھے رہنا اک نیکی رہ جانی", "رب دے رستے خرچ جو کیتا اوہ دولت لافانی",
     "Maal dhan sab aithay rehna ik naiki reh jaani, Rabb de rastay kharch jo keeta oh daulat laa-faani",
     "All worldly wealth and possessions remain behind in the dust; only sincere goodness endures, an immortal treasure spent in God’s way."),
    ("Mian Muhammad Bakhsh", "wisdom", "Sada Na Baaghin Bulbul Bole",
     "سدا نہ باغیں بلبل بولے سدا نہ باغ بہاراں", "سدا نہ ماپے حسن جوانی سدا نہ صحبت یاراں",
     "Sada na baaghin bulbul bolay sada na baagh bahaaraan, Sada na maapay husn jawaani sada na sohbat yaaraan",
     "Not forever does the nightingale sing, nor does spring linger eternal; cherish the fleeting present with wisdom, humility, and grace."),
    ("Omar Khayyam", "wisdom", "The Moving Finger Writes And Having Writ Moves On",
     "The Moving Finger writes; and, having writ,", "Moves on: nor all thy Piety nor Wit Shall lure it back to cancel half a Line.",
     "The Moving Finger writes; and, having writ, Moves on...",
     "The Moving Finger of Destiny writes, and having written, moves onward; neither your tears nor your cleverness can erase a single syllable."),
    ("Omar Khayyam", "wisdom", "Be Happy For This Moment This Moment Is Your Life",
     "Be happy for this moment.", "This moment is your life.",
     "Be happy for this moment. This moment is your life.",
     "Find contentment in the living present; for this fleeting breath right now is your true life."),
    ("Mirza Ghalib", "wisdom", "Bas Ke Dushwaar Hai Har Kaam Ka Aasaan Hona",
     "بس کہ دشوار ہے ہر کام کا آساں ہونا", "آدمی کو بھی میسر نہیں انساں ہونا",
     "Bas ke dushwaar hai har kaam ka aasaan hona, Aadmi ko bhi mayassar nahi insaan hona",
     "So arduous is it for any noble enterprise to be easy; even mortal man finds it difficult to truly attain genuine humanity."),
    ("Allama Iqbal", "wisdom", "Acha Hai Dil Ke Saath Rahe Pasban-e-Aql",
     "اچھا ہے دل کے ساتھ رہے پاسبانِ عقل", "لیکن کبھی کبھی اسے تنہا بھی چھوڑ دے",
     "Acha hai dil ke saath rahe paasban-e-aql, Lekin kabhi kabhi usey tanha bhi chhor de",
     "It is wise for intellect to keep guard over the heart; yet at times, let the heart wander free in its own divine intuition."),
    ("Allama Iqbal", "wisdom", "Duniya Hai Rawaan Dawaan Har Shay Hai Safar Mein",
     "دنیا ہے رواں دواں ہر شے ہے سفر میں", "ثبات اک تغیر کو ہے زمانے میں",
     "Duniya hai rawaan dawaan har shai hai safar mein, Sabaat ik taghayyur ko hai zamaane mein",
     "The world is in ceaseless flow, every atom is on a journey; change alone is the permanent law of existence."),
    ("Traditional Hikmat", "wisdom", "Waqt Ki Qeemat Ko Pehchaano Ke Yeh Anmol Hai",
     "وقت کی قیمت کو پہچانو کہ یہ انمول ہے", "ہر گزرتا پل نئی حکمت کا اک پیغام ہے",
     "Waqt ki qeemat ko pehchaano ke yeh anmol hai, Har guzarta pal nayi hikmat ka ik paighaam hai",
     "Treasure the true worth of time, for it is priceless; each passing moment delivers a profound lesson of wisdom."),
    ("Traditional Hikmat", "wisdom", "Sabr Ki Manzil Pe Jaa Kar Milta Hai Sukoon",
     "صبر کی منزل پہ جا کر ملتا ہے سکون", "ہر تلخ گھڑی کے بعد آتا ہے جنون",
     "Sabr ki manzil pe jaa kar milta hai sukoon, Har talkh ghari ke baad aata hai junoon",
     "Upon reaching the sanctuary of patience, enduring serenity is found; after every bitter trial, victorious triumph unfolds."),
    ("Traditional Hikmat", "wisdom", "Khamoshi Mein Bhi Ik Sada-e-Haq Hai",
     "خاموشی میں بھی اک صدائے حق ہے", "جو سن سکے اس کے لیے روشن ورق ہے",
     "Khamoshi mein bhi ik sada-e-haq hai, Jo sun sakay uss ke liye roshan waraq hai",
     "Even in silent stillness, the Voice of Truth echoes; for whoever listens with the soul, each moment is an illuminated page."),

    # ==========================================
    # GHAM & MELANCHOLY (50 strictly unique verses)
    # ==========================================
    ("Muneer Niazi", "gham", "Hamesha Der Kar Deta Hoon Main Har Kaam Karne Mein",
     "ہمیشہ دیر کر دیتا ہوں میں ہر کام کرنے میں", "ضروری بات کہنی ہو کوئی وعدہ نبھانا ہو",
     "Hamesha der kar deta hoon main har kaam karne mein, Zaroori baat kehni ho koi waada nibhaana ho",
     "I always end up arriving too late in everything I do; whether to speak a crucial word, or to honor a tender promise."),
    ("Muneer Niazi", "gham", "Kujh Shehar De Log Vi Zaalim San",
     "کج شہر دے لوک وی ظالم سن، کج سانوں مرن دا شوق وی سی", "اک ہور دریا دا سامنا سی منیرؔ مینوں، اک پار کیتا تاں ویکھیا میں",
     "Kujh shehar de log vi zaalim san, kujh saanoon maran da shauq vi si, Ik hor darya da saamna si Muneer mainoon",
     "Partly the townspeople were callous, partly we ourselves courted self-destruction; when I crossed one river, Muneer, another ocean awaited."),
    ("Muneer Niazi", "gham", "Subh-e-Kaazib Ki Hawa Mein Dard Tha",
     "صبحِ کاذب کی ہوا میں درد تھا", "چھپ گیا تارا کوئی خاموش سا",
     "Subh-e-kaazib ki hawa mein dard tha, Chhup gaya taara koi khamosh sa",
     "In the cold breeze of the false dawn lived a tender ache; a quiet, solitary star concealed itself behind gray clouds."),
    ("Mohsin Naqvi", "gham", "Zindagi Ke Mele Mein Tanha Chhod Gaye",
     "زندگی کے میلے میں تنہا چھوڑ گئے", "وہ جن پر مان تھا وہ دامن جھٹک گئے",
     "Zindagi ke mele mein tanha chhod gaye, Woh jin par maan tha woh daaman jhatak gaye",
     "In the crowded carnival of life they left me alone; the very ones I took pride in brushed away my reaching hand."),
    ("Mohsin Naqvi", "gham", "Gham Ne Bakhshi Hai Mujhe Shaan-e-Dilaweez",
     "غم نے بخشی ہے مجھے شانِ دلاویز", "ورنہ ہم بھی تھے زمانے کے تماشائی",
     "Gham ne bakhshi hai mujhe shaan-e-dil-aawez, Warna hum bhi thay zamaane ke tamaashaayi",
     "Grief has bestowed upon me an enchanting dignity; otherwise I too was merely a casual spectator of the world."),
    ("Nasir Kazmi", "gham", "Hum To Baithe Hain Shab-e-Hijr Ke Maare Hue",
     "ہم تو بیٹھے ہیں شبِ ہجر کے مارے ہوئے", "دیکھتے ہیں کہ سحر ہوتی ہے کب تک",
     "Hum to baithe hain shab-e-hijr ke maare hue, Dekhte hain ke sehar hoti hai kab tak",
     "We sit afflicted by the long night of parting, watching patiently to see when the morning light will finally break."),
    ("Jaun Elia", "gham", "Shayad Mujhe Kisi Se Mohabbat Nahi Hui",
     "شاید مجھے کسی سے محبت نہیں ہوئی", "لیکن یقین سب کو دلاتا رہا ہوں میں",
     "Shayad mujhe kisi se mohabbat nahi hui, Lekin yaqeen sab ko dilaata raha hoon main",
     "Perhaps I never truly fell in love with anyone; yet I spent my life reassuring everyone that I did."),
    ("Mir Taqi Mir", "gham", "Dil Woh Nagar Nahi Ke Phir Aabaad Ho Sake",
     "دل وہ نگر نہیں کہ پھر آباد ہو سکے", "پچھتاؤ گے سنو ہو یہ بستی اجاڑ کے",
     "Dil woh nagar nahi ke phir aabaad ho sakay, Pachhtaaoge suno ho yeh basti ujaad ke",
     "The heart is not a city that can easily be rebuilt; you will regret it, hear me, after laying waste to this settlement."),
    ("Traditional Gham", "gham", "Dil Ke Nihaan Khanon Mein Ik Dard Chhupa Hua",
     "دل کے نہاں خانوں میں اک درد ہے چھپا ہوا", "خاموشیوں میں بھی اک نغمہ ہے گونجتا ہوا",
     "Dil ke nihaan khanon mein ik dard hai chhupa hua, Khamoshiyon mein bhi ik naghma hai goonjta hua",
     "In the quiet chambers of the soul lies a tender ache; even in stillness, a gentle melody echoes with emotion."),
    ("Traditional Gham", "gham", "Khamoshiyon Ne Raaz Bataaye Hain Kayi",
     "خاموشیوں نے راز بتائے ہیں کئی", "آنسوؤں نے چراغ جلائے ہیں کئی",
     "Khamoshiyon ne raaz bataaye hain kayi, Aansoo-on ne chiragh jalaaye hain kayi",
     "Silence has whispered many profound secrets; tears in the dark have kindled many guiding lamps.")
]

print(f"DUA_WISDOM_GHAM_VERSES loaded: {len(DUA_WISDOM_GHAM_VERSES)} items.")
