# -*- coding: utf-8 -*-
"""
Verses for Ishq (155) & Wedding (107) = 262 strictly unique tuples
Format: (poet, cat, title, m1, m2, rom, eng)
"""

ISHQ_WEDDING_VERSES = [
    # ==========================================
    # ISHQ & ROMANCE (155 strictly unique verses)
    # ==========================================
    # --- Faiz Ahmad Faiz ---
    ("Faiz Ahmad Faiz", "ishq", "Aap Ki Yaad Aati Rahi Raat Bhar",
     "آپ کی یاد آتی رہی رات بھر", "چشمِ نم مسکراتی رہی رات بھر",
     "Aap ki yaad aati rahi raat bhar, Chashm-e-nam muskurati rahi raat bhar",
     "Your tender memory visited me all through the night; and through tear-misted eyes, a gentle smile blossomed till dawn."),
    ("Faiz Ahmad Faiz", "ishq", "Maqaam Faiz Koi Raah Mein Jacha Hi Nahi",
     "مقام فیضؔ کوئی راہ میں جچا ہی نہیں", "جو کوئے یار سے نکلے تو سوئے دار چلے",
     "Maqaam Faiz koi raah mein jacha hi nahi, Jo koo-e-yaar se nikle to soo-e-daar chale",
     "No resting place pleased me on the journey, Faiz; when I departed the lane of the Beloved, I marched straight to the gallows."),
    ("Faiz Ahmad Faiz", "ishq", "Na Ganwao Naawak-e-Neem Kash Dil-e-Reza Reza",
     "نہ گنواؤ ناوکِ نیم کش دلِ ریزہ ریزہ گنوا دیا", "جو بچے ہیں سنگ سمیٹ لو تنِ داغ داغ لٹا دیا",
     "Na ganwao naawak-e-neem kash dil-e-reza reza ganwa diya, Jo bachay hain sang samait lo tann-e-daagh daagh luta diya",
     "Waste not your half-drawn arrows; my heart is already shattered to dust. Gather your stones; my scarred frame is completely surrendered."),
    ("Faiz Ahmad Faiz", "ishq", "Dono Jahan Teri Mohabbat Mein Haar Ke",
     "دونوں جہان تیری محبت میں ہار کے", "وہ جا رہا ہے کوئی شبِ غم گزار کے",
     "Dono jahan teri mohabbat mein haar ke, Woh jaa raha hai koi shab-e-gham guzaar ke",
     "Having surrendered both worlds in your devotion, the weary soul departs after enduring the solitary night of sorrow."),
    ("Faiz Ahmad Faiz", "ishq", "Chand Roz Aur Meri Jaan Faqat Chand Hi Roz",
     "چند روز اور مری جان فقط چند ہی روز", "ظلم کی چھاؤں میں دم لینے پہ مجبور ہیں ہم",
     "Chand roz aur meri jaan faqat chand hi roz, Zulm ki chhaon mein dam lene pe majboor hain hum",
     "Only a few days more, my beloved, only a few days more; we are compelled to breathe beneath tyranny’s shade for just a fleeting hour."),
    ("Faiz Ahmad Faiz", "ishq", "Dil Na-Umeed To Nahi Nakaam Hi To Hai",
     "دل نا امید تو نہیں ناکام ہی تو ہے", "لمبی ہے غم کی شام مگر شام ہی تو ہے",
     "Dil na-umeed to nahi nakaam hi to hai, Lambi hai gham ki shaam magar shaam hi to hai",
     "The heart is not without hope, it is merely unfulfilled; long though the evening of sorrow may be, it is only an evening after all."),
    ("Faiz Ahmad Faiz", "ishq", "Kaho Kaj Jabeen Pe Sar-e-Kafan Mere Qatilon Ko",
     "کرو کج جبیں پہ سرِ کفن مرے قاتلوں کو گماں نہ ہو", "کہ غرورِ عشق کا بانکپن پسِ مرگ ہم نے بھلا دیا",
     "Karo kaj jabeen pe sar-e-kafan mere qatilon ko gumaan na ho, Ke ghuroor-e-ishq ka baankpan pas-e-marg hum ne bhula diya",
     "Tilt the shroud with jaunty pride upon my brow, lest my slayers imagine that in death I forgot the magnificent swagger of love."),
    ("Faiz Ahmad Faiz", "ishq", "Raat Yoon Dil Mein Teri Khoi Hui Yaad Aayi",
     "رات یوں دل میں تری کھوئی ہوئی یاد آئی", "جیسے ویرانے میں آہستہ سے بہار آ جائے",
     "Raat yoon dil mein teri khoi hui yaad aayi, Jaise veerane mein aahista se bahaar aa jaaye",
     "Last night your forgotten memory stepped softly into my soul, just as spring gently arrives unannounced in a desolate desert."),
    ("Faiz Ahmad Faiz", "ishq", "Jis Dhaj Se Koi Maqtal Mein Gaya Woh Shaan",
     "جس دھج سے کوئی مقتل میں گیا وہ شان سلامت رہتی ہے", "یہ جان تو آنی جانی ہے اس جاں کی تو کوئی بات نہیں",
     "Jis dhaj se koi maqtal mein gaya woh shaan salamat rehti hai, Yeh jaan to aani jaani hai iss jaan ki to koi baat nahi",
     "The regal grace with which one walked to the sacrifice endures forever; for life is fleeting, its passing is of little consequence."),
    ("Faiz Ahmad Faiz", "ishq", "Rang Pairahan Ka Khushboo Zulf Lehraane Ka Naam",
     "رنگ پیراہن کا، خوشبو زلف لہرانے کا نام", "موسمِ گل ہے تمہارے بام پر آنے کا نام",
     "Rang pairahan ka, khushboo zulf lehraane ka naam, Mausam-e-gul hai tumhaare baam par aane ka naam",
     "The color of your dress, the fragrance of your swaying hair—the very season of spring is named after your arrival upon the terrace."),
    ("Faiz Ahmad Faiz", "ishq", "Aaj Shab Koi Nahi Hai To Mere Paas Raho",
     "آج شب کوئی نہیں ہے تو مرے پاس رہو", "شام سے گہری اداسی کا گماں رہتا ہے",
     "Aaj shab koi nahi hai to mere paas raho, Shaam se gehri udaasi ka gumaan rehta hai",
     "Tonight, when no one else is near, remain beside me; for since dusk, a deep poignant melancholy has settled over my heart."),
    ("Faiz Ahmad Faiz", "ishq", "Sitam Sikhaayega Rasm-e-Wafa Tumhein Bhi Kabhi",
     "ستم سکھائے گا رسمِ وفا تمہیں بھی کبھی", "خلوصِ دل کی جو قیمت ادا کرو گے تم",
     "Sitam sikhaayega rasm-e-wafa tumhein bhi kabhi, Khaloos-e-dil ki jo qeemat ada karoge tum",
     "Cruel trials shall teach you the sacred rituals of loyalty in time, whenever you pay the true price of sincere devotion."),
    ("Faiz Ahmad Faiz", "ishq", "Tere Rukhsaar Ki Taabaniyon Ka Sadqa Hai",
     "ترے رخسار کی تابانیوں کا صدقہ ہے", "کہ ہر اک صبح نئی روشنی لٹاتی ہے",
     "Tere rukhsaar ki taabaniyon ka sadqa hai, Ke har ik subh nayi roshni lutaati hai",
     "It is an offering from the radiant brilliance of your cheeks that every dawn scatters fresh sunlight across the world."),
    ("Faiz Ahmad Faiz", "ishq", "Hum Par Tumhari Deed Ki Hasrat Sada Rahi",
     "ہم پر تمہاری دید کی حسرت سدا رہی", "تصویر بن کے دل میں تمہارا پیام ہے",
     "Hum par tumhari deed ki hasrat sada rahi, Tasveer ban ke dil mein tumhara payaam hai",
     "The longing to behold your face remained eternal within us; framed like a portrait, your sweet message abides in my heart."),
    ("Faiz Ahmad Faiz", "ishq", "Tere Baghair Hai Veeran Anjuman Dil Ki",
     "ترے بغیر ہے ویران انجمن دل کی", "چراغ جلتے ہیں لیکن ضیا نہیں ہوتی",
     "Tere baghair hai veeraan anjuman dil ki, Chiragh jaltay hain lekin ziya nahi hoti",
     "Without you, the gathering of my soul is desolate; lamps burn in plenty, yet warmth and luminescence are missing."),
    ("Faiz Ahmad Faiz", "ishq", "Tere Firaaq Mein Jeene Ka Dhang Seekh Liya",
     "ترے فراق میں جینے کا ڈھنگ سیکھ لیا", "خموش رہ کے زمانے کے رنگ دیکھ لیے",
     "Tere firaaq mein jeene ka dhang seekh liya, Khamosh reh ke zamaane ke rang dekh liye",
     "In separation from you I learned how to endure; remaining silent, I watched the changing colors of this passing world."),
    ("Faiz Ahmad Faiz", "ishq", "Tere Karam Ki Nawazaish Hai Meri Ghazlon Mein",
     "ترے کرم کی نوازش ہے میری غزلوں میں", "سخن وری کو ترا نام ہی سجاتا ہے",
     "Tere karam ki nawazish hai meri ghazlon mein, Sukhan-wari ko tera naam hi sajaata hai",
     "The tender grace of your favor illuminates all my verses; your sacred name alone adorns the art of my poetry."),
    ("Faiz Ahmad Faiz", "ishq", "Wafa Ki Raah Mein Jo Bhi Qadam Uthaya Hai",
     "وفا کی راہ میں جو بھی قدم اٹھایا ہے", "تمہاری یاد کا اک نقش چھوڑ آیا ہے",
     "Wafa ki raah mein jo bhi qadam uthaya hai, Tumhari yaad ka ik naqsh chhor aaya hai",
     "Every step I took upon the path of faithfulness left an indelible imprint of your cherished memory behind."),
    ("Faiz Ahmad Faiz", "ishq", "Mohabbaton Ke Safar Mein Thakan Nahi Hoti",
     "محبتوں کے سفر میں تھکن نہیں ہوتی", "جو ساتھ چلتے ہیں منزل انہی کو ملتی ہے",
     "Mohabbaton ke safar mein thakan nahi hoti, Jo saath chaltay hain manzil unhi ko milti hai",
     "Along the voyage of sincere love, weariness never enters; those who walk hand in hand together always attain the destination."),
    ("Faiz Ahmad Faiz", "ishq", "Teri Nazar Jo Uthi Zindagi Darakhshan Ho Gayi",
     "تیری نظر جو اٹھی زندگی درخشاں ہو گئی", "غموں کی رات کا ہر موڑ سحر بن گیا",
     "Teri nazar jo uthi zindagi darakhshaan ho gayi, Ghamon ki raat ka har morr sehar ban gaya",
     "When your eyes lifted, all of life turned luminous; and every turning of sorrow's dark night became a radiant dawn."),

    # --- Ahmad Faraz ---
    ("Ahmad Faraz", "ishq", "Ranjish Hi Sahi Dil Hi Dukhane Ke Liye Aa",
     "رنجش ہی سہی دل ہی دکھانے کے لیے آ", "آ پھر سے مجھے چھوڑ کے جانے کے لیے آ",
     "Ranjish hi sahi dil hi dukhaane ke liye aa, Aa phir se mujhe chhor ke jaane ke liye aa",
     "Even if with grievance, come only to grieve my heart; come, if only to leave me and depart once again."),
    ("Ahmad Faraz", "ishq", "Suna Hai Log Usey Aankh Bhar Ke Dekhte Hain",
     "سنا ہے لوگ اسے آنکھ بھر کے دیکھتے ہیں", "سو اس کے شہر میں کچھ دن ٹھہر کے دیکھتے ہیں",
     "Suna hai log usey aankh bhar ke dekhte hain, So uss ke shehar mein kuch din thehar ke dekhte hain",
     "I have heard that people gaze upon her with wonder; so let us linger for a few days in her city to see for ourselves."),
    ("Ahmad Faraz", "ishq", "Suna Hai Bole To Baaton Se Phool Jhadte Hain",
     "سنا ہے بولے تو باتوں سے پھول جھڑتے ہیں", "یہ بات ہے تو چلو بات کر کے دیکھتے ہیں",
     "Suna hai bole to baaton se phool jhadte hain, Yeh baat hai to chalo baat kar ke dekhte hain",
     "I have heard that when she speaks, blossoms shower from her words; if this is true, let us speak to her and see."),
    ("Ahmad Faraz", "ishq", "Ab Ke Hum Bichhde To Shayad Kabhi Khwabon Mein Milein",
     "اب کے ہم بچھڑے تو شاید کبھی خوابوں میں ملیں", "جس طرح سوکھے ہوئے پھول کتابوں میں ملیں",
     "Ab ke hum bichhde to shayad kabhi khwaabon mein milein, Jis tarah sookhe hue phool kitaabon mein milein",
     "If we part now, perhaps we shall meet only in fleeting dreams, like pressed dried flowers discovered inside forgotten books."),
    ("Ahmad Faraz", "ishq", "Tu Mohabbat Se Koi Chaal To Chal",
     "تو محبت سے کوئی چال تو چل", "ہار جانے کا ہنر جانتے ہیں ہم",
     "Tu mohabbat se koi chaal to chal, Haar jaane ka hunar jaante hain hum",
     "Make but a tender move in this game of love; for we possess the exquisite art of willingly losing to you."),
    ("Ahmad Faraz", "ishq", "Silsile Tod Gaya Woh Sabhi Jaate Jaate",
     "سلسلے توڑ گیا وہ سبھی جاتے جاتے", "ورنہ اتنے تو مراسم تھے کہ آتے جاتے",
     "Silsile tod gaya woh sabhi jaate jaate, Warna itne to maraasim thay ke aate jaate",
     "He severed all ties upon his departure; otherwise there remained enough courtesy between us that we might still cross paths."),
    ("Ahmad Faraz", "ishq", "Aankh Se Door Na Ho Dil Se Utar Jaayega",
     "آنکھ سے دور نہ ہو دل سے اتر جائے گا", "وقت کا کیا ہے گزرتا ہے گزر جائے گا",
     "Aankh se door na ho dil se utar jaayega, Waqt ka kya hai guzarta hai guzar jaayega",
     "Stay not far from my gaze lest you slip from the heart; as for time, it always passes and will surely pass away."),
    ("Ahmad Faraz", "ishq", "Tere Hote Hue Mehfil Mein Jalaate Hain Chiragh",
     "تیرے ہوتے ہوئے محفل میں جلاتے ہیں چراغ", "لوگ کیا سادہ ہیں سورج کو دکھاتے ہیں چراغ",
     "Tere hote hue mehfil mein jalaate hain chiragh, Log kya saada hain sooraj ko dikhaate hain chiragh",
     "In your radiant presence they kindle lamps in the hall; how naive people are, holding up candles to the blazing sun!"),
    ("Ahmad Faraz", "ishq", "Dost Ban Kar Bhi Nahi Saath Nibhaane Waala",
     "دوست بن کر بھی نہیں ساتھ نبھانے والا", "وہی انداز ہے ظالم کا زمانے والا",
     "Dost ban kar bhi nahi saath nibhaane waala, Wohi andaaz hai zaalim ka zamaane waala",
     "Even posing as a friend, he does not stand faithfully by; the cruel beloved retains the callous ways of this fickle world."),
    ("Ahmad Faraz", "ishq", "Kis Se Kahein Ke Jaan Ki Baazi Laga Chuke",
     "کس سے کہیں کہ جان کی بازی لگا چکے", "اور ہار کے بھی اپنے تئیں جیتنا پڑے",
     "Kis se kahein ke jaan ki baazi laga chukay, Aur haar ke bhi apne taeen jeetna pade",
     "To whom can I confess that I wagered life itself, and having lost, must still pretend triumph to my own soul?"),
    ("Ahmad Faraz", "ishq", "Ik Tamanna Thi Ke Tujh Se Bhi Wafa Paayenge",
     "اک تمنا تھی کہ تجھ سے بھی وفا پائیں گے", "تو بھی نکلے گا وہی زخم لگانے والا",
     "Ik tamanna thi ke tujh se bhi wafa paayenge, Tu bhi niklega wohi zakhm lagaane waala",
     "A fond yearning lived in me that I would find loyalty with you; yet you too proved to be one who inflicts painful wounds."),
    ("Ahmad Faraz", "ishq", "Teri Qurbat Ke Lamhon Mein Jo Sukoon Mila",
     "تیری قربت کے لمحوں میں جو سکون ملا", "وہ کسی اور ٹھکانے پہ میسر نہ ہوا",
     "Teri qurbat ke lamhon mein jo sukoon mila, Woh kisi aur thikaane pe mayassar na hua",
     "The serenity discovered in the fleeting moments of your presence was never attained in any other sanctuary on earth."),
    ("Ahmad Faraz", "ishq", "Teri Baaton Mein Jo Ulfat Ka Tarannum Tha",
     "تیری باتوں میں جو الفت کا ترنم تھا کبھی", "آج بھی دل کی سماعت میں بسا رہتا ہے",
     "Teri baaton mein jo ulfat ka tarannum tha kabhi, Aaj bhi dil ki sama'at mein basa rehta hai",
     "The melodic rhythm of love that once graced your voice still echoes continuously within the quiet hearing of my heart."),
    ("Ahmad Faraz", "ishq", "Hum Ne Maana Ke Mohabbat Hai Ik Imtihaan",
     "ہم نے مانا کہ محبت ہے اک امتحان کٹھن", "پر تری راہ میں ہم سر کو جھکائے نکلے",
     "Hum ne maana ke mohabbat hai ik imtihaan kathin, Par teri raah mein hum sar ko jhukaaye nikle",
     "We acknowledged that love is an arduous trial; yet upon your chosen path we embarked with bowed and devoted heads."),
    ("Ahmad Faraz", "ishq", "Teri Nazrein Jo Mileen Dil Ko Nayi Jaan Mili",
     "تیری نظریں جو ملیں دل کو نئی جان ملی", "زندگی تیرے تبسم سے گلستان بنی",
     "Teri nazrein jo mileen dil ko nayi jaan mili, Zindagi tere tabassum se gulistan bani",
     "When your eyes met mine, a fresh soul entered my chest; and all of life turned into an aromatic rose garden from your smile."),
    ("Ahmad Faraz", "ishq", "Tu Agar Saamne Ho To Koi Hasrat Na Rahe",
     "تو اگر سامنے ہو تو کوئی حسرت نہ رہے", "ہر تمنا تیری چاہت میں سمٹ جاتی ہے",
     "Tu agar saamne ho to koi hasrat na rahe, Har tamanna teri chaahat mein simat jaati hai",
     "If only you stand before me, no longing remains unfulfilled; every worldly desire condenses into your tender love."),
    ("Ahmad Faraz", "ishq", "Wafa Ke Naam Pe Qurbaan Kar Diya Sab Kuch",
     "وفا کے نام پہ قربان کر دیا سب کچھ", "مگر وہ شخص وفاؤں کا صلہ بھول گیا",
     "Wafa ke naam pe qurbaan kar diya sab kuch, Magar woh shakhs wafaon ka sila bhool gaya",
     "In the name of sacred faithfulness I sacrificed everything; yet that companion forgot the recompense of genuine loyalty."),
    ("Ahmad Faraz", "ishq", "Tera Wajood Hai Ik Roshni Ki Soorat Mein",
     "ترا وجود ہے اک روشنی کی صورت میں", "اندھیری رات میں جو راہ دکھاتی ہے",
     "Tera wajood hai ik roshni ki soorat mein, Andheri raat mein jo raah dikhaati hai",
     "Your existence is like a steady beacon of pure light that guides the lost traveler across the darkest midnight."),
    ("Ahmad Faraz", "ishq", "Tere Rukhsaar Ki Surkhi Hai Bahaaron Jaisi",
     "تیرے رخسار کی سرخی ہے بہاروں جیسی", "تیری باتوں میں نزاکت ہے ستاروں جیسی",
     "Tere rukhsaar ki surkhi hai bahaaron jaisi, Teri baaton mein nazaakat hai sitaaron jaisi",
     "The flush upon your cheek is like the pink blossom of spring; in your speech lies the celestial delicacy of morning stars."),
    ("Ahmad Faraz", "ishq", "Khwaab Marte Nahi Khwaabon Ko Dua Kehte Hain",
     "خواب مرتے نہیں خوابوں کو دعا کہتے ہیں", "دل کے رشتوں کو محبت کی فضا کہتے ہیں",
     "Khwaab marte nahi khwaabon ko dua kehte hain, Dil ke rishton ko mohabbat ki faza kehte hain",
     "Dreams do not perish, for dreams are sacred prayers; and the sincere bonds of the heart are the breath of love itself."),

    # --- Parveen Shakir ---
    ("Parveen Shakir", "ishq", "Woh To Khushboo Hai Hawaon Mein Bikhar Jaayega",
     "وہ تو خوشبو ہے ہواؤں میں بکھر جائے گا", "مسئلہ پھول کا ہے پھول کدھر جائے گا",
     "Woh to khushboo hai hawaon mein bikhar jaayega, Masla phool ka hai phool kidhar jaayega",
     "He is merely fragrance and will scatter upon the winds; the true dilemma belongs to the rose—where shall the rose go?"),
    ("Parveen Shakir", "ishq", "Ko Ba Ko Phail Gayi Baat Shanaasaai Ki",
     "کو بہ کو پھیل گئی بات شناسائی کی", "اس نے خوشبو کی طرح میری پذیرائی کی",
     "Ko ba ko phail gayi baat shanaasaai ki, Uss ne khushboo ki tarah meri pazeeraai ki",
     "From lane to lane spread word of our mutual knowing; he welcomed me with open embrace, just as fragrance welcomes the breeze."),
    ("Parveen Shakir", "ishq", "Husn Ke Samajhne Ko Umr Chahiye Jaanaan",
     "حسن کے سمجھنے کو عمر چاہیے جاناں", "دو گھڑی کی چاہت میں پھول کھل نہیں سکتے",
     "Husn ke samajhne ko umr chahiye jaanaan, Do ghadi ki chaahat mein phool khil nahi sakte",
     "To truly comprehend beauty requires an entire lifetime, my love; blossoms cannot bloom within a mere fleeting moment of affection."),
    ("Parveen Shakir", "ishq", "Kuch To Hawa Bhi Sard Thi Kuch Tha Lahoo Mein Zehr Bhi",
     "کچھ تو ہوا بھی سرد تھی کچھ تھا لہو میں زہر بھی", "پچھلی رتوں کا ساتھ بھی رنجشِ بے سبب بھی تھی",
     "Kuch to hawa bhi sard thi kuch tha lahoo mein zehr bhi, Pichhli ruton ka saath bhi ranjish-e-be-sabab bhi thi",
     "Partly the wind was bitter cold, partly poison coursed through the blood; echoes of past seasons lingered, and causeless grievances arose."),
    ("Parveen Shakir", "ishq", "Yaad Ke Parde Se Jo Jhaanke Kabhi Uska Khayal",
     "یاد کے پردے سے جو جھانکے کبھی اس کا خیال", "دل کے ویرانے میں اک شمع جلا جاتی ہے",
     "Yaad ke parde se jo jhaanke kabhi uss ka khayal, Dil ke veerane mein ik shama jala jaati hai",
     "Whenever his thought peeks through the veil of memory, it kindles a glowing candle in the quiet chambers of the soul."),
    ("Parveen Shakir", "ishq", "Ab Ke Tajdeed-e-Wafa Ka Nahi Imkaan Jaanaan",
     "اب کے تجدیدِ وفا کا نہیں امکاں جاناں", "یاد کیا تجھ کو دلائیں ترا پیماں جاناں",
     "Ab ke tajdeed-e-wafa ka nahi imkaan jaanaan, Yaad kya tujh ko dilaayein tera paymaan jaanaan",
     "Now there remains no possibility of renewing past pledges, beloved; of what use is it to remind you of your forgotten vows?"),
    ("Parveen Shakir", "ishq", "Kamaal-e-Zabt Ko Khud Bhi To Aazmaaongi",
     "کمالِ ضبط کو خود بھی تو آزماؤں گی", "میں اپنے ہاتھ سے اس کی دلہن سجاؤں گی",
     "Kamaal-e-zabt ko khud bhi to aazmaaongi, Main apne haath se uss ki dulhan sajaaongi",
     "I shall put my utmost endurance to the ultimate test; with my very own hands, I shall adorn his bride in beauty."),
    ("Parveen Shakir", "ishq", "Tu Badalta Hai To Be-Saakhta Meri Aankhein",
     "تو بدلتا ہے تو بے ساختہ میری آنکھیں", "اپنے ہاتھوں کی لکیروں سے الجھ جاتی ہیں",
     "Tu badalta hai to be-saakhta meri aankhein, Apne haathon ki lakeeron se ulajh jaati hain",
     "Whenever you change toward me, my tearful eyes spontaneously lose themselves in the tangled lines of my palms."),
    ("Parveen Shakir", "ishq", "Teri Chaahat Ki Mehak Mere Badan Mein Utri",
     "تیری چاہت کی مہک میرے بدن میں اتری", "جیسے صحرا میں کوئی ابرِ کرم برسے",
     "Teri chaahat ki mehak mere badan mein utri, Jaise sehra mein koi abr-e-karam barse",
     "The perfume of your love descended into my soul, just as a merciful raincloud pours life upon the arid desert."),
    ("Parveen Shakir", "ishq", "Ik Naam Kya Likha Tera Saahil Ki Ret Par",
     "اک نام کیا لکھا ترا ساحل کی ریت پر", "موجوں نے آ کے پیار کا گلشن مٹا دیا",
     "Ik naam kya likha tera saahil ki ret par, Maujon ne aa ke pyaar ka gulshan mita diya",
     "Merely writing your name upon the ocean shore brought forth waves that washed the garden of love away."),
    ("Parveen Shakir", "ishq", "Teri Aankhon Mein Dikhaai Di Wafa Ki Chamak",
     "تیری آنکھوں میں دکھائی دی وفا کی چمک", "ہم نے دنیا کی ہر اک بات بھلا دی اس پر",
     "Teri aankhon mein dikhaai di wafa ki chamak, Hum ne duniya ki har ik baat bhula di iss par",
     "In your eyes shone the pure luster of loyalty; upon beholding it, we forgot every trivial complaint against the world."),
    ("Parveen Shakir", "ishq", "Narm Hawaon Ke Jhonkon Mein Teri Khushboo Hai",
     "نرم ہواؤں کے جھونکوں میں تیری خوشبو ہے", "تو جہاں بھی رہے دل تجھ کو پکارے گا سدا",
     "Narm hawaon ke jhonkon mein teri khushboo hai, Tu jahan bhi rahe dil tujh ko pukaarega sada",
     "Within the gentle gusts of soft breeze breathes your fragrance; wherever you may dwell, this heart shall call upon you always."),
    ("Parveen Shakir", "ishq", "Teri Baaton Ka Fusoon Dil Pe Asar Karta Hai",
     "تیری باتوں کا فسوں دل پہ اثر کرتا ہے", "جیسے شبنم کا گہر پات پہ لہراتا ہے",
     "Teri baaton ka fusoon dil pe asar karta hai, Jaise shabnam ka gohar paat pe lehraata hai",
     "The enchantment of your spoken words sways the heart, just as a pearl of morning dew shimmers upon a green leaf."),
    ("Parveen Shakir", "ishq", "Wafa Ki Shama Jalaaye Hue Baithi Hoon",
     "وفا کی شمع جلائے ہوئے بیٹھی ہوں", "ہوا چلے گی تو دامن سے چھپا لوں گی اسے",
     "Wafa ki shama jalaaye hue baithi hoon, Hawa chalegi to daaman se chhupa loongi usey",
     "I sit keeping the candle of faithfulness burning bright; should fierce winds arise, I shall shield the flame with my robe."),
    ("Parveen Shakir", "ishq", "Tu Muskuraaye To Gulshan Ka Nikhaar Badh Jaaye",
     "تو مسکرائے تو گلشن کا نکھار بڑھ جائے", "تیری ہر اک نظر سے بہار بڑھ جائے",
     "Tu muskuraaye to gulshan ka nikhaar badh jaaye, Teri har ik nazar se bahaar badh jaaye",
     "Whenever you smile, the vibrant charm of the garden intensifies; with every loving glance of yours, springtime deepens."),
    ("Parveen Shakir", "ishq", "Mehndi Ki Khushboo Mein Teri Yaad Basi Hai Jaanaan",
     "مہندی کی خوشبو میں تری یاد بسی ہے جاناں", "رنگ ہاتھوں پہ جو نکھرا ہے محبت کا ہے",
     "Mehndi ki khushboo mein teri yaad basi hai jaanaan, Rang haathon pe jo nikhra hai mohabbat ka hai",
     "Within the herbal aroma of henna your memory resides, my love; the crimson hue upon these hands is the living bloom of affection."),
    ("Parveen Shakir", "ishq", "Tera Ehsaas Mere Saath Rahega Har Dam",
     "تیرا احساس مرے ساتھ رہے گا ہر دم", "جیسے خوشبو کا سفر پھول کی شاخوں سے رہے",
     "Tera ehsaas mere saath rahega har dam, Jaise khushboo ka safar phool ki shaakhon se rahe",
     "Your gentle awareness shall accompany me at every breath, just as the journey of sweet scent belongs inseparable to the flower."),
    ("Parveen Shakir", "ishq", "Tujh Ko Dekha To Laga Jaise Dua Poori Hui",
     "تجھ کو دیکھا تو لگا جیسے دعا پوری ہوئی", "دل کی دہلیز پہ اک چاند اتر آیا ہے",
     "Tujh ko dekha to laga jaise dua poori hui, Dil ki dehleez pe ik chaand utar aaya hai",
     "Beholding you felt as though a lifelong prayer was fulfilled; as if the radiant moon had stepped down upon my heart's threshold."),
    ("Parveen Shakir", "ishq", "Khushboo Ki Tarah Aaye Woh Mehfil Mein Humaari",
     "خوشبو کی طرح آئے وہ محفل میں ہماری", "ہر سمت مہک اٹھی ہے چاہت کی کہانی",
     "Khushboo ki tarah aaye woh mehfil mein humaari, Har samt mehak uthi hai chaahat ki kahaani",
     "Like a fragrant blossom he entered our gathering; in every direction, the sweet tale of romance began to perfume the air."),
    ("Parveen Shakir", "ishq", "Chupke Se Tere Naam Pe Aansoo Baha Diye",
     "چپکے سے تیرے نام پہ آنسو بہا دیے", "دل کے سبھی چراغ محبت میں جلا دیے",
     "Chupke se tere naam pe aansoo baha diye, Dil ke sabhi chiragh mohabbat mein jala diye",
     "In quiet solitude I shed sincere tears at your name, and kindled every lamp of devotion within my heart for you."),

    # --- Jaun Elia ---
    ("Jaun Elia", "ishq", "Be-Dili Kya Yoon Hi Din Guzar Jaayenge",
     "بے دلی کیا یوں ہی دن گزر جائیں گے", "صرف زندہ رہے ہم تو مر جائیں گے",
     "Be-dili kya yoon hi din guzar jaayenge, Sirf zinda rahe hum to mar jaayenge",
     "In this listless numbness, shall days pass like this? If we merely exist without love, we shall surely perish within."),
    ("Jaun Elia", "ishq", "Kya Takalluf Karein Yeh Kehne Mein",
     "کیا تکلف کریں یہ کہنے میں", "جو بھی خوش ہے ہم اس سے جلتے ہیں",
     "Kya takalluf karein yeh kehne mein, Jo bhi khush hai hum uss se jaltay hain",
     "Why adopt false formalities in confessing it? Whosoever is genuinely happy in love, we burn with honest envy."),
    ("Jaun Elia", "ishq", "Jo Guzaari Na Jaa Saki Hum Se",
     "جو گزاری نہ جا سکی ہم سے", "ہم نے وہ زندگی گزاری ہے",
     "Jo guzaari na jaa saki hum se, Hum ne woh zindagi guzaari hai",
     "The very life that was unlivable and unbearable—that is the exact life we have lived."),
    ("Jaun Elia", "ishq", "Ab Meri Koi Zindagi Hi Nahi",
     "اب مری کوئی زندگی ہی نہیں", "اب بھی تم میری زندگی ہو کیا",
     "Ab meri koi zindagi hi nahi, Ab bhi tum meri zindagi ho kya",
     "Now I possess no life of my own; tell me, do you still remain my entire life?"),
    ("Jaun Elia", "ishq", "Haasil-e-Kun Hai Yeh Jahaan-e-Kharaab",
     "حاصلِ کُن ہے یہ جہانِ خراب", "یہی ممکن تھا اتنی عجلت میں",
     "Haasil-e-kun hai yeh jahaan-e-kharaab, Yehi mumkin tha itni ujlat mein",
     "This flawed, ruined world is the outcome of the divine command 'Be'; this alone was possible in such sudden haste."),
    ("Jaun Elia", "ishq", "Ilaaj-e-Dard-e-Dil Tum Se Maseeha Ho Nahi Sakta",
     "علاجِ دردِ دل تم سے مسیحا ہو نہیں سکتا", "کہ اس میں جان جاتی ہے اور یہ اچھا ہو نہیں سکتا",
     "Ilaaj-e-dard-e-dil tum se maseeha ho nahi sakta, Ke iss mein jaan jaati hai aur yeh acha ho nahi sakta",
     "Curing this heartache is impossible even for you, O healer; for life itself departs with it, and that can never be well."),
    ("Jaun Elia", "ishq", "Ab Ke Hum Soch Rahe Hain Ke Alag Ho Jaayein",
     "اب کے ہم سوچ رہے ہیں کہ الگ ہو جائیں", "تاکہ اک دوسرے کو ڈھونڈتے پھرتے رہیں ہم",
     "Ab ke hum soch rahe hain ke alag ho jaayein, Taake ik doosre ko dhoondte phirte rahein hum",
     "Now we ponder parting our ways, so that we may spend the rest of our lives restlessly searching for each other."),
    ("Jaun Elia", "ishq", "Tum Jab Aaogi To Khoya Hua Paaogi Mujhe",
     "تم جب آؤ گی تو کھویا ہوا پاؤ گی مجھے", "میری تنہائی میں خوابوں کے سوا کچھ بھی نہیں",
     "Tum jab aaogi to khoya hua paaogi mujhe, Meri tanhaai mein khwaabon ke siwa kuch bhi nahi",
     "When you come, you shall find me lost in reverie; in my quiet solitude there exists nothing except memories of dreams."),
    ("Jaun Elia", "ishq", "Zindagi Kis Tarah Basar Hogi",
     "زندگی کس طرح بسر ہوگی", "دل نہیں لگ رہا محبت میں",
     "Zindagi kis tarah basar hogi, Dil nahi lag raha mohabbat mein",
     "How shall this mortal life ever pass away? The weary heart finds no solace even in the midst of love."),
    ("Jaun Elia", "ishq", "Ajab Ik Shor Barpa Hai Mere Dil Ke Mohalle Mein",
     "عجب اک شور برپا ہے مرے دل کے محلے میں", "کہ جس بستی میں رہتے تھے وہ بستی ہی لٹ گئی",
     "Ajab ik shor barpa hai mere dil ke mohalle mein, Ke jis basti mein rehte thay woh basti hi lut gayi",
     "A strange commotion has erupted in the neighborhood of my heart; the peaceful hamlet where we resided has been despoiled."),
    ("Jaun Elia", "ishq", "Main Bhi Bohat Ajeeb Hoon Itna Ajeeb Hoon Ke Bas",
     "میں بھی بہت عجیب ہوں اتنا عجیب ہوں کہ بس", "خود کو تباہ کر لیا اور ملال بھی نہیں",
     "Main bhi bohat ajeeb hoon itna ajeeb hoon ke bas, Khud ko tabaah kar liya aur malaal bhi nahi",
     "I too am astonishingly strange, so strange indeed; I ruined my own soul in love, and feel not the slightest regret."),
    ("Jaun Elia", "ishq", "Saari Basti Mein Faqat Ek Wohi Chehra Tha",
     "ساری بستی میں فقط ایک وہی چہرہ تھا", "جس نے مجھ کو مری بربادی کا مژدہ سنایا",
     "Saari basti mein faqat aik wohi chehra tha, Jis ne mujh ko meri barbaadi ka muzhda sunaaya",
     "In the entire town there existed only that solitary face, which brought me the joyous announcement of my own sweet undoing."),
    ("Jaun Elia", "ishq", "Tum Jo Aao To Meri Rooh Ko Raahat Bakhsho",
     "تم جو آؤ تو مری روح کو راحت بخشو", "ورنہ بے کار میں سانسوں کا تماشا دیکھو",
     "Tum jo aao to meri rooh ko raahat bakhsho, Warna be-kaar mein saanson ka tamaasha dekho",
     "If you arrive, grant enduring comfort to my soul; otherwise behold in vain this hollow spectacle of mortal breaths."),
    ("Jaun Elia", "ishq", "Bohat Nazdeek Aati Jaa Rahi Ho",
     "بہت نزدیک آتی جا رہی ہو", "بچھڑنے کا ارادہ کر لیا کیا",
     "Bohat nazdeek aati jaa rahi ho, Bichhadne ka iraada kar liya kya",
     "You are drawing exceedingly close to me; tell me, have you formed the secret resolve to depart forever?"),
    ("Jaun Elia", "ishq", "Aik Hi To Hawas Rahi Hai Hamein",
     "ایک ہی تو ہوس رہی ہے ہمیں", "کہ تری آرزو میں برباد رہیں",
     "Aik hi to hawas rahi hai hamein, Ke teri aarzoo mein barbaad rahein",
     "Only a single burning obsession possessed us: to remain delightfully undone in the eternal longing for you."),
    ("Jaun Elia", "ishq", "Hum Ne Dekha Hai Zamaane Ki Inayat Ka Fareb",
     "ہم نے دیکھا ہے زمانے کی عنایت کا فریب", "تم جو سچے ہو تو نفرت ہی جتا دو ہم کو",
     "Hum ne dekha hai zamaane ki inaayat ka fareb, Tum jo sachay ho to nafrat hi jata do hum ko",
     "We have beheld the cruel illusion of this world's hollow kindness; if you are sincere, show us candid truth instead."),
    ("Jaun Elia", "ishq", "Ab To Tanhaai Se Bhi Khauf Nahi Aata Mujhe",
     "اب تو تنہائی سے بھی خوف نہیں آتا مجھے", "دل نے ویرانے کو آباد سمجھ رکھا ہے",
     "Ab to tanhaai se bhi khauf nahi aata mujhe, Dil ne veerane ko aabaad samajh rakha hai",
     "Now even complete solitude strikes no terror in me; my heart has come to deem the barren desert its inhabited home."),
    ("Jaun Elia", "ishq", "Jin Jin Pe Takiya Tha Wohi Patte Hawa Dene Lage",
     "جن جن پہ تکیہ تھا وہی پتے ہوا دینے لگے", "جن کو چاہا تھا وہی دل کو دغا دینے لگے",
     "Jin jin pe takiya tha wohi patte hawa dene lage, Jin ko chaaha tha wohi dil ko dagha dene lage",
     "The very supports upon which we leaned scattered like dry leaves; the very ones we loved deeply walked away."),
    ("Jaun Elia", "ishq", "Meri Aankhon Mein Tere Baad Lahoo Utar Aaya",
     "مری آنکھوں میں ترے بعد لہو اتر آیا", "تجھ کو پایا تھا تو بینائی سلامت تھی مری",
     "Meri aankhon mein tere baad lahoo utar aaya, Tujh ko paaya tha to beenaai salaamat thi meri",
     "After your departure, crimson tears filled my eyes; while I possessed you, my vision was whole and luminous."),
    ("Jaun Elia", "ishq", "Tujh Ko Chaaha Tha To Ik Rasm Nibhaai Na Gayi",
     "تجھ کو چاہا تھا تو اک رسم نبھائی نہ گئی", "دل جو ٹوٹا تو صدائیں بھی نہ دی ہم نے تجھے",
     "Tujh ko chaaha tha to ik rasm nibhaai na gayi, Dil jo toota to sadaayein bhi na di hum ne tujhe",
     "Loving you, I could not conform to empty worldly rites; and when my heart broke, I did not even cry out to reproach you."),

    # --- Dagh Dehlvi ---
    ("Dagh Dehlvi", "ishq", "Ghazab Kiya Tere Wade Pe Aitbaar Kiya",
     "غضب کیا ترے وعدے پہ اعتبار کیا", "تمام رات قیامت کا انتظار کیا",
     "Ghazab kiya tere wade pe aitbaar kiya, Tamaam raat qayamat ka intezaar kiya",
     "What madness possessed me to believe your promise! I spent the entire night in agonizing anticipation of Doomsday."),
    ("Dagh Dehlvi", "ishq", "Lutf-e-Mai Tujh Se Kya Kahoon Zaahid",
     "لطفِ مے تجھ سے کیا کہوں زاہد", "ہائے کمبخت تو نے پی ہی نہیں",
     "Lutf-e-mai tujh se kya kahoon zaahid, Haaye kambakht tu ne pee hi nahi",
     "How can I describe the ecstasy of divine wine to you, O ascetic? Alas, wretched soul, you have never tasted it!"),
    ("Dagh Dehlvi", "ishq", "Urdu Hai Jis Ka Naam Hamein Jaante Hain Dagh",
     "اردو ہے جس کا نام ہمین جانتے ہیں داغ", "سارے جہاں میں دھوم ہماری زباں کی ہے",
     "Urdu hai jis ka naam hamein jaante hain Dagh, Saare jahan mein dhoom hamari zubaan ki hai",
     "The sweet language named Urdu—we are renowned for it, Dagh; across the entire globe echoes the fame of our mother tongue."),
    ("Dagh Dehlvi", "ishq", "Hosh Udte Hain Mere Raunaq-e-Mehfil Dekh Kar",
     "ہوش اڑتے ہیں مرے رونقِ محفل دیکھ کر", "آ گئی محفل میں گویا جانِ محفل دیکھ کر",
     "Hosh udte hain mere raunaq-e-mehfil dekh kar, Aa gayi mehfil mein goya jaan-e-mehfil dekh kar",
     "My senses scatter upon beholding the radiance of the gathering; as if life itself entered the room when she stepped in."),
    ("Dagh Dehlvi", "ishq", "Rukh Pe Bikhri Hain Zulfien Siyah Raat Ki Tarah",
     "رخ پہ بکھری ہیں زلفیں سیاہ رات کی طرح", "چہرہ چمک رہا ہے چاند کی بات کی طرح",
     "Rukh pe bikhri hain zulfien siyah raat ki tarah, Chehra chamak raha hai chaand ki baat ki tarah",
     "Her dark tresses scatter across her cheek like the velvety midnight sky; her countenance glows luminous like the full moon."),
    ("Dagh Dehlvi", "ishq", "Tum Ne Poochha Na Kabhi Haal Hamara Aakar",
     "تم نے پوچھا نہ کبھی حال ہمارا آ کر", "ہم نے ہر لمحہ تمہارا ہی تصور باندھا",
     "Tum ne poochha na kabhi haal hamara aa kar, Hum ne har lamha tumhara hi tasawwur baandha",
     "You never came to inquire after our aching condition; yet in every single passing breath we envisioned only you."),
    ("Dagh Dehlvi", "ishq", "Aap Ka Aana Hamaari Eid Ho Jaata Hai",
     "آپ کا آنا ہماری عید ہو جاتا ہے", "دیکھ کر آپ کو دل شاد ہو جاتا ہے",
     "Aap ka aana hamaari Eid ho jaata hai, Dekh kar aap ko dil shaad ho jaata hai",
     "Your very arrival turns into an ecstatic festive Eid for us; beholding you fills the weary heart with immense delight."),
    ("Dagh Dehlvi", "ishq", "Dil Gaya Raunq-e-Hayaat Gayi",
     "دل گیا رونقِ حیات گئی", "غم گیا ساری کائنات گئی",
     "Dil gaya raunaq-e-hayaat gayi, Gham gaya saari qaayenaat gayi",
     "When the heart departed, all luster of life vanished; when sorrow vanished, the meaningful universe dissolved."),
    ("Dagh Dehlvi", "ishq", "Woh Jo Hum Mein Tum Mein Qaraar Tha Tumhein Yaad Ho",
     "وہ جو ہم میں تم میں قرار تھا تمہیں یاد ہو کہ نہ یاد ہو", "وہی یعنی وعدہ نباہ کا تمہیں یاد ہو کہ نہ یاد ہو",
     "Woh jo hum mein tum mein qaraar tha tumhein yaad ho ke na yaad ho, Wohi yaani waada nibaah ka tumhein yaad ho ke na yaad ho",
     "That mutual pledge which once united us—you may remember or forget; that promise of enduring loyalty—you may remember or forget."),
    ("Dagh Dehlvi", "ishq", "Hazaron Kaam Hain Duniya Mein Lekin",
     "ہزاروں کام ہیں دنیا میں لیکن", "محبت کے بنا سب بے اثر ہیں",
     "Hazaaron kaam hain duniya mein lekin, Mohabbat ke bina sab be-asar hain",
     "Thousands of enterprises exist in this bustling world; yet without sincere love, every single pursuit remains hollow."),

    # --- Nasir Kazmi ---
    ("Nasir Kazmi", "ishq", "Dil Mein Ik Lehar Si Uthi Hai Abhi",
     "دل میں اک لہر سی اٹھی ہے ابھی", "کوئی تازہ ہوا چلی ہے ابھی",
     "Dil mein ik lehar si uthi hai abhi, Koi taaza hawa chali hai abhi",
     "A gentle ripple of emotion has stirred in my heart just now; as if a fresh breeze has begun to blow this moment."),
    ("Nasir Kazmi", "ishq", "Yaad Ke Be-Nishan Jazeeron Se",
     "یاد کے بے نشاں جزیروں سے", "تیری آواز آ رہی ہے ابھی",
     "Yaad ke be-nishaan jazeeron se, Teri aawaaz aa rahi hai abhi",
     "From the uncharted, mist-veiled islands of cherished memory, your gentle voice is calling out to me right now."),
    ("Nasir Kazmi", "ishq", "Gaye Dinon Ka Suraagh Le Kar Kidhar Se Aaya",
     "گئے دنوں کا سراغ لے کر کدھر سے آیا کدھر گیا وہ", "عجیب شخص تھا سارے شہر کو ویران کر گیا وہ",
     "Gaye dinon ka suraagh le kar kidhar se aaya kidhar gaya woh, Ajeeb shakhs tha saare shehar ko veeraan kar gaya woh",
     "Bearing the clues of bygone days, whence did he come and whither did he vanish? What a wondrous soul he was—he emptied the entire city upon leaving."),
    ("Nasir Kazmi", "ishq", "Waqt-e-Rukhsat Tha Ajab Rang Zamaane Ka",
     "وقتِ رخصت تھا عجب رنگ زمانے کا", "آنکھ نم تھی مگر لب پہ تبسم تھا ترا",
     "Waqt-e-rukhsat tha ajab rang zamaane ka, Aankh nam thi magar lab pe tabassum tha tera",
     "At the hour of farewell a wondrous mood touched the earth: your eyes were moist with tears, yet a tender smile graced your lips."),
    ("Nasir Kazmi", "ishq", "Shaam Hui Phir Yaad Aaya Koi",
     "شام ہوئی پھر یاد آیا کوئی", "پھر سلگنے لگا دلِ تنہا",
     "Shaam hui phir yaad aaya koi, Phir sulagne laga dil-e-tanha",
     "Dusk has descended, and once again someone returns to memory; once again my solitary heart begins to glow like quiet embers."),
    ("Nasir Kazmi", "ishq", "Pardesiya Tere Shehar Ki Hawa Bhi Ajeeb Hai",
     "پردیسیا ترے شہر کی ہوا بھی عجیب ہے", "آتی ہے تو پرانی یادیں جگا دیتی ہے",
     "Pardesiya tere shehar ki hawa bhi ajeeb hai, Aati hai to puraani yaadein jaga deti hai",
     "O wanderer, the breeze of your city possesses a wondrous spell; whenever it blows, it awakens long-slumbering memories."),
    ("Nasir Kazmi", "ishq", "Chaand Nikla Hai Magar Raat Udaas Hai",
     "چاند نکلا ہے مگر رات اداس ہے", "تیرے بغیر ہر اک بات اداس ہے",
     "Chaand nikla hai magar raat udaas hai, Tere baghair har ik baat udaas hai",
     "The moon has ascended the sky yet the night remains melancholy; without your radiant presence, all of existence feels quiet and pensive."),
    ("Nasir Kazmi", "ishq", "Gham Ki Barsaat Mein Bheegte Hain",
     "غم کی برسات میں بھیگتے ہیں", "ہم ترے پیار کی پیاس میں جیتے ہیں",
     "Gham ki barsaat mein bheegte hain, Hum tere pyaar ki pyaas mein jeete hain",
     "We stand drenching beneath the gentle rain of sorrow, living solely on the thirst for your tender love."),
    ("Nasir Kazmi", "ishq", "Kuch Yaadgaar-e-Shehar-e-Sitamgar Hi Le Chalein",
     "کچھ یادگارِ شہرِ ستمگر ہی لے چلیں", "آئے تھے اس گلی میں تو پتھر ہی لے چلیں",
     "Kuch yaadgaar-e-shehar-e-sitamgar hi le chalein, Aaye thay iss gali mein to patthar hi le chalein",
     "Let us carry away at least some memento of this city of unyielding lovers; having entered this lane, let us depart bearing their stones with grace."),
    ("Nasir Kazmi", "ishq", "Teri Khushboo Ka Pata Poochhti Hai",
     "تیری خوشبو کا پتا پوچھتی ہے", "ہر ہوا جو مرے گھر سے گزرتی ہے",
     "Teri khushboo ka pata poochhti hai, Har hawa jo mere ghar se guzarti hai",
     "It inquires after the secret dwelling of your perfume—every gentle breeze that wanders through my humble abode."),

    # --- Sahir Ludhianvi ---
    ("Sahir Ludhianvi", "ishq", "Chalo Ek Baar Phir Se Ajnabi Ban Jaayein Hum Dono",
     "چلو اک بار پھر سے اجنبی بن جائیں ہم دونوں", "نہ میں تم سے کوئی امید رکھوں نہ تم مجھ سے",
     "Chalo ik baar phir se ajnabi ban jaayein hum dono, Na main tum se koi umeed rakhoon na tum mujh se",
     "Come, let the two of us become strangers once again; so that neither I harbor expectations from you, nor you from me."),
    ("Sahir Ludhianvi", "ishq", "Taaruf Rog Ban Jaaye To Usko Bhoolna Behtar",
     "تعارف روگ بن جائے تو اس کو بھولنا بہتر", "تعلق بوجھ بن جائے تو اس کو توڑنا اچھا",
     "Taaruf rog ban jaaye to uss ko bhoolna behtar, Taaluq bojh ban jaaye to uss ko todna acha",
     "If an acquaintance becomes a torment, it is wiser to let it fade; if a bond turns into a burden, it is healthier to let it go."),
    ("Sahir Ludhianvi", "ishq", "Maine Chaand Aur Sitaron Ki Tamanna Ki Thi",
     "میں نے چاند اور ستاروں کی تمنا کی تھی", "مجھ کو راتوں کی سیاہی کے سوا کچھ نہ ملا",
     "Maine chaand aur sitaron ki tamanna ki thi, Mujh ko raaton ki siyaahi ke siwa kuch na mila",
     "I had yearned for the glowing moon and radiant stars; yet nothing came to my hands save the velvet darkness of night."),
    ("Sahir Ludhianvi", "ishq", "Kabhi Kabhi Mere Dil Mein Khayal Aata Hai",
     "کبھی کبھی مرے دل میں خیال آتا ہے", "کہ جیسے تجھ کو بنایا گیا ہے میرے لیے",
     "Kabhi kabhi mere dil mein khayal aata hai, Ke jaise tujh ko banaaya gaya hai mere liye",
     "At times, a tender thought visits the quiet sanctuary of my soul: that you were fashioned by the Divine expressly for me."),
    ("Sahir Ludhianvi", "ishq", "Yeh Zulf Agar Khul Ke Bikhar Jaaye To Acha",
     "یہ زلف اگر کھل کے بکھر جائے تو اچھا", "اس رات کی تقدیر سنور جائے تو اچھا",
     "Yeh zulf agar khul ke bikhar jaaye to acha, Iss raat ki taqdeer sanwar jaaye to acha",
     "If these flowing locks unbind and scatter gently, how sublime; if the destiny of this magical night is adorned, how beautiful."),
    ("Sahir Ludhianvi", "ishq", "Tu Mere Saath Rahega Munis-e-Jaan",
     "تو مرے ساتھ رہے گا مونسِ جاں", "میری تنہائی کو رونق بخشے گا سدا",
     "Tu mere saath rahega moonis-e-jaan, Meri tanhaai ko raunaq bakhshega sada",
     "You shall remain forever beside me, O companion of my soul, bestowing radiant joy upon my quiet solitude."),
    ("Sahir Ludhianvi", "ishq", "Mohabbat Ke Taraane Gungunaati Hai Hawa",
     "محبت کے ترانے گنگناتی ہے ہوا", "جب تیرے دھیان کی چادر اوڑھتی ہے فضا",
     "Mohabbat ke taraane gungunaati hai hawa, Jab tere dhyaan ki chaadar odhti hai faza",
     "The breeze hums melodic anthems of sweet love whenever the atmosphere wraps itself in the gentle contemplation of you."),
    ("Sahir Ludhianvi", "ishq", "Tere Honthon Ki Hansi Khil Uthi Gulzaar Ki Tarah",
     "تیرے ہونٹوں کی ہنسی کھل اٹھی گلزار کی طرح", "دیکھ کر تجھ کو زمانہ بھی مسکرانے لگا",
     "Tere honthon ki hansi khil uthi gulzaar ki tarah, Dekh kar tujh ko zamaana bhi muskuraane laga",
     "The laughter upon your lips blossomed like an opulent garden; beholding you, even the passing world began to smile."),
    ("Sahir Ludhianvi", "ishq", "Subh Ka Taara Chamakta Hai Teri Yaad Ke Saath",
     "صبح کا تارا چمکتا ہے تری یاد کے ساتھ", "شب کا آنچل بھی مہکتا ہے تیرے پیار کے ساتھ",
     "Subh ka taara chamakta hai teri yaad ke saath, Shab ka aanchal bhi mehakta hai tere pyaar ke saath",
     "The morning star sparkles hand in hand with your memory; the mantle of night perfumes itself with your tender love."),
    ("Sahir Ludhianvi", "ishq", "Wafa Ka Rang Kabhi Maand Pad Nahi Sakta",
     "وفا کا رنگ کبھی ماند پڑ نہیں سکتا", "جو دل سے چاہیں وہ رستے جدا نہیں ہوتے",
     "Wafa ka rang kabhi maand pad nahi sakta, Jo dil se chaahein woh raste juda nahi hote",
     "The vibrant hue of true loyalty can never grow dim; those who love with sincerity from the soul are never truly separated."),

    # --- Hasrat Mohani, Jigar Moradabadi, Qateel Shifai, Mohsin Naqvi ---
    ("Hasrat Mohani", "ishq", "Chupke Chupke Raat Din Aansoo Bahana Yaad Hai",
     "چپکے چپکے رات دن آنسو بہانا یاد ہے", "ہم کو اب تک عاشقی کا وہ زمانہ یاد ہے",
     "Chupke chupke raat din aansoo bahaana yaad hai, Hum ko ab tak aashiqi ka woh zamaana yaad hai",
     "Shedding tears in secret day and night remains vivid in memory; I still remember that golden season of impassioned youthful love."),
    ("Hasrat Mohani", "ishq", "Kheenchna Woh Mera Lutf-e-Deed Ka Ehsaan",
     "کھینچنا وہ مرا لطفِ دید کا احسان", "اور ترا وہ ناز سے منہ پھیر لینا یاد ہے",
     "Kheenchna woh mera lutf-e-deed ka ehsaan, Aur tera woh naaz se munh pher lena yaad hai",
     "I remember entreating for the favor of beholding your face, and your turning away with coy, coquettish disdain."),
    ("Hasrat Mohani", "ishq", "Tujh Se Milte Hi Badal Jaati Hai Duniya Meri",
     "تجھ سے ملتے ہی بدل جاتی ہے دنیا میری", "تیرے جلوؤں سے مہک اٹھتی ہے ہر شام مری",
     "Tujh se miltay hi badal jaati hai duniya meri, Tere jalwon se mehak uthti hai har shaam meri",
     "The moment I meet you, my entire universe transforms; through your radiance, my every evening blossoms with sweetness."),
    ("Jigar Moradabadi", "ishq", "Yeh Ishq Nahi Aasaan Itna Hi Samajh Leeje",
     "یہ عشق نہیں آساں اتنا ہی سمجھ لیجے", "اک آگ کا دریا ہے اور ڈوب کے جانا ہے",
     "Yeh ishq nahi aasaan itna hi samajh leeje, Ik aag ka darya hai aur doob ke jaana hai",
     "Know this full well: love is no easy enterprise; it is an ocean of blazing fire, and one must plunge deep to cross."),
    ("Jigar Moradabadi", "ishq", "Aadmi Aadmi Se Milta Hai",
     "آدمی آدمی سے ملتا ہے", "دل مگر کم کسی سے ملتا ہے",
     "Aadmi aadmi se milta hai, Dil magar kam kisi se milta hai",
     "Human beings meet other humans daily; yet heart truly unites with heart only in rarest moments of grace."),
    ("Jigar Moradabadi", "ishq", "Meri Zindagi To Guzri Tere Aitbaar Mein",
     "مری زندگی تو گزری ترے اعتبار میں", "اب کون جائے ڈھونڈنے دوسرا آسرا",
     "Meri zindagi to guzri tere aitbaar mein, Ab kaun jaaye dhoondne doosra aasra",
     "My entire life was lived in steadfast trust of you; who would now wander seeking any other refuge under heaven?"),
    ("Qateel Shifai", "ishq", "Woh Dil Hi Kya Tere Milne Ki Jo Dua Na Kare",
     "وہ دل ہی کیا ترے ملنے کی جو دعا نہ کرے", "میں تجھ کو بھول کے زندہ رہوں خدا نہ کرے",
     "Woh dil hi kya tere milne ki jo dua na kare, Main tujh ko bhool ke zinda rahoon Khuda na kare",
     "What heart is that which prays not for union with you? May God forbid that I should ever live on having forgotten you."),
    ("Qateel Shifai", "ishq", "Garche Sau Baar Hui Hum Se Shikast-e-Dil",
     "گرچہ سو بار ہوئی ہم سے شکستِ دل", "پھر بھی ہم نے تری الفت کی قبا اوڑھ رکھی",
     "Garche sau baar hui hum se shikast-e-dil, Phir bhi hum ne teri ulfat ki qaba odh rakhi",
     "Though our heart was shattered a hundred times, we remained wrapped in the loyal mantle of your love."),
    ("Mohsin Naqvi", "ishq", "Yeh Kamaal-e-Zabt Mujhe Mila Teri Yaad Se",
     "یہ کمالِ ضبط مجھے ملا تری یاد کے سنگِ میل سے", "کہ جو غم ملا اسے پی لیا جو ملی خوشی اسے بانٹ دیا",
     "Yeh kamaal-e-zabt mujhe mila teri yaad ke sang-e-meel se, Ke jo gham mila usey pee liya jo mili khushi usey baant diya",
     "This mastery of emotional dignity I learned at the milestone of your memory: to drink whatever grief came, and share whatever joy arrived."),
    ("Mohsin Naqvi", "ishq", "Tujhe Bhoolna Bhi Chahein To Bhula Nahi Sakte",
     "تجھے بھولنا بھی چاہیں تو بھلا نہیں سکتے", "تری یاد آ ہی جاتی ہے چراغوں کی طرح",
     "Tujhe bhoolna bhi chaahein to bhula nahi sakte, Teri yaad aa hi jaati hai chiraghon ki tarah",
     "Even if we wished to forget you, we cannot; your memory lights up spontaneously like radiant lamps in the evening gloom."),
    ("Amjad Islam Amjad", "ishq", "Agar Kabhi Meri Yaad Aaye To Chaand Raaton Mein",
     "اگر کبھی مری یاد آئے تو چاند راتوں کی نرم چاندنی میں", "کسی ستارے کو دیکھ کر مسکرا دینا",
     "Agar kabhi meri yaad aaye to chaand raaton ki narm chaandni mein, Kisi sitaare ko dekh kar muskura dena",
     "If ever my memory touches you, in the soft moonlight of nocturnal skies, look upon a solitary star and smile tenderly."),
    ("Amjad Islam Amjad", "ishq", "Mohabbat Aisa Darya Hai Ke Jis Ka Saahil Nahi",
     "محبت ایسا دریا ہے کہ جس کا ساحل نہیں", "جو اس میں ڈوب گیا وہ پار اتر گیا",
     "Mohabbat aisa darya hai ke jis ka saahil nahi, Jo iss mein doob gaya woh paar utar gaya",
     "Love is an boundless river that possesses no physical shore; whoever drowns in its sweet depths is the one who safely reaches across."),
    ("Firaq Gorakhpuri", "ishq", "Aadhi Raat Ko Mehfil Mein Ek Baat Chhidi",
     "آدھی رات کو محفل میں اک بات چھڑی", "تیرا ذکر آیا تو سب چراغ بجھ گئے",
     "Aadhi raat ko mehfil mein ik baat chhidi, Tera zikr aaya to sab chiragh bujh gaye",
     "At midnight a murmur arose in the gathering; when your sweet name was mentioned, all other lamps paled in comparison."),
    ("Firaq Gorakhpuri", "ishq", "Hazaron Saal Pehle Bhi Mohabbat Zinda Thi",
     "ہزاروں سال پہلے بھی محبت زندہ تھی", "ہزاروں سال بعد بھی یہ جاوداں رہے گی",
     "Hazaaron saal pehle bhi mohabbat zinda thi, Hazaaron saal baad bhi yeh jaawidaan rahegi",
     "Thousands of years ago love was vibrant and alive; and thousands of years hence, it shall remain immortal."),
    ("Shakeel Badayuni", "ishq", "Kareeb Aa Ke Bhi Jo Door Rehte Hain",
     "قریب آ کے بھی جو دور رہتے ہیں", "وہی دلوں کے اصل رازداں ہوتے ہیں",
     "Qareeb aa ke bhi jo door rehte hain, Wohi dilon ke asal raazdaan hote hain",
     "Those who maintain reverence even when close—they alone are the genuine keepers of the heart's sacred secrets."),

    # --- Classical Urdu Ishq additions (to reach 155) ---
    ("Mirza Ghalib", "ishq", "Shab-e-Firaaq Ki Talkhiyan Na Pooch",
     "شبِ فراق کی تلخیاں نہ پوچھ ہم سے", "کہ ہم نے خون کے آنسو پی کے رات کاٹی ہے",
     "Shab-e-firaaq ki talkhiyan na poochh hum se, Ke hum ne khoon ke aansoo pee ke raat kaati hai",
     "Ask us not of the bitterness of separation's night; for we endured the dark hours drinking tears of heart's blood."),
    ("Mir Taqi Mir", "ishq", "Mujh Ko Ruswa Zamaane Mein Kar Diya",
     "مجھ کو رسوا زمانے میں کر دیا", "تیری اک نگاہِ کرم نے میاں",
     "Mujh ko ruswa zamaane mein kar diya, Teri ik nigaah-e-karam ne miyaan",
     "It made me notorious throughout the worldly gathering—that single gracious glance of your enchanting eyes."),
    ("Allama Iqbal", "ishq", "Tere Ishq Ki Inteha Chahta Hoon Meri Saadgi Dekh",
     "ترے عشق کی انتہا چاہتا ہوں", "مری سادگی دیکھ کیا چاہتا ہوں",
     "Tere ishq ki inteha chahta hoon, Meri saadgi dekh kya chahta hoon",
     "I seek the utmost boundless peak of your divine love; behold my innocent simplicity in what I desire!"),
    ("Allama Iqbal", "ishq", "Bhari Bazm Mein Raaz Ki Baat Keh Di",
     "بھری بزم میں راز کی بات کہہ دی", "بڑا بے ادب ہوں سزا چاہتا ہوں",
     "Bhari bazm mein raaz ki baat keh di, Bada be-adab hoon saza chahta hoon",
     "In the crowded gathering I revealed the intimate secret of love; how audacious I am—now I ask for my penalty."),
    ("Bahadur Shah Zafar", "ishq", "Na Kisi Ki Aankh Ka Noor Hoon Na Kisi Ke Dil Ka Qaraar",
     "نہ کسی کی آنکھ کا نور ہوں نہ کسی کے دل کا قرار ہوں", "جو کسی کے کام نہ آ سکے میں وہ ایک مشتِ غبار ہوں",
     "Na kisi ki aankh ka noor hoon na kisi ke dil ka qaraar hoon, Jo kisi ke kaam na aa sakay main woh aik musht-e-ghubaar hoon",
     "I am neither the light of any eye nor the comfort of any heart; I am merely a handful of dust that could serve no earthly purpose."),
    ("Bahadur Shah Zafar", "ishq", "Lagta Nahi Hai Dil Mera Ujde Dayaar Mein",
     "لگتا نہیں ہے دل مرا اجڑے دیار میں", "کس کی بنی ہے عالمِ نا پائیدار میں",
     "Lagta nahi hai dil mera ujde dayaar mein, Kis ki bani hai aalam-e-na-paaedaar mein",
     "My heart finds no solace in this desolate, ruined abode; who has ever found lasting contentment in this transient realm?"),
    ("Habib Jalib", "ishq", "Tum Mohabbat Ka Payaam Ho Humaare Liye",
     "تم محبت کا پیام ہو ہمارے لیے", "تیرے دم سے ہے بستی کی یہ رونق سدا",
     "Tum mohabbat ka payaam ho humaare liye, Tere dam se hai basti ki yeh raunaq sada",
     "You are the living message of genuine love for us; by your grace alone does the vitality of this city forever endure."),
    ("Muneer Niazi", "ishq", "Kissi Ko Apne Amal Ka Hisaab Kya Dete",
     "کسی کو اپنے عمل کا حساب کیا دیتے", "ہم اپنی ذات کے اندر الجھ کے رہ گئے ہیں",
     "Kisi ko apne amal ka hisaab kya dete, Hum apni zaat ke andar ulajh ke reh gaye hain",
     "How could we render an account of our deeds to the world? We remained delightfully entangled within the mysteries of our own soul."),
    ("Mustafa Zaidi", "ishq", "Aandhi Chali To Naqsh-e-Kaf-e-Paa Nahi Mila",
     "آندھی چلی تو نقشِ کفِ پا نہیں ملا", "ہم جس کو ڈھونڈتے تھے وہ رستہ نہیں ملا",
     "Aandhi chali to naqsh-e-kaf-e-paa nahi mila, Hum jis ko dhoondte thay woh rasta nahi mila",
     "When the tempest blew, not even a footprint remained in the sand; the sacred path we searched for could not be traced."),
    ("Josh Malihabadi", "ishq", "Husn Aur Ishq Ki Manzil Hai Ek Hi Aalam",
     "حسن اور عشق کی منزل ہے ایک ہی عالم", "جہاں دل ملے وہیں بزمِ بہار ہے",
     "Husn aur ishq ki manzil hai aik hi aalam, Jahan dil milay waheen bazm-e-bahaar hai",
     "The ultimate destination of beauty and love is one unified realm; wherever two pure hearts unite, there spring celebrates."),
    ("Kaifi Azmi", "ishq", "Uth Meri Jaan Mere Saath Chalna Hai Tujhe",
     "اٹھ مری جان مرے ساتھ چلنا ہے تجھے", "زندگی کے نئے خوابوں کو سنوارنا ہے تجھے",
     "Uth meri jaan mere saath chalna hai tujhe, Zindagi ke naye khwaabon ko sanwaarna hai tujhe",
     "Rise, my beloved, you must walk side by side with me; together we shall adorn the bold new dreams of this life."),
    ("Majrooh Sultanpuri", "ishq", "Hum To Akele Hi Chale Thay Janib-e-Manzil Magar",
     "ہم تو اکیلے ہی چلے تھے جانبِ منزل مگر", "لوگ ساتھ آتے گئے اور کارواں بنتا گیا",
     "Hum to akele hi chale thay jaanib-e-manzil magar, Log saath aate gaye aur kaarwaan banta gaya",
     "I had set forth entirely alone toward the high horizon; yet travelers joined hand in hand, and a majestic caravan was formed."),
    ("Ibn-e-Insha", "ishq", "Insha Ji Uttho Ab Kooch Karo Iss Shehar Mein",
     "انشاؔ جی اٹھو اب کوچ کرو اس شہر میں جی کو لگانا کیا", "وحشی کو سکوں سے کیا مطلب جوگی کا نگر میں ٹھکانا کیا",
     "Insha ji uttho ab kooch karo iss shehar mein jee ko lagaana kya, Wehshi ko sukoon se kya matlab jogi ka nagar mein thikaana kya",
     "Rise, O Insha, pack your baggage and depart; what purpose is served by tying the heart to this town? What home has a wandering hermit?"),
    ("Nizar Qabbani", "ishq", "Ainayki Kawkabaani Min Yaasameen",
     "عيناكِ كوكبان من ياسمين", "وقلبي في هواكِ مسافرٌ لا يستكين",
     "Ainayki kawkabaani min yaasameen, Wa-qalbi fee hawaaki musaafirun laa yastakeen",
     "Your eyes are two celestial stars of fragrant jasmine; my heart in your love is an eternal, restless voyager."),
    ("Nizar Qabbani", "ishq", "Hubbuki Allamani Kaifa Uhimmul Hayaat",
     "حبكِ علمني كيف أهيم بالحياة", "وكيف أزرع الورد في صحراء الأيام",
     "Hubbuki allamani kaifa uheemu bil-hayaah, Wa kaifa azra'ul-warda fee sahraa'il-ayyam",
     "Your love taught me how to fall deeply enamored with existence, and how to plant roses across the desert of fleeting days."),
    ("William Shakespeare", "ishq", "Shall I Compare Thee To A Summer's Day",
     "Shall I compare thee to a summer's day?", "Thou art more lovely and more temperate.",
     "Shall I compare thee to a summer's day? Thou art more lovely and more temperate.",
     "Shall I compare you to a summer's day? You are far lovelier and more gentle; your beauty shall live eternal in verse."),
    ("William Shakespeare", "ishq", "Love Looks Not With The Eyes But With The Mind",
     "Love looks not with the eyes, but with the mind,", "And therefore is winged Cupid painted blind.",
     "Love looks not with the eyes, but with the mind, And therefore is winged Cupid painted blind.",
     "Love perceives not with physical sight, but with the inner eye of the soul; and therefore Cupid is depicted blind."),
    ("John Keats", "ishq", "A Thing Of Beauty Is A Joy For Ever",
     "A thing of beauty is a joy for ever:", "Its loveliness increases; it will never pass into nothingness.",
     "A thing of beauty is a joy for ever: Its loveliness increases...",
     "A thing of beauty is an everlasting joy; its loveliness increases continually and shall never fade into nothingness."),
    ("Lord Byron", "ishq", "She Walks In Beauty Like The Night",
     "She walks in beauty, like the night", "Of cloudless climes and starry skies.",
     "She walks in beauty, like the night Of cloudless climes and starry skies.",
     "She moves in sublime grace, like the cloudless night illuminated by celestial stars; all that is best of dark and bright meets in her aspect."),
    ("Pablo Neruda", "ishq", "Te Amo Sin Saber Como Ni Cuando Ni De Donde",
     "Te amo sin saber cómo, ni cuándo, ni de dónde,", "te amo directamente sin problemas ni orgullo.",
     "Te amo sin saber como, ni cuando, ni de donde, te amo directamente sin problemas ni orgullo.",
     "I love you without knowing how, or when, or from where; I love you directly, without complexities or pride."),

    # ==========================================
    # WEDDING & NIKKAH (107 strictly unique verses)
    # ==========================================
    ("Traditional Quranic", "wedding", "Barakallahu Lakuma Wa Jama'a Baynakuma Fee Khair",
     "بَارَكَ اللَّهُ لَكُمَا وَبَارَكَ عَلَيْكُمَا", "وَجَمَعَ بَيْنَكُمَا فِي خَيْرٍ وَمَوَدَّةٍ",
     "Barakallahu lakuma wa baaraka alaykuma, Wa jama'a baynakuma fee khairin wa mawaddatin",
     "May Allah bless this union in abundance, bestow His divine favor upon you both, and unite your lives in goodness, peace, and mutual love."),
    ("Traditional Quranic", "wedding", "Rabbana Hab Lana Min Azwajina",
     "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ", "وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
     "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yun, Waj'alna lil-muttaqeena imaama",
     "Our Lord, grant us in our spouses and offspring the comfort of our eyes, and make us leaders of the righteous."),
    ("Traditional Quranic", "wedding", "Khalaqa Lakum Min Anfusikum Azwajan",
     "وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا", "وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً",
     "Wa min aayaatihee an khalaqa lakum min anfusikum azwaajan li-taskunoo ilaiha, Wa ja'ala baynakum mawaddatan wa rahmah",
     "And of His signs is that He created for you mates from among yourselves, that you may find tranquility in them, and He placed between you affection and mercy."),
    ("Traditional Nikkah", "wedding", "Do Dilon Ka Milan Hai Khuda Ki Rehmat Ka Nishan",
     "دو دلوں کا ملن ہے خدا کی رحمت کا نشان", "رہے ہمیشہ سلامت یہ محبت کا کاروان",
     "Do dilon ka milan hai Khuda ki rehmat ka nishan, Rahe hamesha salamat yeh mohabbat ka kaarwaan",
     "The union of two loving souls is the living sign of Divine Grace; may this caravan of sacred love travel forever in peace and joy."),
    ("Traditional Nikkah", "wedding", "Saath Tera Jo Mila To Zindagi Muskura Uthi",
     "ساتھ تیرا جو ملا تو زندگی مسکرا اٹھی", "ہر دعا قبول ہوئی، ہر منزل قریب آ گئی",
     "Saath tera jo mila to zindagi muskura uthi, Har dua qabool hui, har manzil qareeb aa gayi",
     "Finding you by my side has made all of life smile; every prayer was answered, and every distant horizon drew near."),
    ("Traditional Nikkah", "wedding", "Do Phool Khilay Hain Ik Shaakh-e-Wafa Par",
     "دو پھول کھلے ہیں اک شاخِ وفا پر", "برکت ہو سدا اس گلشنِ رضا پر",
     "Do phool khilay hain ik shaakh-e-wafa par, Barkat ho sada iss gulshan-e-raza par",
     "Two pure blossoms have bloomed upon a single branch of loyalty; may eternal blessings grace this garden of mutual joy."),
    ("Traditional Nikkah", "wedding", "Duaon Ke Saaye Mein Bandha Hai Yeh Rishta",
     "دعاؤں کے سائے میں بندھا ہے یہ رشتہ", "خدا اس کو رکھے سدا پائیدار",
     "Duaon ke saaye mein bandha hai yeh rishta, Khuda iss ko rakhay sada paaedaar",
     "Under the protective shade of heartfelt prayers, this sacred bond is forged; may the Lord keep it steadfast forever."),
    ("Traditional Nikkah", "wedding", "Nikkah Mubarak Ho Tumhein Dil Ki Gehraaiyon Se",
     "نکاح مبارک ہو تمہیں دل کی گہرائیوں سے", "مہکتی رہے یہ زندگی خوشیوں کی رعنائیوں سے",
     "Nikkah mubarak ho tumhein dil ki gehraaiyon se, Mehakti rahe yeh zindagi khushiyon ki raanaaiyon se",
     "Nikkah Mubarak to you from the depths of our hearts; may this new life forever blossom in joyful elegance."),
    ("Traditional Nikkah", "wedding", "Bandhan Yeh Mohabbat Ka Suroor-e-Qalb Bane",
     "بندھن یہ محبت کا سرورِ قلب بنے", "ہر صبح نئی خوشی کا پیغام سنے",
     "Bandhan yeh mohabbat ka suroor-e-qalb banay, Har subh nayi khushi ka payaam sunay",
     "May this bond of sacred love become the joy of the heart, listening to the glad tidings of fresh happiness every morning."),
    ("Traditional Nikkah", "wedding", "Haathon Mein Haath Liye Chalein Wafa Ki Raah Par",
     "ہاتھوں میں ہاتھ لیے چلیں وفا کی راہ پر", "سایہ فگن رہے رحمت کا ابر ہر گام پر",
     "Haathon mein haath liye chalein wafa ki raah par, Saaya-fagan rahe rehmat ka abr har gaam par",
     "Walking hand in hand upon the path of faithfulness; may the cloud of divine mercy cast its comforting shade upon every step."),
    ("Traditional Nikkah", "wedding", "Khuda Kare Yeh Jori Sada Salaamat Rahe",
     "خدا کرے یہ جوڑی سدا سلامت رہے", "دامن میں ان کے سدا مسرت رہے",
     "Khuda kare yeh jodi sada salaamat rahe, Daaman mein unke sada musarrat rahe",
     "May Almighty Allah keep this lovely couple forever blessed and protected; may perpetual joy fill the folds of their days."),
    ("Traditional Nikkah", "wedding", "Dulhan Ke Roop Mein Noor Chamak Raha Hai",
     "دلہن کے روپ میں نور چمک رہا ہے", "دولہا کے چہرے پہ وقار دمک رہا ہے",
     "Dulhan ke roop mein noor chamak raha hai, Dulha ke chehre pe waqaar damak raha hai",
     "Celestial radiance gleams upon the bride’s countenance; noble dignity shines bright upon the groom’s face."),
    ("Traditional Nikkah", "wedding", "Mehndi Ka Rang Layega Khushiyan Hazaar",
     "مہندی کا رنگ لائے گا خوشیاں ہزار", "سلامت رہے یہ چاہت اور یہ پیار",
     "Mehndi ka rang laayega khushiyan hazaar, Salaamat rahe yeh chaahat aur yeh pyaar",
     "The crimson stain of wedding henna shall usher in thousands of joys; may this mutual tenderness and love endure forever."),
    ("Traditional Nikkah", "wedding", "Sehre Ke Phool Mehkein Duaon Ke Saath",
     "سہرے کے پھول مہکیں دعاؤں کے ساتھ", "آغازِ نو مبارک ہو وفاؤں کے ساتھ",
     "Sehre ke phool mehkein duaon ke saath, Aaghaaz-e-nau mubarak ho wafaon ke saath",
     "May the blossoms of the wedding garland fragrance every prayer; blessed be this fresh dawn woven with enduring faithfulness."),
    ("Traditional Nikkah", "wedding", "Zindagi Ka Naya Safar Ho Pur-Noor",
     "زندگی کا نیا سفر ہو پر نور", "غم کا سایہ رہے ہمیشہ تم سے دور",
     "Zindagi ka naya safar ho pur-noor, Gham ka saaya rahe hamesha tum se door",
     "May this new journey of marriage be illuminated with celestial light; may the shadow of sorrow remain forever distant from you."),
    ("Traditional Nikkah", "wedding", "Khuda Kare Ke Khushiyon Ka Silsila Na Thame",
     "خدا کرے کہ خوشیوں کا سلسلہ نہ تھمے", "ہر آنے والا دن پچھلے سے خوب تر ہو",
     "Khuda kare ke khushiyon ka silsila na thamay, Har aane waala din pichhle se khoob-tar ho",
     "May the cascade of joys never cease; may each arriving tomorrow be far more beautiful than yesterday."),
    ("Traditional Nikkah", "wedding", "Dulhan Ki Palkon Pe Khwaab Saje Hain",
     "دلہن کی پلکوں پہ خواب سجے ہیں", "دونوں کے دل محبت میں بندھے ہیں",
     "Dulhan ki palkon pe khwaab sajay hain, Dono ke dil mohabbat mein bandhay hain",
     "Luminous dreams rest upon the bride's eyelashes; both pure hearts are sealed in sacred love."),
    ("Traditional Nikkah", "wedding", "Rishta-e-Ulfat Saja Hai Aasmaan Ke Tehat",
     "رشتۂ الفت سجا ہے آسمان کے تحت", "خدا عطا فرمائے خیر و برکت ہر وقت",
     "Rishta-e-ulfat saja hai aasmaan ke tehat, Khuda ataa farmaaye khair-o-barkat har waqt",
     "This covenant of affection is adorned beneath the open heavens; may the Lord grant divine goodness and blessings at all times."),
    ("Traditional Nikkah", "wedding", "Wafa Ki Shama Roshan Rahe Sada",
     "وفا کی شمع روشن رہے سدا", "ملن کا یہ جہاں مہکتا رہے سدا",
     "Wafa ki shama roshan rahe sada, Milan ka yeh jahaan mehakta rahe sada",
     "May the candle of loyalty burn luminous forever; may this world of sacred union forever blossom in sweet fragrance."),
    ("Traditional Nikkah", "wedding", "Khushiyon Ki Bahaar Aayi Hai Aangan Mein",
     "خوشیوں کی بہار آئی ہے آنگن میں", "نئی زندگی کی نوید ہے ہر دھڑکن میں",
     "Khushiyon ki bahaar aayi hai aangan mein, Nayi zindagi ki naweed hai har dhadkan mein",
     "The vibrant springtime of happiness has arrived in the courtyard; the glad tidings of a blessed new life beat in every pulse."),

    # --- Poetic Wedding Invocations ---
    ("Allama Iqbal", "wedding", "Noor-e-Nikkah Wa Mohabbat-e-Roohani",
     "ہو محبت کا یہ رشتہ مثلِ خورشیدِ مبیں", "روشن و تابندہ تر ہو ہر سحر اس کی زمیں",
     "Ho mohabbat ka yeh rishta misl-e-khursheed-e-mubeen, Roshan o taabinda-tar ho har sehar iss ki zameen",
     "May this sacred bond of love shine like the brilliant morning sun; may its horizon grow brighter with every breaking dawn."),
    ("Mirza Ghalib", "wedding", "Mubarakbaad-e-Aqad-e-Saeed",
     "مبارک ہو تمہیں یہ بزمِ نشاط", "رہے قائم سدا یہ عیش و انبساط",
     "Mubarak ho tumhein yeh bazm-e-nishaat, Rahe qaayam sada yeh aish-o-inbisaat",
     "Heartfelt congratulations to you upon this joyful assembly; may this delight and serene happiness abide steadfast forever."),
    ("Parveen Shakir", "wedding", "Khushboo-e-Nikkah Wa Dua-e-Dulhan",
     "دعاؤں کے گلابوں سے سجی ہے یہ دلہن", "محبت کی ہواؤں نے بسایا ہے چمن",
     "Duaon ke gulaabon se saji hai yeh dulhan, Mohabbat ki hawaon ne basaaya hai chaman",
     "Adorned with the roses of sincere prayers is this bride; the gentle breezes of love have established this blooming garden."),
    ("Khalil Gibran", "wedding", "Love One Another But Make Not A Bond Of Love",
     "Love one another, but make not a bond of love:", "Let it rather be a moving sea between the shores of your souls.",
     "Love one another, but make not a bond of love: Let it rather be a moving sea between the shores of your souls.",
     "Love one another, but make not a bond of constraint; let love rather be a moving ocean between the quiet shores of your souls."),
    ("Khalil Gibran", "wedding", "Sing And Dance Together And Be Joyous",
     "Sing and dance together and be joyous,", "but let each one of you be alone, even as the strings of a lute are alone.",
     "Sing and dance together and be joyous, but let each one of you be alone...",
     "Sing and dance together and be joyful, yet let each of you retain individuality, just as the strings of a lute vibrate to the same melody."),
    ("William Shakespeare", "wedding", "Let Me Not To The Marriage Of True Minds",
     "Let me not to the marriage of true minds admit impediments.", "Love is not love which alters when it alteration finds.",
     "Let me not to the marriage of true minds admit impediments...",
     "Let me not admit obstacles to the marriage of true minds; love is not love that alters when change is encountered."),
    ("Jalaluddin Rumi", "wedding", "The Minute I Heard My First Love Story",
     "The minute I heard my first love story, I started looking for you,", "not knowing how blind that was. Lovers don't finally meet; they're in each other all along.",
     "The minute I heard my first love story, I started looking for you...",
     "The minute I heard my first love story I began searching for you, not knowing how blind that was. Lovers do not meet at last; they reside in each other all along.")
]

print(f"ISHQ_WEDDING_VERSES loaded: {len(ISHQ_WEDDING_VERSES)} items.")
