# -*- coding: utf-8 -*-
"""
Verses for Khudi (Motivation) & Sufi (Spiritual)
Format: (poet, cat, title, m1, m2, rom, eng)
"""

KHUDI_SUFI_VERSES = [
    # ==========================================
    # KHUDI & MOTIVATION
    # ==========================================
    # --- Allama Iqbal ---
    ("Allama Iqbal", "khudi", "Khudi Ko Kar Buland Itna Ke Har Taqdeer Se Pehle",
     "خودی کو کر بلند اتنا کہ ہر تقدیر سے پہلے", "خدا بندے سے خود پوچھے بتا تیری رضا کیا ہے",
     "Khudi ko kar buland itna ke har taqdeer se pehle, Khuda bande se khud poochhe bata teri raza kya hai",
     "Exalt your Self to such height that before decreeing each destiny, God Himself shall ask you: Tell me, what is your desire?"),
    ("Allama Iqbal", "khudi", "Sitaron Se Aage Jahan Aur Bhi Hain",
     "ستاروں سے آگے جہاں اور بھی ہیں", "ابھی عشق کے امتحان اور بھی ہیں",
     "Sitaron se aage jahan aur bhi hain, Abhi ishq ke imtehan aur bhi hain",
     "Beyond the stars exist yet other realms; other trials of love still await you."),
    ("Allama Iqbal", "khudi", "Tu Shaheen Hai Parwaaz Hai Kaam Tera",
     "تو شاہیں ہے پرواز ہے کام تیرا", "ترے سامنے آسماں اور بھی ہیں",
     "Tu shaheen hai parwaaz hai kaam tera, Tere saamne aasmaan aur bhi hain",
     "You are an eagle; soaring is your destiny; endless skies stretch wide before your wings."),
    ("Allama Iqbal", "khudi", "Nahi Tera Nasheman Qasr-e-Sultani Ke Gumbad Par",
     "نہیں تیرا نشیمن قصرِ سلطانی کے گنبد پر", "تو شاہیں ہے، بسیرا کر پہاڑوں کی چٹانوں میں",
     "Nahi tera nasheman qasr-e-sultani ke gumbad par, Tu shaheen hai, basera kar pahadon ki chattanon mein",
     "Your nest belongs not upon the dome of imperial palaces; you are a royal falcon, make your abode on towering mountain peaks."),
    ("Allama Iqbal", "khudi", "Apni Duniya Aap Paida Kar Agar Zindon Mein Hai",
     "اپنی دنیا آپ پیدا کر اگر زندوں میں ہے", "سرِّ آدم ہے، ضمیرِ کن فکاں ہے زندگی",
     "Apni duniya aap paida kar agar zindon mein hai, Sirr-e-aadam hai, zameer-e-kun fayakoon hai zindagi",
     "Create your own world if you count among the living; life is the secret of Man, the divine conscious spark of Creation."),
    ("Allama Iqbal", "khudi", "Amal Se Zindagi Banti Hai Jannat Bhi Jahannam Bhi",
     "عمل سے زندگی بنتی ہے جنت بھی جہنم بھی", "یہ خاکی اپنی فطرت میں نہ نوری ہے نہ ناری ہے",
     "Amal se zindagi banti hai jannat bhi jahannam bhi, Yeh khaaki apni fitrat mein na noori hai na naari hai",
     "Actions shape human life into Heaven or Hell; for mortal clay by nature is neither celestial light nor infernal fire."),
    ("Allama Iqbal", "khudi", "Manzil Se Aage Badh Kar Manzil Talaash Kar",
     "منزل سے آگے بڑھ کر منزل تلاش کر", "مل جائے تجھ کو دریا تو سمندر تلاش کر",
     "Manzil se aage badh kar manzil talaash kar, Mil jaaye tujh ko darya to samandar talaash kar",
     "Stride beyond the horizon and seek yet higher destinations; if you discover a flowing river, seek the boundless ocean."),
    ("Allama Iqbal", "khudi", "Ki Muhammad Se Wafa Tu Ne To Hum Tere Hain",
     "کی محمد سے وفا تو نے تو ہم تیرے ہیں", "یہ جہاں چیز ہے کیا لوح و قلم تیرے ہیں",
     "Ki Muhammad se wafa tu ne to hum tere hain, Yeh jahaan cheez hai kya lauh-o-qalam tere hain",
     "If you are loyal to the Prophet, then all of creation belongs to you; what is this mortal earth? The Divine Tablet and Pen are yours."),
    ("Allama Iqbal", "khudi", "Dhoondta Phirta Hoon Ai Iqbal Apne Aap Ko",
     "ڈھونڈتا پھرتا ہوں اے اقبال اپنے آپ کو", "آپ ہی گویا مسافر آپ ہی منزل ہوں میں",
     "Dhoondta phirta hoon ai Iqbal apne aap ko, Aap hi goya musaafir aap hi manzil hoon main",
     "I wander searching for my own true self, O Iqbal; as if I myself am the traveler, and I myself the ultimate destination."),
    ("Allama Iqbal", "khudi", "Fard Qaayam Rabt-e-Millat Se Hai Tanha Kuch Nahi",
     "فرد قائم ربطِ ملت سے ہے تنہا کچھ نہیں", "موج ہے دریا میں اور بیرونِ دریا کچھ نہیں",
     "Fard qaayam rabt-e-millat se hai tanha kuch nahi, Mauj hai darya mein aur beroon-e-darya kuch nahi",
     "The individual derives strength from bond with the community; alone he is nothing, as a wave exists within the river and dissolves without."),
    ("Allama Iqbal", "khudi", "Ghulami Mein Na Kaam Aati Hain Shamshirein Na Tadbeerein",
     "غلامی میں نہ کام آتی ہیں شمشیریں نہ تدبیریں", "جو ہو ذوقِ یقیں پیدا تو کٹ جاتی ہیں زنجیریں",
     "Ghulami mein na kaam aati hain shamshirein na tadbeerein, Jo ho zauq-e-yaqeen paida to kat jaati hain zanjeerein",
     "In bondage, neither swords nor clever schemes avail; but when the spark of inner faith is awakened, all iron shackles shatter."),
    ("Allama Iqbal", "khudi", "Nigah-e-Mard-e-Momin Se Badal Jaati Hain Taqdeerein",
     "نگاہِ مردِ مومن سے بدل جاتی ہیں تقدیریں", "جو ہو جائے یقیں محکم تو کٹ جاتی ہیں شمشیریں",
     "Nigaah-e-mard-e-momin se badal jaati hain taqdeerein, Jo ho jaaye yaqeen mohkam to kat jaati hain shamshirein",
     "The focused gaze of the person of faith transforms destiny itself; when conviction is steadfast, opposing swords break away."),
    ("Allama Iqbal", "khudi", "Yaqeen Mohkam Amal Peham Mohabbat Faateh-e-Aalam",
     "یقینِ محکم، عملِ پیہم، محبت فاتحِ عالم", "جہادِ زندگانی میں ہیں یہ مردوں کی شمشیریں",
     "Yaqeen-e-mohkam, amal-e-paiham, mohabbat faateh-e-aalam, Jihaad-e-zindagaani mein hain yeh mardon ki shamshirein",
     "Unyielding faith, ceaseless dynamic action, and world-conquering love—these are the sharp swords in the struggles of life."),
    ("Allama Iqbal", "khudi", "Tere Ilm-o-Mohabbat Ki Nahi Hai Inteha Koi",
     "ترے علم و محبت کی نہیں ہے انتہا کوئی", "نہیں ہے تیرے سینے میں سوا تیرے خدا کوئی",
     "Tere ilm-o-mohabbat ki nahi hai inteha koi, Nahi hai tere seene mein siwa tere Khuda koi",
     "To your knowledge and spiritual love there is no horizon; within your heart resides none other than the One Divine."),
    ("Allama Iqbal", "khudi", "Guzar Jaa Aql Se Aage Ke Yeh Noor-e-Chiragh Hai",
     "گزر جا عقل سے آگے کہ یہ نورِ چراغ ہے", "دل کی بینائی سے پیدا نیا جہان کر",
     "Guzar jaa aql se aage ke yeh noor-e-chiragh hai, Dil ki beenaai se paida naya jahaan kar",
     "Step beyond cold intellect, for it is merely a road lamp; through the inner vision of the soul, birth an illuminated new world."),
    ("Allama Iqbal", "khudi", "Khudi Ka Sirr-e-Nihaan La Ilaha Illallah",
     "خودی کا سرِّ نہاں لا الٰہ الا اللہ", "خودی ہے تیغ فساں لا الٰہ الا اللہ",
     "Khudi ka sirr-e-nihaan La ilaha illallah, Khudi hai tegh-e-fasaan La ilaha illallah",
     "The concealed secret of Selfhood is 'There is no god but Allah'; the Self is a whetted blade sharpened on Divine Unity."),
    ("Allama Iqbal", "khudi", "Parwaaz Hai Dono Ki Issi Ek Faza Mein",
     "پرواز ہے دونوں کی اسی ایک فضا میں", "کرگس کا جہاں اور ہے شاہیں کا جہاں اور",
     "Parwaaz hai dono ki issi aik faza mein, Kargas ka jahaan aur hai shaheen ka jahaan aur",
     "Both fly in the selfsame sky; yet the world of the vulture is one, and the majestic realm of the falcon is entirely another."),
    ("Allama Iqbal", "khudi", "Moti Samajh Ke Shaan-e-Karimi Ne Chun Liye",
     "موتی سمجھ کے شانِ کریمی نے چن لیے", "قطرے جو تھے مرے عرقِ انفعال کے",
     "Moti samajh ke shaan-e-kareemi ne chun liye, Qatre jo thay mere araq-e-infa'aal ke",
     "The Divine Grace gathered them like precious pearls—the drops that fell from my brow in repentant humility."),
    ("Allama Iqbal", "khudi", "Uqaabi Rooh Jab Bedaar Hoti Hai Jawanon Mein",
     "عقابی روح جب بیدار ہوتی ہے جوانوں میں", "نظر آتی ہے ان کو اپنی منزل آسمانوں میں",
     "Uqaabi rooh jab bedaar hoti hai jawanon mein, Nazar aati hai unko apni manzil aasmaanon mein",
     "When the soaring spirit of the eagle awakens in the youth, they behold their true destination in the boundless heavens."),
    ("Allama Iqbal", "khudi", "Nishan-e-Raah Dikhate Thay Jo Sitaaron Ko",
     "نشانِ راہ دکھاتے تھے جو ستاروں کو", "ترس گئے ہیں کسی رہبرِ شناسا کو",
     "Nishaan-e-raah dikhaate thay jo sitaaron ko, Taras gaye hain kisi rehbar-e-shanaasa ko",
     "Those who once guided the course of distant stars have grown thirsty for a visionary guide of truth."),

    # --- Habib Jalib & Josh & Faiz & World ---
    ("Habib Jalib", "khudi", "Zulm Rahe Aur Amn Bhi Ho",
     "ظلم رہے اور امن بھی ہو", "کیا ممکن ہے تم ہی کہو",
     "Zulm rahe aur amn bhi ho, Kya mumkin hai tum hi kaho",
     "That tyranny endure while peace thrives—tell me, is that ever possible? Speak the truth!"),
    ("Habib Jalib", "khudi", "Deep Jis Ka Mahallaat Hi Mein Jale",
     "دیپ جس کا محلات ہی میں جلے", "ایسے دستور کو صبحِ بے نور کو میں نہیں مانتا",
     "Deep jis ka mahallaat hi mein jalay, Aisay dastoor ko subh-e-be-noor ko main nahi maanta",
     "A lamp that shines only in imperial palaces—such an unjust system, such a sunless dawn, I refuse to accept!"),
    ("Habib Jalib", "khudi", "Sach Kehne Ka Zauq Jo Hai Woh Mitaa Nahi Sakte",
     "سچ کہنے کا ذوق جو ہے وہ مٹا نہیں سکتے", "ہم اہلِ قلم ہیں ہم کو جھکا نہیں سکتے",
     "Sach kehne ka zauq jo hai woh mitaa nahi sakte, Hum ahl-e-qalam hain hum ko jhuka nahi sakte",
     "The burning passion to utter truth cannot be extinguished; we are the bearers of the pen, we cannot be bowed."),
    ("Josh Malihabadi", "khudi", "Kaam Hai Mera Taghayyur Naam Hai Mera Shabab",
     "کام ہے میرا تغیر نام ہے میرا شباب", "میرا نعرہ انقلاب و انقلاب و انقلاب",
     "Kaam hai mera taghayyur naam hai mera shabaab, Mera naara inqilaab o inqilaab o inqilaab",
     "My task is transformation, my name is youth; my triumphant cry is renewal, revolution, and awakening!"),
    ("Josh Malihabadi", "khudi", "Aql Parasti Ka Parda Chaak Kar De",
     "عقل پرستی کا پردہ چاک کر دے", "اپنے عزم کو فولاد کی طرح سخت کر دے",
     "Aql parasti ka parda chaak kar de, Apne azm ko folaad ki tarah sakht kar de",
     "Tear away the veil of timid hesitation; temper your inner resolve as hard as unyielding steel."),
    ("Maya Angelou", "khudi", "Still I Rise Like Dust I Rise",
     "You may write me down in history with your bitter, twisted lies,", "You may trod me in the very dirt, but still, like dust, I'll rise.",
     "You may write me down in history with your bitter, twisted lies... But still, like dust, I'll rise.",
     "You may write me down with bitter lies, you may tread me in the dirt; but still, like dust, I shall rise triumphant."),
    ("Maya Angelou", "khudi", "Just Like Moons And Like Suns",
     "Just like moons and like suns, with the certainty of tides,", "Just like hopes springing high, still I'll rise.",
     "Just like moons and like suns, with the certainty of tides, Still I'll rise.",
     "Like celestial moons and suns, with the inevitability of ocean tides, like hopes leaping high, I will rise."),
    ("Rudyard Kipling", "khudi", "If You Can Keep Your Head When All About You",
     "If you can keep your head when all about you are losing theirs,", "Yours is the Earth and everything that's in it, and you'll be a Man.",
     "If you can keep your head when all about you are losing theirs...",
     "If you can maintain calm mastery when others lose theirs and blame you, yours is the earth and all its promise."),
    ("Alfred Lord Tennyson", "khudi", "To Strive To Seek To Find And Not To Yield",
     "Tho' much is taken, much abides; and though we are not now that strength", "One equal temper of heroic hearts, made weak by time, but strong in will: to strive, to seek, to find, and not to yield.",
     "To strive, to seek, to find, and not to yield...",
     "Though much is taken, much endures; strong in will to strive, to seek, to find, and never to yield."),
    ("Robert Frost", "khudi", "The Woods Are Lovely Dark And Deep",
     "The woods are lovely, dark and deep,", "But I have promises to keep, and miles to go before I sleep.",
     "The woods are lovely, dark and deep, But I have promises to keep...",
     "The forest is enchanting, dark and deep; yet I have sacred promises to honor, and miles to journey before I sleep."),

    # ==========================================
    # SUFI & SPIRITUAL
    # ==========================================
    # --- Baba Bulleh Shah ---
    ("Baba Bulleh Shah", "sufi", "Tere Ishq Nachaya Kar Ke Thaiya Thaiya",
     "تیرے عشق نچایا کر کے تھیا تھیا", "تیرے ناں دا ورد کریندا دل دا رندا",
     "Tere ishq nachaya kar ke thaiya thaiya, Tere naan da wird kareenda dil da randa",
     "Your divine love has made me dance in ecstatic surrender; my restless heart beats solely to the rhythm of Your sacred name."),
    ("Baba Bulleh Shah", "sufi", "Bulleya Ki Jaana Main Kaun",
     "بلھیا کی جاناں میں کون", "نہ میں مومن وچ مسیت ہاں، نہ میں پاکاں وچ پلیت ہاں",
     "Bulleya ki jaana main kaun, Na main momin vich maseet aan, na main paakaan vich paleet aan",
     "O Bulleh, what know I of who I am? Neither confined to formal mosques, nor defined by dogma; I am lost in the Beloved."),
    ("Baba Bulleh Shah", "sufi", "Makkeh Gayan Gal Mukdi Nahi",
     "مکے گیاں گل مکدی ناہیں", "بھاویں سو سو حج کر آئیے",
     "Makkeh gayan gal mukdi naahi, Bhawein sau sau hajj kar aaiye",
     "Journeying to Mecca settles not the soul's quest, even though you perform a hundred pilgrimages, unless the ego dissolves."),
    ("Baba Bulleh Shah", "sufi", "Je Dil Wich Ishq Da Deeva Balay",
     "جے دل وچ عشق دا دیوا بلے", "تاں ہر اک منزل سوکھی ملے",
     "Je dil vich ishq da deeva balay, taan har ik manzil saukhi milay",
     "When the lamp of divine love is kindled within the heart, every difficult horizon is attained with effortless ease."),
    ("Baba Bulleh Shah", "sufi", "Padh Padh Ilm Hazaar Kitaaban",
     "پڑھ پڑھ علم ہزار کتاباں، کدے اپنے آپ نوں پڑھیا نہیں", "بجھ جا دل دے چور نوں بلھیا، کعبہ دل وچ وسدا ھے",
     "Padh padh ilm hazaar kitaaban, kaday apne aap noon padheya nahi, Bujh jaa dil de chor noon Bulleya, Kaaba dil vich wasda hai",
     "You read thousands of scholarly books, yet never read your own inner soul; catch the thief within, Bulleh, the true sanctuary dwells inside."),
    ("Baba Bulleh Shah", "sufi", "Ik Nuktay Wich Gal Mukdi Hai",
     "اک نقطے وچ گل مکدی ہے", "پھڑ نکتہ چھڈ حساباں نوں",
     "Ik nuktay vich gal mukdi hai, Phad nukta chhad hisaabaan noon",
     "The entire truth concludes within a single point; grasp that Divine Point and abandon all calculating arguments."),
    ("Baba Bulleh Shah", "sufi", "Ranjha Ranjha Kardi Hun Main Aape Ranjha Hoi",
     "رانجھا رانجھا کردی ہن میں آپے رانجھا ہوئی", "سدو نی مینوں دھیدو رانجھا، ہیر نہ آکھو کوئی",
     "Ranjha Ranjha kardi hun main aape Ranjha hoi, Saddo ni meenoon Dheedo Ranjha, Heer na aakho koi",
     "Repeating 'Ranjha, Ranjha' ceaselessly, I have become Ranjha myself; call me Dheedo Ranjha, let no one call me Heer anymore."),
    ("Baba Bulleh Shah", "sufi", "Mera Piya Ghar Aaya Sanu Mil Gayi Wadhayi",
     "میرا پیا گھر آیا سانوں مل گئی ودھائی", "اج سکھ دا دیوا بلیا ہر پاسے روشنائی",
     "Mera piya ghar aaya saanoon mil gayi wadhaayi, Aaj sukh da deeva baleya har paasay roshnaayi",
     "My Beloved has returned home; glad felicitations surround us! Today the lamp of peace is kindled and brilliance illuminates every space."),

    # --- Sultan Bahu ---
    ("Sultan Bahu", "sufi", "Alif Allah Chambe Di Booti Mann Mere Wich Murshid Laai Hoo",
     "الف اللہ چنبے دی بوٹی، من میرے وچ مرشد لائی ھو", "نفی اثبات دا پانی ملیا، ہر رگے ہر جائی ھو",
     "Alif Allah chambe di booti, mann mere vich murshid laai Hoo, Nafi asbaat da paani mileya, har ragay har jaai Hoo",
     "The Master planted the jasmine sapling of Allah’s name in my soul; watered with truth, its fragrance fills every space."),
    ("Sultan Bahu", "sufi", "Dil Kaaley Kolo Munh Kaala Changa",
     "دل کالے کولوں منہ کالا چنگا، جے کوئی اس نوں جانے ھو", "منہ کالا ہووے جگ دیکھدا، دل کالا کفر کماوے ھو",
     "Dil kaaley kolo munh kaala changa, je koi uss noon jaane Hoo, Munh kaala howay jag dekhda, dil kaala kufr kamaaway Hoo",
     "Better a blackened face than a blackened heart, if only one truly understands; a dark face is seen by mortals, a dark heart harbors deceit."),
    ("Sultan Bahu", "sufi", "Eeman Salamat Har Koyi Mangay",
     "ایمان سلامت ہر کوئی منگے، عشق سلامت کوئی نہ منگے ھو", "منگن ایمان شرماون عشقوں، دل نوں غیر نال رنگے ھو",
     "Eeman salaamat har koyi mangay, ishq salaamat koyi na mangay Hoo, Mangan eeman sharmaawan ishqon, dil noon ghair naal rangay Hoo",
     "Everyone prays for safety of their creed, but none asks for safety of ecstatic Love; they seek safety yet shy from Love's divine fire."),
    ("Sultan Bahu", "sufi", "Baghdad Shehar Di Ki Wadhayi",
     "بغداد شہر دی کی وڈیائی، جتھے پیر جیلانی وسدے ھو", "جس دل وچ اوہ وس جاوے، اوتھے رحمت دے دریا وگدے ھو",
     "Baghdad shehar di ki waddyaayi, jithay Peer Jilaani wasday Hoo, Jis dil vich ohu was jaaway, othe rehmat de darya wagday Hoo",
     "Great is the glory of Baghdad where the saintly master dwells; in whichever heart he resides, rivers of mercy flow without end."),

    # --- Jalaluddin Rumi ---
    ("Jalaluddin Rumi", "sufi", "Out Beyond Ideas Of Wrongdoing And Rightdoing",
     "از کفر و ز اسلام برون صحرائیست", "ما را به میان آن فضا سودائیست",
     "Az kufr o ze islam baroon sahraa-eest, Ma ra ba miyaan-e aan faza sauda-eest",
     "Out beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there; when the soul lies down in that grass, the world is too full to talk about."),
    ("Jalaluddin Rumi", "sufi", "Bishno Az Nai Choon Hikayat Meekonad",
     "بشنو از نی چون حکایت می‌کند", "از جدایی‌ها شکایت می‌کند",
     "Bishno az nai choon hikayat meekonad, Az judaai-haa shikayat meekonad",
     "Listen to the reed flute as it tells its tale, lamenting the ache of separation from its reed-bed origin."),
    ("Jalaluddin Rumi", "sufi", "The Wound Is The Place Where The Light Enters You",
     "The wound is the place where the Light enters you.", "Do not grieve. Anything you lose comes round in another form.",
     "The wound is the place where the Light enters you...",
     "The wound is the sacred portal through which Divine Light enters your being; do not despair, for divine love renews all things."),
    ("Jalaluddin Rumi", "sufi", "You Are Not A Drop In The Ocean",
     "You are not a drop in the ocean.", "You are the entire ocean in a drop.",
     "You are not a drop in the ocean. You are the entire ocean in a drop.",
     "You are not merely a single drop in the ocean; you are the vast, entire ocean present in a single drop."),
    ("Jalaluddin Rumi", "sufi", "Let The Beauty Of What You Love Be What You Do",
     "Let the beauty of what you love be what you do.", "There are hundreds of ways to kneel and kiss the ground.",
     "Let the beauty of what you love be what you do...",
     "Let the sublime beauty of what you adore become what you practice; there exist a thousand ways to bow and kiss the earth in devotion."),
    ("Jalaluddin Rumi", "sufi", "Silence Is The Language Of God",
     "Silence is the language of God,", "all else is poor translation.",
     "Silence is the language of God, all else is poor translation.",
     "Stillness and silence are the mother tongue of the Divine; all spoken words are but humble translations."),

    # --- Amir Khusro ---
    ("Amir Khusro", "sufi", "Chaap Tilak Sab Chheeni Re Mose Naina Milayike",
     "چھاپ تلک سب چھینی رے موسے نیناں ملائی کے", "بات اگم کہہ دینی رے موسے نیناں ملائی کے",
     "Chaap tilak sab chheeni re mose naina milaayi ke, Baat agam keh deeni re mose naina milaayi ke",
     "You stripped away my pride and outward appearance with a single gaze; you whispered the unspoken divine secret with your eyes."),
    ("Amir Khusro", "sufi", "Zehal-e-Miskeen Makun Taghaful Dora-e-Naina",
     "زحالِ مسکیں مکن تغافل دورائے نیناں بنائے بتیاں", "کہ تابِ ہجراں ندارم اے جاں، نہ لیہو کاہے لگائے چھتیاں",
     "Zehal-e-miskeen makun taghaful doraaye naina banaaye batiyan, Ke taab-e-hijraan nadaaram ai jaan, na leeho kaahay lagaaye chhatiyan",
     "Neglect not this humble lover by turning away your eyes; for I have no endurance for separation, why hold me not close to your heart?"),
    ("Amir Khusro", "sufi", "Kusro Darya Prem Ka Ulti Wa Ki Dhaar",
     "خسرو دریا پریم کا، الٹی وا کی دھار", "جو اترا سو ڈوب گیا، جو ڈوبا سو پار",
     "Khusro darya prem ka, ulti wa ki dhaar, Jo utra so doob gaya, jo dooba so paar",
     "O Khusro, wondrous is the river of divine love; its current flows in reverse: he who tries to swim it drowns, and he who drowns crosses safe.")
]

print(f"KHUDI_SUFI_VERSES loaded: {len(KHUDI_SUFI_VERSES)} items.")
