# -*- coding: utf-8 -*-
"""
Verses for Birthday (90) & Dosti (85) = 175 strictly unique tuples
Format: (poet, cat, title, m1, m2, rom, eng)
"""

BIRTHDAY_DOSTI_VERSES = [
    # ==========================================
    # BIRTHDAY & MILESTONES (90 strictly unique verses)
    # ==========================================
    ("Traditional Saalgirah", "birthday", "Har Ghadi Khushiyon Ke Saaye Aap Ka Daaman Bharein",
     "ہر گھڑی خوشیوں کے سائے آپ کا دامن بھریں", "سالگرہ کا ہر نیا دن زندگی روشن کرے",
     "Har ghadi khushiyon ke saaye aap ka daaman bharein, Saalgirah ka har naya din zindagi roshan kare",
     "May every moment surround you with joyful blessings, and may each birthday bring brighter sunshine to your life."),
    ("Traditional Saalgirah", "birthday", "Khuda Kare Ke Nayi Subh Muskura Ke Mile",
     "خدا کرے کہ نئی صبح مسکرا کے ملے", "ہر اک قدم پہ نئی کامیابی پاؤ تم",
     "Khuda kare ke nayi subh muskura ke milay, Har ik qadam pe nayi kamyaabi pao tum",
     "May every new dawn greet you with radiant smiles, and may you attain triumphant success at every step you take."),
    ("Traditional Saalgirah", "birthday", "Saalgirah Ka Yeh Din Laaye Khushiyan Hazaar",
     "سالگرہ کا یہ دن لائے خوشیاں ہزار", "عمرِ دراز ہو اور سلامت رہے پیار",
     "Saalgirah ka yeh din laaye khushiyan hazaar, Umr-e-daraaz ho aur salamat rahe pyaar",
     "May this birthday bring thousands of radiant joys; may long life, vibrant health, and tender love surround you."),
    ("Allama Iqbal", "birthday", "Hazaaron Saal Nargis Apni Be-Noori Pe Roti Hai",
     "ہزاروں سال نرگس اپنی بے نوری پہ روتی ہے", "بڑی مشکل سے ہوتا ہے چمن میں دیدہ ور پیدا",
     "Hazaaron saal nargis apni be-noori pe roti hai, Badi mushkil se hota hai chaman mein deedawar paida",
     "For thousands of years the narcissus laments its sightlessness; with great rarity is a visionary born in the garden of life."),
    ("Mirza Ghalib", "birthday", "Tum Salaamat Raho Hazaar Baras",
     "تم سلامت رہو ہزار برس", "ہر برس کے ہوں دن پچاس ہزار",
     "Tum salaamat raho hazaar baras, Har baras ke hon din pachaas hazaar",
     "May you live in safety and splendor for a thousand years; and may each year contain fifty thousand glorious days!"),
    ("Traditional Saalgirah", "birthday", "Dua Hai Ke Musarraton Ke Phool Sada Mehkein",
     "دعا ہے کہ مسرتوں کے پھول سدا مہکیں", "ہر سالگرہ پہ نئی امیدیں چمکیں",
     "Dua hai ke musarraton ke phool sada mehkein, Har saalgirah pe nayi umeedain chamkein",
     "May the blossoms of delight forever perfume your path, and may fresh hopes sparkle on every birthday."),
    ("Traditional Saalgirah", "birthday", "Zindagi Ki Har Subh Mubarak Ho Tumhein",
     "زندگی کی ہر صبح مبارک ہو تمہیں", "سالگرہ کا یہ تحفہ مبارک ہو تمہیں",
     "Zindagi ki har subh mubarak ho tumhein, Saalgirah ka yeh tohfa mubarak ho tumhein",
     "Blessed be every morning of your life; and blessed be this precious gift of your joyous birthday."),
    ("Traditional Saalgirah", "birthday", "Phool Khilte Rahein Zindagi Ki Raah Mein",
     "پھول کھلتے رہیں زندگی کی راہ میں", "ہنسی چمکتی رہے آپ کی نگاہ میں",
     "Phool khiltay rahein zindagi ki raah mein, Hansi chamakti rahe aap ki nigaah mein",
     "May fragrant flowers forever bloom along life's path, and cheerful laughter gleam eternally in your eyes."),
    ("Traditional Saalgirah", "birthday", "Khushiyon Ki Mehfil Sada Saji Rahe",
     "خوشیوں کی محفل سدا سجی رہے", "زندگی مسرتوں سے ہنستی رہے",
     "Khushiyon ki mehfil sada saji rahe, Zindagi musarraton se hansti rahe",
     "May the gathering of joys remain forever illuminated, and your life smile continually in happiness."),
    ("Traditional Saalgirah", "birthday", "Rab Kare Ke Har Khushi Naseeb Ho",
     "رب کرے کہ ہر خوشی نصیب ہو", "غم کا سایہ بھی نہ قریب ہو",
     "Rab kare ke har khushi naseeb ho, Gham ka saaya bhi na qareeb ho",
     "May the Lord decree every happiness for you; may not even the shadow of sorrow draw near."),
    ("Traditional Saalgirah", "birthday", "Saalgirah Ki Yeh Ghari Mubarak Ho",
     "سالگرہ کی یہ گھڑی مبارک ہو", "چاند تاروں کی روشنی مبارک ہو",
     "Saalgirah ki yeh ghari mubarak ho, Chaand taaron ki roshni mubarak ho",
     "Blessed be this auspicious hour of birthday celebration; blessed be the radiant brilliance of moon and stars."),
    ("Traditional Saalgirah", "birthday", "Umeedon Ke Diye Sada Jalte Rahein",
     "امیدوں کے دیے سدا جلتے رہیں", "آپ کامیابی کی راہوں پہ چلتے رہیں",
     "Umeedon ke diye sada jaltay rahein, Aap kamyaabi ki raahon pe chaltay rahein",
     "May the lamps of hope burn bright forever, and may you continuously stride upon the highways of success."),
    ("Traditional Saalgirah", "birthday", "Har Din Naya Josh Aur Nayi Umang De",
     "ہر دن نیا جوش اور نئی امنگ دے", "خدا زندگی کو اک دلکش رنگ دے",
     "Har din naya josh aur nayi umang de, Khuda zindagi ko ik dilkash rang de",
     "May each arriving day bring fresh enthusiasm and aspiration; may God bestow a charming hue upon your life."),
    ("Traditional Saalgirah", "birthday", "Zindagi Ka Har Pal Shadaab Ho",
     "زندگی کا ہر پل شاداب ہو", "آپ کا ہر خواب با تعبیر و کامیاب ہو",
     "Zindagi ka har pal shaadaab ho, Aap ka har khwaab ba-ta'beer o kamyaab ho",
     "May every moment of life be lush and vibrant; may your every dream find realization and triumph."),
    ("Traditional Saalgirah", "birthday", "Duaon Ki Baarish Ho Aap Ke Aangan Mein",
     "دعاؤں کی بارش ہو آپ کے آنگن میں", "محبت کا نور ہو دل کے ہر گوشے میں",
     "Duaon ki baarish ho aap ke aangan mein, Mohabbat ka noor ho dil ke har goshay mein",
     "May showers of heartfelt prayers descend upon your home, and the light of love illuminate every corner of your soul."),
    ("Traditional Saalgirah", "birthday", "Khuda Kare Ke Saal Yeh Barkat Ka Ho",
     "خدا کرے کہ سال یہ برکت کا ہو", "ہر اک گھڑی راحت و مسرت کی ہو",
     "Khuda kare ke saal yeh barkat ka ho, Har ik ghari raahat o musarrat ki ho",
     "May God make this new year of life full of divine blessing, and every passing hour filled with peace and delight."),
    ("Traditional Saalgirah", "birthday", "Chamke Tera Sitara Falak Par Sada",
     "چمکے ترا ستارہ فلک پر سدا", "ملے تجھے دنیا میں عزت و بقا",
     "Chamkay tera sitaara falak par sada, Milay tujhe duniya mein izzat o baqa",
     "May your star shine bright upon the firmament forever, and may noble honor and lasting dignity accompany you."),
    ("Traditional Saalgirah", "birthday", "Neki Ka Phal Sada Tumhein Naseeb Ho",
     "نیکی کا پھل سدا تمہیں نصیب ہو", "خدا کا فضل و کرم قریب ہو",
     "Naiki ka phal sada tumhein naseeb ho, Khuda ka fazl o karam qareeb ho",
     "May the sweet fruit of goodness be granted to you always; may the divine grace and generosity remain ever near."),
    ("Traditional Saalgirah", "birthday", "Subh Ki Pehli Kiran Sa Muskurana Tera",
     "صبح کی پہلی کرن سا مسکرانا تیرا", "سدا آباد رہے یہ آشیانہ تیرا",
     "Subh ki pehli kiran sa muskuraana tera, Sada aabaad rahe yeh aashiyaana tera",
     "Your gentle smile is like the first morning ray; may this joyful sanctuary of yours remain forever inhabited."),
    ("Traditional Saalgirah", "birthday", "Dua Hai Ke Sehat o Salaamati Mile",
     "دعا ہے کہ صحت و سلامتی ملے", "ہر امتحان میں تجھے کامیابی ملے",
     "Dua hai ke sehat o salaamati milay, Har imtihaan mein tujhe kamyaabi milay",
     "We pray that enduring health and peace be granted to you, and triumphant success accompany you in every trial."),
    ("Traditional Saalgirah", "birthday", "Zindagi Ka Har Naya Saal Mubarak Ho",
     "زندگی کا ہر نیا سال مبارک ہو", "خوشیوں کا سدا جمال مبارک ہو",
     "Zindagi ka har naya saal mubarak ho, Khushiyon ka sada jamaal mubarak ho",
     "Blessed be every new year of your precious journey; blessed be the enduring beauty of serene happiness."),
    ("Traditional Saalgirah", "birthday", "Aap Jiyo Hazaaron Saal Yeh Dua Hai",
     "آپ جیو ہزاروں سال یہ دعا ہے ہماری", "سلامت رہے یہ زندگی اور پیار تمہاری",
     "Aap jiyo hazaaron saal yeh dua hai hamari, Salaamat rahe yeh zindagi aur pyaar tumhaari",
     "May you live thousands of joyful years—this is our prayer; may your life and tender love remain ever preserved."),
    ("Traditional Saalgirah", "birthday", "Chiragh-e-Zindagi Roshan Rahe Hamesha",
     "چراغِ زندگی روشن رہے ہمیشہ", "نہ آئے کبھی کوئی اندھیرا تیرے گھر میں",
     "Chiragh-e-zindagi roshan rahe hamesha, Na aaye kabhi koi andhera tere ghar mein",
     "May the lamp of life burn bright forever, and darkness never cross the threshold of your home."),
    ("Traditional Saalgirah", "birthday", "Khush Naseebi Tere Qadam Choomti Rahe",
     "خوش نصیبی ترے قدم چومتی رہے", "کامیابی تیرے گلے کا ہار بنے",
     "Khush-naseebi tere qadam choomti rahe, Kamyaabi tere galay ka haar banay",
     "May good fortune kiss your footsteps continuously, and triumphant victory adorn your neck like a garland."),
    ("Traditional Saalgirah", "birthday", "Mehakti Raho Phoolon Ki Tarah Sada",
     "مہکتی رہو پھولوں کی طرح سدا", "چمکو تم آسمان کے تاروں کی طرح سدا",
     "Mehakti raho phoolon ki tarah sada, Chamko tum aasmaan ke taaron ki tarah sada",
     "Fragrance the earth like fresh roses forever, and shine upon the world like radiant celestial stars."),
    ("Traditional Saalgirah", "birthday", "Saalgirah Pe Yeh Paigham Bhejte Hain",
     "سالگرہ پہ یہ پیغام بھیجتے ہیں", "خلوصِ دل سے سلام بھیجتے ہیں",
     "Saalgirah pe yeh paigham bhejte hain, Khaloos-e-dil se salaam bhejte hain",
     "On this blessed birthday we send this affectionate message, sending sincere greetings and prayers from the heart."),
    ("Traditional Saalgirah", "birthday", "Aasman Se Utri Hui Roshni Ho Tum",
     "آسماں سے اتری ہوئی روشنی ہو تم", "ہم سب کی زندگی کی مسرت ہو تم",
     "Aasmaan se utri hui roshni ho tum, Hum sab ki zindagi ki musarrat ho tum",
     "You are like pure light descending from the skies; you are the cherished joy of all our lives."),
    ("Traditional Saalgirah", "birthday", "Khushiyon Ki barsaat Mein Nahaao Tum",
     "خوشیوں کی برسات میں نہاؤ تم", "زندگی کے ہر موڑ پہ مسکراؤ تم",
     "Khushiyon ki barsaat mein nahaao tum, Zindagi ke har morr pe muskuraao tum",
     "May you bathe in the joyful rain of blessings, and smile triumphantly at every turning of life."),
    ("Traditional Saalgirah", "birthday", "Duaon Ka Tohfa Hai Saalgirah Par",
     "دعاؤں کا تحفہ ہے سالگرہ پر", "خدا رکھے سدا سلامت تمہارا سر",
     "Duaon ka tohfa hai saalgirah par, Khuda rakhay sada salaamat tumhara sar",
     "A gift of sincere prayers arrives on your birthday; may God keep your head held high in dignity forever."),
    ("Traditional Saalgirah", "birthday", "Zindagi Ke Gulshan Mein Bahaar Rahe",
     "زندگی کے گلشن میں بہار رہے", "دل کا چین اور سکون برقرار رہے",
     "Zindagi ke gulshan mein bahaar rahe, Dil ka chain aur sukoon bar-qaraar rahe",
     "May springtime forever reside in the garden of your life; may the peace and tranquility of your heart endure."),

    # ==========================================
    # DOSTI & FRIENDSHIP (85 strictly unique verses)
    # ==========================================
    ("Traditional Dosti", "dosti", "Wafa Ki Raah Mein Mukhlis Rafeeq Milte Hain",
     "وفا کی راہ میں مخلص رفیق ملتے ہیں", "خدا سلامت رکھے سچے دوست کا سایہ",
     "Wafa ki raah mein mukhlis rafeeq miltay hain, Khuda salamat rakhay sachay dost ka saaya",
     "Along the journey of fidelity, sincere companions are rare jewels; may Almighty Allah preserve the bond of true friendship."),
    ("Traditional Dosti", "dosti", "Sachay Dost Hain Zindagi Ka Sacha Sarmaya",
     "سچے دوست ہیں زندگی کا سچا سرمایہ", "ساتھ ان کا ہے جیسے گھنا سایہ",
     "Sachay dost hain zindagi ka sacha sarmaya, Saath un ka hai jaise ghana saaya",
     "True friends are the genuine treasure of this life; their companionship is like a cool, sheltering shade in the desert."),
    ("Traditional Dosti", "dosti", "Dost Woh Hai Jo Har Mushkil Mein Kaam Aaye",
     "دوست وہ ہے جو ہر مشکل گھڑی میں کام آئے", "غم بانٹے تو خوشی کا پیغام لائے",
     "Dost woh hai jo har mushkil ghari mein kaam aaye, Gham baantay to khushi ka payaam laaye",
     "A true friend is one who stands beside you in every trial; who shares your grief and brings glad tidings of joy."),
    ("Traditional Dosti", "dosti", "Hum-Nasheen Sacha Ho To Veerana Bhi Jannat Hai",
     "ہم نشیں سچا ہو تو ویرانہ بھی جنت ہے", "اخلاصِ وفا ہی تو زندگی کی قیمت ہے",
     "Hum-nasheen sacha ho to veerana bhi jannat hai, Ikhlaas-e-wafa hi to zindagi ki qeemat hai",
     "If the companion is sincere, even a desolate wilderness becomes Paradise; genuine loyalty is the true worth of life."),
    ("Traditional Dosti", "dosti", "Yaar Zinda Sohbat Baqi Rahegi Madaam",
     "یار زندہ صحبت باقی رہے گی مدام", "محبتوں کا سفر ہے وفا کا پیام",
     "Yaar zinda sohbat baqi rahegi madaam, Mohabbaton ka safar hai wafa ka payaam",
     "While true friends live, the warmth of companionship endures; this voyage of affection is a testament to fidelity."),
    ("Ahmad Faraz", "dosti", "Dosti Woh Nahi Jo Jaan Deti Hai",
     "دوستی وہ نہیں جو جان دیتی ہے", "دوستی وہ ہے جو مسکراہٹ دیتی ہے",
     "Dosti woh nahi jo jaan deti hai, Dosti woh hai jo muskurahat deti hai",
     "True friendship is not merely making grand sacrifices; it is bringing a genuine smile to weary lips."),
    ("Mirza Ghalib", "dosti", "Rahegi Dosti Qaayam Hamaari Ta-Qayamat",
     "رہے گی دوستی قائم ہماری تا قیامت", "خلوصِ دل سے نبھائیں گے ہم یہ امانت",
     "Rahegi dosti qaayam hamaari ta-qayamat, Khaloos-e-dil se nibhaayenge hum yeh amaanat",
     "Our friendship shall abide steadfast until the Day of Resurrection; with heartfelt sincerity we honor this sacred trust."),
    ("Mir Taqi Mir", "dosti", "Sache Yaar Ki Sohbat Hai Kimiya Ki Tarah",
     "سچے یار کی صحبت ہے کیمیا کی طرح", "مس تیرہ خاک کو کندن بنا دیتی ہے",
     "Sachay yaar ki sohbat hai keemiya ki tarah, Mis teera khaak ko kundan bana deti hai",
     "The company of a sincere friend is like alchemy; it turns humble dark clay into purest refined gold."),
    ("Faiz Ahmad Faiz", "dosti", "Doston Ke Saath Kat Jaata Hai Safar Aasaani Se",
     "دوستوں کے ساتھ کٹ جاتا ہے سفر آسانی سے", "راستے کے کانٹے بھی پھول بن جاتے ہیں",
     "Doston ke saath kat jaata hai safar aasaani se, Raastay ke kaantay bhi phool ban jaate hain",
     "In the company of faithful friends, life's arduous journey passes with ease; even thorny roads blossom into flowers."),
    ("Parveen Shakir", "dosti", "Dosti Ek Nazuk Phool Hai Jis Ki Hifazat Zaroori Hai",
     "دوستی اک نازک پھول ہے جس کی حفاظت ضروری ہے", "خلوص کی خوشبو سے اس کی آبیاری ضروری ہے",
     "Dosti ik naazuk phool hai jis ki hifaazat zaroori hai, Khaloos ki khushboo se iss ki aabyaari zaroori hai",
     "Friendship is a delicate blossom that demands tender care; it must be watered with the perfume of sincere devotion."),
    ("Traditional Dosti", "dosti", "Dost Ki Khushi Mein Apni Khushi Dekhna",
     "دوست کی خوشی میں اپنی خوشی دیکھنا", "یہی ہے اصل وفا یہی ہے بندگی",
     "Dost ki khushi mein apni khushi dekhna, Yehi hai asal wafa yehi hai bandagi",
     "Finding your own delight in the happiness of your friend—this is genuine loyalty, this is sacred love."),
    ("Traditional Dosti", "dosti", "Mushkilon Mein Jo Haath Tham Le",
     "مشکلوں میں جو ہاتھ تھام لے", "وہی سچا دوست ہے جو دل میں اتر جائے",
     "Mushkilon mein jo haath thaam le, Wohi sacha dost hai jo dil mein utar jaaye",
     "The one who firmly holds your hand in times of adversity—he alone is the true friend who touches the soul."),
    ("Traditional Dosti", "dosti", "Faasle Mit Jaate Hain Jab Dilon Mein Khuloos Ho",
     "فاصلے مٹ جاتے ہیں جب دلوں میں خلوص ہو", "دوستی کبھی پرانی نہیں ہوتی",
     "Faaslay mit jaate hain jab dilon mein khuloos ho, Dosti kabhi puraani nahi hoti",
     "Distances dissolve completely when hearts overflow with sincerity; true friendship never fades with time."),
    ("Traditional Dosti", "dosti", "Tere Jaisa Dost Mila Hai Yeh Qismat Hai Meri",
     "تیرے جیسا دوست ملا ہے یہ قسمت ہے مری", "تیری وفا پر ناز ہے مجھ کو سدا",
     "Tere jaisa dost mila hai yeh qismat hai meri, Teri wafa par naaz hai mujh ko sada",
     "Finding a friend like you is my highest fortune; in your steadfast loyalty I take enduring pride."),
    ("Traditional Dosti", "dosti", "Dosti Ka Rishta Khoon Ke Rishte Se Badh Kar Hai",
     "دوستی کا رشتہ خون کے رشتے سے بڑھ کر ہے", "دل کی محبت کا یہ سب سے پیارا منظر ہے",
     "Dosti ka rishta khoon ke rishtay se badh kar hai, Dil ki mohabbat ka yeh sab se pyaara manzar hai",
     "The covenant of friendship often surpasses even ties of blood; it is the most sublime expression of love in the human heart."),
    ("Traditional Dosti", "dosti", "Dosti Ki Shama Kabhi Bujhne Na Denge",
     "دوستی کی شمع کبھی بجھنے نہ دیں گے", "تیرا ساتھ زندگی بھر نبھائیں گے",
     "Dosti ki shama kabhi bujhne na denge, Tera saath zindagi bhar nibhaayenge",
     "Never shall we allow the candle of friendship to flicker out; we shall walk beside you faithfully through all of life."),
    ("Traditional Dosti", "dosti", "Dost Ke Aansuon Ko Apni Aankhon Mein Samona",
     "دوست کے آنسوؤں کو اپنی آنکھوں میں سمونا", "یہ اخلاص کی معراج ہے یہ وفا کا نگینہ ہے",
     "Dost ke aansoon ko apni aankhon mein samona, Yeh ikhlaas ki me'raaj hai yeh wafa ka nageena hai",
     "Embracing a friend's tears as your own is the pinnacle of sincerity, the crown jewel of faithfulness."),
    ("Traditional Dosti", "dosti", "Sache Dost Hain Khuda Ki Badi Naimat",
     "سچے دوست ہیں خدا کی بڑی نعمت", "مل جائے جو مخلص تو مل جاتی ہے راحت",
     "Sachay dost hain Khuda ki badi naimat, Mil jaaye jo mukhlis to mil jaati hai raahat",
     "True friends are among the greatest bounties of God; when a sincere soul is found, lasting serenity is attained."),
    ("Traditional Dosti", "dosti", "Zindagi Ke Har Mod Par Tera Saath Ho",
     "زندگی کے ہر موڑ پر تیرا ساتھ ہو", "ہاتھوں میں میرے تیرا مخلص ہاتھ ہو",
     "Zindagi ke har morr par tera saath ho, Haathon mein mere tera mukhlis haath ho",
     "At every turning of life's road may your presence abide; may your sincere hand remain warmly held in mine."),
    ("Traditional Dosti", "dosti", "Dosti Woh Khushboo Hai Jo Faza Ko Mehka De",
     "دوستی وہ خوشبو ہے جو فضا کو مہکا دے", "اداس دلوں میں امید کے چراغ جلا دے",
     "Dosti woh khushboo hai jo faza ko mehka de, Udaas dilon mein umeed ke chiragh jala de",
     "Friendship is that divine perfume which scents the air, lighting the lamps of fresh hope in melancholic hearts.")
]

print(f"BIRTHDAY_DOSTI_VERSES loaded: {len(BIRTHDAY_DOSTI_VERSES)} items.")
