const fs = require('fs');
const path = require('path');

const LANGS = ['en', 'es', 'fr', 'ar', 'hi', 'zh', 'pt', 'ru', 'de', 'ja', 'ko', 'it', 'tr', 'id', 'ur', 'bn', 'vi', 'sw'];

const translationsDir = path.join(__dirname, '../lib/blog/translations');
if (!fs.existsSync(translationsDir)) {
  fs.mkdirSync(translationsDir, { recursive: true });
}

// Data generator for Post 1
const post1Data = {
  slug: "complete-guide-to-pakistani-wedding-invitation-wording-urdu-english",
  data: {
    en: { title: "The Complete Guide to Pakistani & Islamic Wedding Invitation Wording (Urdu & English Examples)", subtitle: "Comprehensive wording examples for Nikkah, Mehndi, Barat, and Walima cards with authentic Bismillah calligraphy, Quranic verses, host etiquette, and RSVP notes.", category: "Wedding & Nikkah", seoTitle: "Pakistani & Islamic Wedding Invitation Wording Guide (Urdu & English)", metaDescription: "Explore 50+ Pakistani and Islamic wedding invitation wording examples in Urdu & English for Nikkah, Mehndi, Barat & Walima cards. Includes Quranic verses and RSVP etiquette." },
    ur: { title: "پاکستانی شادی کارڈ تحریر گائیڈ (اردو اور انگریزی الفاظ)", subtitle: "نکاح، مہندی، بارات اور ولیمہ کے لیے روایتی اور جدید ترین اردو اور انگلش الفاظ و دعائیں", category: "Wedding & Nikkah", seoTitle: "پاکستانی شادی اور نکاح کارڈ تحریر گائیڈ — کارڈزی", metaDescription: "نکاح، مہندی، بارات اور ولیمہ کارڈز کے لیے بہترین اردو اور انگریزی تحریر، قرآنی آیات اور دعائیں۔ کارڈزی پر خوبصورت ڈیجیٹل کارڈز دیکھیں۔" },
    ar: { title: "دليل صيغ دعوات الزفاف الباكستانية والإسلامية (أردو وإنجليزي)", subtitle: "عبارات راقية لدعوات النكاح والحناء والوليمة باللغتين العربية والإنجليزي", category: "Wedding & Nikkah", seoTitle: "دليل صيغ دعوات الزفاف الإسلامية والباكستانية — كاردزي", metaDescription: "اكتشف أفضل صيغ دعوات عقد النكاح والزفاف باللغات العربية والأردو والإنجليزية مع آيات قرآنية وتنسيق رائع عبر كاردزي." },
    es: { title: "Guía Completa de Textos para Invitaciones de Boda (Urdu e Inglés)", subtitle: "Frases elegantes y bendiciones tradicionales para bodas, Nikkah, Mehndi y Walima.", category: "Wedding & Nikkah", seoTitle: "Guía de Textos para Invitaciones de Boda Islámicas — Cardzy", metaDescription: "Descubra ejemplos de textos para invitaciones de boda en urdu e inglés para Nikkah, Mehndi, Barat y Walima con versículos del Corán." },
    fr: { title: "Guide Complet de Rédaction des Invitations de Mariage (Ourdou & Anglais)", subtitle: "Formules élégantes et bénédictions traditionnelles pour les cérémonies de Nikkah et Walima.", category: "Wedding & Nikkah", seoTitle: "Guide des Textes de Faire-Part de Mariage Islamique — Cardzy", metaDescription: "Exemples de formules pour invitations de mariage islamiques et pakistanaises en ourdou et anglais. Versets du Coran et étiquette." },
    hi: { title: "पाकिस्तानी शादी कार्ड आमंत्रण पाठ गाइड (उर्दू और अंग्रेजी)", subtitle: "निकाह, मेहंदी और वलीमा के लिए पारंपरिक और आधुनिक उर्दू व अंग्रेजी शब्द", category: "Wedding & Nikkah", seoTitle: "शादी और निकाह निमंत्रण पत्र गाइड — कार्डज़ी", metaDescription: "निकाह, मेहंदी, बारात और वलीमा कार्ड के लिए बेहतरीन उर्दू और अंग्रेजी संदेश और कुरान की आयतें पढ़ें।" },
    zh: { title: "婚礼请柬措辞与文案完整指南（乌尔都语与英语）", subtitle: "包含 Nikkah 订婚、Mehndi 仪式和 Walima 喜宴的经典与现代文字模板。", category: "Wedding & Nikkah", seoTitle: "伊斯兰与巴基斯坦婚礼请柬文案指南 — Cardzy", metaDescription: "探索50+双语婚礼请柬文案范例（乌尔都语与英语），包含 Nikkah、Mehndi、Walima 喜宴及古兰经祝福语。" },
    pt: { title: "Guia Completo de Texto para Convites de Casamento (Urdu e Inglês)", subtitle: "Frases elegantes e bênçãos tradicionais para cerimónias de Nikkah e celebrações.", category: "Wedding & Nikkah", seoTitle: "Guia de Texto para Convites de Casamento Islâmicos — Cardzy", metaDescription: "Exemplos de textos para convites de casamento em urdu e inglês para Nikkah, Mehndi e Walima com versículos sagrados." },
    ru: { title: "Полное руководство по текстам свадебных приглашений (Урду и Английский)", subtitle: "Элегантные фразы и благословения для обрядов Никах, Мехнди и Валима.", category: "Wedding & Nikkah", seoTitle: "Руководство по текстам мусульманских свадебных приглашений — Cardzy", metaDescription: "Примеры текстов свадебных приглашений на урду и английском для Никаха, Мехнди и Валима. Коранические стихи и этикет." },
    de: { title: "Vollständiger Leitfaden für Hochzeitseinladungstexte (Urdu & Englisch)", subtitle: "Elegante Formulierungen und Segen für Nikkah, Mehndi und Walima Feiern.", category: "Wedding & Nikkah", seoTitle: "Leitfaden für islamische Hochzeitseinladungstexte — Cardzy", metaDescription: "Entdecken Sie Formulierungsbeispiele für Nikkah-, Mehndi- und Walima-Einladungskarten auf Urdu und Englisch." },
    ja: { title: "結婚式招待状の文面と例文完全ガイド（ウルドゥー語＆英語）", subtitle: "Nikkah（結婚契約）、Mehndi、Walima披露宴のためのエレガントな文例集。", category: "Wedding & Nikkah", seoTitle: "イスラム・巴基斯坦結婚式招待状文面ガイド — Cardzy", metaDescription: "Nikkah、Mehndi、Walima用のウルドゥー語＆英語の結婚式招待状文例集。コーランの聖句とマナーを解説。" },
    ko: { title: "결혼식 초대장 문구 작성 완벽 가이드 (우르두어 및 영어)", subtitle: "니카(Nikkah) 및 피로연을 위한 우아한 전통 문구와 현대적 축하 메세지.", category: "Wedding & Nikkah", seoTitle: "이슬람 결혼식 초대장 문구 가이드 — Cardzy", metaDescription: "니카, 멘디, 발리마 초대장을 위한 우르두어 및 영어 문구 예시와 코란 구절 안내." },
    it: { title: "Guida Completa ai Testi per Inviti di Nozze (Urdu e Inglese)", subtitle: "Frasi eleganti e benedizioni tradizionali per cerimonie Nikkah, Mehndi e Walima.", category: "Wedding & Nikkah", seoTitle: "Guida ai Testi per Inviti di Nozze Islamici — Cardzy", metaDescription: "Esempi di frasi per inviti di matrimonio in urdu e inglese per cerimonie Nikkah, Mehndi e Walima con versi del Corano." },
    tr: { title: "Düğün Davetiyesi Yazım ve Metin Rehberi (Urduca ve İngilizce)", subtitle: "Nikah, Kına Gecesi ve Düğün için geleneksel ve modern davet sözleri.", category: "Wedding & Nikkah", seoTitle: "İslami ve Geleneksel Düğün Davetiye Metinleri Rehberi — Cardzy", metaDescription: "Nikah, Kına ve Düğün davetiyeleri için Urduca ve İngilizce davet yazısı örnekleri ve Ayet-i Kerimeler." },
    id: { title: "Panduan Lengkap Teks Undangan Pernikahan (Bahasa Urdu & Inggris)", subtitle: "Kalimat elegan dan doa pernikahan untuk acara Akad Nikah, Mehndi, dan Resepsi.", category: "Wedding & Nikkah", seoTitle: "Panduan Teks Undangan Pernikahan Islami — Cardzy", metaDescription: "Kumpulan contoh teks undangan Akad Nikah, Mehndi, dan Walima dalam Bahasa Urdu & Inggris beserta ayat Al-Qur'an." },
    bn: { title: "পাকিস্তানি ও ইসলামিক বিয়ের নিমন্ত্রণপত্রের লেখা গাইড (উর্দু ও ইংরেজি)", subtitle: "নিকাহ, মেহেদি, বারাত এবং ওয়ালিমা কার্ডের জন্য ঐতিহ্যবাহী ও আধুনিক ভাষার বাক্য ও দোয়া", category: "Wedding & Nikkah", seoTitle: "ইসলামিক বিয়ের কার্ডের ভাষা নির্দেশিকা — কার্ডজি", metaDescription: "নিকাহ, মেহেদি ও ওয়ালিমা নিমন্ত্রণপত্রের জন্য সেরা উর্দু ও ইংরেজি বাক্য, কুরআনের আয়াত এবং নিমন্ত্রণ সামাজিক রীতি।" },
    vi: { title: "Hướng Dẫn Viết Lời Mời Đám Cưới Hồi Giáo & Pakistan (Tiếng Urdu & Anh)", subtitle: "Mẫu câu trang trọng cho lễ Nikkah, Mehndi và tiệc Walima kèm câu chúc ý nghĩa.", category: "Wedding & Nikkah", seoTitle: "Hướng Dẫn Viết Thiệp Mời Đám Cưới Hồi Giáo — Cardzy", metaDescription: "Khám phá các mẫu lời mời đám cưới Hồi giáo bằng tiếng Urdu và tiếng Anh cho lễ Nikkah, Mehndi và tiệc Walima." },
    sw: { title: "Mwongozo Kamilifu wa Maneno ya Kadi za Harusi za Kiislamu (Kiuswahili & Kiingereza)", subtitle: "Mifano ya maneno ya rafu na baraka za Nikkah, Mehndi na Walima.", category: "Wedding & Nikkah", seoTitle: "Mwongozo wa Maneno ya Kadi za Harusi — Cardzy", metaDescription: "Mifano ya maneno ya kadi za harusi za Nikkah na Walima kwa Kiingereza na Urdu ikiwa na aya za Qur'ani Tukufu." }
  }
};

console.log('Post 1 metadata defined.');
