// Shared translations for new static pages
// Each key maps to all 18 supported languages

export type LangCode = 'en'|'ur'|'es'|'fr'|'ar'|'hi'|'zh'|'pt'|'ru'|'de'|'ja'|'ko'|'it'|'tr'|'id'|'bn'|'vi'|'sw'

export function pt(dict: Record<LangCode, string>, lang: string): string {
  return dict[(lang as LangCode)] ?? dict['en']
}

export const CONTACT_T = {
  badge:        { en:'Get In Touch', ur:'ہم سے رابطہ کریں', es:'Contáctanos', fr:'Contactez-nous', ar:'تواصل معنا', hi:'संपर्क करें', zh:'联系我们', pt:'Entre em Contato', ru:'Связаться', de:'Kontakt aufnehmen', ja:'お問い合わせ', ko:'문의하기', it:'Contattaci', tr:'İletişime Geçin', id:'Hubungi Kami', bn:'যোগাযোগ করুন', vi:'Liên Hệ', sw:'Wasiliana Nasi' },
  h1a:          { en:'Contact', ur:'رابطہ کریں', es:'Contactar', fr:'Contacter', ar:'تواصل مع', hi:'संपर्क करें', zh:'联系', pt:'Contate', ru:'Связаться с', de:'Kontakt', ja:'お問い合わせ', ko:'문의하기', it:'Contatta', tr:'İletişim', id:'Hubungi', bn:'যোগাযোগ', vi:'Liên Hệ', sw:'Wasiliana na' },
  h1b:          { en:'Cardzy', ur:'کارڈزی', es:'Cardzy', fr:'Cardzy', ar:'كاردزي', hi:'Cardzy', zh:'Cardzy', pt:'Cardzy', ru:'Cardzy', de:'Cardzy', ja:'Cardzy', ko:'Cardzy', it:'Cardzy', tr:'Cardzy', id:'Cardzy', bn:'Cardzy', vi:'Cardzy', sw:'Cardzy' },
  heroDesc:     { en:'Have a question, need help with a custom order, or want to learn about pricing? Our support team is ready to assist you. We typically respond within a few hours via WhatsApp and within 24 hours by email.', ur:'کوئی سوال ہے، کسٹم آرڈر میں مدد چاہیے، یا قیمتوں کے بارے میں جاننا چاہتے ہیں؟ ہماری سپورٹ ٹیم آپ کی مدد کے لیے تیار ہے۔ ہم عام طور پر واٹس ایپ پر چند گھنٹوں اور ای میل پر 24 گھنٹوں میں جواب دیتے ہیں۔', es:'¿Tienes una pregunta, necesitas ayuda con un pedido personalizado o quieres saber sobre precios? Nuestro equipo está listo para ayudarte.', fr:"Vous avez une question, besoin d'aide pour une commande personnalisée ou vous souhaitez en savoir plus sur les tarifs ? Notre équipe est prête à vous aider.", ar:'هل لديك سؤال، أو تحتاج مساعدة في طلب مخصص، أو تريد معرفة الأسعار؟ فريق الدعم لدينا مستعد لمساعدتك.', hi:'कोई प्रश्न है, कस्टम ऑर्डर में मदद चाहिए, या मूल्य निर्धारण के बारे में जानना चाहते हैं? हमारी सहायता टीम आपकी सहायता के लिए तैयार है।', zh:'有问题、需要定制订单帮助或想了解定价？我们的支持团队随时准备为您提供帮助。', pt:'Tem uma pergunta, precisa de ajuda com um pedido personalizado ou quer saber sobre preços? Nossa equipe está pronta para ajudar.', ru:'Есть вопрос, нужна помощь с заказом или хотите узнать о ценах? Наша команда поддержки готова помочь.', de:'Haben Sie eine Frage, benötigen Hilfe bei einer benutzerdefinierten Bestellung oder möchten mehr über die Preise erfahren? Unser Support-Team ist bereit, Ihnen zu helfen.', ja:'ご質問、カスタム注文のサポート、価格についてのお問い合わせはお気軽にどうぞ。サポートチームがお手伝いします。', ko:'질문이 있으신가요, 맞춤 주문 도움이 필요하신가요, 또는 가격에 대해 알고 싶으신가요? 지원 팀이 도와드립니다.', it:'Hai una domanda, hai bisogno di aiuto con un ordine personalizzato o vuoi sapere i prezzi? Il nostro team di supporto è pronto ad aiutarti.', tr:'Bir sorunuz mu var, özel sipariş yardımına mı ihtiyacınız var veya fiyatlandırma hakkında bilgi almak mı istiyorsunuz? Destek ekibimiz yardımcı olmaya hazır.', id:'Ada pertanyaan, butuh bantuan pesanan khusus, atau ingin tahu harga? Tim dukungan kami siap membantu.', bn:'কোনো প্রশ্ন আছে, কাস্টম অর্ডারে সাহায্য দরকার, বা মূল্য জানতে চান? আমাদের সাপোর্ট টিম সাহায্য করতে প্রস্তুত।', vi:'Có câu hỏi, cần hỗ trợ đặt hàng tùy chỉnh hoặc muốn tìm hiểu về giá cả? Đội ngũ hỗ trợ của chúng tôi luôn sẵn sàng giúp đỡ bạn.', sw:'Una swali, unahitaji msaada na agizo maalum, au unataka kujua bei? Timu yetu ya msaada iko tayari kukusaidia.' },
  whatsappTitle:{ en:'WhatsApp', ur:'واٹس ایپ', es:'WhatsApp', fr:'WhatsApp', ar:'واتساب', hi:'व्हाट्सएप', zh:'WhatsApp', pt:'WhatsApp', ru:'WhatsApp', de:'WhatsApp', ja:'WhatsApp', ko:'WhatsApp', it:'WhatsApp', tr:'WhatsApp', id:'WhatsApp', bn:'হোয়াটসঅ্যাপ', vi:'WhatsApp', sw:'WhatsApp' },
  whatsappDesc: { en:'For fast support, custom card orders, and pricing help. Our WhatsApp line is monitored every day and usually responds within a few hours.', ur:'فوری سپورٹ، کسٹم کارڈ آرڈرز، اور قیمتوں کی مدد کے لیے۔ ہماری واٹس ایپ لائن ہر روز مانیٹر کی جاتی ہے اور عام طور پر چند گھنٹوں میں جواب دیا جاتا ہے۔', es:'Para soporte rápido, pedidos de tarjetas personalizadas y ayuda con precios. Nuestra línea de WhatsApp se monitorea todos los días.', fr:"Pour un support rapide, des commandes de cartes personnalisées et de l'aide sur les prix. Notre ligne WhatsApp est surveillée chaque jour.", ar:'للدعم السريع وطلبات البطاقات المخصصة ومساعدة الأسعار. خط واتساب لدينا تتم مراقبته يومياً.', hi:'त्वरित सहायता, कस्टम कार्ड ऑर्डर और मूल्य सहायता के लिए। हमारी व्हाट्सएप लाइन प्रतिदिन मॉनिटर की जाती है।', zh:'快速支持、定制卡片订单和价格帮助。我们的WhatsApp每天都有人监看，通常在几小时内回复。', pt:'Para suporte rápido, pedidos de cartões personalizados e ajuda com preços. Nossa linha WhatsApp é monitorada todos os dias.', ru:'Для быстрой поддержки, заказов карточек и помощи с ценами. Наш WhatsApp отслеживается ежедневно.', de:'Für schnellen Support, benutzerdefinierte Kartenbestellungen und Preishilfe. Unsere WhatsApp-Linie wird täglich überwacht.', ja:'迅速なサポート、カスタムカード注文、価格のヘルプ。WhatsAppは毎日監視され、数時間以内に返信します。', ko:'빠른 지원, 맞춤 카드 주문 및 가격 도움을 위해. WhatsApp은 매일 모니터링되며 보통 몇 시간 내에 응답합니다.', it:'Per supporto rapido, ordini di carte personalizzate e assistenza sui prezzi. La nostra linea WhatsApp è monitorata ogni giorno.', tr:'Hızlı destek, özel kart siparişleri ve fiyat yardımı için. WhatsApp hattımız her gün izlenmekte ve genellikle birkaç saat içinde yanıt verilmektedir.', id:'Untuk dukungan cepat, pesanan kartu kustom, dan bantuan harga. Saluran WhatsApp kami dipantau setiap hari.', bn:'দ্রুত সাপোর্ট, কাস্টম কার্ড অর্ডার এবং মূল্য সাহায্যের জন্য। আমাদের হোয়াটসঅ্যাপ লাইন প্রতিদিন পর্যবেক্ষণ করা হয়।', vi:'Để được hỗ trợ nhanh, đặt hàng thiệp tùy chỉnh và giúp đỡ về giá. Đường dây WhatsApp của chúng tôi được theo dõi hàng ngày.', sw:'Kwa msaada wa haraka, maagizo ya kadi maalum na msaada wa bei. Mstari wetu wa WhatsApp unafuatiliwa kila siku.' },
  chatNow:      { en:'Chat Now', ur:'ابھی چیٹ کریں', es:'Chatear ahora', fr:'Chatter maintenant', ar:'تحدث الآن', hi:'अभी चैट करें', zh:'立即聊天', pt:'Conversar agora', ru:'Написать сейчас', de:'Jetzt chatten', ja:'今すぐチャット', ko:'지금 채팅하기', it:'Chatta ora', tr:'Şimdi Sohbet Et', id:'Chat Sekarang', bn:'এখনই চ্যাট করুন', vi:'Trò chuyện ngay', sw:'Ongea Sasa' },
  emailTitle:   { en:'Email Support', ur:'ای میل سپورٹ', es:'Soporte por Email', fr:'Support Email', ar:'الدعم عبر البريد', hi:'ईमेल सहायता', zh:'邮件支持', pt:'Suporte por Email', ru:'Поддержка по Email', de:'E-Mail-Support', ja:'メールサポート', ko:'이메일 지원', it:'Supporto Email', tr:'E-posta Desteği', id:'Dukungan Email', bn:'ইমেইল সাপোর্ট', vi:'Hỗ Trợ Email', sw:'Msaada wa Barua Pepe' },
  emailDesc:    { en:'Send us a detailed message for account questions, billing, partnerships, or feature feedback. We respond to all emails within 24 hours.', ur:'اکاؤنٹ کے سوالات، بلنگ، شراکت داری، یا فیچر فیڈبیک کے لیے ہمیں تفصیلی پیغام بھیجیں۔ ہم تمام ای میلز کا 24 گھنٹوں میں جواب دیتے ہیں۔', es:'Envíanos un mensaje detallado para preguntas de cuenta, facturación, asociaciones o comentarios. Respondemos todos los correos en 24 horas.', fr:'Envoyez-nous un message détaillé pour les questions de compte, la facturation, les partenariats ou les commentaires. Nous répondons dans les 24 heures.', ar:'أرسل لنا رسالة مفصلة لأسئلة الحساب أو الفواتير أو الشراكات. نرد على جميع الرسائل خلال 24 ساعة.', hi:'खाते के प्रश्नों, बिलिंग, साझेदारी, या फीचर फीडबैक के लिए हमें विस्तृत संदेश भेजें। हम सभी ईमेल का 24 घंटे में जवाब देते हैं।', zh:'发送详细消息咨询账户问题、账单、合作或功能反馈。我们在24小时内回复所有邮件。', pt:'Envie uma mensagem detalhada para perguntas de conta, faturamento, parcerias ou feedback. Respondemos a todos os e-mails em 24 horas.', ru:'Напишите нам для вопросов об аккаунте, выставлении счетов или партнёрстве. Отвечаем на все письма в течение 24 часов.', de:'Senden Sie uns eine detaillierte Nachricht für Kontofragen, Abrechnung, Partnerschaften oder Feedback. Wir antworten innerhalb von 24 Stunden.', ja:'アカウントの質問、請求、パートナーシップ、フィードバックについて詳細なメッセージをお送りください。すべてのメールに24時間以内に返信します。', ko:'계정 질문, 청구, 파트너십 또는 피드백에 대한 자세한 메시지를 보내주세요. 모든 이메일에 24시간 내로 답변합니다.', it:'Inviaci un messaggio dettagliato per domande sull\'account, fatturazione, partnership o feedback. Rispondiamo a tutte le email entro 24 ore.', tr:'Hesap soruları, faturalama, ortaklıklar veya özellik geri bildirimi için bize ayrıntılı bir mesaj gönderin. Tüm e-postalara 24 saat içinde yanıt veriyoruz.', id:'Kirim pesan lengkap untuk pertanyaan akun, tagihan, kemitraan, atau umpan balik. Kami merespons semua email dalam 24 jam.', bn:'অ্যাকাউন্ট প্রশ্ন, বিলিং, অংশীদারিত্ব, বা ফিডব্যাকের জন্য আমাদের বিস্তারিত বার্তা পাঠান। আমরা সব ইমেইলের ২৪ ঘণ্টার মধ্যে উত্তর দিই।', vi:'Gửi cho chúng tôi tin nhắn chi tiết về câu hỏi tài khoản, thanh toán, hợp tác hoặc phản hồi tính năng. Chúng tôi trả lời tất cả email trong vòng 24 giờ.', sw:'Tutumie ujumbe wa kina kwa maswali ya akaunti, bili, ushirikiano, au maoni. Tunajibu barua pepe zote ndani ya masaa 24.' },
  sendEmail:    { en:'Send Email', ur:'ای میل بھیجیں', es:'Enviar Email', fr:'Envoyer Email', ar:'إرسال بريد', hi:'ईमेल भेजें', zh:'发送邮件', pt:'Enviar Email', ru:'Написать письмо', de:'E-Mail senden', ja:'メールを送る', ko:'이메일 보내기', it:'Invia Email', tr:'E-posta Gönder', id:'Kirim Email', bn:'ইমেইল পাঠান', vi:'Gửi Email', sw:'Tuma Barua Pepe' },
  locationTitle:{ en:'Business Location', ur:'کاروباری مقام', es:'Ubicación', fr:'Localisation', ar:'الموقع', hi:'व्यवसाय स्थान', zh:'公司地址', pt:'Localização', ru:'Местонахождение', de:'Standort', ja:'所在地', ko:'위치', it:'Sede', tr:'Konum', id:'Lokasi', bn:'অবস্থান', vi:'Địa Điểm', sw:'Mahali' },
  locationDesc: { en:'Cardzy is a digital-first global platform headquartered in Pakistan. We serve users worldwide with support available in 18 languages across every time zone.', ur:'کارڈزی ایک ڈیجیٹل گلوبل پلیٹ فارم ہے جس کا ہیڈکوارٹر پاکستان میں ہے۔ ہم دنیا بھر میں 18 زبانوں میں سپورٹ فراہم کرتے ہیں۔', es:'Cardzy es una plataforma global digital con sede en Pakistán. Atendemos usuarios de todo el mundo en 18 idiomas.', fr:"Cardzy est une plateforme numérique mondiale dont le siège est au Pakistan. Nous servons des utilisateurs du monde entier en 18 langues.", ar:'كاردزي منصة رقمية عالمية مقرها باكستان. نخدم المستخدمين حول العالم بـ 18 لغة.', hi:'Cardzy एक डिजिटल-फर्स्ट ग्लोबल प्लेटफॉर्म है जिसका मुख्यालय पाकिस्तान में है। हम दुनिया भर में 18 भाषाओं में सेवा प्रदान करते हैं।', zh:'Cardzy是一个总部位于巴基斯坦的数字全球平台，为全球用户提供18种语言的支持。', pt:'Cardzy é uma plataforma global digital com sede no Paquistão. Atendemos usuários no mundo inteiro em 18 idiomas.', ru:'Cardzy — цифровая глобальная платформа со штаб-квартирой в Пакистане. Мы обслуживаем пользователей по всему миру на 18 языках.', de:'Cardzy ist eine digitale globale Plattform mit Hauptsitz in Pakistan. Wir betreuen Nutzer weltweit in 18 Sprachen.', ja:'Cardzyはパキスタンを拠点とするデジタルグローバルプラットフォームです。18言語で世界中のユーザーをサポートしています。', ko:'Cardzy는 파키스탄에 본사를 둔 디지털 우선 글로벌 플랫폼입니다. 18개 언어로 전 세계 사용자를 지원합니다.', it:"Cardzy è una piattaforma digitale globale con sede in Pakistan. Serviamo utenti in tutto il mondo in 18 lingue.", tr:'Cardzy, Pakistan merkezli dijital bir küresel platformdur. 18 dilde dünya genelinde kullanıcılara hizmet vermekteyiz.', id:'Cardzy adalah platform digital global yang berkantor pusat di Pakistan. Kami melayani pengguna di seluruh dunia dalam 18 bahasa.', bn:'Cardzy হলো একটি ডিজিটাল-ফার্স্ট গ্লোবাল প্ল্যাটফর্ম যার সদর দপ্তর পাকিস্তানে। আমরা ১৮টি ভাষায় বিশ্বজুড়ে ব্যবহারকারীদের সেবা দিই।', vi:'Cardzy là nền tảng kỹ thuật số toàn cầu có trụ sở tại Pakistan. Chúng tôi phục vụ người dùng trên toàn thế giới bằng 18 ngôn ngữ.', sw:'Cardzy ni jukwaa la kidijitali la kimataifa lenye makao makuu Pakistan. Tunahudumia watumiaji duniani kote kwa lugha 18.' },
  supportHours: { en:'Support Hours', ur:'سپورٹ کے اوقات', es:'Horario de soporte', fr:'Heures de support', ar:'ساعات الدعم', hi:'सहायता समय', zh:'支持时间', pt:'Horário de Suporte', ru:'Часы работы поддержки', de:'Support-Zeiten', ja:'サポート時間', ko:'지원 시간', it:'Orari di supporto', tr:'Destek Saatleri', id:'Jam Dukungan', bn:'সাপোর্টের সময়', vi:'Giờ Hỗ Trợ', sw:'Masaa ya Msaada' },
  waHours:      { en:'WhatsApp Response Times', ur:'واٹس ایپ جواب کا وقت', es:'Tiempos de respuesta WhatsApp', fr:'Temps de réponse WhatsApp', ar:'أوقات الرد على واتساب', hi:'व्हाट्सएप प्रतिक्रिया समय', zh:'WhatsApp响应时间', pt:'Tempos de resposta WhatsApp', ru:'Время ответа в WhatsApp', de:'WhatsApp-Antwortzeiten', ja:'WhatsApp応答時間', ko:'WhatsApp 응답 시간', it:'Tempi di risposta WhatsApp', tr:'WhatsApp Yanıt Süreleri', id:'Waktu Respons WhatsApp', bn:'হোয়াটসঅ্যাপ প্রতিক্রিয়া সময়', vi:'Thời Gian Phản Hồi WhatsApp', sw:'Muda wa Kujibu WhatsApp' },
  emailHours:   { en:'Email Response Times', ur:'ای میل جواب کا وقت', es:'Tiempos de respuesta Email', fr:'Temps de réponse Email', ar:'أوقات الرد على البريد', hi:'ईमेल प्रतिक्रिया समय', zh:'邮件响应时间', pt:'Tempos de resposta Email', ru:'Время ответа на Email', de:'E-Mail-Antwortzeiten', ja:'メール応答時間', ko:'이메일 응답 시간', it:'Tempi di risposta Email', tr:'E-posta Yanıt Süreleri', id:'Waktu Respons Email', bn:'ইমেইল প্রতিক্রিয়া সময়', vi:'Thời Gian Phản Hồi Email', sw:'Muda wa Kujibu Barua Pepe' },
  aboutTeamTitle:{ en:'About Our Support Team', ur:'ہماری سپورٹ ٹیم کے بارے میں', es:'Sobre nuestro equipo', fr:'À propos de notre équipe', ar:'عن فريق الدعم', hi:'हमारी सहायता टीम के बारे में', zh:'关于我们的支持团队', pt:'Sobre Nossa Equipe', ru:'О нашей команде поддержки', de:'Über unser Support-Team', ja:'サポートチームについて', ko:'지원팀 소개', it:'Il nostro team di supporto', tr:'Destek Ekibimiz Hakkında', id:'Tentang Tim Dukungan Kami', bn:'আমাদের সাপোর্ট টিম সম্পর্কে', vi:'Về Đội Ngũ Hỗ Trợ', sw:'Kuhusu Timu Yetu ya Msaada' },
  faqTeaser:    { en:'Looking for Quick Answers?', ur:'فوری جوابات تلاش کر رہے ہیں؟', es:'¿Buscas respuestas rápidas?', fr:'Vous cherchez des réponses rapides ?', ar:'هل تبحث عن إجابات سريعة؟', hi:'त्वरित उत्तर ढूंढ रहे हैं?', zh:'寻找快速答案？', pt:'Procurando respostas rápidas?', ru:'Ищете быстрые ответы?', de:'Suchen Sie schnelle Antworten?', ja:'クイックアンサーをお探しですか？', ko:'빠른 답변을 찾고 계신가요?', it:'Cerchi risposte rapide?', tr:'Hızlı Cevaplar mı Arıyorsunuz?', id:'Mencari Jawaban Cepat?', bn:'দ্রুত উত্তর খুঁজছেন?', vi:'Tìm Kiếm Câu Trả Lời Nhanh?', sw:'Unatafuta Majibu ya Haraka?' },
  viewFaq:      { en:'View FAQ', ur:'FAQ دیکھیں', es:'Ver FAQ', fr:'Voir la FAQ', ar:'عرض الأسئلة', hi:'FAQ देखें', zh:'查看常见问题', pt:'Ver FAQ', ru:'Смотреть FAQ', de:'FAQ ansehen', ja:'FAQを見る', ko:'FAQ 보기', it:'Vedi FAQ', tr:'SSS\'yi Gör', id:'Lihat FAQ', bn:'FAQ দেখুন', vi:'Xem FAQ', sw:'Tazama Maswali' },
  helpWith:     { en:'What Our Support Team Can Help You With', ur:'ہماری سپورٹ ٹیم آپ کی کس چیز میں مدد کر سکتی ہے', es:'Con qué puede ayudarte nuestro equipo', fr:'Ce que notre équipe peut faire pour vous', ar:'ما يمكن لفريق الدعم مساعدتك به', hi:'हमारी सहायता टीम आपकी किन चीजों में मदद कर सकती है', zh:'我们的支持团队可以帮助您解决哪些问题', pt:'Com o que nossa equipe pode ajudar', ru:'Чем наша команда может вам помочь', de:'Wobei unser Support-Team helfen kann', ja:'サポートチームができること', ko:'지원팀이 도울 수 있는 것', it:'Come può aiutarti il nostro team', tr:'Destek Ekibimiz Size Nasıl Yardımcı Olabilir', id:'Apa yang Dapat Dibantu Tim Dukungan Kami', bn:'আমাদের সাপোর্ট টিম আপনাকে কিসে সাহায্য করতে পারে', vi:'Đội Ngũ Hỗ Trợ Có Thể Giúp Gì Cho Bạn', sw:'Timu Yetu ya Msaada Inaweza Kukusaidia Nini' },
} as const
